### ISSUE TITLE
Boston.gov/news page not updating

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#1002]
I posted two new posts today (with Inspectional Services), but it doesn't look like either of them are on the boston.gov/news page

Here are the links to the two posts:
boston.gov/news/getting-what-you-pay-gas-pump-tips-our-weights-and-measures-division
boston.gov/news/how-we-inspect-airline-scales-ensure-accuracy

**Comment by reillyzlab** [comment]
@duffy-james can you take a look and see if there is an obvious content fix?

**Comment by reillyzlab** [comment]
Purging issue - duplicate, so closing
