### ISSUE TITLE
500 error page implememtation

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1003]
Implement a 500 error page

@sebastianebarb drop in a design

**Comment by sebastianebarb** [comment]
![Error page 500 error](https://user-images.githubusercontent.com/20642299/69674385-60830b00-106a-11ea-8fae-3e0847b84528.png)

**Comment by sebastianebarb** [comment]
https://drive.google.com/open?id=0B0RwQU94BhGeZldzT29NTGp5QVk&authuser=sebastian.ebarb@boston.gov&usp=drive_fs

**Comment by reillyzlab** [comment]
@duffy-james can you advise on wording for this?

**Comment by reillyzlab** [comment]
Should also include some way to do some logging.

**Comment by jimafisk** [comment]
https://support.acquia.com/hc/en-us/articles/360005448173-Custom-503-Error-Page-With-Varnish

**Comment by duffy-james** [comment]
@reillyzlab David and I chatted about this. Think this works:

Sorry! Looks like something went wrong on our end. We're currently working to fix the issue. You can try re-loading the page in a few minutes, or email feedback@boston.gov with any questions or concerns.

**Comment by subaha-cob** [comment]
@andrebtlima I will need @davidrkupton to finish this up.

**Comment by subaha-cob** [comment]
@andrebtlima I connect with David about this yesterday, and he laughed because he said it will be very difficult to implement. That is because a 500 error means your servers are down and Drupal cannot even get to the pages to execute anything. 

One thing he mentioned though was for us to bring it up in our next TAM call and ask Acquia about it.

**Comment by subaha-cob** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Boston.Gov</title>
</head>
<body style="font-family: arial,serif; margin: 20px;">
<svg style="max-width: 160px;" viewBox="0 0 179 24" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="M8.514 13.327c1.73 0 3.143-.687 4.24-2.06l2.256 2.33c-1.79 2.024-3.898 3.035-6.326 3.035-2.43 0-4.43-.77-6-2.31C1.115 12.783.33 10.84.33 8.495c0-2.347.8-4.305 2.402-5.875C4.33 1.05 6.29.264 8.605.264c2.586 0 4.75.99 6.495 2.966l-2.188 2.49c-1.112-1.387-2.496-2.08-4.15-2.08-1.322 0-2.454.434-3.393 1.302-.94.868-1.41 2.037-1.41 3.508 0 1.472.442 2.653 1.33 3.543.887.892 1.962 1.337 3.224 1.337M17.69.627h3.517V16.45H17.69V.627zm13.846 3.056V16.45h-3.518V3.683h-4.466V.627h12.45v3.056h-4.466M46.332 16.45h-3.518v-6.247L37.356.627h3.812l3.405 5.886L47.98.627h3.81l-5.458 9.576v6.247m21.713-8.496c0 1.052-.19 2.01-.568 2.87-.38.862-.9 1.523-1.56 1.984-.662.46-1.423.692-2.284.692-.996 0-1.787-.298-2.373-.895-.587-.596-.88-1.407-.88-2.433 0-1.036.185-1.986.556-2.85.37-.865.89-1.538 1.56-2.02s1.443-.722 2.32-.722c1.01 0 1.802.302 2.373.906.57.604.855 1.426.855 2.468zM66.2 7.876c0-.557-.126-.993-.38-1.31-.255-.314-.618-.47-1.09-.47-.482 0-.914.185-1.296.557-.38.373-.677.878-.887 1.516a6.475 6.475 0 0 0-.315 2.04c0 .58.128 1.022.385 1.33.257.306.637.46 1.14.46.467 0 .888-.177 1.26-.53.374-.355.665-.85.872-1.49.207-.637.31-1.34.31-2.104zm1.615 9.326c-.467 0-.853-.06-1.16-.18v-1.484c.333.104.628.156.888.156.695 0 1.154-.534 1.377-1.6l1.69-7.983h-1.394l.164-.827 1.51-.594.162-.72c.23-1.03.578-1.763 1.047-2.198.468-.435 1.134-.653 1.995-.653.597 0 1.144.11 1.642.335l-.474 1.375a3.005 3.005 0 0 0-1.06-.22c-.357 0-.644.113-.86.337-.214.224-.38.59-.493 1.102l-.14.67h1.782l-.288 1.39h-1.782l-1.735 8.225c-.208.984-.548 1.708-1.02 2.172-.472.463-1.09.695-1.852.695m22.679-.75h-6.9V.627h6.133c1.067 0 1.988.13 2.763.385.773.257 1.355.604 1.747 1.042.706.815 1.06 1.735 1.06 2.76 0 1.24-.4 2.16-1.196 2.763-.27.21-.458.343-.563.396-.105.053-.293.14-.564.26.978.212 1.756.653 2.335 1.325.578.67.868 1.505.868 2.5 0 1.103-.376 2.076-1.128 2.92-.872.982-2.39 1.472-4.555 1.472zM87.11 7.034h1.67c.976 0 1.7-.106 2.175-.317.473-.21.71-.668.71-1.37 0-.7-.218-1.166-.654-1.392-.435-.226-1.172-.34-2.21-.34h-1.69v3.42zm0 6.428h2.413c1.007 0 1.763-.124 2.266-.373.503-.25.755-.74.755-1.473 0-.73-.267-1.214-.8-1.448-.535-.235-1.388-.352-2.56-.352H87.11v3.644zm25.19.804c-1.593 1.562-3.555 2.343-5.885 2.343-2.33 0-4.293-.782-5.886-2.344-1.595-1.562-2.392-3.505-2.392-5.83 0-2.323.797-4.266 2.39-5.828 1.594-1.562 3.556-2.343 5.887-2.343 2.33 0 4.292.78 5.886 2.343 1.594 1.562 2.39 3.505 2.39 5.83 0 2.323-.796 4.266-2.39 5.828zm-1.194-5.818c0-1.41-.45-2.614-1.353-3.61s-2.012-1.494-3.327-1.494-2.424.498-3.326 1.494c-.903.996-1.354 2.2-1.354 3.61 0 1.412.45 2.61 1.354 3.6.902.988 2.01 1.482 3.326 1.482 1.315 0 2.424-.494 3.327-1.482.902-.99 1.353-2.188 1.353-3.6zm10.112-4.663c-.34.28-.508.65-.508 1.11 0 .46.207.826.62 1.097.414.272 1.368.593 2.865.962 1.496.37 2.657.925 3.484 1.664.826.74 1.24 1.82 1.24 3.237 0 1.42-.53 2.57-1.59 3.452-1.06.883-2.455 1.325-4.184 1.325-2.496 0-4.744-.93-6.743-2.785l2.097-2.58c1.7 1.494 3.27 2.24 4.714 2.24.646 0 1.153-.14 1.522-.418.368-.28.553-.658.553-1.133s-.197-.852-.588-1.132c-.39-.28-1.165-.562-2.323-.85-1.836-.436-3.177-1.006-4.026-1.708-.85-.7-1.274-1.803-1.274-3.305 0-1.5.537-2.66 1.612-3.474 1.075-.815 2.417-1.223 4.025-1.223 1.053 0 2.105.18 3.158.544 1.052.36 1.97.874 2.75 1.538l-1.78 2.58c-1.37-1.04-2.782-1.56-4.24-1.56-.587 0-1.05.138-1.387.417m17.463-.1V16.45h-3.52V3.683h-4.464V.627h12.45v3.056h-4.466m19.886 10.583c-1.594 1.562-3.556 2.343-5.886 2.343s-4.293-.782-5.886-2.344c-1.594-1.562-2.39-3.505-2.39-5.83 0-2.323.796-4.266 2.39-5.828 1.593-1.562 3.555-2.343 5.886-2.343 2.33 0 4.292.78 5.886 2.343 1.594 1.562 2.39 3.505 2.39 5.83 0 2.323-.796 4.266-2.39 5.828zm-1.195-5.818c0-1.41-.452-2.614-1.354-3.61-.902-.996-2.012-1.494-3.327-1.494-1.316 0-2.425.498-3.327 1.494-.902.996-1.354 2.2-1.354 3.61 0 1.412.45 2.61 1.353 3.6.902.988 2.01 1.482 3.326 1.482 1.314 0 2.424-.494 3.326-1.482.902-.99 1.353-2.188 1.353-3.6zM175.007.627h3.518V16.45h-3.518l-7.51-9.914v9.914h-3.518V.627h3.29l7.737 10.187V.627" fill="#091F2F"/><path d="M83 20h96v3.5H83V20z" fill="#FB4D42"/></g></svg>
<div style="max-width: 66.667rem; margin-left: auto; margin-right: auto;">
  <section style="width: 50%; float: left; line-height: 24px; font-size: 16px;">
  <div style="">
    <h1 style="border-bottom:5px solid #000; color: #091f2f;text-transform: uppercase; font-weight: bold; line-height: 67px; font-size: 40px;">Error</h1>
    <p><em>Sorry! Looks like something went wrong on our end. We're currently working to fix the issue. You can try re-loading the page in a few minutes, or email <a href="mailto:feedback@boston.gov" title="" class="nv-h-l-a" data-modal="feedback">feedback@boston.gov</a> with any questions or concerns.</em></p>
  </div>
  </section>
</div>

</body>
</html>
`

**Comment by subaha-cob** [comment]
@andrebtlima I just emailed you the actual page to attach to your ticket.

**Comment by davidrkupton** [comment]
Re-opening this ticket.  I am not sure if Acquia did this for us or not, I can ask them if there is a custom 500 error.
Also 2 other points:
1. web services such as commissions app should have some better error handling, and we should look into how they can generate error messages that the Drupal framework can accept and display, and 
2. I can see that Drupal 9 has some additional error handling so that unhandled PHP errors on the website don't cause the site to fail, but for the site to raise its own 500 errors.  This means we may have the capability to add the messaging suggested earlier in this issue by Sebastian. 
@duffy-james lets discuss, we can re-close this ticket if you dont want me to look into this.

**Comment by davidrkupton** [comment]
https://drupal.stackexchange.com/questions/248924/custom-500-error-page-is-there-a-way-to-theme-a-fatal-error

Last couple of posts may provide a way for us to add a last-defense catch all for errors, and process them prior to the code failing into Drupals default 500 state.  This may allow us to redirect to a custom page holding the desired error message.

I am 50% hopeful this would work, the 500 error module mentioned in the posts appears not to be well used and for a simple error hook/service I think it would be preferable to have our own solution.

**Comment by duffy-james** [comment]
We have a Jira ticket for this work; closing this for now
