### ISSUE TITLE
boston.gov/trash missing image 

### ISSUE THREAD

**Issue by carolinestj** [CityOfBoston/boston.gov-d8#1005]
boston.gov/trash missing image 

<img width="2042" alt="Screen Shot 2019-11-27 at 9 22 16 AM" src="https://user-images.githubusercontent.com/22770827/69731257-93bfab80-10f7-11ea-927d-3bd487ff987a.png">

**Comment by reillyzlab** [comment]
@carolinestj can you provide the image and I can drop it in? Grid of icon for recycling is the one we're looking for.

**Comment by carolinestj** [comment]
Yeah this is the one we used before! ![HERO-IMAGE-2](https://user-images.githubusercontent.com/22770827/69747899-320e3a00-1115-11ea-823f-85fcc31af60d.jpg)

**Comment by reillyzlab** [comment]
@davidrkupton got the following error message when tried to replace the image in 'recycle right'

This entity (media: 166140) cannot be referenced.

Needs to be placed on these two pages:

- [ ] boston.gov/trash-and-recycling
- [ ] https://www.boston.gov/recycling-boston

**Comment by reillyzlab** [comment]
Closing because resolved.
