### ISSUE TITLE
Metrolist/affordable properties - table sort needed

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1006]
Sort still needed for 'zipcode' for Metrolist/affordable properties - https://www.boston.gov/metrolist/affordable-properties

D8:
![Screen Shot 2019-11-27 at 12 28 08 PM](https://user-images.githubusercontent.com/20731897/69746080-86afb600-1111-11ea-8111-7211f335378e.png)

D7:
Looks like Zipcode was the only sortable column for the Affordable Properties table in D7 (https://boston.prod.acquia-sites.com/metrolist/affordable-properties):

![zip](https://user-images.githubusercontent.com/5913244/69501780-3dbfed80-0ed6-11ea-86c9-d79837ae6079.png)

**Comment by jimafisk** [comment]
Looks like we also need to fix the filters on both https://www.boston.gov/metrolist/lottery-and-resale and https://www.boston.gov/metrolist/affordable-properties

<details>
<summary>Lottery</summary>

![lottery_filters](https://user-images.githubusercontent.com/5913244/69747531-8bc23480-1114-11ea-91ff-f019498b7a12.png)

</details>
<details>
<summary>Affordable Properties</summary>

![affordable_properties_filter](https://user-images.githubusercontent.com/5913244/69747541-9086e880-1114-11ea-9932-efc693657229.png)

</details>

These ^ should be texboxes. With the template fixes I made for the Calendar page, this should be easy to implement.

**Comment by jimafisk** [comment]
This should be all set on next deploy:

<details>
<summary>Lottery Sortable Columns</summary>

![sort_lottery](https://user-images.githubusercontent.com/5913244/69917323-904b5d80-1432-11ea-9758-242f4095921f.png)

</details>
<details>
<summary>Lottery Neighborhood Filter</summary>

![filter_lottery](https://user-images.githubusercontent.com/5913244/69917326-95a8a800-1432-11ea-99e4-6b242d85ddc6.png)

</details>
<details>
<summary>Affordable Properties Sortable Columns</summary>

![sort_ap](https://user-images.githubusercontent.com/5913244/69917331-9b9e8900-1432-11ea-8e9b-e132b1e62f87.png)

</details>
<details>
<summary>Affordable Properties Neighborhood Filter</summary>

![filter_ap](https://user-images.githubusercontent.com/5913244/69917334-a1946a00-1432-11ea-84a6-36098058e65a.png)

</details>

**Comment by reillyzlab** [comment]
@jimafisk Neither item on this page are coming through: https://d8-stg.boston.gov/metrolist/affordable-properties

**Comment by jimafisk** [comment]
@reillyzlab can you check again? I think this was just a caching issue. I purged varnish so I think you should see the changes now. Thanks!

**Comment by reillyzlab** [comment]
Fixed
