### ISSUE TITLE
Acquia files 95% full on prod

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1012]
Acquia files 95% full on prod

See email

**Comment by jimafisk** [comment]
@davidrkupton @mmcgowanBOS what do you think about this proposal?

Short term fix remove all backups from D7 env (maybe even D8 if necessary): 
- `/mnt/gfs/home/boston/drush-backups/`
- `/mnt/files/boston.prod/backups/`

Longer term fix: Move all D7 remnants off the server. Do you think we'll manually need to remove the files dir `/mnt/gfs/boston/sites/default/files`, or will deleting the environment in AC take care of that?
