### ISSUE TITLE
Need ability to hide page

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1016]
Need ability to hide pages from search results and search engines.

Was one of the advanced functionalities on Drupal 7. Could easily select check boxes to choose where to hide.

**Comment by jimafisk** [comment]
We used Rabbit Hole for this in D7: https://www.drupal.org/project/rabbit_hole

**Comment by subaha-cob** [comment]
@andrebtlima we were just chatting about this for accessibility to hide pages from search engines.

**Comment by subaha-cob** [comment]
Test on UAT: https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
@subaha-cob how would I test this?

**Comment by subaha-cob** [comment]
@andrebtlima to test open any page in edit mode
Goto Advanced tab
click Metatags
click Advanced to collapse
find the Robot section
select from the checkboxes

**Comment by andrebtlima** [comment]
Tested on dev. Working properly.
