### ISSUE TITLE
Charts not working on new site

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1022]
The charts on the budget website are not displaying on D8:
<img width="963" alt="Screen Shot 2019-12-02 at 10 45 32 AM" src="https://user-images.githubusercontent.com/12868231/69973079-e2eb4f00-14f0-11ea-9fce-44afb69ebd9f.png">

In the console it looks like maybe D8 is parsing the source code differently:
<img width="641" alt="Screen Shot 2019-12-02 at 10 52 56 AM" src="https://user-images.githubusercontent.com/12868231/69973687-ea5f2800-14f1-11ea-8d2b-76ae2f1c86b4.png">

Let me know if there is a new/better way to get these onto the site in D8, and I'll go through and update them.

**Comment by reillyzlab** [comment]
https://www.boston.gov/finance/fiscal-year-2020

**Comment by reillyzlab** [comment]
D7 link: http://boston.gov/departments/budget/fy20-budget

**Comment by jimafisk** [comment]
D7: https://boston.prod.acquia-sites.com/departments/budget/fy20-budget

**Comment by paylakatel** [comment]
We figured out a solution to this today - we've added a text "type" to the text components called "JSON Friendly" that doesn't do any filtering/changing of the input. l'll now go through and change every chart to use this new text type so they display on the site.

**Comment by andrebtlima** [comment]
Resolved so closing
