### ISSUE TITLE
Event: End time should be optional (not required)

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1024]
End time on event should be optional (not required).

James mentioned this was adjusted on public notices so may be able to replicate that.

![Screen Shot 2019-12-02 at 12 00 32 PM](https://user-images.githubusercontent.com/20731897/69984836-08378780-1508-11ea-9d86-a43e1126091a.png)

**Comment by subaha-cob** [comment]
@andrebtlima This ticket is actually very involved. I have to do a lot of work plus install a new module to get it to work. I will leave it in low priority for now.

**Comment by subaha-cob** [comment]
@andrebtlima test on https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
@subaha-cob as far as I can tell this isn't working on UAT. If I try to create a new event or edit an existing event such that there are no values in the the End Date and End Time field it will not allow me to publish.

**Comment by subaha-cob** [comment]
@andrebtlima can you take a picture of what your form looks like? Basically I am trying to see if you have the new form set up or still using the older one like the one with the error messages above.

**Comment by andrebtlima** [comment]
![Uploading Screen Shot 2020-09-30 at 2.31.37 PM.png…]()

**Comment by subaha-cob** [comment]
@andrebtlima I think I may have misunderstood this bug. Are you saying there will alway be no end day at all?

**Comment by subaha-cob** [comment]
I am not sure where exactly we left this, but @andrebtlima was going to take a look at this and figure if it is really a bug or just how we are adding our end dates.

**Comment by rachelsater** [comment]
This is still an issue that needs to be addressed

**Comment by rachelsater** [comment]
@subaha-cob I'm testing and I'm getting this error

![image](https://user-images.githubusercontent.com/72876352/110487577-b642c180-80bb-11eb-9fa6-b45e2404797a.png)

**Comment by subaha-cob** [comment]
Won't fix.
