### ISSUE TITLE
Data cell not updating in Metrolist lottery page

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1028]
DND is reporting having issues getting a cell to update in the table located on the [lottery and resale opportunities page](https://www.boston.gov/metrolist/lottery-and-resale?combine=&page=1). They were looking to have multiple AMIs listed here:
![image](https://user-images.githubusercontent.com/7929556/70056038-c874ac80-15a8-11ea-996b-e8357b59e485.png)

But only one AMI is coming over from Salesforce. I'm not sure if we've ever had multiple AMIs for this column, but it feels like maybe this is just a character limit issue?

**Comment by duffy-james** [comment]
@reillyzlab @jimafisk DND confirmed that this did work at some point.

**Comment by reillyzlab** [comment]
@AmyWipfler or @SusannaRH22 can you check this here: https://d8-stg.boston.gov/metrolist/lottery-and-resale

And, verify whether this appears to be working on staging before we push to production?

If you can let us know it's whether it's working as a comment in here, or comment what's wrong (if so) with applicable screen shots.

**Comment by AmyWipfler** [comment]
@reillyzlab Unfortunately not working on Staging. Just checked on Canvas Apartments and it should be 60% and 80%, but only 60% is rendering. Let me know when you'd like me to check again!

Metrolist Staging:
![image](https://user-images.githubusercontent.com/55395593/71533326-16d64c00-28c6-11ea-9f99-d47046f3a5c8.png)

Salesforce Record:
![image](https://user-images.githubusercontent.com/55395593/71533357-340b1a80-28c6-11ea-8024-abca475d2eba.png)

**Comment by reillyzlab** [comment]
![Screen Shot 2019-12-30 at 2 36 39 PM](https://user-images.githubusercontent.com/20731897/71597612-ec78ce80-2b11-11ea-8f33-15b9a51d7f12.png)

@davidrkupton still not coming through accurately -- this should be showing 60% and 80%

**Comment by andrebtlima** [comment]
Closing given the current metrolist work happening.
