### ISSUE TITLE
Add back "view" option in related content search

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1029]
In the Drupal 7 site, users could click a "view" link when searching for related content to preview what they were linking to. Looks like we've lost that in Drupal 8:

![image](https://user-images.githubusercontent.com/7929556/70069313-91f65c00-15bf-11ea-859f-09f6f8f5505a.png)

The "view" option would show up alongside the link. After a user clicked on it, it would open the page up in another tab.

**Comment by subaha-cob** [comment]
@andrebtlima  Test on UAT: https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
Tested on develop. Working properly.
