### ISSUE TITLE
Metrolist - table intros getting cut off

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1030]
Metrolist - lottery and resale intro getting cut off

1. boston.gov/metrolist/lottery-and-resale

![Screen Shot 2019-12-03 at 11 34 51 AM](https://user-images.githubusercontent.com/20731897/70070119-0ed60580-15c1-11ea-9cb7-5cfaf7ad4700.png)

2. https://www.boston.gov/metrolist/affordable-properties

![Screen Shot 2019-12-03 at 2 03 17 PM](https://user-images.githubusercontent.com/20731897/70081073-d0971100-15d5-11ea-9deb-15e5ffe5bbee.png)

**Comment by jimafisk** [comment]
@reillyzlab this should be all set on prod now:
- https://www.boston.gov/metrolist/lottery-and-resale
- https://www.boston.gov/metrolist/affordable-properties

If you still notice issues, please reopen. Thanks!
