### ISSUE TITLE
Upcoming news component styling issue - Flags missing

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1031]
Flags and numbers missing from the two left upcoming items:
![image](https://user-images.githubusercontent.com/7929556/70070372-7c823180-15c1-11ea-93e2-1d071ec633e0.png)

Plus main featured item flag missing.

![Screen Shot 2019-12-03 at 2 01 04 PM](https://user-images.githubusercontent.com/20731897/70081149-ff14ec00-15d5-11ea-8dca-d1743a5c4087.png)

Found on homepage

**Comment by jimafisk** [comment]
So it looks like this field is tied to `published_date`:

![published_date](https://user-images.githubusercontent.com/5913244/70275560-5fde2900-177c-11ea-8bec-fb886f5d1cc7.png)

If you set that, it will fix the display:

![display](https://user-images.githubusercontent.com/5913244/70275472-332a1180-177c-11ea-80de-8a14ba7d0f0e.png)

@duffy-james - Is this supposed to be tied to `updated_date` or something else?

**Comment by jimafisk** [comment]
Potentially related "Updated" and "published" dates not automatically being set: https://github.com/CityOfBoston/boston.gov-d8/issues/922

**Comment by reillyzlab** [comment]
Appears to be resolved so closing
