### ISSUE TITLE
URL structure issues

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1033]
On program and article pages, the URL structure did not transfer accurately - many pages are still out of wack. 

This will most highly affect our comparative Google Analytics, but is a big pain point for content editing/historical content references.

Example:
Should be/was on D7: /departments/arts-and-culture/boston-cultural-council 

On D8 it is: /arts-and-culture/boston-cultural-council

How do we bring the /departments back on those pages?

These should also map to the breadcrumbs.

**Comment by reillyzlab** [comment]
@duffy-james please test on staging. if okay, reassign to me and comment

**Comment by duffy-james** [comment]
@reillyzlab still seeing missing url aliases, checked these Transportation and Environment page, and it doesn't appear to be working:
https://d8-stg.boston.gov/environment-and-energy/boston-climate-action

**Comment by reillyzlab** [comment]
Sending back to @davidrkupton to take a look again

**Comment by subaha-cob** [comment]
@andrebtlima It took a while to figure out why url structure was wrong on some pages and correct on others. But it boiled down to simply selecting a department or contact. We should consider making this a required field in the future to avoid things like this.

**Comment by subaha-cob** [comment]
@andrebtlima This is working as expected. The ones that are not working probably do not have a contact or department attached to it. Or the URL alias is manually imported.
