### ISSUE TITLE
Linking to document through "link" option in WYSIWYG field not working

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1037]
Currently, users can search internally for pages on Boston.gov, including documents, through the link button in the WYSIWYG field:
![image](https://user-images.githubusercontent.com/7929556/70158244-eadbf800-1684-11ea-89ca-13a25a4c6a85.png)

But, when you link to a document, it gives you a relative link to the document's location in Drupal, not a publicly resolvable url. Here's an example:
![image](https://user-images.githubusercontent.com/7929556/70158346-19f26980-1685-11ea-8a8b-1e86125bfee4.png)

If you try to click on that link (https://www.boston.gov/media/18356/edit) after saving, its gives you a 403 forbidden error.

We need to either:

- remove the ability to add files this way, or
- fix this so that the link goes directly to a publicly resolvable url for the pdf.

**Comment by andrebtlima** [comment]
Resolved so closing.
