### ISSUE TITLE
Apostrophe showing up as code in title of post

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1040]
The apostrophe in the [title of this post](https://www.boston.gov/news/bostons-first-lgbtq-supported-senior-housing-development-created) is showing up as a character code, instead of the apostrophe:
![image](https://user-images.githubusercontent.com/7929556/70178784-dca0d280-16aa-11ea-9f8e-45d9b3191bca.png)

I haven't noticed this anywhere else, though, so it might be an isolated incident. I jumped into the post itself to see if there was anything that might be causing the error, but didn't see anything.

**Comment by duffy-james** [comment]
Some more examples:
![image](https://user-images.githubusercontent.com/7929556/70259950-48dc0e80-175d-11ea-99e4-55e68b4e059f.png)

Links to those posts:
https://www.boston.gov/news/20-districts-20-days-campaign-support-boston-main-streets-during-holiday-season-kicks
https://www.boston.gov/news/20-districts-20-days-campaign-support-boston-main-streets-during-holiday-season-kicks

**Comment by andrebtlima** [comment]
Resolved so closing.
