### ISSUE TITLE
Drupal Training - Module Updates

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#1042]

**Comment by reillyzlab** [comment]
For update 8.8

**Comment by jimafisk** [comment]
The 8.7 to 8.8 upgrade was tricky, here are update steps that work:
- Get core up to latest 8.7.x version: `lando composer update drupal/core --with-dependencies`
- Upgrade blocking dependency: `lando composer update drupal/pathauto`
- Allow core to move from 8.7 to 8.8: `lando composer require drupal/core:~8.8.1 --no-update`
- Allow fresh install to run: `rm composer.lock` and `rm -R vendor/`
- Run install to get 8.8 code: `lando composer install`
- Fix broken database update: `lando composer update drupal/date_recur` and `lando composer update drupal/date_recur_modular`
- Run database updates: `lando drush updb`
- Export config to match updated database schema: `lando drush cex`

**Comment by reillyzlab** [comment]
Deployed on 12/24.
