### ISSUE TITLE
Adding end date to public notice breaks display on boston.gov/public-notices

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1044]
When a user adds an end date to a public notice, located here in the backend:
![image](https://user-images.githubusercontent.com/7929556/70267611-cbb89580-176c-11ea-9525-020bd008c89a.png)

It breaks the display of the notice on boston.gov/public-notices:
![image](https://user-images.githubusercontent.com/7929556/70267702-f60a5300-176c-11ea-85eb-3dfb17d0c47d.png)

If a user does not add an end date and time, it looks fine:
![image](https://user-images.githubusercontent.com/7929556/70267746-0de1d700-176d-11ea-962d-9810e6311b7c.png)

**Comment by duffy-james** [comment]
I closed issue #1019 because this is related / essentially the same thing

**Comment by andrebtlima** [comment]
Resolved so closing.
