### ISSUE TITLE
Funniness with sidebar and too many horizontal rules

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1050]
Style funkiness on sidebar when sidebar items when items added to pre-set contact template.

Multiple unnecessary horizontal lines.

Example here:

https://www.boston.gov/departments/parks-and-recreation

![Screen Shot 2019-12-06 at 10 44 22 AM](https://user-images.githubusercontent.com/20731897/70335587-9025d600-1815-11ea-9c5c-4504f3282210.png)

**Comment by rachelsater** [comment]
addressed in a different ticket. closing this one
