### ISSUE TITLE
Blank images in the icon uploader - we should clear out

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1051]
If the image isn't appearing in the icon uploader, then we should be clearing this out.

![Screen Shot 2019-12-06 at 10 49 25 AM](https://user-images.githubusercontent.com/20731897/70342538-3c21ee00-1823-11ea-956e-4e54e14cf7dd.png)

We can have a non-developer do this, but we need guidance on what to do.

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine I haven't able to reproduce this. Can you? Is this still an issue?

**Comment by padora-cob** [comment]
I think I found the issue, not sure why caused it but there are only a hand full of icons that have this issue. Looks like someone re-added them at some point as the filename.svg. 

We can apple a fix or we can delete the duplicate entry as it seems the few I have checked were only used in the past on old content revisions. I think it would be safe to try and remove them. 

Let em know if we want a quick meeting to go over this a little more, @duffy-james or @rachelsater

**Comment by rachelsater** [comment]
@padora-cob Let's delete the old ones and see if the issue goes away with that please!

**Comment by padora-cob** [comment]
Sounds good, I will try removing them on STG and do a sanity check that we we don't get any errors or issues. After that I can do the same on PROD.

**Comment by rachelsater** [comment]
you are the best!

**Comment by duffy-james** [comment]
Looks like Alex addressed this in 2021. I don't see this as an existing issue.
