### ISSUE TITLE
Seal covering breadcrumb

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1057]
Seal covering the breadcrumbs when breadcrumb is longer in length. Few examples:

![Screen Shot 2019-12-09 at 1 35 40 PM](https://user-images.githubusercontent.com/20731897/70462486-fb2b1300-1a88-11ea-9ced-c5b0973bee18.png)

![Screen Shot 2019-12-09 at 1 31 35 PM](https://user-images.githubusercontent.com/20731897/70462404-c7e88400-1a88-11ea-8a19-a5ec8f9069f6.png)

**Comment by padora-cob** [comment]
I think the Seal is now only showing on the Home page. Is it supposed to be in every page header? 

If not then I think we can close this issue.

**Comment by reillyzlab** [comment]
@padora-cob the seal shows up on every page when the site alert isn't up.

**Comment by rachelsater** [comment]
@padora-cob is this ready for review? I can't figure it out

**Comment by rachelsater** [comment]
Cannot verify this is still an issue. Closing this ticket. Will create a new ticket if needed
