### ISSUE TITLE
Group of Links - List showing extra text in description

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1061]
There are extra characters appearing at the end of the description text in the Group of Links - List component:
![image](https://user-images.githubusercontent.com/7929556/70470861-fe7aca80-1a99-11ea-955d-b70734230924.png)

There's nothing there on the backend:
![image](https://user-images.githubusercontent.com/7929556/70470909-1e11f300-1a9a-11ea-9627-b8b2e1115d00.png)
![image](https://user-images.githubusercontent.com/7929556/70471005-53b6dc00-1a9a-11ea-8752-c56ea4fc1fa6.png)

But these characters are appearing: &#13

For what it's worth, this appears to be related to the "carriage return":
https://stackoverflow.com/questions/5082253/what-is-html-entity-13

**Comment by andrebtlima** [comment]
Resolved so closing.

**Comment by reillyzlab** [comment]
Resolved so closing
