### ISSUE TITLE
Button text not displaying in backend

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1062]
Instead of showing the text in white, the button link is displaying as the same color as the background:
![image](https://user-images.githubusercontent.com/7929556/70472926-06d50480-1a9e-11ea-9fe7-ee3817d9967c.png)

When you hover, the text does appear:
![image](https://user-images.githubusercontent.com/7929556/70472984-253b0000-1a9e-11ea-9152-5806db21b7c5.png)

**Comment by subaha-cob** [comment]
Test on: https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
Tested on develop. Working properly.
