### ISSUE TITLE
Empty list component set to Bids and RFPs view reads "No Public Notices" 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1066]
The component is still pulling in the procurement advertisement content type, but when there are none published or "posted" it reads "No public notices found." Should probably read, "No procurement advertisements found"

<img width="1433" alt="Screen Shot 2019-12-10 at 10 57 42 AM" src="https://user-images.githubusercontent.com/57111927/70545733-0c812780-1b3c-11ea-9a5c-6e981797a295.png">

**Comment by davidrkupton** [comment]
Less than 1 day.

**Comment by reillyzlab** [comment]
Approved good via #1133
