### ISSUE TITLE
Create new listing template for Procurement Advertisements 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1068]
When list component is set to Bids and RFPs view and Landing display, it pulls in the entire procurement add rather than the list format:

<img width="1433" alt="Screen Shot 2019-12-10 at 11 04 42 AM" src="https://user-images.githubusercontent.com/57111927/70546910-0f7d1780-1b3e-11ea-9cd5-0714a856e73e.png">
<img width="1416" alt="Screen Shot 2019-12-10 at 11 17 40 AM" src="https://user-images.githubusercontent.com/57111927/70547345-b792e080-1b3e-11ea-9d77-5fc811779d57.png">

Additionally, when it pulls in multiple ads, the formatting for the second ad gets messed up:

<img width="679" alt="Screen Shot 2019-12-10 at 11 05 04 AM" src="https://user-images.githubusercontent.com/57111927/70546961-1c9a0680-1b3e-11ea-85a6-b3c0b2d66e5f.png">

**Comment by davidrkupton** [comment]
Approx 1 day work.

**Comment by andrebtlima** [comment]
A few updates from procurement. So the descriptive text that we were talking about is actually the Header component for the Listing Page content type, so no need to do anything there. But the "preview" of the Procurement Advertisement that the List component pulls in when set to View:Bids and RFPs and Display: Landing should have the following information: 

EV/Project #
Project Name
Start Date
End Date
Contact
Procurement type

I made this little mock up just to demonstrate where spatially we'd want these different pieces of information displayed:

<img width="826" alt="Screen Shot 2020-01-10 at 11 59 38 AM" src="https://user-images.githubusercontent.com/57111927/72171311-b99bc980-33a0-11ea-8fb2-cd133a97c6f2.png">
