### ISSUE TITLE
Reset filter missing (and needed) on news, events, public notices

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1073]
Reset filter missing (and needed) on news, events, public notices

See metrolist for example of styling.

**Comment by jimafisk** [comment]
This should be all set on next deploy. Just keep in mind that the reset button only appears once a search has been made to filter results:

<details>
<summary>News</summary>

![news_filter](https://user-images.githubusercontent.com/5913244/70831346-51b58b80-1dc0-11ea-9ecc-4de0271b332e.png)

</details>
<details>
<summary>Events</summary>

![events_filter](https://user-images.githubusercontent.com/5913244/70831351-59753000-1dc0-11ea-8376-397259bb7cc7.png)

</details>
<details>
<summary>Public Notices</summary>

![pn_filter](https://user-images.githubusercontent.com/5913244/70831363-6003a780-1dc0-11ea-9081-2659a2756579.png)


</details>

**Comment by reillyzlab** [comment]
This is resolved so closing
