### ISSUE TITLE
Latest News LP - List showing extra text in description

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/boston.gov-d8#1077]
![image](https://user-images.githubusercontent.com/57374913/70724663-fce31980-1cc8-11ea-9d19-4b9bbb8accfe.png)

https://www.boston.gov/news

**Comment by subaha-cob** [comment]
![image](https://user-images.githubusercontent.com/57374913/70724663-fce31980-1cc8-11ea-9d19-4b9bbb8accfe.png)

**Comment by reillyzlab** [comment]
CLosing because deployed
