### ISSUE TITLE
Add/revise descriptive text in Workbench fields and standardize across Workbench 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1078]

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine is this something we still want to do?

**Comment by duffy-james** [comment]
@rachelsater actually think this would be beneficial, but it would be great to have a starting point. I thought General Assembly did some of that initial work on descriptive text, but I'd have to poke around to see if I can find it.

@jfalvey do you have that research that GA did as part of this project?

**Comment by rachelsater** [comment]
@duffy-james @jfalvey are either one of these the right files?  https://drive.google.com/drive/u/3/folders/1foE2idJ0PIcxo_84s2KTD69F_oYyl6oG 

https://drive.google.com/drive/u/3/folders/1_bojXdClHgiSD6R92mEqtE9sndXVUgdw

**Comment by jfalvey** [comment]
Here's the folder:
https://drive.google.com/drive/u/0/folders/1VHEIv8xYUxeTP9XyH3lmCYNey6KJFKCP

On Wed, Sep 1, 2021 at 9:26 AM rachelsater ***@***.***> wrote:

> @duffy-james
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_duffy-2Djames&d=DwMCAg&c=jHPlKdF3zLuO12CD8lDt5g&r=odOwVJIq7cYqYJrLymzrQOXFK3GJaIlQRfluBTxmYVE&m=LOgX-PZRUk8ZGbXdIh-r6y7ggphD-9IVZXbY9bDBZo0&s=F2Vz9M3h6UWuEAv3W8BApSx7UXy0yPs6fW-INbZxABo&e=>
> @jfalvey
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jfalvey&d=DwMCAg&c=jHPlKdF3zLuO12CD8lDt5g&r=odOwVJIq7cYqYJrLymzrQOXFK3GJaIlQRfluBTxmYVE&m=LOgX-PZRUk8ZGbXdIh-r6y7ggphD-9IVZXbY9bDBZo0&s=8Z5BLXZYXtrDOZXsdHroyDngQgdPhAUZ4hVJsqdLgFw&e=>
> are either one of these the right files?
> https://drive.google.com/drive/u/3/folders/1foE2idJ0PIcxo_84s2KTD69F_oYyl6oG
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__drive.google.com_drive_u_3_folders_1foE2idJ0PIcxo-5F84s2KTD69F-5FoYyl6oG&d=DwMCAg&c=jHPlKdF3zLuO12CD8lDt5g&r=odOwVJIq7cYqYJrLymzrQOXFK3GJaIlQRfluBTxmYVE&m=LOgX-PZRUk8ZGbXdIh-r6y7ggphD-9IVZXbY9bDBZo0&s=uVDf5GlcGGBecfaAQABmsikxa6wZRgA96jB354rqvvw&e=>
>
>
> https://drive.google.com/drive/u/3/folders/1_bojXdClHgiSD6R92mEqtE9sndXVUgdw
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__drive.google.com_drive_u_3_folders_1-5FbojXdClHgiSD6R92mEqtE9sndXVUgdw&d=DwMCAg&c=jHPlKdF3zLuO12CD8lDt5g&r=odOwVJIq7cYqYJrLymzrQOXFK3GJaIlQRfluBTxmYVE&m=LOgX-PZRUk8ZGbXdIh-r6y7ggphD-9IVZXbY9bDBZo0&s=HCc6_XEMddv2NtaGYCoL4mlnlr2SzYQIgEG4MDMDGxk&e=>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CityOfBoston_boston.gov-2Dd8_issues_1078-23issuecomment-2D910284712&d=DwMCAg&c=jHPlKdF3zLuO12CD8lDt5g&r=odOwVJIq7cYqYJrLymzrQOXFK3GJaIlQRfluBTxmYVE&m=LOgX-PZRUk8ZGbXdIh-r6y7ggphD-9IVZXbY9bDBZo0&s=kLB_-gjJlJC1SVMP9QeR3QJH2F44SY3VQIx3SKfGwcs&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AH7AZ4URFP7F5PNPQGDRQYLT7YSZDANCNFSM4J2AKG3A&d=DwMCAg&c=jHPlKdF3zLuO12CD8lDt5g&r=odOwVJIq7cYqYJrLymzrQOXFK3GJaIlQRfluBTxmYVE&m=LOgX-PZRUk8ZGbXdIh-r6y7ggphD-9IVZXbY9bDBZo0&s=_UUzj98PdLdnBzX-S2CuUoF_DAg6UEp-e4dfwonTmx4&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCAg&c=jHPlKdF3zLuO12CD8lDt5g&r=odOwVJIq7cYqYJrLymzrQOXFK3GJaIlQRfluBTxmYVE&m=LOgX-PZRUk8ZGbXdIh-r6y7ggphD-9IVZXbY9bDBZo0&s=mwDVDMRZdzfG1zmNCbk4YuHwfN8rtKmVox7ZFt-A7h0&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCAg&c=jHPlKdF3zLuO12CD8lDt5g&r=odOwVJIq7cYqYJrLymzrQOXFK3GJaIlQRfluBTxmYVE&m=LOgX-PZRUk8ZGbXdIh-r6y7ggphD-9IVZXbY9bDBZo0&s=QrTUzoVu7kyyVT-iJ6FN56tMHgDXaOdankGaV4XeV5M&e=>.
>
>


-- 

[image: COB_B_Blue_square-01.png]

Jeanethe Falvey

Chief Digital Officer, Digital Team <http://boston.gov/digital>

Department of Innovation & Technology

City of Boston | City Hall Room 703

During COVID19 the best way to reach me is through email |
***@***.***


Explore the Digital Team's latest news <http://boston.gov/digital> and active
development <https://github.com/CityOfBoston/digital/wiki>.

**Comment by rachelsater** [comment]
@jfalvey thanks! 
@duffy-james After looking at the documents, which recommendations do we want to go with? Here's an example https://docs.google.com/presentation/d/1JikdJLDySCtZTcjMMws7a-LDjd_ZpVy4/edit#slide=id.p37. Also, I think we will need to prioritize the recommendations. thanks!

**Comment by rachelsater** [comment]
Closing this ticket as most of these issues were either taken care of or are no longer issues
