### ISSUE TITLE
Workbench: Revision selection and 'state' of content

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1082]
When a site admin selection a revision and hits revert, then the state of that content immediately goes to publish, not draft. The content should go to draft.

**Comment by reillyzlab** [comment]
@andrebtlima figuring out what happening for content authors and editors

**Comment by duffy-james** [comment]
@andrebtlima looks like this bug cam back -- I just tried reverting a page and it published the version I tried to revert to.
