### ISSUE TITLE
Enhance the usability for tables outside of short term fixes

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1084]
More info: https://drive.google.com/drive/u/0/folders/1foE2idJ0PIcxo_84s2KTD69F_oYyl6oG

**Comment by reillyzlab** [comment]
Related to #323

**Comment by reillyzlab** [comment]
Here's a 'table style guide' the general assembly group put together: https://docs.google.com/document/d/1JaO-zKP3QnFuOEPVWzY3QD38CCDzdZERHZHIjT_4z9A/edit

**Comment by rachelsater** [comment]
@padora-cob Should I de-couple the one open issue and then close this ticket?

**Comment by padora-cob** [comment]
I think that would be fine.
