### ISSUE TITLE
Group of links - grid - front end UI 

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1086]
When adding a group of links - grid and upload/add a document a user can successful add the document and see that in the workbench. 

However, when clicking the item on the front end UI it does not take the user to the document. A user just clicks clicking on the grid item (box) and nothing happens.

**Comment by jimafisk** [comment]
Hey @reillyzlab I'm having trouble reproducing this. I've tried the following ways:

<details>
<summary>Using CTA</summary>

![output](https://user-images.githubusercontent.com/5913244/70826970-39407380-1db6-11ea-80f3-62047389555a.gif)

</details>
<details>
<summary>Using Grid Links</summary>

![output2](https://user-images.githubusercontent.com/5913244/70826978-3e9dbe00-1db6-11ea-8c7a-3359bdef037e.gif)

</details>

Should I be trying something else? Thanks!

**Comment by reillyzlab** [comment]
Using Chrome and Firefox on MacOS - see example created here: https://d8-stg.boston.gov/departments/licensing-board#testing

Using grid links on group of links - grid

**Comment by jimafisk** [comment]
Ah I see. When I remove the "Grid links" from the component and re-add a new one it seems to work: https://d8-stg.boston.gov/departments/licensing-board

Is it acceptable to fix this manually that way, or have you found so many that it's untenable?

For reference that document was previously using this file: https://d8-stg.boston.gov/files/security-education-platform-module-3pdf

**Comment by andrebtlima** [comment]
This problem is solved by adding a title to the grid link title field which is currently not a required field: 
<img width="1431" alt="Screen Shot 2019-12-19 at 2 43 34 PM" src="https://user-images.githubusercontent.com/57111927/71204370-ff67e500-226d-11ea-88c2-352b78ff7887.png">

**Comment by andrebtlima** [comment]
@jimafisk lets make this title field required and then I'll retest

**Comment by jimafisk** [comment]
Hey @andrebtlima, now that I'm looking at this I see why maybe we didn't require this initially. So the "Title" field circled above actually belongs to the "Document" paragraph (https://boston.lndo.site:3443/admin/structure/paragraphs_type/document/fields), which is used in additional places (not just `grid_links`). So if we make this required, it will be required globally across the site. Is that something you'd like to do? Alternatively, I can update the template to allow the document link to work even if the title is omitted.

**Comment by andrebtlima** [comment]
Hey @jimafisk thanks for looking at this, yeah the latter sounds like the right fix.

**Comment by jimafisk** [comment]
This should be all set on the next deploy. Now if an editor neglects to add a title, the filename will be used by default:

![missing_title](https://user-images.githubusercontent.com/5913244/71298413-f5211600-2355-11ea-91a9-a4931454a46a.png)

The key was line 122 of `docroot/modules/custom/bos_components/modules/bos_link_collections/bos_link_collections.module` was not allowing link creation if the title was missing. I modified it to call `_bos_core_get_file_name` to default to the filename as the title.

**Comment by reillyzlab** [comment]
Approving passed testing

**Comment by andrebtlima** [comment]
Resolved so closing.
