### ISSUE TITLE
Make changes to improve color contrast, visibility of alerts, and recognizability of links to improve accessibility within Drupal Workbench.

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1088]
<img width="743" alt="Screen Shot 2019-12-13 at 10 48 03 AM" src="https://user-images.githubusercontent.com/57111927/70812679-156d3580-1d96-11ea-823e-0e410d34ebc2.png">

**Comment by andrebtlima** [comment]
This was one of General Assembly's recommendations.

**Comment by rachelsater** [comment]
@subaha-cob Since this was created before your accessibility work, should I close this ticket?

**Comment by subaha-cob** [comment]
@rachelsater yes you can close this.

**Comment by rachelsater** [comment]
@subaha-cob thank you!
