### ISSUE TITLE
Reorganize the Image Upload pop-up to reduce errors and prioritize accessibility

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1089]
This was one of General Assembly's recommendations.

<img width="763" alt="Screen Shot 2019-12-13 at 10 50 11 AM" src="https://user-images.githubusercontent.com/57111927/70812831-611fdf00-1d96-11ea-9184-f25adf44cf5c.png">

<img width="722" alt="Screen Shot 2019-12-13 at 10 50 18 AM" src="https://user-images.githubusercontent.com/57111927/70812862-6e3cce00-1d96-11ea-96c8-9f2d37d17f9e.png">

**Comment by duffy-james** [comment]
latest version looks good @padora-cob

**Comment by rachelsater** [comment]
@padora-cob can I close this ticket or not yet?

**Comment by stephaniemar** [comment]
Drupal - 9

**Comment by duffy-james** [comment]
Closing this ticket; info is now in Jira
