### ISSUE TITLE
Design improvements to moderation state display in workbench

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1090]
General Assembly recommended making some changes to the moderation state display in the Workbench, namely adding a sticky moderation state bar to the top of the workbench which reflects (color+text) the moderations state of the page:

<img width="775" alt="Screen Shot 2019-12-13 at 10 57 39 AM" src="https://user-images.githubusercontent.com/57111927/70813416-6d586c00-1d97-11ea-9a46-9c64f59608af.png">

<img width="804" alt="Screen Shot 2019-12-13 at 10 57 47 AM" src="https://user-images.githubusercontent.com/57111927/70813423-6e899900-1d97-11ea-8185-a2178a6d6a66.png">

**Comment by rachelsater** [comment]
this is on Production so I'm closing the ticket
