### ISSUE TITLE
Consistently implement field validation

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1096]
This is another General Assembly recommendation and includes the following individual tasks/enhancements:

**1. Ensure that all required fields are identified with red asterisks and/or descriptive text.**

**2. Ensure that fields with character limits are identified and labeled with descriptive text** 
- Turn the box red in the editor, once the user exceeds the character limit.
- Add character limits to components where shorter copy is preferred (ex. Intro Text).

**Comment by rachelsater** [comment]
@padora-cob In order to get this accomplished, do we need to audit which fields are/aren't identified with the red asterisk/descriptive text?

**Comment by rachelsater** [comment]
@padora-cob In order to get this accomplished, do we need to audit which fields are/aren't identified with the red asterisk/descriptive text?

**Comment by padora-cob** [comment]
@rachelsater, that would be best if we could. If not we can talk about another way to do it.

**Comment by rachelsater** [comment]
@padora-cob nope that's cool. I'll talk to James and Micah about it. thanks!

**Comment by duffy-james** [comment]
@rachelsater I definitely think this would be worth it if someone has the capacity to do an audit of everything.

**Comment by duffy-james** [comment]
closing this ticket; info is moved over to Jira
