### ISSUE TITLE
Cannot access drafts

### ISSUE THREAD

**Issue by SusannaRH22** [CityOfBoston/boston.gov-d8#1101]
Gary Battiston and I have both found that we are unable to view drafts that we have started. We've done a broad search for Type: Any and Published: No and nothing is showing up.

**Comment by reillyzlab** [comment]
@SusannaRH22 can you provide additional details on this? Assuming it's in the filtering on 'my edits', but can you confirm exact location - and include screenshots, if possible.

**Comment by SusannaRH22** [comment]
Yea so in various locations (My workbench--> See all content you have edited; All recent content; and My edits) the available filters/settings are "Title," "Type," "Published," and "Items per page." If I set "Published" to "No," nothing shows up. I recently created a draft (James confirmed it was in Draft status) a couple of weeks ago so something should be there. Also Gary says he should have a draft as well but nothing shows up when he searches either.
![image](https://user-images.githubusercontent.com/23034098/71022244-0821b500-20ce-11ea-8a8d-dd2440264ddc.png)

**Comment by andrebtlima** [comment]
Abbie Melewski got in contact with about this same issue, provided this screenshot:

![image (1)](https://user-images.githubusercontent.com/57111927/71034218-ef71c900-20e6-11ea-8b12-255685534464.png)

She is a Content Author. This isn't happening to me as a Site Admin so it might be a role issue.

**Comment by duffy-james** [comment]
Can confirm this is happening to multiple content authors. I tried adjusting permissions in Drupal, but nothing appears to have worked.

**Comment by andrebtlima** [comment]
Potentially relevant

https://www.drupal.org/project/drupal/issues/2971902

**Comment by reillyzlab** [comment]
I tested this as a content author as well. 

Fix under 'my edits' - 'all recent content' is seemingly still having issues but that's a separate thing to resolve.
