### ISSUE TITLE
Archived public notices displaying end time on main page

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1105]
On the main [archived public notices page](https://www.boston.gov/archived-public-notices), some of the notices are displaying the end date, not the start date of the meeting.

For example, [this public notice](https://www.boston.gov/public-notices/11441) starts at 10 a.m.:
![image](https://user-images.githubusercontent.com/7929556/71012114-912ff080-20bc-11ea-96df-bdb3e72ea66e.png)

But on the main page, it's just saying 3 p.m.:
![image](https://user-images.githubusercontent.com/7929556/71012151-9ee57600-20bc-11ea-842b-cabe01ec2174.png)

Chatted with @davidrkupton and this is probably all related to ticket #1104

**Comment by andrebtlima** [comment]
Resolved so closing.
