### ISSUE TITLE
Potential caching issue with status alerts

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1109]
The street cleaning status item didn't update this morning. It's located here:
![image](https://user-images.githubusercontent.com/7929556/71094072-52f80700-2178-11ea-86fa-40cf3451f929.png)

https://content.boston.gov/street-cleaning

The status alert should have flipped to a new message at midnight, but it looks like the cached version of the message stayed on the site for a bit longer. Talked with @davidrkupton about this, and he's going to look into potential issues with caching and timed items in Drupal.

**Comment by reillyzlab** [comment]
Closing per conversation with team on 12/27
