### ISSUE TITLE
 Content authors should not be able to see any page metadata in the sidebar when creating content

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1110]
Permissions issue for content editors

**Comment by duffy-james** [comment]
@rachelsater content authors and content editors should not be able to see the blue top nav bar here when they log in:

![image](https://user-images.githubusercontent.com/7929556/127190843-ba786efe-049b-448f-a9e8-f6de1ed02bf0.png)

They don't (or shouldn't) have permissions to access any of that information, so there's no reason for them to see it. Same goes for the "page metadata" and "advanced" tabs when you create content in the system:

![image](https://user-images.githubusercontent.com/7929556/127191039-1630ea6a-0609-46b3-9010-37317a4c1960.png)

**Comment by rachelsater** [comment]
@duffy-james got it - thanks!

**Comment by rachelsater** [comment]
@davidrkupton should I close this ticket?

**Comment by duffy-james** [comment]
This can be closed, options were remove for "content authors" from the sidebar.
