### ISSUE TITLE
Time field missing from City Hall public notices board

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1111]
The "time" fields are missing from the public notices board on the first floor of City Hall:
![image](https://user-images.githubusercontent.com/7929556/71103166-a6258600-2187-11ea-8c8c-e29eb4dbab7c.png)

As you can see from the screenshot, the "when" and "posted" sections are empty.

**Comment by reillyzlab** [comment]
Resolved so closing
