### ISSUE TITLE
Remove security update alert from appearing in Choose/Upload Document pop up window (and similar pop up windows) for site admins 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1112]
This issue is happening on desktop and laptop, for chrome, firefox and edge. Essentially, when trying to add/upload a document in a Group of Links -Grid component, when you try and add Grid Links and click the "Choose/Upload Document" the document browser opens but the security alert banner prevents you from seeing or clicking the upload button that appears on the bottom left corner of the browser, thus you can't actually upload the document. You can't scroll past the bottom of the list of documents. 

<img width="1429" alt="Screen Shot 2019-12-18 at 11 50 01 AM" src="https://user-images.githubusercontent.com/57111927/71106190-dcb1cf80-218c-11ea-91c1-edef02bef9e8.png">

I think this could be fixed by removing the security update banner. Not from the whole workbench. Just from the pop up window.

**Comment by jimafisk** [comment]
We should probably make that popup window scroll since when @andrebtlima and I looked together, even without the security alert he could just barely see the button. It looks fine on my screen, but it's dependent on the user's screen resolution - there could be folks who don't see it at all.
