### ISSUE TITLE
Title of posts blending into background in news component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1113]
When a user hovers over one of the four related "posts" in a "new and announcements" component, the text blends into the background. Here's a video of what I'm talking about:

https://drive.google.com/file/d/15gQxuj3h9THxu3mUdiKK6AHOOUw1lUNa/view

In some quick testing, it looks like this is only appearing when you have a "news and announcements" component looking for "related" items. The homepage is pulling in all posts, and it appears fine.

I also couldn't confirm if this is also happening with the "events" component. I didn't have any examples on the live site to check.

**Comment by reillyzlab** [comment]
Resolved
