### ISSUE TITLE
Clone option no longer working for content types

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1120]
I attempted to clone an event, but it's not working. I tried clicking "clone" in the sidebar, and at the top of the page, but neither appear to work. Here's a video of the error:
https://drive.google.com/file/d/1rTAnBUBTH9Ktm51mFU-N2S_3bup5A8DL/view

And here's a screenshot of the error:
![image](https://user-images.githubusercontent.com/7929556/71260205-4e625880-2308-11ea-8d0f-14be16aa0ad0.png)

I can confirm that this worked for me two weeks ago. I built a series of public notices for a department and cloned the same notice each time.

**Comment by reillyzlab** [comment]
Duplicate is working for components. This only applies to content types.

**Comment by andrebtlima** [comment]
resolved so closing.

**Comment by andrebtlima** [comment]
Cloning seems to be working on most content types but still not working on events.

**Comment by andrebtlima** [comment]
@subaha-cob if you have time you could take another look at cloning. I'm still unable to clone content on production. Getting this error:

<img width="1070" alt="Screen Shot 2020-03-11 at 10 43 23 AM" src="https://user-images.githubusercontent.com/57111927/76429353-4ead4580-6385-11ea-8b0d-7ab98b2d2025.png">
