### ISSUE TITLE
Add a "department" filter to the events page

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1121]
Currently, users can filter based off:

- the date of the event
- the title of the event
- the event type
- the event neighborhood

![image](https://user-images.githubusercontent.com/7929556/71260416-d6486280-2308-11ea-9db8-dc12bdd08e73.png)

I'd like to add an additional filter that allows users to filter by City Department.

**Comment by duffy-james** [comment]
looks good @padora-cob

**Comment by rachelsater** [comment]
@padora-cob Can I close this ticket?

**Comment by padora-cob** [comment]
Good to go :)

**Comment by rachelsater** [comment]
thanks!
