### ISSUE TITLE
Add a department filter to backend of workbench under "my edits" and "all recent content"

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1122]
Currently, users going to "my edits" or "all recent content" are only able to search the title of the page, filter by content "type", or check by whether the page is published or not:
![image](https://user-images.githubusercontent.com/7929556/71260677-71413c80-2309-11ea-9b0a-a9531d90b850.png)

I'd like to add another option that allows users to filter by City department. In the system, this is the "contact" taxonomy.

**Comment by padora-cob** [comment]
Ready for review on CI: 
![image](https://user-images.githubusercontent.com/62249548/117049850-b38ed200-ace2-11eb-85ec-64019980a31a.png)
