### ISSUE TITLE
EVENT/PROJECT NUMBER field should not be required 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1124]
Not all bids will actually have this number.

<img width="838" alt="Screen Shot 2019-12-20 at 12 30 10 PM" src="https://user-images.githubusercontent.com/57111927/71278087-9becbe80-2324-11ea-9ad5-d7d94561034a.png">

**Comment by mmcgowanBOS** [comment]
This may not be an issue, we determined that this field is needed to build a URL for the actual procurement page / individual listing. Will let Andre follow up.

**Comment by andrebtlima** [comment]
Erik from procurement suggested the following:

If the field is left blank, i.e. nothing is ent under that Event/Project field on the page, the URL could be a sequential number assigned by Drupal as the date and the number bid as entered that day.
The first bid listing with a blank Event ID entered January 6, 2020 appears as boston.gov/bid-listings/202001061
The second bid listing with a blank Event ID entered January 6, 2020 appears as boston.gov/bid-listings/202001062 
The third bid listing with a blank Event ID entered January 6, 2020 appears as boston.gov/bid-listings/202001063

The date does not need to have significance to start date or end date because those can change, so the date it was initially entered is fine.  If Drupal is not able to assign a number based on logic like that, we can come up with an alternative.

**Comment by andrebtlima** [comment]
No longer relevant so closing.
