### ISSUE TITLE
Content Editors & Content Authors can't change the moderation state

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#1129]
@reillyzlab and @andrebtlima did some testing on dev and found an issue. When editing preexisting content (but not creating new content) content editors and content authors (tested both) can't change the moderation state - the only option in the drop down is Draft when there should be option to change to Needs Review.

<img width="1424" alt="moderation_state" src="https://user-images.githubusercontent.com/5913244/71298643-10d8ec00-2357-11ea-8ff4-b606d7cd3fcb.png">

**Comment by jimafisk** [comment]
I update this so `content_author`s can move from "draft" to "needs review":

<details>
<summary>See screenshot</summary>

![content_author](https://user-images.githubusercontent.com/5913244/71299494-8646bb80-235b-11ea-8586-2135c71acd27.png)

</details>

The `content_editor` role is interesting because it doesn't have access to the admin toolbar, so if it's the only role a user has, navigating admin screens is difficult. I assume this is because it it supposed to be used in addition to the `content_author` role to layer on more permissions. This user can set to "needs review" or "published":

<details>
<summary>See screenshot</summary>

![content_editor](https://user-images.githubusercontent.com/5913244/71299544-d4f45580-235b-11ea-9fb1-e83eba112165.png)

</details>

They previously had publishing access, just let me know if that shouldn't be the case:

<details>
<summary>Workflow permissions matrix</summary>

![publish_transition](https://user-images.githubusercontent.com/5913244/71299615-3caaa080-235c-11ea-95a9-516f6837e472.png)

</details>

**Comment by reillyzlab** [comment]
This was resolved before to going to production, so closing this ticket.
