### ISSUE TITLE
Styling issue on listings on pay and apply

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1132]
![Screen Shot 2019-12-23 at 3 58 49 PM](https://user-images.githubusercontent.com/20731897/71380486-5b4baa00-259d-11ea-8a1a-14833309410e.png)

Minor styling issue on some list items on /pay-and-apply

Miscellaneous characters in the descriptive text.

**Comment by phillipbentonkelly** [comment]
![Screenshot 2019-12-23 16 38 35](https://user-images.githubusercontent.com/2627273/71381729-cc419080-25a2-11ea-94bc-ca39ebb7f65b.png)
- [Preview](https://content.boston.gov/boston-ems-patient-feedback)
- [Content Edit](https://content.boston.gov/node/6026/edit?destination=/admin/content%3Ftitle%3Dboston%2520ems%26type%3DAll%26status%3DAll%26langcode%3DAll)


Looks like some HTML got pasted by mistake. Might just that be a simple fix.
