### ISSUE TITLE
"Media entity embed" option should display most recent uploads first

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1140]
When a user uploads a new image or pulls from the image library in the WYSIWYG field, they click on the "media entity embed" link, located here:
![image](https://user-images.githubusercontent.com/7929556/71477953-0a190180-27bb-11ea-8abd-1d235122b545.png)

In the next window that pops up, the image library is displaying the oldest images first, with the last page of the image search being the most recent uploads. I want to reverse this, so that users see the most recently uploaded images first. Here's a screenshot of the window I'm talking about:
![image](https://user-images.githubusercontent.com/7929556/71477994-477d8f00-27bb-11ea-806d-66ea3d374ce5.png)

**Comment by rachelsater** [comment]
@padora-cob  this looks good. ready to move to the next step in the process
