### ISSUE TITLE
"Holidays" text not displaying on homepage

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1141]
Holiday dates are added to the system through structure > taxonomy > holidays. When a new date is added, the text replaces the date at the top of the homepage. It also displays all in red. So, for example, if the date at the top of the homepage here was Christmas:
![image](https://user-images.githubusercontent.com/7929556/71478551-50239480-27be-11ea-8c09-a1a72a53e30f.png)

It would display "Christmas Day", all in red, instead of the date of "Wednesday, December 25."

When I checked for Christmas this year, it didn't appear to work. I went ahead and added all of the holiday dates for 2020, so we could potentially test again on New Year's Day.

**Comment by davidrkupton** [comment]
![image](https://user-images.githubusercontent.com/4700050/71536212-07adc900-28db-11ea-886c-6873ca6728e8.png)
