### ISSUE TITLE
Port salesforce_term_ref module to D8

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#1143]
We used the [salesforce_term_ref](https://www.drupal.org/project/salesforce_term_ref) module in D7 to map incoming plain text data from Salesforce to our Neighborhood taxonomy. We should create a D8 version of this module in order to get this working on the new Boston.gov site.

See @SusannaRH22's note from https://github.com/CityOfBoston/boston.gov-d8/issues/1098:
> Also, the neighborhood/city fields are not showing up on listings either. This was reported but I wasn't sure if it was a Drupal 8 migration bug or not, because I was reviewing the code logic and couldn't figure how the salesforce fields were actually being referenced. For now, I've asked Caitlin to include the Neighborhood/City in the listing title, as an easy fix, but I do think the listing is supposed to include the neighborhood field, and maybe also the secondary "outside boston location" field-- would be good to know the expected behavior here, and if it is buggin currently.

**Comment by jimafisk** [comment]
The quickest path to getting this working in the short term was to add some logic to our custom module, which I've done. In the future it would be nice to port the salesforce_term_ref module to make this configurable. 

<details>
<summary>Screenshot of the data coming across in the view</summary>

![neighborhoods_in_view](https://user-images.githubusercontent.com/5913244/71488718-11a6cd80-27f0-11ea-8458-0f4df77beb03.png)

</details>

<details>
<summary>Screenshots of data on node and source from SF</summary>

Drupal node:
![neighborhoods](https://user-images.githubusercontent.com/5913244/71488729-25eaca80-27f0-11ea-8f54-2fa27fb7638b.png)

Salesforce record:
![sf_neighborhood](https://user-images.githubusercontent.com/5913244/71488743-2e430580-27f0-11ea-81d5-ee0b7852b4e5.png)

</details>

**Comment by reillyzlab** [comment]
@davidrkupton There should be neighborhoods linking back to neighborhood pages. Still not appearing on staging. Re-assigning to you

**Comment by reillyzlab** [comment]
@padora-cob @mmcgowanBOS is this something we shoudl still or can we close?

**Comment by reillyzlab** [comment]
With 2020-2021 updates to metrolist list this is no longer needed. Used a more up-to-date module for this project.
