### ISSUE TITLE
Revisit language on recurring events - M

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1144]
The default language is a bit hit or miss. This [Immigrant Advancement event](https://www.boston.gov/calendar/free-immigration-consultations-volunteer-attorneys) repeats on the first and third Wednesday of the month during the year:
![image](https://user-images.githubusercontent.com/7929556/71481828-743aa200-27cd-11ea-8186-5def40197829.png)

I know working out the logic will be a bit complicated to make the text consistent. I wonder if maybe we set up the logic for display on our calendar page and in the event component, but then allow users to add their own text.

**Comment by duffy-james** [comment]
Any updates might be related to #857 and #975

**Comment by duffy-james** [comment]
@rachelsater here's what I'm thinking specifically for the monthly updates. Here are the variations I can think of for the dev team:

"Repeats on the [day of week] each month through [end date]"

"Repeats on the [day of week] each month for [number] times"

"Repeats on the [day of week] and [day of week] each month through [end date]"

"Repeats on the [day of week] and [day of wee] each month for [number] times"

"Repeats on the [day of week], [day of week], and [day of week] each month through [end date]"

"Repeats on the [day of week], [day of week], and [day of week] each month for [number] times"

The other "repeating" options all seem fine to continue to use. This update is really just for the "monthly" repeating events.

**Comment by rachelsater** [comment]
@duffy-james thanks! @padora-cob is this enough for the ticket or do you need more information?

**Comment by padora-cob** [comment]
@rachelsater, I think it is enough to get me going. I will let you know if there are any scenarios that are not covered by the above language.

**Comment by rachelsater** [comment]
thank you!

**Comment by davidrkupton** [comment]
this may be helpful: I used this with the date_recur component in site alerts: /home/david/sources/boston.gov-d8/docroot/modules/custom/bos_components/modules/bos_messages/src/Plugin/Field/FieldWidget/MODRecurWidget.php

**Comment by duffy-james** [comment]
Closing this ticket out; now accounted for in Jira
