### ISSUE TITLE
"Full column wide (embedded)" option not responsive in WYSIWYG

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1162]
In the WYSIWYG field, the "full column wide (embedded)" option is not responsive to different screen sizes. Ideally, if a user picks this option, the image should respond to whatever screen size our users are on. Currently, we appear to just crop on the left-hand and right-hand sides of images.

[Here's a video of what I'm talking about](https://drive.google.com/file/d/1UUUyp6ww81IxaArQ5Qq3RHMel13Eiqd4/view).

Also, you can kind of see what I'm talking about in these screenshots. Here's the image before minimizing the window:
![image](https://user-images.githubusercontent.com/7929556/71832492-0e75d200-3079-11ea-87cb-d70f7b9a8a5b.png)

And here's after:
![image](https://user-images.githubusercontent.com/7929556/71832534-2188a200-3079-11ea-8995-bef53c613815.png)

**Comment by andrebtlima** [comment]
@duffy-james could you give me an example of this on production? Might be helpful for solving this issue. Thx

**Comment by andrebtlima** [comment]
This looks good on staging. Ready to push to production.
