### ISSUE TITLE
"1/3 column wide (embedded)" option in WYSIWYG cropping images on left and right

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1163]
When a user selects the "1/3 column wide (embedded)" option in the WYSIWYG field, the left-hand and right-hand sides of the images get cropped. They also continue to get cut off as the screen is minimized. Ideally, these images should stay responsive with the screen and maintain the aspect ratio for their height and width.

Here's a screenshot for an image before adding the "1/3" look:
![image](https://user-images.githubusercontent.com/7929556/71833470-f8691100-307a-11ea-9dff-d49ad786e994.png)

Here's what it looks like after (you can see he slight crop on left and right):
![image](https://user-images.githubusercontent.com/7929556/71833512-1171c200-307b-11ea-9821-7b9ce3e0ca1f.png)

[And here's a video](https://drive.google.com/file/d/1N4Ux0dGBRBZFxVaYr8afg1FutS6_OV6r/view) of what it looks like as you minimize.

For what it's worth, the "1/2 column wide (embedded)" option appears to be working in the dropdown.

**Comment by andrebtlima** [comment]
This looks good on staging. Ready to push to production.
