### ISSUE TITLE
Contrast on Featured Guides issue

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1169]
<img width="1434" alt="Screen Shot 2020-01-07 at 3 29 44 PM" src="https://user-images.githubusercontent.com/57111927/71927020-91bf2280-3162-11ea-9c7a-8825b5a5f130.png">
<img width="1437" alt="Screen Shot 2020-01-07 at 3 29 37 PM" src="https://user-images.githubusercontent.com/57111927/71927021-9257b900-3162-11ea-97ec-8a2efd7bdb47.png">

**Comment by davidrkupton** [comment]
Hey, an idea for this, we could add a drop shadow, or a contrasting border to the text (like we did with the date-ribbon on featured items).  This may go some way to helping the lost-text situation, although it will never be a true a11y solution - to do that requires a re-think and re-design (e.g. (on mouse-over) a gradient down each card to the primary color, with the text set (or moving) lower over the primary color area - I've never been sure what value the 1,2,3,4 element provides, although its caused us much effort to get working.....)

**Comment by reillyzlab** [comment]
@sebastianebarb this mentions a contrast issue. Can you look it over and let us know if you see an issue and how you'd advise adjusting if so?

**Comment by sebastianebarb** [comment]
I would like to keep the photo as it's one f the few ways the site is less flat. we have also gotten positive feedback on it. can we make the overlay look more like the header on the home page? ![Screen Shot 2021-04-12 at 3 26 19 PM](https://user-images.githubusercontent.com/20642299/114450045-83e92000-9ba3-11eb-93e3-f10cd9203bf1.png)

**Comment by subaha-cob** [comment]
Check UAT for solution https://d8-uat.boston.gov/

**Comment by rachelsater** [comment]
@subaha-cob looks good to me! @duffy-james whatcha think?

**Comment by stephaniemar** [comment]
Hey @carolinestj do you have any thoughts on this?

**Comment by carolinestj** [comment]
If we could make all instances of the text look white when it's on a photo that would be best, see screenshot 1 for example 

The blue text with the white is really wonky looking and not on brand and probably very hard to read, see screenshot 2 for example 

![screenshot 1](https://user-images.githubusercontent.com/22770827/153638450-cb0b685e-9f95-4cfb-a78b-59391221e860.png)
![screenshot 2](https://user-images.githubusercontent.com/22770827/153638448-a16a5862-9a2c-4bfe-abf4-d36145e21f98.png)

**Comment by subaha-cob** [comment]
@duffy-james this is on UAT
https://d8-uat.boston.gov/

**Comment by duffy-james** [comment]
@subaha-cob fix this; closing issue
