### ISSUE TITLE
Google calendar integration for events calendar 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1170]

**Comment by mmcgowanBOS** [comment]
Spoke to Jeaenethe and wants to make this a priority if there is downtime in between projects.
For example see Eventbrite integration "Add to clanedar".
https://www.eventbrite.com/e/a-feminists-guide-to-botany-online-botanical-painting-session-tickets-121982903147?aff=ebdssbcitybrowse&keep_tld=1

**Comment by subaha-cob** [comment]
@mmcgowanBOS @andrebtlima Got it. Adding to my to dos.

**Comment by subaha-cob** [comment]
Currently on UAT. Minus the ability to add future recurring events.

**Comment by andrebtlima** [comment]
Closing this ticket, related tickets #1806 and #1807 still open
