### ISSUE TITLE
News component should pull in content based on "published date"

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1184]
Currently the news component is pulling in posts based on the "authored on" date. 
![image](https://user-images.githubusercontent.com/57111927/72444578-48805b80-377e-11ea-8050-438bd11a8154.png)

**Comment by subaha-cob** [comment]
@andrebtlima Can you give me a URL of the page this is occurring on? I started working on, but I realized I may be working on the wrong page.

**Comment by subaha-cob** [comment]
@andrebtlima I don't think this is still an issue. let me know if it is though. Also add a link to a sample page for me to reproduce or steps to reproduce.

**Comment by andrebtlima** [comment]
@subaha-cob we probably have this fixed on most pages because we've gotten into the habit of just correcting the issue on a case by case basis as it arises. @duffy-james , you can correct me if I'm mischaracterizing this. Let's say someone were to create an article and add Neighborhood Development in the Related Content tab of the editor. This would mean that theoretically this article would get pulled into the news component on DND's department profile page when the article was published. But I think the news component looks for the "Authored Date" of a node to determine whether to pull in, i.e. nodes authored more recently will show up in the news component over nodes authored a while ago. But this creates a problem when someone creates a node, let's say an article again, and doesn't actually publish it. So this node has already been "authored" but hasn't been published. So if the person waits to publish that node for a while, it will likely not show up in a given new component because based on it's "authored date" it's old. I think that's what's happening. Does that make sense?

**Comment by rachelsater** [comment]
Closing
