### ISSUE TITLE
Events page only shows first instance of recurring events 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1187]

**Comment by duffy-james** [comment]
@andrebtlima looks like this is broken again on the actual events page. I'm not seeing any of the recurring events now (ignore the pop-up events, they're one-offs):

![image](https://user-images.githubusercontent.com/7929556/76217869-9ac38300-61e9-11ea-9ea0-ebf9d69e598f.png)

I'm going back to fix, but that was a screenshot as of this morning.
