### ISSUE TITLE
Preferred contact field should be required (phone vs. email) in Person Profile

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1188]

**Comment by andrebtlima** [comment]
The option for N/A should be removed.

**Comment by reillyzlab** [comment]
@duffy-james I'm seeing these profiles for example which makes me feel like N/A should be an option. Thoughts? / Can we close this and leave as is?

https://www.boston.gov/innovation-and-technology/digital-equity-fund#digital-equity-fund-council

**Comment by duffy-james** [comment]
Agree, this should be closed. 

We've leveraged person profiles in other ways on Boston.gov that shouldn't make these fields required (per your example).
