### ISSUE TITLE
When viewing a revision, I don't see the "Tasks" button in top right-hand corner

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1190]
When viewing a revision, I'm not seeing the "Tasks" button in the right hand corner that I see on drafts and other pages:
<img width="1277" alt="Screen Shot 2020-01-22 at 2 18 13 PM" src="https://user-images.githubusercontent.com/12868231/72926404-63c10d00-3d22-11ea-98fe-4f294b848213.png">
<img width="1280" alt="Screen Shot 2020-01-22 at 2 21 01 PM" src="https://user-images.githubusercontent.com/12868231/72926457-720f2900-3d22-11ea-9117-d244af2d6c4e.png">

Expected behavior: to be able to view the "Tasks" button and see the options for publishing the revision like I can when viewing a draft or published page:
<img width="1280" alt="Screen Shot 2020-01-22 at 2 22 07 PM" src="https://user-images.githubusercontent.com/12868231/72926562-a7b41200-3d22-11ea-9f55-7a32a7b44c73.png">

**Comment by reillyzlab** [comment]
Closing this ticket - updates to the workbench were done after this
