### ISSUE TITLE
Add feature to export .csv of active users 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1195]

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine is this something we still want to add? thanks

**Comment by duffy-james** [comment]
@rachelsater depends? I don't think it's a major priority, but I was just looking for a way to export a csv of all of the users in Drupal. An export feature — full stop — might be a nice addition. For instance, the ability to pull a csv of specific content types, or content from a specific department, would be a great addition if it's not too much of a lift.

**Comment by padora-cob** [comment]
Just need to add and configure the Views Data Export module: https://www.drupal.org/project/views_data_export
