### ISSUE TITLE
Orphaned components

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1200]
When trying to edit a page, there will be components that show up on the published page like the map component below: 
![image](https://user-images.githubusercontent.com/12868231/73384347-1bad6780-4299-11ea-8024-5e59e5cc988f.png)

But when I go to edit the page, the component is not in the list of components (no map listed):
![image](https://user-images.githubusercontent.com/12868231/73384410-3aabf980-4299-11ea-872b-8420d5d14706.png)

If I try to edit the component itself, it says it is orphaned: 
![image](https://user-images.githubusercontent.com/12868231/73384460-51525080-4299-11ea-8140-eafc25d55a3e.png)

If I try to edit and save or delete the component from that screen, I get this error:
![image](https://user-images.githubusercontent.com/12868231/73384532-71820f80-4299-11ea-94a9-2c3766ae3d66.png)

We don't think that this is a problem with just map components as André and I have seen this behavior before with Boards and Commissions components, but we were unable to take screenshots and reproduce the error.

**Comment by rachelsater** [comment]
@duffy-james is this still an issue?

**Comment by rachelsater** [comment]
@duffy-james hiya! is this still an issue? thanks!
