### ISSUE TITLE
Wrong message when search returns no results in Pay and Apply

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1229]
The message here should read "No results found" but instead reads

<img width="1437" alt="Screen Shot 2020-02-10 at 4 01 56 PM" src="https://user-images.githubusercontent.com/57111927/74189672-d8e77a00-4c1e-11ea-99e6-70428a88e6cb.png">

**Comment by reillyzlab** [comment]
Wont' do because we're doing larger changes to pay and apply.
