### ISSUE TITLE
Add document section in components getting cut off at bottom

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1231]
If a user tries to add an existing document to a component, the button to actually add the document is getting cut off. In this example, I'm trying to add the five-year-plan-2020-0.pdf document:
![image](https://user-images.githubusercontent.com/7929556/74467147-8a2c2100-4e66-11ea-9bb4-8d3653e770f5.png)

You can see the bottom is getting cut off, including the button to upload. I'm assuming this is getting cut off because of the security notice at the top.

**Comment by andrebtlima** [comment]
related to #1112

**Comment by reillyzlab** [comment]
This is no longer an issue so closing
