### ISSUE TITLE
Add Department and Cabinet options for Awarding Authority field

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1240]
Currently, the field Awarding Authority is pulling from the Contact category of our taxonomy. That category only contains departments, not cabinets, so if there is a procurement advertisement for which the Awarding Authority is a Cabinet, you will not be able to enter it into that field because, again, our taxonomy does not include Cabinets. 

I think the most straight forward solution here would be to keep the autocomplete text field but allow the field to also accept a value that is not found in the taxonomy. If that won't work, I think the solution then is to offer the user two options. To enter a department or a cabinet, with two different text fields one that autocompletes, pulling from the Contacts section of the taxonomy, and the other a standard write in field for Cabinets. Using the two fields would be mutually exclusive, so if a user entered info in the Department text field they would not be able to enter anything in the Cabinet text field, and vice versa.

**Comment by reillyzlab** [comment]
Haven't heard anything since launch. Won't do, but can re-open later if need be.
