### ISSUE TITLE
Component styling (drawer) issues on how-to pages

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1273]
The drawers component on [this how-to page](https://www.boston.gov/departments/neighborhood-development/boston-home-center/get-financial-help-remove-lead-your-home) has a lot of extra padding, also the title is tight to the container at the top: 

![image](https://user-images.githubusercontent.com/7929556/76335598-2f51e200-62cb-11ea-8e29-f352ca6a6149.png)

For a frame of reference, here's how it should look:
![image](https://user-images.githubusercontent.com/7929556/76335716-527c9180-62cb-11ea-9b4f-50b40e723078.png)

My guess is that it's been like this for a while. We typically don't add components to how-to pages, so it would have been tough for someone to catch.

**Comment by reillyzlab** [comment]
@duffy-james is this still an issue?

**Comment by reillyzlab** [comment]
@sebastianebarb specs for mobile may be needed.

**Comment by padora-cob** [comment]
I believe that this will no longer be an issue once we change out the main styling for the How-To content type via this ticket: https://github.com/CityOfBoston/boston.gov-d8/issues/1808

**Comment by padora-cob** [comment]
The styles that are "leaking": 
![image](https://user-images.githubusercontent.com/62249548/117482148-f692b480-af31-11eb-86e0-5157df488193.png)

**Comment by padora-cob** [comment]
This issue should fixed with the #1808 updates to How-To pages and can be closed once PR #2063 is merged.  

It can be tested at: https://d8-ci.boston.gov/departments/neighborhood-development/boston-home-center/get-financial-help-remove-lead-your-home

**Comment by rachelsater** [comment]
@padora-cob I asked Julianne to review these and here's her feedback:

It looks good, but the behaviors should be like the regular drawers.  For example, the + should spin to - 
the > should as well. They should act the same way they do on this page https://www.boston.gov/bphc-permits
