### ISSUE TITLE
Can't filter redirects without errors/ filter not working

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1305]
When trying to filter and search through old redirects on the site, I keep running across the same error message:
![image](https://user-images.githubusercontent.com/7929556/78827852-cc2e9a80-79b1-11ea-89fa-78b0f102c7b2.png)

In particular, I'm trying to remove the redirects for these pages so I can republish the content:

/how-get-boat-mooring-permit
/renew-boat-mooring-permit
/apply-boat-mooring-permit

@davidrkupton suspects there might be a memory issue.

**Comment by andrebtlima** [comment]
I'm not getting that error, but looks like the filter is just straight up not working. Unless I'm doing something wrong

**Comment by reillyzlab** [comment]
Closing this ticket
