### ISSUE TITLE
Problem when adding a public notice as a featured item on Events and Notices component 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1306]
On prod, when you add a public notice (rather than event) as a featured item in an Events and Notices component,  it pulls in the full notice not the preview card:

<img width="775" alt="Screen Shot 2020-04-09 at 12 35 40 PM" src="https://user-images.githubusercontent.com/57111927/78920832-035c8480-7a62-11ea-92df-6ab9359ec113.png">
<img width="1436" alt="Screen Shot 2020-04-09 at 12 35 06 PM" src="https://user-images.githubusercontent.com/57111927/78920838-048db180-7a62-11ea-92b4-b32869c7f19e.png">

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine is this still an issue? thanks

**Comment by duffy-james** [comment]
@rachelsater this is still an issue — my guess is that it's related to the fact that the "public notice" content type doesn't have a thumbnail image. It would be great if we could just force a default icon for all of our notices. We don't need to add the ability to include images to notices, similar to our events.

**Comment by rachelsater** [comment]
@duffy-james ah ok. which default icon were you thinking?

**Comment by duffy-james** [comment]
@rachelsater it would be the same icon we were using before for our notices when the "Events and notices" component included images:

![image](https://user-images.githubusercontent.com/7929556/130259466-bd308fbd-b2b7-4712-a3fe-3e9eea6de21c.png)

Just a bigger version of that would be fine for the "featured" section.

**Comment by duffy-james** [comment]
@subaha-cob fixed this; closing the ticket
