### ISSUE TITLE
Fix File ID missing error on live site

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1355]
Some pages on Boston.gov display a "file ID (number) is missing ()" on the live site:
![image](https://user-images.githubusercontent.com/7929556/81582653-491cad80-937e-11ea-8c2f-cdb23807806b.png)

Here are a few examples I've seen so far:

https://www.boston.gov/departments/youth-engagement-and-employment
https://www.boston.gov/departments/diversity/black-employee-network/black-history-boston
https://www.boston.gov/departments/womens-advancement

I'm sure there are other pages as well. What I'm trying to figure out is:

1. What is missing on these pages?
2. How can I fix it?

I'm assuming there's an issue one of the images on these pages, but if there was a way for me to narrow that down, it would be a huge help.

**Comment by duffy-james** [comment]
Here's some more examples of this:

https://www.boston.gov/departments/landmarks-commission
https://www.boston.gov/departments/womens-advancement

**Comment by reillyzlab** [comment]
Closing this ticket
