### ISSUE TITLE
Remove the "preview" button under the "moderation state"

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1356]
Can we remove the "preview" button, located here?

![image](https://user-images.githubusercontent.com/7929556/81584133-576bc900-9380-11ea-9727-95984aae6f84.png)

I spoke with a user working on drafted content, and he was getting error messages when clicking on the preview button. Since users can already preview their content in "draft" form when they save, this button seems confusing/redundant. I also want to encourage our users to save their work as much as possible.

**Comment by padora-cob** [comment]
I removed access to the preview action for all roles except administrators. If you would also like me to remove it for administrators just let me know.

**Comment by duffy-james** [comment]
looks good @padora-cob — I can't see the "preview" button.

**Comment by rachelsater** [comment]
@padora-cob Can we close this?

**Comment by padora-cob** [comment]
Sure can, thanks!

**Comment by rachelsater** [comment]
thank you!
