### ISSUE TITLE
Update "newsletter" component message after subscription

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1358]
Currently in our newsletter component, a user is shown this message after entering their email address and zip code and subscribing:

![image](https://user-images.githubusercontent.com/7929556/81859391-2d0e3d00-9533-11ea-984e-9842e78339be.png)

We need to adjust this message so it makes more sense for the user. I'm hoping to add a message like this:

"If this is the first time you've subscribed to a City of Boston newsletter, you'll see a confirmation email in your inbox to confirm your subscription. If you don't see that email, be sure to check your spam and junk folders."

**Comment by davidrkupton** [comment]
This is a patterns change.
The text is set in `scripts/components/newsletter.js`, Line 27.
Update there and then redeploy patterns.

**Comment by andrebtlima** [comment]
@subaha-cob if you make this change, we can deploy with the next round of accessibility updates

**Comment by subaha-cob** [comment]
@andrebtlima fixed. Test in UAT once I push today.

**Comment by subaha-cob** [comment]
Pushed to UAT: https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
@subaha-cob I'm still seeing the original message in UAT: 
![Uploading Screen Shot 2020-09-22 at 1.31.16 PM.png…]()

**Comment by subaha-cob** [comment]
@andrebtlima I am seeing the change. See image below.
![image](https://user-images.githubusercontent.com/57374913/93918843-ebf51900-fcda-11ea-8b58-df2f282a7eda.png)

But just to clarify which page are you testing?

**Comment by andrebtlima** [comment]
@subaha-cob looks like my screenshot didn't upload properly. I was testing on the home page. Maybe a caching issue. let me try incognito

**Comment by andrebtlima** [comment]
@subaha-cob yep, it worked. ok moving to Ready to Deploy

**Comment by andrebtlima** [comment]
Tested on develop. Working properly.
