### ISSUE TITLE
Top of site alert getting cut off on pages

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1381]
There's currently a site alert set up across all pages on Boston.gov, minus the homepage. It appears that the top quarter of the FYI component is slightly cut off:
![image](https://user-images.githubusercontent.com/7929556/82252937-fe6ed880-991d-11ea-8b23-389908ea5593.png)
![image](https://user-images.githubusercontent.com/7929556/82252952-062e7d00-991e-11ea-8e93-a2e511a2fa3f.png)

It appears that the error is on all of our content types. I checked and saw the error on Chrome, Firefox, and Safari.

**Comment by andrebtlima** [comment]
@duffy-james I'm no longer seeing this issue, but did you see this when you were logged into Drupal? Or were you hitting the site as an anonymous user.

**Comment by rachelsater** [comment]
working on production!
