### ISSUE TITLE
Modules are not under GPL

### ISSUE THREAD

**Issue by sdubois** [CityOfBoston/boston.gov-d8#1388]
https://github.com/CityOfBoston/boston.gov-d8/tree/develop/docroot/modules/custom
https://www.drupal.org/about/licensing#project-licensing

Drupal modules are considered derivative works of Drupal and are required to be licensed under the GPL.

**Comment by rachelsater** [comment]
@mmcgowanBOS @padora-cob Is this something that still needs to be addressed?

**Comment by mmcgowanBOS** [comment]
Hi Rachel,
There was a whole email chain in response to this. @davidrkupton gave a pretty thorough response, and I believe we decided that is probably makes the most sense for us to switch to the GPL license and be in line with the greater Drupal community. For now though we are more or less going to ignore until someone from our legal team or Chief @jfalvey can clarify the reasons past stakeholders chose the CCO1.0  license.

**Comment by rachelsater** [comment]
@mmcgowanBOS sounds good! should I close this ticket or leave it?

**Comment by mmcgowanBOS** [comment]
I guess we can keep it open.

**Comment by rachelsater** [comment]
fab thanks!
