### ISSUE TITLE
Remove extra spacing in 'full column wide (embedded)' option of 'formatted text' components

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1389]
In the WYSIWYG fields of Boston.gov for the "formatted text" component, you have options to add different photo stylings to images. The "full column wide (embedded)" options, located here:
![image](https://user-images.githubusercontent.com/7929556/82685945-0632c380-9c23-11ea-8cdf-4b72172c3ad7.png)

creates a lot of white space on the left and right of the image:
![image](https://user-images.githubusercontent.com/7929556/82686017-22cefb80-9c23-11ea-963f-5d20d05d878d.png)
![image](https://user-images.githubusercontent.com/7929556/82686353-bc96a880-9c23-11ea-8715-0fee24d05491.png)

To be clear, in the "body" field of our content types, this option for some reason works. However, in the "formatted text" _component_, it does not fully embed in its container. I'm hoping we can remove this extra spacing and make sure the image is fully embedded and responsive in these text components.

**Comment by rachelsater** [comment]
'm closing this ticket because I created a new ticket (#1995) to address this and other spacing issue fixes.
