### ISSUE TITLE
Drupal previewing old pdfs in "draft" view instead of new, updated versions

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1411]
A user is reporting an issue where, when she uploads a new pdf to a component replacing an existing pdf, she can only see the old pdf in "draft" when she previews the page. However, when the page is published, the correct, new link appears live on the site. And, when you go back into the page, the correct link is now there.

She's getting confused because she can't tell if her new pdf is making it up on the site. This specific issue is on [this page on the site](https://www.boston.gov/departments/parks-and-recreation/parcel-priority-plan), in the "grid of cards" component for "survey results", but I think I've run into this issue elsewhere.

**Comment by rachelsater** [comment]
@duffy-james Is this still an issue?

**Comment by duffy-james** [comment]
just tested @rachelsater -- not an issue anymore.
