### ISSUE TITLE
Finalize Design edits to match boston.gov

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1452]
@sebastianebarb

Re: [notes on Metrolist.pdf]

- AMI Estimator
  - Remove border [on Yearly/Monthly toggle] - Removed the gray border from the blue “selected” state. If you’re saying we should remove the entire border then please specify (though I think that would make it harder to make out the buttons).
  - Un-round corners
    - The rounded corners are not part of the button but rather the focus outline. In Chrome 83 (released a few weeks ago) the focus outline changed from a drop-shadow to a rounded border. Unfortunately in Chrome there is no way to modify the border radius without also changing the outline’s overall appearance. Notably when I do change to the squared style, then we also lose the outline around the AMI filter’s range thumbs (see attached). The range thumbs still turn red when highlighted but from an accessibility standpoint we can’t rely on color alone to convey information. But regardless, if the outline style is to be modified at all it should probably be modified for all of Boston.gov and not just Metrolist so we have a consistent experience.

@André Lima

Re: https://docs.google.com/document/d/1y7RMUiQkozv4pJfhBMspk1UtrSmO75XndrvwN2HRbr0/edit?usp=sharing

- Search
  - When user clicks on one of the drawers it adds a white space/box select, but only at the top
    - This is also due to the focus outline. Can remove but not without the same issues described above.

**Comment by AmyWipfler** [comment]
[notes on Metrolist (2).pdf](https://github.com/CityOfBoston/boston.gov-d8/files/4815570/notes.on.Metrolist.2.pdf)

**Comment by AmyWipfler** [comment]
![AMI Filter - Focus Outline Comparison](https://user-images.githubusercontent.com/55395593/85335004-45fefc00-b4aa-11ea-8146-7f826d7edbe5.png)

**Comment by AmyWipfler** [comment]
Was prioritzed for 6/ 21-7/2 sprint, but did not get feedback on the above notes. Backlogged for remaining work.

**Comment by reillyzlab** [comment]
@lizcormack-bos any idea on whether this is outstanding or if we should close? 

I can also loop back with Marcy if that's better?

**Comment by lizcormack-bos** [comment]
@reillyzlab I'm not sure about this one! I doubt Marcy would know either - could Sebastian confirm whether these changes are live?

**Comment by reillyzlab** [comment]
Potentially @sebastianebarb do you think there is more we need to do here or do you think we can close this ticket?

**Comment by reillyzlab** [comment]
Confirmed with Sebastian, closing
