### ISSUE TITLE
As a housing seeker, I want to be able to access all URLs in the AMI Estimator experience, so that I don't get 404 errors.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1455]
URLs to map:

- https://www.boston.gov/metrolist/ami-estimator/household-income
- https://www.boston.gov/metrolist/ami-estimator/disclosure
- https://www.boston.gov/metrolist/ami-estimator/result

**Comment by padora-cob** [comment]
The URLs should now be mapped to the JS app on CI.

**Comment by AmyWipfler** [comment]
Validation that functionality works as expected.

**Comment by padora-cob** [comment]
This is now ready to test on CI.
