### ISSUE TITLE
When large enough numbers are entered, different numbers are sent to the text field of the AMI Estimator

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1458]
Screen Capture:
2020 05 07, When large enough numbers are entered, different numbers are sent to the text field.mp4
 
Title:
When large enough numbers are entered, different numbers are sent to the text field
 
Steps:
1.     Go to the URL for the calculator
2.     Choose a number for the amount of people in the household
3.     00:00 – Enter 1111111 until the numbers being entered change
 
Expected Results:
·      The numbers being entered do not change from one
 
Actual Results:
·      The numbers being entered eventually change from one to different numbers (This happens at 00:05)

**Comment by ebshrier** [comment]
unable to recreate

**Comment by duffy-james** [comment]
Closing issue for now.
