### ISSUE TITLE
As a housing seeker, I would like to not be shown any results that have a minimum income threshold above my income, so that I don't waste my time investigating them.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1491]
- Data entered during AMI Estimator use should inform what listings are shown to a user
- Minimum income values should surface in a way that the user can tell a filter has been applied
- For unit combos that do not have minimum income values entered, the user should not be deterred from applying
- A user should be able to remove the application of a minimum income attribute

**Comment by padora-cob** [comment]
I need to add the "minimumIncome" field to the Units object with the data we already have. If we have no value for minimum income then we will hand back a NULL value.

**Comment by padora-cob** [comment]
minimumIncome has been added to the Development API on the CI ENV. 

![image](https://user-images.githubusercontent.com/62249548/86614588-3b039b80-bf81-11ea-8aa9-1f997498962d.png)

**Comment by padora-cob** [comment]
Updated the new field name to "incomeQualification" 
![image](https://user-images.githubusercontent.com/62249548/86624323-1fa08c80-bf91-11ea-954a-1a80d83cc932.png)

**Comment by AmyWipfler** [comment]
@hguiney Do you want me to test this yet? Not seeing any changes on CI

**Comment by AmyWipfler** [comment]
@hguiney Ran a test, and wasn't able to validate functionality.Here's the steps of what I ran in CI on Chrome

1. Entered an annual income of $40,000/yr for a family of 4 in the AMI Estimator.
2. Went to the search page, selected the check box in the top right that read "Hide I-R homes with min thresholds >$40,000 year"

Expected result: Listings at The Beverly (where minimum incomes are $70,000+) would be removed from my options
Actual result: No listings changed, I was still shown The Beverly as an option.

**Comment by AmyWipfler** [comment]
I like the checkbox design/placement! Can we change the copy next to it to "Hide homes that require a household income over [$ annual income]/year

Let me know if you want me to run this by users for design  comments. Thanks!

**Comment by AmyWipfler** [comment]
@hguiney I re-ran the test with the updated API and it worked great! Do you have ideas about how the checkbox placement can work with mobile? atm, it's a bit out of place

**Comment by AmyWipfler** [comment]
@hguiney Mobile looks good! Can you change the copy to "Hide homes that require a household income over [$ annual income]/year" before we deploy tomorrow? Thanks!
