### ISSUE TITLE
As a housing seeker, I would like more guarantee that listings on ML are still available to be rented, so that I don't waste my time applying to units that are already filled

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1492]
- In any FCFS listings, there should be a way for a user to notfiy the ML Program manager that they were told this housing is no longer available.
- Property Managers who have submitted any listing should be asked the status of their posting every 2 weeks
- Property Managers should be given a streamlined way to signal the removal of a listing from the site
- Any reminders to Property managers should not go out to any listings with Lottery Deadlines

**Comment by padora-cob** [comment]
I think we can us a webform or two to let the users submit when they think a Unit is no longer available. Will need to know where to put the call to action button(s) and what values we would want on the forms. 

After that we can hook the new webforms up to SF is wanted.
