### ISSUE TITLE
As a housing seeker, I want to be able to filter listings by Rental Price, so that I can find housing within my budget.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1495]
- While on the Search page, a user should be able to toggle/enter a rental price ceiling and floor that effects which units/listings they see
- Any listing that does not have a set rent price should show regardless of use of a price filter
- The price filter should be the top filter option (above current Offer section)

**Comment by hguiney** [comment]
@AmyWipfler Ready for review: https://d8-ci.boston.gov/metrolist/search

**Comment by AmyWipfler** [comment]
Looking great @hguiney ! Review notes here:

- Noticed that we lost the ** for any listings that do not have a fixed rent price.
![image](https://user-images.githubusercontent.com/55395593/87076431-be2a2900-c1ef-11ea-9323-bb97bf0513d1.png)

- Is it possible to clarify that the 0-4000 slider is price per month? Perhaps we add the copy "per month" behind the larger  rent price number here?
![image](https://user-images.githubusercontent.com/55395593/87076541-eade4080-c1ef-11ea-9a17-406eab317e6a.png)

- I'm tempted to place the Rental Price Filter section below the Offer Filter section, in the hopes that a user selects "For Rent" before engaging with this filter so that it's less confusing to have For Sale units showing up. Thoughts? There may be a better way to solve for that confusion.

**Comment by AmyWipfler** [comment]
I also expected the filter to be able to apply to the units within a given property card, similar to how the AMI filter works. So in this screenshot I would expect to see all items except the 1 bedroom units that cost $1440/month.

![image](https://user-images.githubusercontent.com/55395593/87077644-6ee4f800-c1f1-11ea-9d9d-47a1a2639dc2.png)
