### ISSUE TITLE
As PM of Metrolist, I would like to implement Google Tag Manager for the Filtering options on the search page, so that I better understand how users are interacting with the site.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1504]
- There should be an aggregate way to see the volume of interactions with key filter fields (see image)

**Comment by AmyWipfler** [comment]
![Filter Tags_1](https://user-images.githubusercontent.com/55395593/86405885-22913980-bc80-11ea-8d7a-abae643e8c7c.png)
![Filter Tags_2](https://user-images.githubusercontent.com/55395593/86405887-2329d000-bc80-11ea-9191-2dd9d9d2de02.png)

**Comment by mmcgowanBOS** [comment]
This is now live on Boston.gov and can be seen in Google Analytics Event Tracking.

https://analytics.google.com/analytics/web/#/report/content-event-events/a99773468w108307691p112911200/_u.date00=20200711&_u.date01=20200711&explorer-segmentExplorer.segmentId=analytics.eventAction&_r.drilldown=analytics.eventCategory:Metrolist&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22PT%22,%22filter%22,0%5D%5D/

I'm going to close and re-assign to @AmyWipfler . If there are any issues, please feel free to re-open.

Thanks.
