### ISSUE TITLE
My neighborhood: Add card for mayor

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1521]
In the representation section of my neighborhood look up, we need to add a card for the mayor. The card layout should follow the same format at the City Council and ONS cards.

- The card title should read "Your Mayor".
- [This picture of the mayor should show](https://www.boston.gov/sites/default/files/styles/person_photo_profile_large_360x360_/public/img/2016/w/walsh-bio.jpg?itok=HJhj2cqZ).
- Under the picture, it should read "MARTIN J. WALSH" 
- Under the name, it should read "Learn more about [Boston's mayor](https://www.boston.gov/departments/mayors-office/martin-j-walsh)."

**Comment by paylakatel** [comment]
Looks good on dev2 except I see a small typo on "Learn more about Boston's Mayor" (it says "Major").
<img width="519" alt="Screen Shot 2020-07-18 at 1 58 21 PM" src="https://user-images.githubusercontent.com/12868231/87858837-cfb1b600-c8fe-11ea-81b5-509ad4d39e3e.png">

**Comment by mmcgowanBOS** [comment]
OK. Updated and ready for review on dev2.

https://d8-dev2.boston.gov/my-neighborhood

**Comment by paylakatel** [comment]
Looks good on dev2.

**Comment by mmcgowanBOS** [comment]
This is now live on Prod. Closing for now.
