### ISSUE TITLE
My neighborhood: Add card for state/federal representatives

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1522]
Could we add a card to the "Representation" section that follows the same format as the "Street Sweeping" card in the "City Services" section.

- The title of the card should be "Your State and Federal Reps"
- We can use this "person" icon as the icon:
![person](https://user-images.githubusercontent.com/12868231/87466788-e4333d00-c5e4-11ea-898b-cc51964dc2ac.png)
- The text should read: "For more information on your State and Federal representatives, visit the [Find My Legislator tool](https://malegislature.gov/search/findmylegislator)."

**Comment by paylakatel** [comment]
Looks good on dev2.

**Comment by mmcgowanBOS** [comment]
Great. CLosing for now.

**Comment by paylakatel** [comment]
@mmcgowanBOS per conversation with Jeanethe in slack, can we change the title of this card to read "State and Federal Representation"

**Comment by mmcgowanBOS** [comment]
OK. Updated and ready for review on dev2.

https://d8-dev2.boston.gov/my-neighborhood

**Comment by paylakatel** [comment]
Looks good on dev2

**Comment by mmcgowanBOS** [comment]
This is now live on Prod. Closing for now.
