### ISSUE TITLE
My neighborhood: Update "Note" section on pools card

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1523]
On the "Pools" card in the "Summer Resources" section, could we change the "Note" text to read: "For more information about pool hours during COVID-19, please visit the [BCYF page](https://www.boston.gov/departments/boston-centers-youth-families)."

**Comment by paylakatel** [comment]
Update to the language: "Only some outdoor pools are open during COVID-19, but they are open to all City residents. For more information about pool hours during COVID-19, please visit the [BCYF page](https://www.boston.gov/departments/boston-centers-youth-families)."

**Comment by paylakatel** [comment]
@mmcgowanBOS on dev2, it looks the language was updated with the original language, not the sentence in the comment below ("Only some outdoor pools are open during COVID-19, but they are open to all City residents. For more information about pool hours during COVID-19, please visit the BCYF page.") that we talked about with Jeanethe on Thursday.
<img width="311" alt="Screen Shot 2020-07-18 at 1 56 29 PM" src="https://user-images.githubusercontent.com/12868231/87858792-7c3f6800-c8fe-11ea-9f76-90168f626c89.png">

**Comment by mmcgowanBOS** [comment]
OK. Updated and ready for review on dev2.

https://d8-dev2.boston.gov/my-neighborhood

**Comment by paylakatel** [comment]
@mmcgowanBOS Could we add this same disclaimer ("Only some outdoor pools are open during COVID-19, but they are open to all City residents. For more information about pool hours during COVID-19, please visit the BCYF page.") to the BCYF locations card it self in the "City Spaces" section:
<img width="1367" alt="Screen Shot 2020-07-20 at 12 20 27 PM" src="https://user-images.githubusercontent.com/12868231/87961206-66a77b00-ca83-11ea-9273-b3100cba7393.png">

**Comment by paylakatel** [comment]
Looks good on dev2.

**Comment by mmcgowanBOS** [comment]
This is now live on Prod. Closing for now.

**Comment by paylakatel** [comment]
@mmcgowanBOS we got new language for this. Could we change the "note" section on this card to read: "BCYF Clougherty and Mirabella Outdoor Pools are open at limited capacity by reservation only to City of Boston residents. All other BCYF indoor pools remain closed at this time due to COVID-19 restrictions. We have new procedures this year that you can read more about at [Boston.gov/BCYF](https://www.boston.gov/departments/boston-centers-youth-families)."

**Comment by mmcgowanBOS** [comment]
This is updated and ready to review on dev2.

https://d8-dev2.boston.gov/my-neighborhood

**Comment by paylakatel** [comment]
This looks good on dev2.

**Comment by paylakatel** [comment]
One more small change to the language here. Could we make the "note" section read: 

"BCYF Clougherty and Mirabella outdoor pools are open at limited capacity by reservation only to City of Boston residents. All other BCYF indoor pools will remain open only for participating youth for in-person summer programming at this time. We have new protocols and procedures this year that you can read more about on the [BCYF page](https://boston.gov/departments/boston-centers-youth-families)."

**Comment by mmcgowanBOS** [comment]
OK. This has been updated and read for review on dev2.

https://d8-dev2.boston.gov/my-neighborhood

**Comment by paylakatel** [comment]
this looks good on dev2.
