### ISSUE TITLE
My neighborhood: My neighborhood: Update "Note" section on the library card

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1524]
On the library card in the "City Spaces" section, could we update the "Note" text to read: "To learn more about the city's library system and library hours during COVID-19, visit [blp.org](https://www.bpl.org/)."

**Comment by paylakatel** [comment]
Update to the language: "Due to COVID-19, BPL sites are offering modified services. Please visit [blp.org](https://www.bpl.org/) for more information about what sites are open and their hours."

**Comment by paylakatel** [comment]
@mmcgowanBOS on dev2, it looks the language was updated with the original language, not the sentence in the comment below ("Due to COVID-19, BPL sites are offering modified services. Please visit blp.org for more information about what sites are open and their hours.") that we talked about with Jeanethe on Thursday.

**Comment by mmcgowanBOS** [comment]
OK. Updated and ready for review on dev2.

https://d8-dev2.boston.gov/my-neighborhood

**Comment by paylakatel** [comment]
Looks good on dev2.

**Comment by mmcgowanBOS** [comment]
This is now live on Prod. Closing for now.
