### ISSUE TITLE
My neighborhood: Use "splash pads" instead of "tot sprays"

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1525]
We need to switch out our use of "tot sprays" on my neighborhood to "splash pads".

- On the "Summer Resources" section card, could we make the description text read "Cooling centers, pools and splash pads near you."
- On the "Tot Spray" card, could we change the title to "A splash pad near you"
- On the "Tot Spray" card, could we change the header text to read "Splash pad location"

**Comment by paylakatel** [comment]
Looks good on dev2

**Comment by mmcgowanBOS** [comment]
Great. Closing for now.
