### ISSUE TITLE
My neighborhood: Translation on my neighborhood

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1527]
Would it be possible to make the translate button work on the my neighborhood application? If not, what service would we need and what would the estimated cost of the service be?

This definitely tied into other efforts around translate that have been going on, so may warrant a larger conversation about how to effectively implement this across web-apps on the site.

**Comment by mmcgowanBOS** [comment]
This seems to be working. Ready to review using the Google Translate free tool.

https://translate.google.com/translate?sl=auto&u=https%3A%2F%2Fd8-dev2.boston.gov%2Fmy-neighborhood

**Comment by paylakatel** [comment]
On the my neighborhood page on dev2, I don't see the "Translate" button in the header: 
<img width="1440" alt="Screen Shot 2020-07-23 at 9 53 55 AM" src="https://user-images.githubusercontent.com/12868231/88294618-7b298480-ccca-11ea-940d-88b6dd2741b8.png">

Also, when I visit the link above, I can't select an address. When I click on one, it populates the search box, but no cards show up. [Here is a screen recording of what I'm talking about.](https://drive.google.com/file/d/1QAXHEEv0mmCjjo5afEkE6tHBGTrZXRTZ/view?usp=sharing)

**Comment by mmcgowanBOS** [comment]
OK. I just spent some time with Alex Dora and we have resolved the Varnish cache issue. The Translate button should now appear AND the Google Translate service should work as well. Again, "36A Belmont St..." is the only address that will display the cards in dev2. Please let me know if anything isn't working for you.

https://d8-dev2.boston.gov/my-neighborhood

**Comment by paylakatel** [comment]
This looks good on dev2! thank you!

**Comment by mmcgowanBOS** [comment]
OK. I'm going to close for now. Feel free to re-open if need be.
