### ISSUE TITLE
My neighborhood: update subheader text for "Representation" screen

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1539]
On the "Representation" screen, could we change the subheader text (circled below) with this: "Your representation and voting information."
<img width="1205" alt="Screen Shot 2020-07-21 at 9 35 37 AM" src="https://user-images.githubusercontent.com/12868231/88061551-a464dc00-cb35-11ea-919d-a91409074768.png">

**Comment by mmcgowanBOS** [comment]
Updated and ready for review on dev2.

https://d8-dev2.boston.gov/my-neighborhood

**Comment by paylakatel** [comment]
Looks good on dev2.

**Comment by mmcgowanBOS** [comment]
OK. I'm going to close for now. Feel free to re-open if need be.
