### ISSUE TITLE
My neighborhood: Polling location "note" text update

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1540]
On the "Polling Location" card, could we update the "note" text so that it reads:

"Find out if you are [registered to vote](https://www.sec.state.ma.us/VoterRegistrationSearch/MyVoterRegStatus.aspx) and [where your polling location is](https://www.sec.state.ma.us/VoterRegistrationSearch/MyVoterRegStatus.aspx)." 
<img width="374" alt="Screen Shot 2020-07-21 at 9 45 29 AM" src="https://user-images.githubusercontent.com/12868231/88062537-f5290480-cb36-11ea-8759-9fd59ed1487b.png">

**Comment by mmcgowanBOS** [comment]
https://d8-dev2.boston.gov/my-neighborhood

**Comment by paylakatel** [comment]
This looks good on dev2.

**Comment by mmcgowanBOS** [comment]
OK. This is updated and read for review on dev2.

https://d8-dev2.boston.gov/my-neighborhood

**Comment by paylakatel** [comment]
This looks good on dev2. Thank you!
