### ISSUE TITLE
City Hall background in text component - should be removed.

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1550]
Text component in Drupal allows users to select adding a 'City Hall icon' to the text component background. 

This shouldn't be allowed across the website.

**Comment by reillyzlab** [comment]
@duffy-james @sebastianebarb assuming we should remove this, correct? Or would be there a reason we should keep?

**Comment by sebastianebarb** [comment]
I am fine with removing, no one uses it.

**Comment by reillyzlab** [comment]
Let's remove this as an option. Low priority.

**Comment by reillyzlab** [comment]
If this isn't concerning let's leave it as an option and focus time elsewhere. Closing ticket; we can re-open if it becomes an issue
