### ISSUE TITLE
My neighborhood: remove "cooling centers" language 

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1551]
We need to remove "cooling centers" from the "Summer resources" card. I believe we only use this language in the following two places: 

1. The section card should just read "Pools and splash pads near you." 
<img width="361" alt="Screen Shot 2020-07-27 at 9 51 02 AM" src="https://user-images.githubusercontent.com/12868231/88549751-b12e7780-cfee-11ea-81ad-d914c92cdc83.png">

2. The header text in the "Summer Resources" section should read "Pools and splash pads near you."
<img width="1126" alt="Screen Shot 2020-07-27 at 9 51 40 AM" src="https://user-images.githubusercontent.com/12868231/88549829-c7d4ce80-cfee-11ea-8884-25411257434f.png">

**Comment by mmcgowanBOS** [comment]
Updated on Prod. Closing for now.
