### ISSUE TITLE
As a housing seeker, I want to be informed that there are no units available in a Development where all Units are Closed, so that I understand I have missed the window to apply should I find the link to the page in future.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1554]

**Comment by padora-cob** [comment]
Will need to know what the UI/Copy is for this, but implementation should be simple.

**Comment by AmyWipfler** [comment]
@padora-cob Here's my Google Doc mockup of what we'd want users to see: https://docs.google.com/document/d/1EYWfS5mIG9OFUMzgJ2Wgy-49kJHFnIoqCMOnXqOlCWU/edit?usp=sharing

**Comment by padora-cob** [comment]
Ready for review on CI.
