### ISSUE TITLE
My neighborhood: update clean up process to remove duplicates 

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1556]
As discussed in our meeting on 7/29 with David, Matt is going to update the clean up process code so it removes any potential duplicates from the Drupal database. 

This function is needed right now to address the ~1500 duplicate records in the Drupal database, but should not be needed in the future as 1. we should not get sent duplicates from the Analytics Team and 2. the import process should not add any duplicate SAM IDs (it should just update 1 record twice if it encounters a duplicate). That said, this is a good fail safe to add to the clean up code to make sure we don't end up with duplicate records that are stale in the Drupal database.

**Comment by mmcgowanBOS** [comment]
This has been updated and is now live on Prod. We added a removeDupes function that is part of the mnl_cleanup queue worker. mnl_cleanup queue worker is and has been scheduled to run after every import on the 2nd of every month. The cleanup / de-dupe worker can be triggered manually too via drush (drush queue-run mnl_cleanup) at any time.

https://github.com/CityOfBoston/boston.gov-d8/pull/1566

Closing for now. Feel free to re-open if any issues come about.
