### ISSUE TITLE
My neighborhood: update language on historic districts card

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1567]
Can we update the "Note" section on the "Historic Districts" card under the "City Spaces" section to read: 

"Learn more about the [City's historic districts](https://www.boston.gov/departments/landmarks-commission) and [what it means to be inside of one](https://www.boston.gov/departments/landmarks-commission/how-we-review-design-changes-historic-districts)."

<img width="368" alt="Screen Shot 2020-08-04 at 12 06 31 PM" src="https://user-images.githubusercontent.com/12868231/89317148-fe43c680-d64a-11ea-8f7c-56c341afc28a.png">

**Comment by mmcgowanBOS** [comment]
This has been updated and is up on Prod now. Closing for now. Feel free to re-open if I missed anything.

https://www.boston.gov/my-neighborhood

**Comment by paylakatel** [comment]
This looks good - thank you!
