### ISSUE TITLE
Unable to update and save my neighborhood boston.gov page

### ISSUE THREAD

**Issue by paylakatel** [CityOfBoston/boston.gov-d8#1603]
I am trying to update a link on the transaction grid component on the my neighborhood look up page that is below the actual web app.

When I make a change to that component and try to save the page, I get this error message and am unable to save it:
<img width="1280" alt="Screen Shot 2020-09-14 at 10 16 38 AM" src="https://user-images.githubusercontent.com/12868231/93098266-aac68e80-f674-11ea-8ed1-34b10b7dd13e.png">

**Comment by mmcgowanBOS** [comment]
I just looked into this and it seems there are some config settings that were overwritten recently, possibly by last weeks's core update.

**Comment by paylakatel** [comment]
working on production now - thank you.
