### ISSUE TITLE
AMI Values from AMI Estimator are not being pulled over to Search filters as expected.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1606]
Expected result = Whatever AMI% is recommended for me, will be auto-assigned to the AMI Filter on the Metro list Search page.

Actual result = I calculate my AMI and am routed to the Metrolist search page with no filters applied.

**Comment by mmcgowanBOS** [comment]
@AmyWipfler and @andrebtlima , I updated the code base with a condition that seems to have fixed the issue.  It appears Hugh did have a condition in place to check for the recommended AMI, but some of the variables were being overwritten and never were actually applied to the filter. In any event this is working for me now. I've deployed to the Dev env in Acquia. You can test it with the link below. If this looks good to both of you I can continue pushing this up through the pipe to Production.

https://d8-dev.boston.gov/metrolist

Thanks!

**Comment by andrebtlima** [comment]
@mmcgowanBOS working for me as well.

**Comment by mmcgowanBOS** [comment]
OK. I just pushed this to Prod and seems to be working there as well. Going to close for now.

Thanks everyone.
