### ISSUE TITLE
As a ML user, I would like the option to include my email address when I submit feedback on the ML Feedback Form, so that DND has the opportunity to follow-up with me about my feedback.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1619]
- Have the option to add email in a text field as part of form submission
- Have that email address legible in the email that is sent to Dana/Amy/DND
- Locate the text field below the other open text field, but before "Submit"

**Comment by padora-cob** [comment]
Added new email field per request, ready to test on CI.

**Comment by AmyWipfler** [comment]
Implemented
