### ISSUE TITLE
As a community member, I would like the data most important to me in DND projects to be legible on BuildingHousing, so that I can learn what I want without having to contact DND.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1623]
- MVP Content Plan
- Atomic/molecule level content

**Comment by lizcormack-bos** [comment]
MVP Content UX Requirement Document: https://docs.google.com/document/d/1SGyAnTOgB4wgibFDF180mIWRYSPSagem36OJ50dQlzM/edit?usp=sharing

In progress! Cross referencing the Field Usage Data here: https://docs.google.com/spreadsheets/d/171sYSdGeWKukXzgwLM-7Ge4r44hixdqPmKHCB8q2_v4/edit?usp=sharing
