### ISSUE TITLE
Get Project Information

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1624]
- Connection to Salesforce should be stable, high capacity, and never expire
- All data from Salesforce should be stored Drupal-side for further manipulation as needed

**Comment by padora-cob** [comment]
- Connect to the new BH SF sandbox on LOCAL and CI
- Create new branch for buildinghousing_ci and deploy to CI
- Create Drupal entities (Project, Parcel, Account, Contact) - Starting with these main objects
- Create basic mapping between Drupal Entities and SF Objects (Project, Parcel, Account, Contact)
- Verify data sync between Drupal and SF for (Project, Parcel, Account, Contact) - Import data
- Create default display pages for (Project, Parcel, Account, Contact)
- Create Views list page, for development use, for (Project, Parcel)
