### ISSUE TITLE
Copy updates to Metrolist Feedback Webform

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1640]
Browser = Chrome
Reported = 10/20/20
Priority = Low (cosmetic)

Can we get the lines realigned with the bubbles on the Likert scale?

![image](https://user-images.githubusercontent.com/55395593/96612310-9a38b200-12cb-11eb-846c-331686666b8b.png)

**Comment by padora-cob** [comment]
Still investigating, cannot reproduce yet with Chrome on OS X.

**Comment by AmyWipfler** [comment]
New copy for Metrolist Feedback Form.

We care about your experience using Metrolist. Please take a moment to let us know what you think.

How do you feel about the following statement: ”Using Metrolist made my housing search easier.”?

We can remove the line to avoid the above issues. This form should now notify via email kelsey.bruun@boston.gov , me, dana.smith@boston.gov

**Comment by padora-cob** [comment]
Updated on CI ready to test.
