### ISSUE TITLE
iFrame component not working on the site

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1641]
It looks like the "iframe" component is no longer working. You can see an example on the [parks construction page](https://www.boston.gov/departments/parks-and-recreation/design-and-construction-boston-parks). I also have an [unpublished test page](https://content.boston.gov/duffy-test-page) with some iframe components added, and they are also not redndering.

The original issue was caught on the [American Legion page](https://www.boston.gov/departments/transportation/safer-slower-american-legion) on the site. The [English](https://storymaps.arcgis.com/stories/25af97d527d14744a3b45f857f163412) and [Spanish versions](https://storymaps.arcgis.com/stories/45ec6e29d32f40baa3a8a8dd85ad9cad) of their storymap wouldn't display.

**Comment by reillyzlab** [comment]
Believe this is resolved so closing
