### ISSUE TITLE
As a Neighbor, I want to be able to browse and locate Projects on a map, so that I can ID what development is happening nearby me.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1655]

**Comment by AmyWipfler** [comment]
UAC:

- Able to position yourself relative to local landmarks
- Able to position yourself by your location
- Able to position yourself by address
- DND Projects should be consistently marked, ideally by lot lines

**Comment by AmyWipfler** [comment]
@padora-cob This isn't in the current sprint, but feels like progress has been made on this story. No need to move into Sprint 2, but I think what you have is ready to Test next sprint.

**Comment by padora-cob** [comment]
Demo search and reactive map at: https://d8-ci.boston.gov/bh/demo/search & https://d8-ci.boston.gov/bh/maps/liv

**Comment by AmyWipfler** [comment]
Sprint 3 DoD: Test how  users like the reactive map and how they want to place themselves given the Neighbor persona goals.

**Comment by AmyWipfler** [comment]
Sprint 4 DoD = Iterate off potential map functionality in design. Prioritize solving for styling, centering, and Project data that displays on map markers. Also clarify all needed layers. By EoS have mocked up in CI a map for testing and potentially have delivered to test users for feedback. (Liz)

**Comment by AmyWipfler** [comment]
Acheived Figma prototype for testing. Hoping to collaborate real-time on Maps next sprint.
