### ISSUE TITLE
As a Neighbor, I want a direct link to a Project, so that it is easy to find and easy to share.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1656]

**Comment by AmyWipfler** [comment]
Sprint 4 DoD = Ensure that links are unique per project on CI (Alex). Make sure URL structure meets usability standards (Liz).

**Comment by padora-cob** [comment]
Will change out the URL structure to the current proposal: 

Homepage = boston.gov/buildinghousing (this currently re-directs to the Tolemi site)
Project pages = boston.gov/buildinghousing/[Project Title]
Archive = boston.gov/buildinghousing/past-projects

**Comment by AmyWipfler** [comment]
Alex thinks that's achievable by EoS

**Comment by padora-cob** [comment]
New pattern on CI for Projects: https://d8-ci.boston.gov/buildinghousing/blue-hill-avenue-action-plan-b3-parcels
