### ISSUE TITLE
Project Stage Search Facet for Map

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1658]
User Story: _When I land on BuildingHousing, I want to filter projects by their current project stage, so I can see how many projects are currently soliciting community feedback, or which projects are nearing completion._

Final design recommendation: dropdown menu in the list of projects on the map. When a stage is selected, only projects in that stage should appear on the map or in the list view.

<img width="820" alt="Screen Shot 2021-04-12 at 4 43 04 PM" src="https://user-images.githubusercontent.com/72943225/114459158-2a3a2300-9bae-11eb-9f8b-c57f9fb10540.png">

<img width="901" alt="Screen Shot 2021-04-12 at 4 42 57 PM" src="https://user-images.githubusercontent.com/72943225/114459172-2e664080-9bae-11eb-921e-4e4c41d3d2be.png">

Mobile prototype here: https://www.figma.com/proto/k1FN1vdnY7PUy4wfqkKwIS/Mobile-Homepage-Test?node-id=4%3A102&viewport=585%2C800%2C0.25&scaling=scale-down

**Comment by lizcormack-bos** [comment]
Using Fleet components, here are two options for filters in the list view! Dropdown and Checkmarks. 

**Dropdown**

- Pros: takes up less real estate in the list view.
- Cons: impossible for a user to select multiple stages (ie. all under construction _and_ completed). 

![Screen Shot 2021-02-18 at 6.36.11 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/632200d9-f308-40c3-b4a8-daae132a9711)

**Checklist**

- Pros: allows for more flexibility in filtering
- Cons: takes up more space 

![Screen Shot 2021-02-18 at 6.36.18 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/b7456648-7586-4014-aae8-daa72bc09a13)

**Comment by AmyWipfler** [comment]
@lizcormack-bos I'd like to test with the first concept if you're okay with it. Not clear to me yet if users are interested in selecting more than one phase at a time, and I'm pretty confident the checkbox version will be a hard to use UI

**Comment by lizcormack-bos** [comment]
Desktop Maze test report here (still getting new responses): https://app.maze.design/report/2325izfrvklh5t52g

Mobile Maze test report here (just launched, should have ~20 responses shortly): https://app.maze.design/report/2325izfrvklh8m9cv

**Comment by lizcormack-bos** [comment]
Final design: ![Screen Shot 2021-02-25 at 9.40.13 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/4683e0bc-e001-4089-9962-6dee7a20e1d8)

**Comment by duffy-james** [comment]
Closing issue for now.
