### ISSUE TITLE
As a Neighbor, I want to know the exact location of a Project, so that I can understand it's relation to my home.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1659]

**Comment by padora-cob** [comment]
Demo search at: https://d8-ci.boston.gov/bh/demo/search

**Comment by AmyWipfler** [comment]
Sprint 3 DoD: Test map options with users and understand if there are further specs needed to give visitors an understanding of the precise location of the project (i.e. parcel boundaries, shading, iconography).

**Comment by lizcormack-bos** [comment]
The map Alex has up on staging now is great -- we just need to validate that an interactive map at a smaller aspect ratio is still useful to users. I prototyped a pop-up overlay, which will help us validate how important expanding the map is to users, but I definitely need to sync with Alex on technical options!

**Comment by lizcormack-bos** [comment]
Wondering if clicking around a map in this size poses issues (see mockup) - that would be my first choice right now:

![Screen Shot 2020-11-25 at 4.41.21 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/d5100d07-498a-47ab-af1f-b7aacb4f16a6)

**Comment by AmyWipfler** [comment]
Finished map snippet in Sprint 3. Would ideally move to visualization of parcel data next sprint in addition to the map.

**Comment by AmyWipfler** [comment]
Sprint 4 DoD = Learn from Sprint 3 test about Project page Map component and synthesize learnings and interested changes. Hold off on Parcel display exploration except as a map layer.

**Comment by AmyWipfler** [comment]
Users did report the map on the project page helped them ID location.

**Comment by lizcormack-bos** [comment]
Discussed with Alex, we're going to use the map defaults for the small map widget on the project page, but added the + / - button to the widget so users can zoom out for additional context! 

![Screen Shot 2020-12-11 at 2.41.33 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/cfc1e95e-e2aa-4aa5-93e5-c77aa654ccb9)
