### ISSUE TITLE
As a Neighbor, I want to know the type of Project in development, so that I can envision what kind of development is being added nearby.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1660]

**Comment by AmyWipfler** [comment]
Done = Reviewing value sets in SF, defining user definition of "type", and whiteboarding how content interplays with "type" (Test)

**Comment by AmyWipfler** [comment]
Committing to:

Week 1:
- Pull fields options for Project Types
- Whiteboard which Project Types matter to users and try to align

Week 2:
- Consider prototype req't needs

**Comment by AmyWipfler** [comment]
@lizcormack-bos Yes, it's a zoning type that blends residential, commercial, cultural, institutional, or entertainment uses into one space. So for "type" it wouldn't be purely housing, but some mix of school space, office space, and housing (for example).

**Comment by padora-cob** [comment]
I have the Project Type feature going in Drupal: ![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/df9c22cd-71f9-42ca-a546-6d339d2343a2)

Will adjust styles as needed.

**Comment by AmyWipfler** [comment]
Love it! That looks great @padora-cob 


Nice work on parsing the logic behind these. What's a good way for me to review/test?

**Comment by AmyWipfler** [comment]
Sprint 4 DoD = Implement styling and display of key data on Project Pages in CI (Alex)

**Comment by padora-cob** [comment]
Styling is about 90% there for the Project Type. Will move it to CI soon. I am just using a place holder icon atm, will need to add in an icon field to the Project Type Taxonomy. After that we will need to choose icons for each of the Types. 

![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/9f09aa5f-6ee5-4df8-b2de-93aa7d52972e)

**Comment by AmyWipfler** [comment]
That looks great!

**Comment by lizcormack-bos** [comment]
Love the triple decker icon though! Sadly 'Open Space' is a much longer word, so I had to bump the text left in the template for this. Also brainstorming a shorter title than 'Open Space.' Smaller font didn't work hierarchy-wise.

**Comment by padora-cob** [comment]
Will just need to get final icons and maybe adjust some of the logic or display for the type of "Other".
![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/38c9c6d3-98dc-4b87-9cb9-d5bc2c7b3100)
![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/a7f9a699-28c0-4e1d-ba86-7899c3794b67)
![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/1e8cb381-4b34-43a7-b22c-744cfee29ece)
![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/67bb6ae7-4ae5-43ba-8b14-38291e3b1373)
