### ISSUE TITLE
As a Neighbor, I want to see key milestones and their associated dates, so that I can understand development progress to date and anticipate future happenings.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1661]

**Comment by AmyWipfler** [comment]
Done = Brainstorm on depiction options, adding in Critical Project Dates to SF Sync, Figma wireframes options ready to test (Test).

**Comment by padora-cob** [comment]
Screenshots of SF field options for Project Status and Milestone dates: https://drive.google.com/drive/folders/1mUIY__XXwUTVBr2KRgBgoOeufbfMp8Uc?usp=sharing

**Comment by lizcormack-bos** [comment]
Current proposal, will be using this in user testing! 

![Phase Proposal.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/655f5e6b-03ee-453e-875b-37d809787819)

**Comment by AmyWipfler** [comment]
Those look great @lizcormack-bos !

**Comment by lizcormack-bos** [comment]
As discussed in the milestones sync up this week, I'm running with the concept that "moments" occur in the timeline somewhat independent of being "within" a project stage. When a project stage starts, it appears as a smaller dot in the timeline, without an icon. Look forward to getting feedback from this round of user tests!

![Screen Shot 2020-11-25 at 4.42.44 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/40091382-e1d0-4cb5-9b1f-326f58f17932)

**Comment by AmyWipfler** [comment]
Sprint 4 DoD = Review learnings from Sprint 3 testing and synthesize future changes/tweaks needed. (Liz)

**Comment by lizcormack-bos** [comment]
Reversed chronology of timeline so future is at the bottom of the page. "New stages" are now bigger bubbles with icons, and other moments are smaller bubbles on the timeline (lower in hierarchy).

List of currently scoped moment types:

1. Text Update from DO
2. Community Meeting (upcoming, or past)
3. Document Upload
4. RFP Issued (needs more exploration)
5. Developer Selected (needs more exploration)
6. Stage Change (major milestones)

 ![Screen Shot 2020-12-07 at 11.14.06 AM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/1cc2245c-824b-4c4f-bc5a-e3197bd27612)

**Comment by AmyWipfler** [comment]
@padora-cob Implementing these doesn't have to happen this sprint, but here are the SF objects/fields that will help us create these MVP 6 moments.

1. Text Update = Chatter Feed post that is text only from the Project's related Website Update record.
2. Community Meeting = Fields on the Community Meeting Event record related to the Website Update record will fill this component. Chatter Feed/Files on the Community Meeting Event will be used to attach presentations or documents after a meeting. Liz is still ideating this a bit, but we can go with the specs she's sent so far.
3. Document Upload = Chatter Feed/Files on the Website Update related record will be used for these. We'll want to pull over who posted them, when, and their Title and Description. Anything that is not a image file type should go to the timeline.
4. RFP Issued = If the Project field "RFP Issued Date" = TODAY or in the past then it should create an RFP Issued moment and link the user to DND's RFP page (https://www.boston.gov/departments/neighborhood-development/requests-proposals)
5. Developer Selected = If the Project field "Initial TD Vote Date" = TODAY or in the past then it should create a Developer Selected moment and display the title and fields from the related Account in the "Project Developer" Lookup field.
6. Awardee Selected = If the Project field "DND Funding Award Date" = TODAY or in the past then it should create an Awardee Selected moment and display the title and fields from the related Account in the "Project Developer" Lookup field.
7. Stage Change = This will be mostly controlled on the Drupal side, as the Drupal Stages differ from the Salesforce changes. Liz is still scoping the specs for what standard copy we could add to the timeline when a stage has changed.

Thanks!
