### ISSUE TITLE
As a Neighbor, I want to see photos or visualizations of the Project, so that I can envision the future visual landscape nearby my home.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1662]

**Comment by AmyWipfler** [comment]
Sprint 3 DoD: Research to better understand the value of photos/visuals to users. Is there a clear volume of photos? Or frequency of photos desired? By end of sprint feel confident assigning business rules to photo uploads and understand their importance in the project page hierarchy.

**Comment by lizcormack-bos** [comment]
Things to consider re: photo interaction:

- Displaying photos on page (default view)
- What matters to residents (are more photos actually any better)? 
- Is there value in clicking in/ expanding images?
- How might we ensure photos show up well in social share situations?

**Comment by lizcormack-bos** [comment]
Prototyped an overlay after looking at existing Drupal modules for photo galleries! The Lookback test asks users to rate how useful the photos are in improving their understanding of a project on a scale of 1-5. I recommend we aim for an average rating of 4 before launching the MVP, and continue to improve. The rating will ultimately be pretty influenced by the content of the photo.

I do still want to explore alternative ways to display captions.

 ![Screen Shot 2020-11-25 at 4.33.52 PM.png](https://images.zenhubusercontent.com/5f89dabb0e9099f29a126af1d/bdf1e150-c099-4ae4-83c2-d9d1865e7272)

**Comment by AmyWipfler** [comment]
Sprint 4 DoD = review findings from test users and evaluate photo options/recommendations for MVP (Liz). Confirm how legacy photos from projects will be tagged for display in image components (Alex).

**Comment by padora-cob** [comment]
We can now import the photos to the Projects, all of the structure and functionality is complete. 

Still need to apply our styling to the Gallery feature. Will need to choose the rules (size, ratios, resolution....) for the images in the Gallery also. 

![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/90161dfc-a433-4dd6-a302-6f9011f9eb06)
![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/31da8d6c-877b-4912-8df4-ae5ab92c5082)
