### ISSUE TITLE
As a Neighbor,  I want access to Developer presentations, so that I can virtually see what information they have given about the Project.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1663]

**Comment by AmyWipfler** [comment]
Done = Included in wireframes, multiple options for integrating the UI, explore file requirements (Prototype)

**Comment by AmyWipfler** [comment]
@padora-cob Based on our conversation today, it seems that we can either integrate these in through the existing "Meeting PowerPoint" Update in SF or use a Drupal component that a PM would populate through the Content Editor - does that sound right to you?

If so, can you prototype in the Update section on CI what it would look like to surface a .ppt or a .pdf from Salesforce update? Thanks!

**Comment by AmyWipfler** [comment]
Note: file size is limited on Salesforce, unless Chatter is enabled and used for these file hosting situations. File size is unlimited on Drupal until storage on DoIT's is maxed out.

**Comment by AmyWipfler** [comment]
Sprint 3 DoD: Front-end prototype how visual files (presentations or images) will display on Project Pages. Back-end prototype images and files being imported via Chatter on the SFDC Update object.

**Comment by padora-cob** [comment]
On the Drupal side we can now import Images and Documents from SF Attachments and from Salesforce Files (Chatter). 

The good news is that we can bring in the files and data, but we still need to make some adjustments on SF side so that I can categorize and add metadata to the files. That will affect how they are displayed.

**Comment by AmyWipfler** [comment]
Pending Website Update integration (80% of the way) on back-end

Pending how to display meeting recordings and how to relate presentations with the correct stage.

**Comment by AmyWipfler** [comment]
Sprint 4 DoD = Integrate with New Website Update (Alex), Determine display for recordings (pulled from Salesforce URL field) (Liz), Create firmer contingency plan for how to bulk upload old Updates (Alex/Liz/Amy)

**Comment by padora-cob** [comment]
Working on the template / style for the documents in the timeline.
