### ISSUE TITLE
Developer Profile for Project

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1667]
Done = Display Developer Name (min), Contact Info (maybe), MBE/Diversity states (maybe), website (maybe) in the sidebar adjacent to the Project Manager contact information.

Example Developer Account for Salesforce description; https://boston-dnd.my.salesforce.com/001C000001AoqbD

**Comment by lizcormack-bos** [comment]
Final design! Couple things:

There are four fields I'd like to include from the "**Demographic Details**" section on the **Account - Vendor** record type:

- Minority Owned Business
- Woman Owned Business
- Veteran Owned Business
- Boston-Based Business

If demographic details are not filled in, do not display. Likewise for the website - if the **Website** field is not filled in, do not display the link. If it is filled in, display the link and open the developer's website in a **new tab**.

![Developer Profile.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/41833969-233d-4f51-8de0-b34186593432)

**Comment by lizcormack-bos** [comment]
See #1991 - I'm afraid the actual developer name isn't showing anywhere and we'll only see "TBD." 

This was working until mid-deploy on Monday 3/29.
