### ISSUE TITLE
Project Manager Contact Widget

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1668]
### QA Notes:

- [x] Unable to accept, seeing many pages where no Project Manager information is coming through (e.g. https://d8-ci.boston.gov/bh/demo/project/highlandmarcella-package-4)

- [x] In the cases where there really is no project manager contact information, the email shown should be neighborhooddevelopment.dnd@boston.gov

- [x] _Design QA_: Update the copy for the Default component (when there's no PM). Title should be "Contact Information" and body should be "Do you have questions about this lot? We're here to help."

Data from Project's Related Contact in the Project Manager field. Should read Name, Title, Email, and Phone over to BH in line with componentry design for right hand sidebar.

**Comment by AmyWipfler** [comment]
Sprint 4 DoD = Displaying on each Project page, data comes from the Salesforce User.

**Comment by padora-cob** [comment]
Most of the widget is styled:

![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/ebad0b63-fa64-49eb-8743-c3b7d87f8cfd)

Still need to connect the data to it though.

**Comment by AmyWipfler** [comment]
You're zooming! Let me know if you have any questions about connecting to the Salesforce Users.

**Comment by padora-cob** [comment]
Working on syncing new SF fields and other data this afternoon, should be syncing to CI at EoB.

**Comment by padora-cob** [comment]
We now get and store the PM info on the projects.

**Comment by AmyWipfler** [comment]
Haven't been able to accept this yet, because it seems that default text is coming through often even when there is a Project Manager assigned in Salesforce.

e.g. https://d8-ci.boston.gov/bh/demo/project/highlandmarcella-package-4

**Comment by lizcormack-bos** [comment]
Also seeing the default on most projects. I'd like to update the default to the following (ran through Hemingway and removed jargon):

Title: Contact Information
Body: Do you have questions about this lot? We're here to help. 

Apologies, I assume you're pulling that from the inactive project UI in Figma. It's updated there as well.

![Screen Shot 2021-01-19 at 4.44.13 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/760c5d41-afa8-4ae3-b8bf-538978630905)

**Comment by padora-cob** [comment]
Looks like on the manager info not showing.... I had it not show if they were missing any info. Now only if they are missing the Name.

No Phone:
![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/43de4d2e-fe95-423e-a102-c0577c25e027)
