### ISSUE TITLE
As a Neighbor, I would like to be able to vote on Developer proposals, so I can have my voice represented in the selection digitally.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1669]
User Story: _When a DND project that I'm following shares developer presentations for feedback, I want to be able to easily see their proposals and express my preference so I can influence the outcome without spending too much time reaching out or attending meetings._

Often RFPs get multiple bids (especially for housing projects). We envisioned a timeline interaction in which residents could see and vote on 2+ presentations.

**Comment by lizcormack-bos** [comment]
Closing and documenting in the Building Housing backlog Google doc.
