### ISSUE TITLE
As a Neighbor, I would like to be able to make a public comment about a Project, so that I can see a record of my opinion.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1670]
User Story: _When I'm following a DND project, I want to comment on it publicly and see others' comments so that the community's opinion is evident and I feel confident its being heard._

We found that use of comments on the old Building Housing site was very mixed, especially since the old site required users to create an account to leave a comment, and there was no formal process for reviewing or replying to public comments on the site. That said, when we removed the feature, we heard frequent enquiries from DND employees and the public about it being missing. Documenting this as a backlog feature for future consideration.

**Comment by lizcormack-bos** [comment]
Documenting in DND docs and closing.
