### ISSUE TITLE
As a Neighbor, I want to view community meeting details, so I can understand when I will have a chance to engage on the Project.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1672]

**Comment by AmyWipfler** [comment]
Done = Understanding views of meeting details, choosing one (Test)

**Comment by AmyWipfler** [comment]
Sent an email to Ann Roper-Quinn to learn more about the Webex account structure and get admin access.

**Comment by AmyWipfler** [comment]
Sprint 3 DoD: Test front-end component options for Community Meetings with Neighbors. Surface community meeting details from SFDC Sandbox version of Event Update.

**Comment by AmyWipfler** [comment]
Ready to go in the Sandbox:

![image.png](https://images.zenhubusercontent.com/5f774cd93389cdee6cb34b22/abdd32c7-ad1f-44a5-8595-84ae09f06a5d)

**Comment by AmyWipfler** [comment]
Sprint 4 DoD = Build testing Community Meeting Events in Fullcopy (Amy), Integrate key data fields with Community Meeting component to Liz's design specs (Alex).

**Comment by padora-cob** [comment]
Have created both displays for a Meeting on a Project: 
![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/0641c1a9-2c9e-4ec2-b8a0-c60266d1abc7)
![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/1099e7d3-22c8-4e10-8e04-7b66b67daa16)

Still need to add in the new "Add-to-Cal" feature once it is released from upstream, using a placeholder button for now.

Also need to implement the timeline display for a past Meeting.
