### ISSUE TITLE
As a Neighbor, I want to register for the community meeting, so that I can access the meeting and be reminded of it's details on my calendar.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1673]

**Comment by AmyWipfler** [comment]
Done = Clear understanding of technical options for storing registrations (Test)

**Comment by padora-cob** [comment]
We now know that we have a few options for storing the registrations for meetings. I believe we are going to first try and register the Users on the Drupal site via an attached Web Form (Will not create a Drupal User Account). Then we will sync that data with a SF Contact record. While at the same time registering the user to the correct WebEx meeting via API. With that data we can then contact Users at a later date.

**Comment by AmyWipfler** [comment]
Sprint 3 DoD: Create back-end flow as ideated in past sprint (see Miro). Stretch = Test webform flow with users (if Drupal form ready in time for testing sessions).

**Comment by padora-cob** [comment]
Basic Drupal Webform functionality is ready for registration. Can adjust the display as needed: ![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/1daf8eef-e9e4-4635-866c-127e268fc470)

**Comment by AmyWipfler** [comment]
Prototype of Community Meeting Event object ready to go in SF Sandbox:

![image.png](https://images.zenhubusercontent.com/5f774cd93389cdee6cb34b22/d42453cd-011f-4cf2-a7b7-b8e7903e1410)

**Comment by AmyWipfler** [comment]
Great to have a future state concept being tested and tried out. Will mostly be riding on Stella's work for MVP.

**Comment by AmyWipfler** [comment]
Sprint 4 DoD = Implement to meet minimum requirements of linking the the Webex registration page that is a URL field on the Salesforce Community Meeting object (Alex)

**Comment by padora-cob** [comment]
Working on syncing new SF fields and other data this afternoon, should be syncing to CI at EoB.
