### ISSUE TITLE
As a Neighbor, I'd like to see Project meetings on the Events page of boston.gov, so that I can easily find them alongside other community events going on in Boston.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1675]

**Comment by padora-cob** [comment]
Goal for Done: 
- Create new Meeting fields in SF on the Update Object
- Selectively sync Update object with Drupal Events and relate to a Project 
- Display a widget of the Event on the Project page

**Comment by AmyWipfler** [comment]
Sprint 3 DoD: Functionally test how Event Update in SFDC can auto-generate an event component for boston.gov/events and link to custom webform.

**Comment by padora-cob** [comment]
The webform and events in Drupal are both working and now related to Projects. The basic displays are also working.

The last step is to sync the new SF Object to the Drupal Event entity. Once that is done we should be good to go with the backend functionality.

**Comment by AmyWipfler** [comment]
Sprint 4 DoD = Sync Drupal Events to new Community Meeting Event (Alex), validate that event page content meets specs (Liz).

**Comment by padora-cob** [comment]
Working on syncing new SF fields and other data this afternoon, should be syncing to CI at EoB.
