### ISSUE TITLE
Workflow for Project field to be populated on Development

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1681]
So that users can find Metrolist posting

**Comment by AmyWipfler** [comment]
Sprint 3 DoD: Explore what users want to know about applying/moving in even if moving in isn't feasible until 2-3 months from construction completion. Understand whether we want to connect BH <> ML via Salesforce or Drupal.

**Comment by AmyWipfler** [comment]
@padora-cob Doing some thinking on this piece, and wanted to dig up an example for us to work with. I think this Amory Terrace one is a good one for us to explore:

Live Metrolist Listing (Drupal): https://www.boston.gov/metrolist/search/housing/amory-terrace?type=rent&assignment=waitlist
Project Record (SFDC): https://boston-dnd.my.salesforce.com/a04C000000LYaer?srPos=0&srKp=a04
Development Record (SFDC): https://boston-dnd.my.salesforce.com/a4r0y000002YBnm?srPos=0&srKp=a4r
Project Unit (SFDC): https://boston-dnd.my.salesforce.com/a2HC0000003tFoK?srPos=0&srKp=a2H

Do you have insights on how best to make the connection between ML and BH given the objects we're using in Drupal and SFDC?

**Comment by AmyWipfler** [comment]
Without the Affirmative Marketing work represented in SF, it will be hard to connect these two Products. My MVP concept is to have DND Marketing/ML Program Manager/AFHM Assistant post the Update on any DND project with the link when a lottery is available?

**Comment by rachelsater** [comment]
#1771
