### ISSUE TITLE
Review and enhance Google Analytics > Behavior Flow 

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1699]
On our Google Analytics account for boston.gov, if a viewer goes to 'behavior flow' some of the pages are showing up as '(not set)' or 'no params'. 

This appears to happen with select 'views'.

Can someone review why these are showing up as not set and provide a recommendation on how we can resolve this so that we can make better data driven product decisions.

Is this an analytics set up problem/adjustments that need to be made in analytics, or do we need to make changes to Drupal?

Examples: 

1. ![Screen Shot 2020-11-09 at 11 15 07 AM](https://user-images.githubusercontent.com/20731897/98566509-733f2180-2274-11eb-8230-cda29c42a2f8.png)
Under: https://analytics.google.com/analytics/web/#/report/content-engagement-flow/a99773468w108307691p112911200/_r.engageMode=contentGroup&_r.screen=~2F&_r.threshold=50&_.pagrpi=1/

2. 
![Screen Shot 2020-11-09 at 11 16 58 AM](https://user-images.githubusercontent.com/20731897/98566706-b600f980-2274-11eb-908f-b439d790ea87.png)
Under: https://analytics.google.com/analytics/web/#/report/content-engagement-flow/a99773468w108307691p112911200/_r.engageMode=contentGroup&_r.screen=~2F&_r.threshold=50&_.pagrpi=2/

3. 
![Screen Shot 2020-11-09 at 11 17 20 AM](https://user-images.githubusercontent.com/20731897/98566777-cc0eba00-2274-11eb-8dd5-c173525a4f1f.png)
Under: https://analytics.google.com/analytics/web/#/report/content-engagement-flow/a99773468w108307691p112911200/_r.engageMode=contentGroup&_r.screen=~2F&_r.threshold=50&_.pagrpi=2/

**Comment by reillyzlab** [comment]
Example on cityofboston.gov:

![Screen Shot 2020-11-09 at 11 19 42 AM](https://user-images.githubusercontent.com/20731897/98567053-1f810800-2275-11eb-8a40-42558c1f1ab5.png)
Under: https://analytics.google.com/analytics/web/#/report/content-engagement-flow/a2187282w3918273p82932313/_r.engageMode=contentGroup&_r.screen=~2F&_r.threshold=50&_.pagrpi=3/

**Comment by rachelsater** [comment]
Closing because this isn't needed anymore. We can create a new ticket if necessary
