### ISSUE TITLE
Styling missing in table of 'commission members' component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1707]
The "commission members" component on all of our boards and commissions pages appears to have a bug that's removing the styling in the table:

![image](https://user-images.githubusercontent.com/7929556/99099675-c7197580-25a8-11eb-810a-e02a75b9c62c.png)

I checked in Firefox and Chrome, and the bug is the same.

**Comment by subaha-cob** [comment]
@andrebtlima I fixed this issue. I noticed it on UAT and fixed it. You can test on UAT. This can will be pushed when we push Add to calendar and Iframe auto.

**Comment by reillyzlab** [comment]
This was fixed so closing
