### ISSUE TITLE
Metrolist Listing Form: error when existing Contact is selected and the AccountID is not saved on the WebForm

### ISSUE THREAD

**Issue by padora-cob** [CityOfBoston/boston.gov-d8#1715]
Add in a check if the User selected an existing Contact that the AccountID is also saved to the Webform. If it was not then ask SF for it again at the end of the process.

**Comment by AmyWipfler** [comment]
@padora-cob Did we end up resolving this issue? Know it was creating issues for users in late Jan 2021

**Comment by duffy-james** [comment]
Closing issue for now.
