### ISSUE TITLE
As a Property Manager, I would like Income-Restricted to automatically = True if I have entered an AMI value, so that I don't cause ML extra data cleanup costs.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1716]
Common user error in the Metrolist Listing form is for Property Managers to enter and AMI % but then Leave "Income-Restricted" as "No". This then causes the listing to populate as Market Rate instead of Income-Restricted on the front end. Dana could continue being responsible for this, but it has been a common enough error to add in logic rules for.

**Comment by duffy-james** [comment]
Closing issue for now.
