### ISSUE TITLE
Neighborhood lookup: Move the order of the cards around to match traffic

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1719]
Move the order of the cards around to match user traffic:

1. Representation should be the first card
2. Newsletter should be the fourth card

Developer needs to do this.

**Comment by subaha-cob** [comment]
UAT is now up with MNL tickets. 
https://d8-uat.boston.gov/

Try testing with this addresses only:

50 Milk St #2050 Boston, 02108
192 Dudley St Roxbury, 02119
27 Tyler St Boston, 02111
1 State St Ste 1500 Boston, 02108

**Comment by reillyzlab** [comment]
@subaha-cob can you move the newsletters to the 4th card, not the second.
