### ISSUE TITLE
Neighborhood lookup: Remove/turn off summer resources card

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1720]
Remove/turn off summer resources card because these resources are not currently relevant given the time of year.

**Comment by subaha-cob** [comment]
@reillyzlab , @mmcgowanBOS UAT is now up with MNL tickets. 
https://d8-uat.boston.gov/

Try testing with this addresses only:

50 Milk St #2050 Boston, 02108
192 Dudley St Roxbury, 02119
27 Tyler St Boston, 02111
1 State St Ste 1500 Boston, 02108

**Comment by reillyzlab** [comment]
Completed so closing.
