### ISSUE TITLE
Neighborhood lookup: Turn on/enable winter resources card

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1721]
Turn on/enable winter resources card.

There is a card already designed and ready as well as data enabled/in the streams already. Card just has to be turned on via the config, change 1 value and deploy.

Place this where the summer resources card was -- fifth in order.

Please run this by Reilly on staging before fully deploying to production. Would like to see what it looks like before going to prod.

**Comment by reillyzlab** [comment]
If there isn't a link to boston.gov/winter-boston, then we should add. @subaha-cob can you confirm whether this exists or not?

**Comment by subaha-cob** [comment]
@reillyzlab , @mmcgowanBOS UAT is now up with MNL tickets. 
https://d8-uat.boston.gov/

Try testing with this addresses only:

50 Milk St #2050 Boston, 02108
192 Dudley St Roxbury, 02119
27 Tyler St Boston, 02111
1 State St Ste 1500 Boston, 02108

**Comment by reillyzlab** [comment]
@subaha-cob can this be the fifth card?
