### ISSUE TITLE
Build Drupal template for Project Page

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1727]
Custom for BuildingHousing.

**Comment by padora-cob** [comment]
I have a good chunk of the styling going for the Project page, still need to do a number of adjustments for spacing, sizes, floats and adding in other components. 

https://d8-ci.boston.gov/bh/demo/project/blue-hill-avenue-action-plan-b1-parcels

![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/85dda969-397a-4079-ac26-22a01e065493)

**Comment by padora-cob** [comment]
Main template for the Project page is mostly done, will need a design review and some tweaks during the next sprint.

[Uploading... image.png ]
