### ISSUE TITLE
Guidance on how to best prompt for correct address

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1734]
Build in a prompt/description that guides people on how to best search for their address to get the best/most accurate results.

@carolinestj to make suggestions for this.

**Comment by stephaniemar** [comment]
@carolinestj do you know what project this is associated with? if any?

**Comment by carolinestj** [comment]
@stephaniemar Think this was for neighborhood lookup and what the prompts would be when entering your address to get accurate results

**Comment by stephaniemar** [comment]
Enhancement for this search screen: 
https://www.boston.gov/my-neighborhood

**Comment by duffy-james** [comment]
@carolinestj @stephaniemar I imagine this enhancement is similar to the helper text we're adding to Assessing Online.
