### ISSUE TITLE
Represent Past & Future meetings in the timeline

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1737]
### QA Notes:

- [x] Add an 'r' into 'Learn More' on Future meetings. Currently reads as 'Lean More'.
- [x] Finish doing the overrides for boston.gov Events

**FUTURE**

- [x] Title
- [x] Date
- [x] Start/End Time
- [x] Description/Goal
- [ ] Location

**PAST**
All of the above, plus...
- [x] number of attendees
- [x] link to recording
- [x] meeting presentation(s) - ie. multiple translations.
- [x] potential note from DO

**Comment by lizcormack-bos** [comment]
Spec here -- needs the following update:

- [ ] Clarify character limit cutoff to display "read more"
- [ ] Add WedEx recording password to UI

![Community Meetings.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/80734591-f419-44b2-9dd5-7e66a1019cde)

**Comment by lizcormack-bos** [comment]
Final design for the WebEx recording password is now in the Spec! 

![Screen Shot 2021-01-12 at 12.31.45 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/d0234190-f959-49ec-9114-0e643cb136c0)

**Comment by AmyWipfler** [comment]
Yep, added in Salesforce!

**Comment by AmyWipfler** [comment]
![image.png](https://images.zenhubusercontent.com/5f774cd93389cdee6cb34b22/d8e165c5-8f9a-4732-87bd-ae79bfe50f8c)
