### ISSUE TITLE
Add at-large city councilors to Neighborhood Lookup-Front End of Cards

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1739]
We should add at-large city councilors to Neighborhood Lookup under representation.

This would be four councilors in addition to the district councilor.

Imagine we'd change 'your city councilor' to 'your district city councilor' and then some how build in 'your at-large councilors'

Need @carolinestj help re-think the representation section in general because adding four more cards feels like it'll then have a lot of content as well as specifically how to address the district specific councilor versus at-large.

Also wondering if we should move ONS rep into a seperate section at this point? (open question)

Ideally we'd have these designs done by latest end of calendar year 2020.

**Comment by reillyzlab** [comment]
Related: https://github.com/CityOfBoston/boston.gov-d8/issues/1740

**Comment by reillyzlab** [comment]
Design for this.

The information will be manual (i.e. not coming from the data feed/API) for first launch; we will get this live as we keep working through the data feed updates.

<img width="400" alt="Screen Shot 2020-12-22 at 4 23 13 PM" src="https://user-images.githubusercontent.com/20731897/103308005-0ffd8000-49d7-11eb-87dd-012352204aff.png">

Requirements:

- [ ] Move neighborhood contact next to mayor
- [ ] Move 'your city councilor' to second row' (first card in second row)
- [ ] Add this new 'at large councilors' card between 'your city councilor' and 'state and federal representatives'
- [ ] Header should read 'Your At-Large City Councilors' [different than design spec]
- [ ] Image to use for this card can be found here: https://drive.google.com/file/d/1EaFxxR9yNwEVIPF3pLHCNB35Xkrwz3Dg/view
- [ ] URLs for the councilors (in order):
https://www.boston.gov/departments/city-council/annissa-essaibi-george
https://www.boston.gov/departments/city-council/michael-flaherty
https://www.boston.gov/departments/city-council/julia-mejia
https://www.boston.gov/departments/city-council/michelle-wu

- [ ] Edit the 'your city councilor' card body copy, to say "To learn more about Boston's City Council and view all members, visit the City Council page." [i.e. remove: , including at-large councilors]

**Comment by subaha-cob** [comment]
Please test at: https://d8-uat.boston.gov/my-neighborhood?p2

**Comment by subaha-cob** [comment]
Try testing with this addresses ONLY because we don't have the content on UAT:
50 Milk St #2050 Boston, 02108
192 Dudley St Roxbury, 02119
27 Tyler St Boston, 02111
1 State St Ste 1500 Boston, 02108

**Comment by reillyzlab** [comment]
One small change. 

For this sentence can you do "city:" instead [uncapitalize city and add colon]
The four at-large councilors that represent the entire City

**Comment by reillyzlab** [comment]
One small change.

For this sentence can you do "city:" instead [uncapitalize city and add
colon]
The four at-large councilors that represent the entire City

[image: COB_B_Blue_square-01.png]

Reilly Zlab

Director of Product Management, Digital <http://boston.gov/digital>

Department of Innovation and Technology

During COVID19 the best way to reach me is via email |
reilly.zlab@boston.gov

**Comment by reillyzlab** [comment]
Done so closing
