### ISSUE TITLE
Add at-large city councilors to Neighborhood Lookup-Data Add

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1740]
We should add at-large city councilors to Neighborhood Lookup under representation. This would be four councilors.

Believe this information needs to be added to the neighborhood lookup dataset.

Can @mmcgowanBOS @subaha-cob and @JPHaus work on this?

Ideal deadline: Latest by end of calendar year 2020.

**Comment by mmcgowanBOS** [comment]
Stella and I met to review this. @subaha-cob , is going to be working on the front-end update locally and simulate the data update within Drupal by manually modifying the JSON structure.

@JPHaus , do you see any issue getting the "at large" representation data with Civis and then POST-ed to one of our Drupal endpoints? If not, once you're ready, we could test by doing a POST to one of our test environments and endpoints within Acquia/Drupal.

Thanks.

**Comment by subaha-cob** [comment]
I wanted to also note that we are expecting to get a design from Caroline for this feature.

**Comment by subaha-cob** [comment]
https://drive.google.com/file/d/1EaFxxR9yNwEVIPF3pLHCNB35Xkrwz3Dg/view

**Comment by reillyzlab** [comment]
Related: https://github.com/CityOfBoston/boston.gov-d8/issues/1739

**Comment by stephaniemar** [comment]
Enhancement for this search:
https://www.boston.gov/my-neighborhood

**Comment by duffy-james** [comment]
@stephaniemar As far as I can tell, Matt manually added this information. I don't think this is pulling from a dataset because there is no existing dataset for at-large councilors. Going to close this one out.
