### ISSUE TITLE
Caching of address not working when click on boston.gov links while in neighborhood lookup

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1741]
The caching of the address is not working when a user clicks on a boston.gov link while in neighborhood lookup, goes to boston.gov, and then comes back to neighborhood lookup. The address disappears when the user comes from boston.gov

The address should stay cached the entire time.

Example: public spaces > community centers > boston.gov/bcyf

Reilly and Stella both experienced this

**Comment by subaha-cob** [comment]
@reillyzlab Please test at https://d8-uat.boston.gov/my-neighborhood
