### ISSUE TITLE
Address not caching in translated version of neighborhood lookup

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1742]
If user is in translated version of neighborhood lookup and clicks through to a boston.gov page and then goes back to my neighborhood lookup then the address gets stripped out and user has to re-enter address.

Potentially related to: https://github.com/CityOfBoston/boston.gov-d8/issues/1741

**Comment by mmcgowanBOS** [comment]
Couldn't replicate. Closing for now.
