### ISSUE TITLE
Translation not carrying through to other boston.gov links/page when clicked from neighborhood lookup

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1743]
If user goes to a translated version of neighborhood lookup the app works as expected.

If a user clicks through to another boston.gov link (example: boston.gov/bycf on public spaces), then the user is taken to an English version of boston.gov.

The translation should carry through and a user should be taken to the boston.gov page in the language that the user has selected to use.

**Comment by subaha-cob** [comment]
Here are three pages with an embedded iframe:

https://www.boston.gov/departments/boston-bikes/bike-rack-program
https://www.boston.gov/news/state-city-2020

And these pages use both an iframe component and an embedded iframe:

https://www.boston.gov/departments/small-business-development/supporting-bostons-open-businesses
https://www.boston.gov/departments/small-business-development/support-bostons-restaurants

**Comment by reillyzlab** [comment]
Closing this ticket and opening up another just specific to iframes. 

This was resolved for neighborhood lookup specifically but discovered this is an issue with all iframes when doing discovery for neighborhood lookup
