### ISSUE TITLE
Revise the UI for the events component

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1745]
Change the upcoming events component for this and site wide to match the UI from original specs (so that it looks different than upcoming news). Very confusing to users.

http://cob-ideo.herokuapp.com/components/#upcomingevents (see Reilly if you need help getting in)

Want to groom this with James before we implement.

**Comment by andrebtlima** [comment]
Version 1 of this enhancement should reflect the following wireframe (i.e. State 1: Large). 


<img width="976" alt="Screen Shot 2021-01-14 at 9 05 33 AM" src="https://user-images.githubusercontent.com/57111927/104601317-17b05c00-5648-11eb-968e-ad38360ea457.png">



NOTE:
There will be two subsequent enhancements reflecting State 2: Medium and State 3: Small. Ultimately, a user should be able to select which of the three UIs they wish to employ for the event component they are placing on the page.

**Comment by reillyzlab** [comment]
Additional comments: Content editor gets to choose which 'state' they want to use.

**Comment by rachelsater** [comment]
Here's State 2: Medium 

![image](https://user-images.githubusercontent.com/72876352/105224791-a54de900-5b2b-11eb-94e6-45632204f213.png)

State 3: Small
![image](https://user-images.githubusercontent.com/72876352/105224834-b7c82280-5b2b-11eb-8050-93eb9a64cef5.png)

**Comment by rachelsater** [comment]
I created a Large event on this page https://d8-uat.boston.gov/departments/parks-and-recreation/boston-parks-fitness-series. The issues I see are:
1. The big image is blurry 
2. The "Feb 17" flag is black. In the mock up it's blue
3. The event title and details aren't bold (like in the mock up)
4. I added "Poetry in the Park" to the link text and then deleted it but it's appears on the page

![image](https://user-images.githubusercontent.com/72876352/108120886-f0e2ac80-706f-11eb-86a0-fb055db485c0.png)

**Comment by rachelsater** [comment]
For https://d8-uat.boston.gov/departments/arts-and-culture I switched the view to "small". 

Looks good but the flags are black and the flag text is white (different from the mock up). 
And it doesn't look like the text is bold (I think the mock up has the text bolded)

![image](https://user-images.githubusercontent.com/72876352/108121778-53887800-7071-11eb-8f8a-50a7ddfd1a8c.png)

**Comment by rachelsater** [comment]
For the Medium view, I added events to this page https://d8-uat.boston.gov/departments/parks-and-recreation/improvements-paula-titus-park

1. I didn't add anything in the Link Text box but it's still appearing 
![image](https://user-images.githubusercontent.com/72876352/108122653-a0208300-7072-11eb-95ed-c47862c25777.png)

**Comment by subaha-cob** [comment]
@rachelsater - we can chat about this during our next standup. I have pushed a bunch of fixes to UAT. 

1. The big image is blurry - This issue is because the image was too small for the space it was trying to squeeze into. The image for "Featured Events" needs to be bigger
2. The "Feb 17" flag is black. In the mock up it's blue - Done!
3. The event title and details aren't bold (like in the mock up) - This is actually fine. Any bolder and it will be unacceptable. I am currently following the website standards. 
4. I added "Poetry in the Park" to the link text and then deleted it but it's appears on the page - This is also fine. You needed to delete the entire element you add. When it cannot find a text it uses the url by default.

**Comment by subaha-cob** [comment]
Pages:
https://d8-uat.boston.gov/departments/boston-centers-youth-families
https://d8-uat.boston.gov/departments/transportation

**Comment by rachelsater** [comment]
@subaha-cob Please apply this events UI design to all event display types. "Related" and "Referenced" display types should also look like the "Upcoming" display types

**Comment by subaha-cob** [comment]
https://d8-uat.boston.gov/departments/boston-centers-youth-families

**Comment by duffy-james** [comment]
Is "related" supposed to also have options for "small", "medium", and "large"? I only see options for "related" and "related" auto:

![image](https://user-images.githubusercontent.com/7929556/110480647-b8555200-80b4-11eb-9ac5-59ee91c8e8cf.png)

**Comment by subaha-cob** [comment]
@duffy-james are you suggesting removing the "auto" all together? The "auto" was added to give the system the ability to decide what "state" to use in displaying the events. The user doesn’t have to make that decision anymore because it gets taken care of automatically by the system.

I didn't add related medium and large because I didn't think it was needed since it also has an "auto". But we can add it as well if you think we need it there. 

I agree with you about Upcoming/Upcoming Small. We need to pick one there. 

For "public notice" I can take of that change to display default image/icon. That should have been a bug, thanks for catching this.

**Comment by subaha-cob** [comment]
@reillyzlab and @mmcgowanBOS Do we know what "Referenced" events are? Nobody seem to know what they are and why we have a view for them if we don't ever use them. I assumed James will know, but he doesn't.

**Comment by duffy-james** [comment]
Here's what I'm thinking for the fields to keep:

"Upcoming"
"Related auto"
"Related small"
"Related medium"
"Related large"

**Comment by subaha-cob** [comment]
@mmcgowanBOS Just found out from Alex that meterolist is using the "referenced view". It was something Amy requested for and was added.

**Comment by mmcgowanBOS** [comment]
Thanks Stella for following through with this and to Alex to help clarify. I'm glad we didn't that view! :)

> 

>

**Comment by duffy-james** [comment]
@subaha-cob sounds good on referenced. Everything tested out fine for me with "related" and "upcoming". Maybe we move "referenced" and "referenced auto" to the bottom of the "display" options list, since that's just for DND?

Other than that, looks like we're good to go.

**Comment by subaha-cob** [comment]
@rachelsater I am prepping events UI for push to production. I am planning on doing it tomorrow morning. Let me know if not okay.

**Comment by rachelsater** [comment]
Sounds good! Thanks Stella and Jame

**Comment by duffy-james** [comment]
@rachelsater @subaha-cob one small bug I noticed, in this example, the event had an image in the "thumbnail", but it looks like it's overlaying on top of the default image:

![image](https://user-images.githubusercontent.com/7929556/111474431-72c30580-8702-11eb-9f25-9d22a375a5c5.png)

This is for the "related / upcoming large" display.

**Comment by subaha-cob** [comment]
@duffy-james taking a look now.

**Comment by duffy-james** [comment]
@subaha-cob thanks for fixing! Definitely working now but the image looks a little pixelated. I dropped in a high-res image (1080px by 1080 px) and it looks like this:

![image](https://user-images.githubusercontent.com/7929556/111527895-d1a27200-8736-11eb-9301-7d38571ff32e.png)

**Comment by subaha-cob** [comment]
@duffy-james Do you if I push the fix for the image overlap for now? I know what the issue with the image is. It is accepting the "thumbnail" image instead of the actual size of the image. So it keeps overriding because we are calling the "thumbnail" and not the actual image.

**Comment by duffy-james** [comment]
@subaha-cob Sure thing, let's do that for now just to address the overlap issue. We can always use the "featured" option for now.

**Comment by subaha-cob** [comment]
This was updated last week. @rachelsater you may keep this ticket open for another week before you close it.

**Comment by rachelsater** [comment]
this is complete, closing the ticket
