### ISSUE TITLE
Type-Specific Outcomes under Header Images

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1746]
### QA Notes:

- [x] Unclear guidance given on Housing outcomes. MVP outcomes for housing = Neighborhood, Councilor, Units Total, Units Affordable, Property Size

Based on whiteboarding, adding in dynamic fields that are dependent on Project Type for whether they appear.

All Projects:
- Neighborhood (MVP)
- Property Size (MVP)

Housing:
- Units Total (MVP)
- Units affordable (MVP only)
- Affordability Mix component (Post-MVP)
- Units Rent (Post-MVP)
- Units Own (Post- MVP)

Open Space:
- Number of Plots Created (Post-MVP)

Commercial:
- Commercial SF (net) (Post-MVP)

Abutter Sales:
-  Future Annual Tax Revenues (Post-MVP)
- Sale price? (Post-MVP)

**Comment by AmyWipfler** [comment]
Sure! 
![image](https://user-images.githubusercontent.com/55395593/101823312-90c40d00-3af8-11eb-889a-0ff11ccd3d9d.png)

Will bring a more thorough list to whiteboarding tomorrow

**Comment by padora-cob** [comment]
Need to add in the default message and selectively show for type.

**Comment by AmyWipfler** [comment]
@lizcormack-bos Can you re-send the specs/logic for which fields to show on which project types? Looks like "Housing" is showing more fields than the prototype has in them.

e.g. https://d8-ci.boston.gov/bh/demo/project/highlandmarcella-package-4

**Comment by AmyWipfler** [comment]
MVP outcomes for housing = Neighborhood, Councilor, Units Total, Units Affordable, Property Size

**Comment by AmyWipfler** [comment]
Looks great, thank you @padora-cob !

**Comment by lizcormack-bos** [comment]
+1, looks great! Thanks Amy for documenting MVP outcome list.
