### ISSUE TITLE
Final Project Type icons

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1747]

**Comment by lizcormack-bos** [comment]
Final icons approved by Caroline! We're going to use the same icons for all sub-types (ie. all housing types will be the same house).

![Screen Shot 2020-12-22 at 3.06.55 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/954325ab-f02b-4440-9784-085c6aa7c784)

**Comment by padora-cob** [comment]
Added, configured and uploaded all icons currently available to CI.

**Comment by AmyWipfler** [comment]
They look great!

**Comment by padora-cob** [comment]
Add in new icon for the "?"

**Comment by lizcormack-bos** [comment]
Icons are looking great!
