### ISSUE TITLE
Represent Abutter Sales as a Project Type

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1748]
Show all projects with Dispo Type = Abutter or Abutter Sales as a separate Project Type from Open Space, Housing, or Commercial. Have this display a different card on the Project Page that is aligned in design with a map marker that has a unique icon representing these projects on the map. Run by REMS as testing before development.

**Comment by lizcormack-bos** [comment]
Two potential options! 

![Screen Shot 2021-01-08 at 4.36.37 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/14d6af6c-c604-40cf-b604-918f381893bd)

In context:

![Screen Shot 2021-01-08 at 4.36.01 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/8cf8f58c-b7c8-4c85-bc33-ccc4f61e8962)

![Screen Shot 2021-01-08 at 4.36.11 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/fa54304e-f836-4db3-ad37-30b41bb099cf)

**Comment by lizcormack-bos** [comment]
Going to get sign off from REMS, then will move to Development!

**Comment by AmyWipfler** [comment]
Got sign off on the price tag icon from REMS. Good to implement!

**Comment by AmyWipfler** [comment]
This data has been spot-checked and seems to be working as expected. Nice work!

@lizcormack-bos If there are any design QA notes, feel free to add. Moving to Done for now.
