### ISSUE TITLE
"Use to be Determined" Project Type

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1753]
Decide rules for how this should show on Project Page. Maybe this appears as a "?" icon on the map view?

**Comment by lizcormack-bos** [comment]
Remaining dispo types that fall under TBD in the new proposed logic (after separating out abutter sales):

- Community Facility
- Dispo Planning Proj
- To Be Determined

**Comment by AmyWipfler** [comment]
Looking to minimize the number of Dispo Types:

https://docs.google.com/document/d/1wi9CGoOdhL2bY-wdqIujyIaFL_AQSbTGUBKuHcVwUvc/edit?usp=sharing

**Comment by lizcormack-bos** [comment]
The "TBD" project type is live and fulfills this objective. Only remaining question is whether "Community Facility" successfully is successfully mapping to "Commercial" instead of TBD. Seems likely since there are very few TBD projects on the map right now, but made a note to check!
