### ISSUE TITLE
Style Gallery view of Photos

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1754]
**QA NOTES**

- [x] Add 2 spaces between "CLOSE" and "X" so it doesn't look like one word.
- [x] Overlay with "+ Photos"

Theming with blue and Image overlay

**Comment by padora-cob** [comment]
Basic layout and functionality are done, just styling left

**Comment by padora-cob** [comment]
Still working on the count overlay "#+ Photos". It has been a little more annoying then I had hoped, but pushing the rest for up now.

**Comment by lizcormack-bos** [comment]
I'm going to create a new ticket to depict the number of images on the project page, and let's remove that from the scope of this ticket. 

Only change we need is to add two spaces between "CLOSE" and "X" so it doesn't look like one word.

**Comment by lizcormack-bos** [comment]
Noticed one more thing - it looks like the title of images isn't displaying in the photo gallery. In the spec, it should show up as either the file name, or, if a DO edits the title, as that updated title, in the top left of the lightbox. Adding to QA notes!

**Comment by padora-cob** [comment]
Still need to implement these changes, not complete.

**Comment by lizcormack-bos** [comment]
Note, the file name of images is still not showing in the photo gallery. For some reason the project name is showing instead. I'm comfortable closing this for now, and we can keep an ear out if this is a requested feature.
