### ISSUE TITLE
Dates and Content for Moments in the Timeline

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1758]
### QA Notes

- [x] It looks like projects in the Salesforce Project Stage "Construction Complete - project open" are being shown on the site as "In Construction". Can you edit to show these as "Project Complete"?

Examples founds:
https://d8-ci.boston.gov/bh/demo/project/orient-heights-phase-two
https://d8-ci.boston.gov/bh/demo/project/coppersmith-village-rental

Logic is documented in first two tabs of this sheet: https://docs.google.com/spreadsheets/d/1eQRmggs_nI8wTs0vrWEKXsjeCOTiRhv9P1dFrvtq9Wo/edit?usp=sharing

To ensure there are standard rules for where data and content come from for the timeline, we need the following implemented for the different Moments that populate the timeline.

 https://docs.google.com/document/d/1FT8kdOWlDJ4vzBZb3wsPUCw3V_rjtZbO9ks1zfxCrEI/edit?usp=sharing

**Comment by lizcormack-bos** [comment]
Timeline UI thing - need to update so that the entire line between previous and future stage is optimistic blue, and everything after the most recent moment in the active stage should be a dotted line. @padora-cob, let me know if you want to touch base on this! See below for reference.

![Screen Shot 2021-01-12 at 11.13.48 AM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/5934700d-29bd-484b-8d7e-569e6a3ff99c)

**Comment by AmyWipfler** [comment]
So cool that this is working!

**Comment by AmyWipfler** [comment]
@padora-cob It looks like projects in the Salesforce Project Stage "Construction Complete - project open" are being shown on the site as "In Construction". Can you edit to show these as "Project Complete"?

Examples founds:
https://d8-ci.boston.gov/bh/demo/project/orient-heights-phase-two
https://d8-ci.boston.gov/bh/demo/project/coppersmith-village-rental

Logic is documented in first two tabs of this sheet: https://docs.google.com/spreadsheets/d/1eQRmggs_nI8wTs0vrWEKXsjeCOTiRhv9P1dFrvtq9Wo/edit?usp=sharing

**Comment by padora-cob** [comment]
Projects in the Salesforce Project Stage "Construction Complete - project open" are being shown on the site as "Project Complete".

**Comment by AmyWipfler** [comment]
Great, thank you!
