### ISSUE TITLE
List View for Search Map

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1759]
QA/POLISH TASKS

- [ ] Reduce Header size to 21px font size w/ 24px line spacing
- [ ] Reduce vertical space between header and subhead
- [x] Remove Search bar from the left sidebar

**Comment by lizcormack-bos** [comment]
Couple things we've discussed (to validate/ invalidate in user testing):

- Default to displaying 40 (active) projects on the map/in the list view.
- By default, those 40 will be the 40 most recently updated projects.
- Liz to propose small edits to the Boston.gov pagination component. 
- Agree we want to display the "1-40 of 348" above list view.
- We will start by auto-loading search results on text input, but included a 1 second delay (need to evaluate in testing)

Here's the latest list view UI: 
![FOR MVP_Homepage.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/dfe8e0ea-7e08-4967-a28c-f2ebc3792c7d)

Here's the UI for 'No Results' 
![FOR MVP_Homepage_No Results.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/54961a1f-df71-44da-a282-ec442814d0ca)

**Comment by lizcormack-bos** [comment]
@padora-cob FYI, couple small changes to these based on the Design Review on Tues!

- Bold the Project Stage
- Increase the size of the icon (was 25 px width in mockup, now 30 pix)

![Screen Shot 2021-01-06 at 6.56.57 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/4806886f-3c70-4c7b-8353-cbf8ce883baa)

**Comment by padora-cob** [comment]
Holding off until we get the new mobile design as it will affect how the desktop view displays.
