### ISSUE TITLE
Locate Project on Search Map

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1760]
### QA Notes:

- [x] Inactive projects are no longer showing on the map.
- [ ] Have to tap on the cluster icon 2-3 times to zoom into the group, could we make those responsive on first click?

Efficiently use icons and UI help users quickly ID projects of interest.

**Comment by lizcormack-bos** [comment]
Icons finalized, we know we want to work on a Legend for the project types - see [#1799](https://app.zenhub.com/workspaces/buildinghousing-product-board-5bdb03f74b5806bc2bf0117c/issues/cityofboston/boston.gov-d8/1799) in consideration.

![Screen Shot 2021-01-06 at 2.47.25 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/5dcf9fac-e3b0-449f-ac4f-8380bdc9732e)

**Comment by padora-cob** [comment]
I cannot reproduce the "Have to tap on the cluster icon 2-3 times to zoom into the group, could we make those responsive on first click?" issues on CI. Please send back if you can and then demo, thanks.

**Comment by AmyWipfler** [comment]
I couldn't replicate  either. Let's move to Done, and @lizcormack-bos if there are still issues, just send along a screen recording of the interaction.
