### ISSUE TITLE
Parcel overlay on Headline Map

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1761]
**Design Requests**

- [x] Add 45 degree tilt to header image w/ parcel overlay
- [x] Use satellite map
- [x] Keep default map interaction buttons

Show Headline map with Parcel overlays rather than Pins. See design concept below.

**Comment by AmyWipfler** [comment]
![image.png](https://images.zenhubusercontent.com/5f774cd93389cdee6cb34b22/4aaca873-33cb-48b7-b52d-a095c3a58338)

**Comment by AmyWipfler** [comment]
Using Assessors ArcGIS coordinates into presentation.

**Comment by AmyWipfler** [comment]
Preference for Satellite style - Up to Liz which map style to go with.

**Comment by padora-cob** [comment]
Did more research and found a way that we can use ArcGIS and City of Boston data to get a "printable" image of a map overlay. Have been reading through the documentation and trying some request. This would create and image with the parcel overlay.

**Comment by padora-cob** [comment]
Still working on this one.

**Comment by padora-cob** [comment]
Not complete. Making style changes as requested. Working on getting all changes together and pushing up to CI.

**Comment by lizcormack-bos** [comment]
Customization options referenced in the demo today!

![Screen Shot 2021-02-12 at 1.15.42 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/5b7430f1-41aa-4c94-98fa-10acdbcf2140)

**Comment by padora-cob** [comment]
The 45* should apple when available.
