### ISSUE TITLE
Affordability Mix Pie Chart in Sidebar

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1762]
Done = Independent component that visually represents housing outcomes by low, middle, and market incomes. Maze tests run to verify that users understand the income mix and it's impact on their neighborhood.

![image.png](https://images.zenhubusercontent.com/5f774cd93389cdee6cb34b22/2f81093d-7cae-4191-a39c-8d36da16eae6)

^From the Project record

**Comment by lizcormack-bos** [comment]
Link to Boston.gov Income Restricted Housing guide: https://www.boston.gov/income-restricted-housing-guide

**Comment by lizcormack-bos** [comment]
Currently most excited about #6 and #13 in this list: 

![Screen Shot 2021-03-02 at 5.23.36 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/7e86abdb-fa9c-4ebb-831b-6321e6776197)

**Comment by lizcormack-bos** [comment]
Relevant user interview clips:

https://grain.co/highlight/zNLKSFPY6fEvFGUWxYuZdq9JaVtZqOhg2G8Rnoyg
https://grain.co/highlight/bz3bs7jrr7gPNJxtbUDXSTnMZf7Wdkb929UynbSe

**Comment by rachelsater** [comment]
closing this ticket as it was decided not to present an affordability pie chart on the site
