### ISSUE TITLE
Add Button to Open Space + Housing: Homeownership Project Type Components

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1763]
Done = Users are routed to the Open Space Drupal page by interaction with Open Space card on the Project Page, and to the NHI program homepage from the "Housing - Homeownership" component if the dispo type is "Housing - NHI."

- [ ] Add Open Space link to all open space project types.
- [ ] If Dispo type is Housing - NHI, add button to NHI homepage.

**(see comment with images)**

**Comment by lizcormack-bos** [comment]
Add link as a button to all Open Space projects-- see below, button width should be the same as the buttons on the Community Meeting component! 

Here's the Grassroots and Open Space Development Homepage to link to: https://www.boston.gov/housing/grassroots-and-open-space-development

![Screen Shot 2021-03-09 at 4.37.51 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/b4c3ad72-6d19-4572-8fb2-f6fc6383e311)

**Comment by lizcormack-bos** [comment]
final designs: 

![Screen Shot 2021-03-11 at 5.37.12 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/f5cdc165-d05c-4ac4-89b5-0ad2c967c516)

**Comment by padora-cob** [comment]
Ready to test on CI: https://d8-ci.boston.gov/buildinghousing/boylston-street-potential-open-space
and
https://d8-ci.boston.gov/buildinghousing/61-65-woodrow-ave

**Comment by rachelsater** [comment]
after talking to Alex, this ticket is good to go to Prod. The fonts in the mock up is different from the live site so they won't match exactly

**Comment by stephaniemar** [comment]
this looks like it was done but is in stage? need confirmation on this @rachelsater

**Comment by rachelsater** [comment]
correct. it needs to get pushed to the live site still

**Comment by duffy-james** [comment]
Closing issue for now.
