### ISSUE TITLE
MVP Email List Component

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1764]
**QA NOTES**

- [x] Rearrange order in sidebar so DO contact info is above email sign up.

Edit existing component copy to set better expectations for emails. Write back to raw list on related Website Update objects.

**Comment by lizcormack-bos** [comment]
Overview of user needs/ constraints by template:

**1. Inactive Projects**

NEEDS
Neighbors want to be notified if it becomes active in the future (see active project needs).
Other personas may want to know if it becomes available for purchase/development.

CONSTRAINTS
Could be many years before that's the case.

**2. Active Projects**

NEEDS
Neighbors want to be notified when...
1. There's a meeting
2. There are notes and documents available (esp. images/renderings) after a meeting
3. The developer was selected
4. Construction starts
5. Construction ends

CONSTRAINTS
We have no reliable solution yet for email list management, so communication is entirely at the discretion of DOs. A user who signs up could receive many emails, or no emails.

Am I missing anything here?

**Comment by lizcormack-bos** [comment]
Questions:
1. How might we reduce the text (is it possible or necessary to do so)? 
2. Should we add a language drop down to help inform DOs communication?

![Screen Shot 2020-12-28 at 5.21.40 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/17ee2a26-c424-4d10-9854-d7ed5d36a3d9)

**Comment by AmyWipfler** [comment]
Think you captured it well! Only one addition to the Active Project NEEDS section: We want a notification to go out when a lottery is available for newly created units.

**Comment by padora-cob** [comment]
Need to add one more field for name and then create the write back for the web update object.

**Comment by lizcormack-bos** [comment]
Final design and copy here and in the Specs page:

![Email Signup.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/c85f5b0d-f486-41ec-9796-6389c50879ca)

**Comment by AmyWipfler** [comment]
Working great!

**Comment by AmyWipfler** [comment]
All set! Thanks @padora-cob
