### ISSUE TITLE
Projects with Meetings Pinned in List View

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1769]
Done = Designs updated for this with new list view, delivered so that users see projects with meetings in the future pinned to the top of the list.

Final design! 

- if no upcoming meeting, remove the whole section, including the title
- link the date on the preview card directly to the associated event detail page (let me know if this a scope concern!) 
- this section should also reflect the normal filters on the map (ie. if the project isn't in view on the map, don't display in the pinned community meeting section)
- there should be no duplicate projects (ie. if it's in the pinned meeting section, that's the only place it shows on the list)

**Comment by lizcormack-bos** [comment]
Final design! 

- if no upcoming meeting, remove the whole section, including the title
- link the date on the preview card directly to the associated event detail page (let me know if this a scope concern!) 
- this section should also reflect the normal filters on the map (ie. if the project isn't in view on the map, don't display in the pinned community meeting section)
- there should be no duplicate projects (ie. if it's in the pinned meeting section, that's the only place it shows on the list)

![Screen Shot 2021-02-25 at 9.38.17 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/fbfe1886-70db-42ba-85f0-f18abfb2d659)

**Comment by duffy-james** [comment]
Closing issue for now.
