### ISSUE TITLE
Documents in Timeline Styling/Template

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1775]
Complete Timeline needs to MVP spec to be able to support Legacy content and future content.

## QA TASKS:
- [x] The blue used in the file name (description text) and "View More Documents" link should be Optimistic Blue.
- [x] Shrink the bubble on the timeline down to 25px wide
- [x] For all document instances where multiple docs were uploaded, display only one document before cutting it off with the view more button.
- [x] Cut off text after 2 lines and display ellipsis 
- [x] Open documents in a new tab (open to thoughts on this! -Liz)
- [ ] Ensure the color of the timeline adjacent to a document accurately reflects the active stage.

- [x] Sizing for mobile

**Comment by AmyWipfler** [comment]
Specs added for "Read More" and "View More Documents". Implementation needed to complete styling/layout.

**Comment by lizcormack-bos** [comment]
Two 'expand to view more' styles! 

![Screen Shot 2020-12-14 at 10.12.36 AM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/ebcc6f7a-9b84-474e-9c14-e104b9909387)

![Screen Shot 2020-12-14 at 10.12.41 AM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/78d364ab-daf5-4f3c-88e5-1587540e1d39)

**Comment by padora-cob** [comment]
Template is done, just need to finish up the styling

**Comment by lizcormack-bos** [comment]
Two things on docs!

- [ ] The blue used in the file name (description text) and "View More Documents" link should be Optimistic Blue.
- [ ] All docs above the "View More" button should have their own dot on the timeline - see below. But seeing it live, I'd love to shrink those down to 25px wide please! They look a little big on the page.

![Screen Shot 2021-01-12 at 11.22.18 AM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/1ad2c10c-98b1-4803-87f2-0f138d5460df)

**Comment by padora-cob** [comment]
Still need to implement these changes, not complete.
