### ISSUE TITLE
Inactive Project Page Content/Layout

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1777]
**QA NOTES** 

- [x] Update the intro copy on the Contact form (see comment below).
- [x] (bug) Header is showing up twice on the page
- [x] Contact information should show the default view (ie. the generic DND email address, displayed as an "Email Us" link). Currently shows William Epperson's contact info.
- [x] Reduce the vertical spacing between the outcomes and the content below by ~150%. 
- [x] The top section of the page should have a white background (true for all page templates).

Should not rely at all on PM updates. Should mimic Active Project page design/layout. Should include: Headline Map, Images, Interactive Map, Neighborhood, Square Footage, and Email List components. Should have generic default copy in the Project Goals section. MVP, no contact info.

**Comment by AmyWipfler** [comment]
Whiteboarding on Friday?

**Comment by AmyWipfler** [comment]
See Miro board for initial concepts. MVP content = 

- Map with parcel overlay
- Interactive Google map
- Google Street View
- 311 link
- Upaknee list signup (pending Mktg recommendation)
- REMS email address (pending confirmation)
- Neighborhood
- City Councilor
- Square footage
- Default blurb about inactive parcels

![image.png](https://images.zenhubusercontent.com/5f774cd93389cdee6cb34b22/ae3c4b78-8b52-403c-b910-52651d022fac)

**Comment by lizcormack-bos** [comment]
Initial concept below! I'm working on "project preview" cards to list at the bottom of the page (and associated logic for what to display if we do - worth more discussions when we investigate the buyer persona).

I'm wondering whether there are ways to differentiate this more from active/regular projects, but I'm thinking we probably shouldn't sink too much time into it until we understand the buyer more.

![DND-Owned Land (inactive).png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/b8cfef5c-05e0-474f-a22e-4e858e0152ff)

**Comment by AmyWipfler** [comment]
This is great! Let's keep this prototype for improving the potential owner experience. Unfortunately with the dead-ends internally, I don't think we can release with contact info or submission of interest.

If you think those are must-have, I can keep pressing the issue, but I'm making little headway in understanding how we handle information requests currently and which channels they arrive by. Would not want this to be released and then be a dead-end for users as well.

**Comment by lizcormack-bos** [comment]
@AmyWipfler Happy to backlog the "inquiry" button (figured we would, but didn't want to lose that idea). I would like to include some sort of contact info, even if it's a DND info@ email. 

Could we use "NEIGHBORHOODDEVELOPMENT.DND@BOSTON.GOV" ? (which is on the DND homepage)?

**Comment by AmyWipfler** [comment]
Yep! We can go with that. If Jamie gets back with some other option, we'll adjust, but I think the general email should suffice.

**Comment by lizcormack-bos** [comment]
Waiting for copy review from REMS, design is final and approved, will update copy ASAP!

**Comment by lizcormack-bos** [comment]
Final design for this page! See the 'Page Templates' section in Figma.

![Screen Shot 2021-01-19 at 4.58.31 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/0f7a709c-2d8d-4cea-9855-24807506f6d4)

**Comment by lizcormack-bos** [comment]
Spacing & white background look great! Only issue, there seems to be a bug where the title is showing up twice as a header and subhead above that dotted line. Once that's removed, this is good to go!

![Screen Shot 2021-01-29 at 3.09.44 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/59c9e824-bd09-4d90-96f5-59858f98fbf5)

**Comment by lizcormack-bos** [comment]
Last thing! Want to update this copy to the following:

_Do you have a question, or want to express interest in this land? Contact the Department of Neighborhood Development's Real Estate Management office below._

![Screen Shot 2021-01-29 at 3.33.55 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/a7a758a4-8017-48af-a1f8-ee0aed6861de)
