### ISSUE TITLE
Default text for Meeting Goal

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1781]
In Salesforce, there's now a field for "Meeting Goal" (150 char max). This will display in the subhead part of the boston.gov/events template, and in the upcoming meeting timeline moment.

What is the standard text we want to show up on DND Meeting Event pages? Will be default, but can be overwritten by DO/PM is needed.

**Comment by lizcormack-bos** [comment]
**Here's the proposed default copy:** The Department of Neighborhood Development is looking for feedback from the community. Join us to see the latest plans and share your thoughts.

Second option for reference (let me know if anyone prefers this strongly): We need your feedback! Share your thoughts, questions and concerns with the Department of Neighborhood Development as we share the latest plans for this lot. 

FYI, the "Meeting Goal" copy (with this as the default) is what I'd like to use for the upcoming community meeting timeline body copy in [#1737](https://app.zenhub.com/workspaces/buildinghousing-product-board-5bdb03f74b5806bc2bf0117c/issues/cityofboston/boston.gov-d8/1737).

![Screen Shot 2021-01-05 at 5.46.29 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/7def982d-f40b-446f-bd6b-088c10598342)

**Comment by AmyWipfler** [comment]
I like the first option! Implemented in Salesforce and also set character limit to 150 for this field if DOs choose to edit.

**Comment by lizcormack-bos** [comment]
Awesome, thanks!
