### ISSUE TITLE
Added Project filter logic

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1782]
### QA Notes:

- [x] "Community Facility" as Dispo Type should be Outcome = "Commercial"

- [x] "Interagency Transfers" still appearing ( https://d8-ci.boston.gov/bh/demo/project/deforest-street-conservation-transfer
https://d8-ci.boston.gov/bh/demo/project/charlestown-city-square-korea-vietnam-memorial
https://d8-ci.boston.gov/bh/demo/project/174-west-second175-west-first
https://d8-ci.boston.gov/bh/demo/project/parks-transfer-geneva-normandy
https://d8-ci.boston.gov/bh/demo/project/norwell-street-wow-park-parks-transfer)

- [x] Tax Title properties still appearing (https://d8-ci.boston.gov/bh/demo/project/5-boynton-jp-triple-tax-title-building)

- [x] Mixed Use projects are not showing as housing (https://d8-ci.boston.gov/bh/demo/project/quincy-warren
https://d8-ci.boston.gov/bh/demo/project/bartlett-place-building-9-lihtc)

- [x] NHD Development records without Project Type are not showing as housing (https://d8-ci.boston.gov/bh/demo/project/whittier-street-cdbg-construction
https://d8-ci.boston.gov/bh/demo/project/beverly-street-middle-income-development-parcel-1b
https://d8-ci.boston.gov/bh/demo/project/dudley-terrace-apartments
https://d8-ci.boston.gov/bh/demo/project/fairfield-boston-apartments)

Uncovered new rules for Projects which should NOT show up on the site:

IF Dispo Type =
Incoming Transfer OR
Interagency Transfer OR
Non-active/Postponed OR
Tax title - Foreclosure Prevention OR
Tax title - Problem Property OR
Tax title -  Redemption OR
Tax title -  Revenue OR
Tax title -  Site Assembly OR
To be deleted

THEN do not create a BH Project Page

**Comment by padora-cob** [comment]
The new logic stops these projects from showing. Going to move that to stop from import with a query update later.

**Comment by padora-cob** [comment]
The count is looking better on CI now with the filter applying: ![image.png](https://images.zenhubusercontent.com/5f89d184cfdb562ca4003222/b4d6c4be-5788-4fd0-a898-d078c057b44c)

**Comment by AmyWipfler** [comment]
Thanks! In reviewing the project list it looks like "Interagency Transfers" are still coming though. Found these projects: 

https://d8-ci.boston.gov/bh/demo/project/deforest-street-conservation-transfer
https://d8-ci.boston.gov/bh/demo/project/charlestown-city-square-korea-vietnam-memorial
https://d8-ci.boston.gov/bh/demo/project/174-west-second175-west-first
https://d8-ci.boston.gov/bh/demo/project/parks-transfer-geneva-normandy
https://d8-ci.boston.gov/bh/demo/project/norwell-street-wow-park-parks-transfer

**Comment by AmyWipfler** [comment]
This may be WIP, but noticed two other issues with the Project Type filtering:

1. Mixed-Use projects are not showing as Housing:
https://d8-ci.boston.gov/bh/demo/project/quincy-warren
https://d8-ci.boston.gov/bh/demo/project/bartlett-place-building-9-lihtc

2. NHD Development Projects where there's no Project Type are not showing as Housing:
https://d8-ci.boston.gov/bh/demo/project/whittier-street-cdbg-construction
https://d8-ci.boston.gov/bh/demo/project/beverly-street-middle-income-development-parcel-1b
https://d8-ci.boston.gov/bh/demo/project/dudley-terrace-apartments
https://d8-ci.boston.gov/bh/demo/project/fairfield-boston-apartments

Re-referencing to Project Outcome logic here: https://docs.google.com/document/d/1wi9CGoOdhL2bY-wdqIujyIaFL_AQSbTGUBKuHcVwUvc/edit?usp=sharing

**Comment by AmyWipfler** [comment]
Also finding Tax Title projects showing up, like this one:

https://d8-ci.boston.gov/bh/demo/project/5-boynton-jp-triple-tax-title-building

**Comment by AmyWipfler** [comment]
Looks great, thank you!
