### ISSUE TITLE
As a Housing Seeker, I would like more precise AMI recommendations from the AMI Calculator for 2020 income limits, so that I can more granularly search for housing I qualify for.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1786]
We have more precise AMI level data from DND Policy team that needs to be updated. On top of that we have new AMI levels that were not uncovered in original discovery. Any values not highlighted on this list need to be added to the logic for the AMI calculator.

![image](https://user-images.githubusercontent.com/55395593/102514533-95d60e80-405a-11eb-8e51-64ba0fe1ea24.png)

[2020-12-15 2020 AMI CHART.xlsx](https://github.com/CityOfBoston/boston.gov-d8/files/5710763/2020-12-15.2020.AMI.CHART.xlsx)

**Comment by duffy-james** [comment]
Closing issue for now.
