### ISSUE TITLE
As a property manager, I would like to required to check a box on at least 1 unit if I have requested to edit existing units in the Listing Form, so that my submission generates data for Salesforce.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1787]
Common user error is occurring on the ML Listing Form where a user says they want to "re-list" existing units, but then does not select any of the units (probably wants to re-market all units as a Waitlist). Because they are allowed to submit this set of values, the email triggers to Amy, Dana, and Alex, but no units in Salesforce are updated to Pending for Dana's review, and we miss the opportunity to re-market.

So we need to find a way to require at least one unit's worth of detail to allow the user to submit.

**Comment by duffy-james** [comment]
Closing issue for now.
