### ISSUE TITLE
Neighborhood lookup: Varying amounts of hover color on cards when using keyboard tabbing.

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1793]
After a user has entered an address and they cab keyboard tab through the site: The cards are acting differently on hover. 

Some of the gray at the bottom is completely covered by hover. Others there are varying levels of gray appearing (i.e. the card isn't completely covered by the hover. 

The behavior of all cards should behave like the newsletters card and be all covered.

![Screen Shot 2020-12-23 at 2 50 05 PM](https://user-images.githubusercontent.com/20731897/103032498-c79d1880-4525-11eb-8ce9-5d489a2e0354.png)

![Screen Shot 2020-12-23 at 11 55 33 AM](https://user-images.githubusercontent.com/20731897/103032431-9fadb500-4525-11eb-8421-b785b9db08f2.png)

![Screen Shot 2020-12-23 at 11 55 39 AM](https://user-images.githubusercontent.com/20731897/103032432-9fadb500-4525-11eb-8a35-6fb9480b8566.png)

**Comment by subaha-cob** [comment]
@reillyzlab test on https://d8-uat.boston.gov/my-neighborhood?p3

**Comment by subaha-cob** [comment]
UAT is now up with MNL tickets.
https://d8-uat.boston.gov/

Try testing with this addresses only:

50 Milk St #2050 Boston, 02108
192 Dudley St Roxbury, 02119
27 Tyler St Boston, 02111
1 State St Ste 1500 Boston, 02108

**Comment by reillyzlab** [comment]
Checked on staging - passed/complete.
