### ISSUE TITLE
Translation not carrying through to other boston.gov links/page when link clicked within an iframe - M/L

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#1795]
If user goes to a translated version of boston.gov and clicks a link **within an iframe** the translation should carry through and a user should be taken to the boston.gov page in the language that the user has already selected to use.

However, they users is currently taken to an English version of boston.gov.

Pages with an embedded iframe (for reference/testing):

- https://www.boston.gov/departments/parks-and-recreation/planning-design-and-construction-boston-parks
- https://www.boston.gov/departments/boston-bikes/bike-rack-program
- https://www.boston.gov/news/state-city-2020

And these pages use both an iframe component and an embedded iframe:

- https://www.boston.gov/departments/small-business-development/supporting-bostons-open-businesses
- https://www.boston.gov/departments/small-business-development/support-bostons-restaurants

Related issue: https://github.com/CityOfBoston/boston.gov-d8/issues/1743

**Comment by stephaniemar** [comment]
@davidrkupton Do we need to move this to JIRA?

**Comment by davidrkupton** [comment]
@stephaniemar 
This is still an issue, but we cannot do anything about it.
We can close.
