### ISSUE TITLE
"Add to Calendar" feature not working with recurring event - S

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1806]
If a user tries to add a recurring event to their calendar (i.e. Google Calendar, iCal, Yahoo Calendar etc.), only the first event in the series is added.

**Comment by andrebtlima** [comment]
related to 1170

**Comment by rachelsater** [comment]
@subaha-cob is this live?

**Comment by subaha-cob** [comment]
@rachelsater kind of live. Parts of this is live. But the recurring event is a bug  and still needs to be fixed.

**Comment by duffy-james** [comment]
@subaha-cob has this been addressed? If not, I can create a ticket in Jira.

**Comment by stephaniemar** [comment]
@duffy-james Did you end up putting a ticket for this?

**Comment by duffy-james** [comment]
@stephaniemar I did not -- it looked like there was some work done on the issue, but I couldn't tell.

**Comment by stephaniemar** [comment]
@subaha-cob Do you know if any work was done on this issue- should we move it to Jira?

**Comment by subaha-cob** [comment]
@stephaniemar @duffy-james Sorry I didn't reply the first time. This is still an issue but, I don't know if there is a fix for it. It is quite involved and I am not sure how easy it will be to fix. I am hoping the plugin owner will do an update that will fix it someday.

**Comment by stephaniemar** [comment]
I do not want to loose track of this - I can add a ticket to the backlog and make it a research spike? @duffy-james @davidrkupton @subaha-cob

**Comment by duffy-james** [comment]
@stephaniemar sounds good to me.

**Comment by stephaniemar** [comment]
https://bostondoit.atlassian.net/browse/DIG-1026
