### ISSUE TITLE
Change "Add to Calendar" button styling 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#1807]
![Screen Shot 2021-01-13 at 1 56 56 PM](https://user-images.githubusercontent.com/57111927/104498663-0284f000-55aa-11eb-833e-e8df36a478f5.png)

Revise styling of "Add to Calendar" button (shown above)  to all caps and grey color instead of white with drop shadow.

Related to #1170

**Comment by subaha-cob** [comment]
@rachelsater this is now on UAT. Please test when you have a few minutes.

**Comment by subaha-cob** [comment]
@rachelsater Go to any events page:
https://d8-uat.boston.gov/calendar/blue-hill-avenue-virtual-office-hours-afternoon-0
Scroll down and you will see a button

**Comment by rachelsater** [comment]
Looks good thanks! Moving to Ready to Deploy

**Comment by reillyzlab** [comment]
This is on production so closing this ticket.
