### ISSUE TITLE
Resolve Project Goals Character Length

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1809]
**Problem:** Current Project Narrative text (now displaying under Project Goals) is sometimes too long and may not include project goals. Couple options we discussed:

- Work with DOs to edit existing text down to sub 500 char.
- Edit it for DOs.
- Display "Read More" after a certain number of characters.
- Impose 500 char. limit and cut off text (+one of the above).

**Comment by lizcormack-bos** [comment]
SF Data download w/ narrative export from each DO's projects: https://docs.google.com/spreadsheets/d/12L6oS4IejlqrVTan9y_HlN7WabJMiNvjJ8U8Wdfa_Q4/edit#gid=314016440

**Comment by rachelsater** [comment]
We decided to display a "Read More" button if there are more than 1900 characters in the Project Goals section

**Comment by duffy-james** [comment]
Closing issue for now.
