### ISSUE TITLE
Propose Method of Collecting Feedback on Live Site

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1810]
1. Define hypotheses + biggest risks.
2. Determine how to best vet those.
3. How can we gather input to inform them from live users and optimize for learning?

**Comment by lizcormack-bos** [comment]
Progress report on this! 

Amy and I created a draft plan for how to measure success here: https://docs.google.com/spreadsheets/d/1A-1wpfl6_M84TZnrt4J6yrGcGTht1hZNaCdNlBRjm54/edit#gid=0

We'll need to ask Matt for support on a few specific Google Analytics measurements, and are vetting the possibility of using a hot spot/ session recorder. Re: new design/ development requirements, we want to display a variation of the Metrolist feedback form on the bottom of each product page. 

**Prototype Here:** https://www.figma.com/proto/AmxpMA4AvLaivoKwGXapBN/BuildingHousing?node-id=2049%3A419&viewport=510%2C418%2C0.25&scaling=min-zoom

![Screen Shot 2021-01-28 at 12.06.42 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/6f6a1894-ee0c-4781-9a9f-717727753340)

**Comment by lizcormack-bos** [comment]
The other thing we want to find is a bug reporting / site feedback feature. Looking at Drupal modules, [this one](https://www.drupal.org/project/feedback_simple) seems to be the best free and well maintained option, but I don't love the UI (find it hard to believe people notice it very often?). Any suggestions on useful modules for this welcome.

**Comment by lizcormack-bos** [comment]
Final spec proposal here: https://www.figma.com/file/AmxpMA4AvLaivoKwGXapBN/?node-id=2049%3A242

That includes mobile and desktop versions of the feedback form. I landed on a simple question about helpfulness with a 5-point scale. I removed the line to avoid confusion/comparison to our timeline!

**Comment by lizcormack-bos** [comment]
![Screen Shot 2021-02-05 at 6.41.06 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/bedb28a5-8587-49d8-ad9c-570ef52a029e)

**Comment by AmyWipfler** [comment]
Looks great! @padora-cob Please have any submissions to this form email me, you, Liz, james.smith@boston.gov and carol.owens@boston.gov
