### ISSUE TITLE
Browser tests in CI

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1814]
Confirm that Safari and Chrome are performing as expected:

![image.png](https://images.zenhubusercontent.com/5f774cd93389cdee6cb34b22/b7ae8dbc-b0f1-492e-bbf0-d790fee5750d)

![image.png](https://images.zenhubusercontent.com/5f774cd93389cdee6cb34b22/241ca64e-9b07-4f41-8480-b6a12ac41d51)

**Comment by AmyWipfler** [comment]
Project pages are loading well in tests on Windows/iOS with Chrome/Safari. Only consistent issue, is that the auto-zoom size in a desktop browser bumps the photos component and GMaps component below. Perhaps an issue with what we're trying to achieve for mobile?

![image.png](https://images.zenhubusercontent.com/5f774cd93389cdee6cb34b22/7d3ff423-50f5-4077-a69a-c3f6ea54b997)

**Comment by lizcormack-bos** [comment]
Adding screen resolution breakdown!

**For Liz's device testing**
- [ ] iPhone 11 Pro Max 
- [ ] iPhone 8
- [ ] Galaxy S9
- [ ] iPad Mini

![Screen Shot 2021-01-25 at 3.37.12 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/30991ff0-b21e-401b-b2e3-601659171433)

![Screen-Sizes.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/6fa25173-168e-4d3b-bfe8-ef64f1af59a5)
