### ISSUE TITLE
Device testing in CI

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1815]
### **QA NOTES**

- [x] Increase header font size.
- [x] Scale down & center header image.
- [x] Create two columns of outcome data.
- [x] Scale down the photo + map and display smaller side-by-side.
- [x] (leave Contact Info + Email signup until we implement the drawers from spec in [#1812](https://app.zenhub.com/workspaces/buildinghousing-product-board-5bdb03f74b5806bc2bf0117c/issues/cityofboston/boston.gov-d8/1812))
- [x] See timeline spec in Figma. Timeline icons + line should be left aligned, with dates scaled down and sitting above each icon.

**For Liz's device testing**

- [ ] iPhone 11 Pro Max
- [x] iPhone 8
- [ ] Galaxy S9
- [ ] iPad Mini

![image.png](https://images.zenhubusercontent.com/5f774cd93389cdee6cb34b22/ceece75b-6774-4f89-9d21-41d545ab9e74)

**Comment by lizcormack-bos** [comment]
https://live.browserstack.com/dashboard#os=iOS&os_version=14.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fd8-ci.boston.gov%2Fbh%2Fdemo%2Fproject%2Fgarrison-trotter-neighborhood-homes%3F3&speed=1
