### ISSUE TITLE
Update Titles + Subheads on Timeline Stages

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1830]
Need to update the names and subheads for timeline stages, based on final copy review w/ James Duffy.

###  **For Disposition Projects**

Community Feedback
_We’re meeting with community members to gather feedback on plans for the site._

Developer Selection
_We’ll release a Request for Proposals and select a developer for this site._

City Planning
_This project is going through a zoning review with the Boston Planning and Development Agency (BPDA). Then we’ll work with the Developer on funding, design, and compliance._

Under Construction
_Construction is underway. For further information on road closures and parking impact, contact the Project Manager._

Project Complete
_This project is reading for use._ 

### **For Funding-Only Development Projects**
**Dependent on #1805: Development Project Template**

Replace "Community Feedback" with: Funding Awarded
_The Department of Neighborhood Development approved funding for this project._

**Comment by padora-cob** [comment]
Updated copy, need to add the new stage type still.
