### ISSUE TITLE
Optimize Map and List View for Mobile Users

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1832]
Have them render in legible way for top 5 devices.

**Final prototype here:** https://www.figma.com/proto/k1FN1vdnY7PUy4wfqkKwIS/Mobile-Homepage-Test?node-id=4%3A102&viewport=585%2C800%2C0.25&scaling=scale-down

**Comment by AmyWipfler** [comment]
Stretch goal to use testing in this sprint as well.

**Comment by lizcormack-bos** [comment]
Created a new Figma project for the mobile test prototype (to reduce loading time in Maze). Check out the in progress designs here: https://www.figma.com/file/k1FN1vdnY7PUy4wfqkKwIS/Mobile-Homepage-Test?node-id=0%3A1

Couple things in consideration:

- where to collapse the list view (high confidence in the proposed solution)
- how to display the content preview cards (see 2 options in Figma - currently testing in Maze)
- which filtering option works best on mobile (see 2 options in Figma - currently testing in Maze)

**Comment by lizcormack-bos** [comment]
Overall this looks great - there are some performance issues on mobile, but will create new tickets:

- Search bar is cut off by the "Map/Satellite" button.
- "Building in Boston" title is cut off by the "X" button.
