### ISSUE TITLE
Launch bugs - to fix 2.2.21

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1836]
- [x] Change Tab title for homepage from "BuildingHousing - Dev | Boston.gov" to "BuildingHousing | Boston.gov"

- [x] Ensure scrolling the list view doesn't move the map component. See current behavior on Chrome, Windows 10 in this recording:
[https://app.zenhub.com/files/137221633/79eab3b1-9ee9-49e5-a41a-e5281cfb32ce/download](https://app.zenhub.com/files/137221633/79eab3b1-9ee9-49e5-a41a-e5281cfb32ce/download)

- [x] Ensure Footer does not obscure view when zooming in on map view. See current behavior on Chrome, Windows 10 in this recording:
[https://app.zenhub.com/files/137221633/1503ab5b-d204-49a5-a4b9-dd5fcd347774/download](https://app.zenhub.com/files/137221633/1503ab5b-d204-49a5-a4b9-dd5fcd347774/download)

- [x] Update boston.gov links on the Website Update to point to Prod not CI
![image.png](https://images.zenhubusercontent.com/5f774cd93389cdee6cb34b22/cf2db397-ace4-40bb-ad8d-1bfbb8d87c42)

- [ ] Re-configure the Salesforce sync so that posted content can be removed and edited as well as created. Right now Files and Text Updates cannot be deleted or edited from the site.

**Comment by padora-cob** [comment]
All the issues should be fixed on PROD except: "Re-configure the Salesforce sync so that posted content can be removed and edited as well as created. Right now Files and Text Updates cannot be deleted or edited from the site."
