### ISSUE TITLE
Bugs with Community Event

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1837]
- [x] Add to Calendar button not working from the Project Page

![image.png](https://images.zenhubusercontent.com/5f774cd93389cdee6cb34b22/44783182-3c57-4579-a4e2-d60889edd3f3)

- [x] No link to register for the event on the boston.gov Event page (this should source from the "Virtual meeting web address" field on the Salesforce Community Event record when populated.

![image.png](https://images.zenhubusercontent.com/5f774cd93389cdee6cb34b22/cc84bd47-8c65-4c39-9707-dddfc83dbd10)

- [x] Languages supported not appearing on the boston.gov Event page. If this is a request that needs to be made of Matt, please flag for me and I'll bring it up as an improvement to LCA on Events.

- [ ] Host organization is also not appearing according to specs.

- [x] Meetings in the past are not appearing as past or showing any of the necessary data fields (tested with 1 hour in the past)

- [x] When data is edited about a Community Meeting event, those changes to text or time or other information is not being updated on boston.gov

- [x] "Read more" is not shortening the meeting description  in the timeline view as expected.

- [x] When there are two community meetings posted, can we make sure that the one closest to happening is posted in the side bar? I was told this wouldn't happen, but then it did. Sigh.

- [ ] Only one language is showing up on the Event details, even when two are selected in Salesforce. Example: https://boston-dnd.my.salesforce.com/a550y000000DLAv

- [] Meeting Goal, make dynamic 

Live example to test around: https://www.boston.gov/buildinghousing/632-morton-street-potential-urban-ag

**Comment by AmyWipfler** [comment]
@padora-cob Have these fixes been merged? We need to get Community Events fixed because people are posting meetings daily now. We should not hold back because of the Host Organization issue.

**Comment by padora-cob** [comment]
Most of these issues should be fixed on PROD, the ones that are not is:

- Only one language is showing up on the Event details, even when two are selected in Salesforce.
- Host organization is also not appearing according to specs
- Meeting Goal, make dynamic
