### ISSUE TITLE
Connect BH visitors to Fair Housing resources

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1848]

**Comment by reillyzlab** [comment]
@lizcormack-bos any idea what this means?

**Comment by lizcormack-bos** [comment]
@reillyzlab I'll continue to add context, designs etc to other tickets, but this one I don't actually have a strong memory of. It was part of a larger epic to link to additional resources where possible, but we fleshed out the other relevant tasks elsewhere. Closing this for now.
