### ISSUE TITLE
Get confirmation email of BH Project subscription with helpful resources linked

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1858]
- [ ] Plain-text formatted, helpful content written and sent by Postmark whenever a user submits their email on a Project Page. 
- [ ] Email sends to the project's Development Officer alerting them of a new follower (see Google doc for content).

Copy for email:

https://docs.google.com/document/d/1h_UwDr58MHFRSwIQOqssbSDzwiIGIFt5ZBAfYUBq71s/edit?usp=sharing
---

Done = Plain-text formatted, helpful content written and sent by Postmark whenever a user submits their email on a Project Page. Stakeholder signoff needed. Note: links need to be written out.

Liz to propose plan for a targeted summary.

**Comment by lizcormack-bos** [comment]
We can use data from the page or form as inputs! Name, contact info, project name etc.

**Comment by lizcormack-bos** [comment]
Draft here: https://docs.google.com/document/d/1h_UwDr58MHFRSwIQOqssbSDzwiIGIFt5ZBAfYUBq71s/edit?usp=sharing

Sent to Carol + Kelsey in Marketing for review.

**Comment by lizcormack-bos** [comment]
This was reviewed and approved by DND marketing!

**Comment by lizcormack-bos** [comment]
This is working great!
