### ISSUE TITLE
Link to DND resources in an "Additional Resources" block

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1867]
Desired Outcome: A list of the Neighbor's info needs and documentation of where resources exist or don't, where they might be displayed etc.

**Ideate**
1. Audit existing DND resources, guides etc.
2. Do some internal research on upcoming.
3. Assess value to Neighbor + brainstorm concepts.

**Comment by lizcormack-bos** [comment]
Audit here! https://docs.google.com/spreadsheets/d/1I7PoxElWwtrFbll1elU5ipXBYxK3TvNemdNtwYaQq9o/edit#gid=0

**Comment by AmyWipfler** [comment]
This is looking great! Carol or Alexander can probably help with clarifying any additional resources that are upcoming. But even just getting half of these in will be a great start.

**Comment by lizcormack-bos** [comment]
Details from Sebastian on previous effort to add underline to links: https://github.com/CityOfBoston/patterns/pull/436

**Comment by lizcormack-bos** [comment]
Here's what I'm thinking so far --

- [ ] Add link to BPDA in the 'City Planning' description (use underline).
- [ ] Add 3 cards w/ icons to Inactive Projects (ie. city owned land).
- [ ] Add 'Additional Resources' to the Drupal homepage (pending stakeholder approval).

**Comment by lizcormack-bos** [comment]
Final design pending feedback from Marketing! Here are the links: 

**How the City Creates Affordable Housing:** 
https://www.boston.gov/departments/neighborhood-development/how-city-creates-affordable-housing

**How we Sell the City's land:**
https://www.boston.gov/departments/neighborhood-development/how-we-sell-citys-land-and-buildings

**What is Development Review?**
http://www.bostonplans.org/projects/development-review


![Screen Shot 2021-03-17 at 3.48.18 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/99f80de9-3b97-4ffe-84be-0d7ca2aaac2d)
