### ISSUE TITLE
Rework UI structure between List View and Map

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1876]
Done = Rework HTML structure to support a Map View that is scrollable before the List View. 

**Design Notes**
- For now, keep the list collapsed by default.

**Comment by lizcormack-bos** [comment]
Prototype here: https://www.figma.com/proto/AmxpMA4AvLaivoKwGXapBN/BuildingHousing?node-id=2537%3A3753&viewport=-25%2C657%2C0.18793103098869324&scaling=min-zoom

![Screen Shot 2021-02-25 at 9.50.04 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/b50ed506-baa1-4c33-9f65-652fc3a2e571)
