### ISSUE TITLE
Ensure things are being deleted from BH when deleted from Salesforce

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1880]
**THESE NEED TO BE DELATE-ABLE**

- [ ] Text updates
- [ ] Photos from the gallery
- [ ] Documents
- [ ] Community meeting object

Original ticket: Re-configure the Salesforce sync so that posted content can be removed and edited as well as created. Right now Files and Text Updates cannot be deleted or edited from the site.

**Comment by duffy-james** [comment]
@ebshrier it seems like we can actually do this through Drupal. There's a role that exists for a "Metrolist editor" that (I assume) was created for this purpose. I'm going to confirm with @padora-cob.

**Comment by ebshrier** [comment]
Thanks @duffy-james . Once confirmed, would like to know steps for users to follow to make these edits. thanks

**Comment by duffy-james** [comment]
Definitely agree, I just need to confirm what that role can and can't do before granting access. I should have an update by next week.

**Comment by duffy-james** [comment]
This ticket is related to our existing sync issues which we continue to work on. Closing this for now.
