### ISSUE TITLE
Collapse/Expand Stages in Timeline

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1886]
Create way to show/hide moments in the timeline within each stage on all device sizes.

**Comment by lizcormack-bos** [comment]
@AmyWipfler would love your input here - Sebastian felt strongly this would be needed if some projects end up with a lot of content, but I'm not sure where to place it in priority. Creating this ticket so I don't forget!

**Comment by AmyWipfler** [comment]
Currently remaining in the backlog due to lack of user testing on mobile to date and potential conflict with our goal to make information easy to find/transparent.

Could be good to reconsider should timeline length become an issue once the site has been live longer.

**Comment by duffy-james** [comment]
Closing issue for now.
