### ISSUE TITLE
Program Initiative Profile page type - hide "Who's Involved" component

### ISSUE THREAD

**Issue by rachelsater** [CityOfBoston/boston.gov-d8#1887]
The Program Initiative Profile page type always displays "Who's Involved" at the bottom of that page type.

Allow the user to hide that component (toggle on/off?)
 
![image](https://user-images.githubusercontent.com/72876352/108416041-36cc7b80-71fc-11eb-88ea-b293a7dd20a3.png)

**Comment by duffy-james** [comment]
Another thought is, instead of allowing the user to toggle on or off, if the field is empty in Drupal, the section just wouldn't appear on the page.

**Comment by padora-cob** [comment]
We need the same feature on Building housing. Should be able to get the feature in with that work.

**Comment by padora-cob** [comment]
FIle: docroot/modules/custom/bos_content/modules/node_program_initiative_profile/templates/node--program-initiative-profile.html.twig

LOC (184-195):
`    {% if content.field_contacts["#items"] %}
      <section class="b b--g b--fw">
        <div class="b-c">
          <div class="sh m-b500">
            <h2 data-short-title="Departments" class="sh-title">Who's Involved:</h2>
          </div>
          <div class="g">
            {{ content.field_contacts }}
          </div>
        </div>
      </section>
    {% endif %}`

**Comment by padora-cob** [comment]
To test this we will want take a look at a few Program pages with and without contacts. I think all pages have contacts listed currently, so may need to create or update a node to verify.

**Comment by rachelsater** [comment]
Here are some pages that have the "Who's Involved"

https://content.boston.gov/health-and-human-services/working-health-commission

https://content.boston.gov/health-and-human-services/healthy-homes-and-environment

https://content.boston.gov/health-and-human-services/healthy-eating-and-active-living

https://www.boston.gov/civic-engagement/boards-and-commissions

https://www.boston.gov/departments/veterans-services/veterans-services-penpals-and-buddies

thanks!

**Comment by duffy-james** [comment]
@padora-cob @rachelsater created a new program page and tested on ci. I tested without a department, with just one department, and with multiple departments in the field and all looked good to me. Think this one can move forward.
