### ISSUE TITLE
** Call out on Metrolist Listing Page for very-low income units missing

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1893]
We have lost the call-out for what the ** means on the listing page. I believe that this text (from the search page), was inside the drawers for each listing with that symbology on it.

![image](https://user-images.githubusercontent.com/55395593/108734751-c1afbd80-74fd-11eb-86f9-fa72bb183608.png)

![image](https://user-images.githubusercontent.com/55395593/108734789-cffdd980-74fd-11eb-96a8-1701fc10396a.png)

**Comment by reillyzlab** [comment]
Reflected in another ticket so closing this duplicate
