### ISSUE TITLE
ADA Accessible Units not rendering correctly on Metrolist listing pages.

### ISSUE THREAD

**Issue by AmyWipfler** [CityOfBoston/boston.gov-d8#1900]
Data is being mis-represented about ADA units. In this example, even though there are 4 units without ADA build-outs, it's showing as 4 with ADA build-outs.

Here's an example: https://www.boston.gov/metrolist/search/housing/200-old-colony?type=rent&assignment=lottery

In case it's not live by the time this is addressed, here's a recording of the issue: https://www.loom.com/share/65415503030749cb838c8a980bb317da

**Comment by duffy-james** [comment]
Closing issue for now.
