### ISSUE TITLE
Add event link to calendar events created using 'Add to Calendar"

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1910]
**Done Criteria**

- [x] When adding to any calendar via the 'Add to Calendar' button, the event detail page URL is included in the event description.
- [x] Precede the URL with the description copy "Details on how to join event:"

**Background**
Right now, when using "Add to Calendar" on Boston.gov, only the description copy from an event is added to the calendar. We need to add the URL of the event detail page so residents who Add to Calendar can find out how to join the event when the time comes.

See image below for details.

![add to calendar-edited](https://user-images.githubusercontent.com/72943225/109988312-6936a800-7cd5-11eb-82a0-6047d4ba30bd.png)

**Comment by reillyzlab** [comment]
This is on production so closing
