### ISSUE TITLE
Display file name in image gallery

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1924]
**Done Criteria:** The file name OR edited title of an image pulled from Salesforce shows up at the top of a photo in the image gallery.

Building Housing has an image gallery on project pages that users can click through. At the top, there's a line of text intended to be the title of the image (defaults to file name if not edited).

There's a bug and right now the name of the project just shows up on all the photos (see below - [link to example project](https://www.boston.gov/buildinghousing/1-nottingham-community-garden)).

![Screen Shot 2021-05-07 at 5 45 15 PM](https://user-images.githubusercontent.com/72943225/117511599-fe674e80-af5b-11eb-93e2-a1e5405fc98c.png)

**Comment by reillyzlab** [comment]
Think this could potentially a little more global but can @padora-cob or @lizcormack-bos add more content?

**Comment by lizcormack-bos** [comment]
@reillyzlab updated with more details! what do you think? if this is not going to be done globally, I will probably prioritize.

**Comment by duffy-james** [comment]
Closing issue for now.
