### ISSUE TITLE
Add other JPG file sub-types so all images show in gallery (not as documents)

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1926]
A few JPG uploads on [140 Clarendon St ](https://www.boston.gov/buildinghousing/140-clarendon-street)are showing up as documents in the timeline instead of appearing in the image gallery.

Either resolve the issue by expanding what we use to designate IMAGE vs. document, or share a few guidelines so we can tell DOs what exact file type to use (as a backup if we can't fix it in the code).

**Comment by rachelsater** [comment]
@padora-cob Is there a page I can test this one? I don't see JPGs on the 140 Claredon page and I don't see any on other pages either

**Comment by stephaniemar** [comment]
This one looks like it was done - Should we close?
