### ISSUE TITLE
Display icon legend on map overlay

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1947]
see comment for UI - this is in SPECs in Figma (top left).

- when a user taps "X" it should close the legend
- if a user refreshes the page, the legend should reappear

**Comment by lizcormack-bos** [comment]
Updating the Figma files (the map UI is top left in SPECS)

![Map_Collapsed List_1.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/1f0cb77d-2cc4-4a5b-886f-fa6612e13a7c)

**Comment by duffy-james** [comment]
Closing issue for now.
