### ISSUE TITLE
Make "RFP Issued" moment show up in Community Feedback stage if "Selecting a Developer" is not yet activated

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1970]
Right now, if a DND Development Officer doesn't move the project to the appropriate stage, RFPs show up under a "future" state Stage 2. Desired behavior = RFP shows up under currently active stage.

![IMG_8525.PNG](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/551d40ba-d3c7-46a2-ab5f-2a516fb128bd)

**Comment by lizcormack-bos** [comment]
I'm backlogging this since it's technically working if Development Officers use the recommended Saleforce workflow for their projects. Let's not prioritize this unless we validate that it's happening frequently (more than one or two instances at any time) on BH.

**Comment by rachelsater** [comment]
closing because we can't replicate this issue. Will open a new ticket if needed
