### ISSUE TITLE
Remove "We're funding this project..." line of text from development-only funding project template

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1971]
In user tests, people were a little confused by this line. In retrospect, I realize it's written from a pretty informed mindset (ie. you'd have to understand clearly that DND _does_ own the land in all other projects, and that this is therefore different). 

Users didn't harp on the difference in the timeline, so let's remove the additional line of text from the template.

![Screen Shot 2021-03-25 at 2.10.42 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/c902f75b-d017-48f7-9538-0f1537a09003)

**Comment by padora-cob** [comment]
This should be ready to test on CI.

**Comment by stephaniemar** [comment]
Looks like we can close this
