### ISSUE TITLE
"Hide contact form" no longer working on "Department profile" content type

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#1976]
The behavior of the "hide contact form" prevents the default from appearing when a user clicks a "mailto" link on the website. The location of the "hide contact form" is here on the "department profile" content type:

![image](https://user-images.githubusercontent.com/7929556/112544767-ccc06c80-8d8d-11eb-9e6b-d175d7da12a6.png)

It appears to have stopped working in a recent update. We just start receiving complaints that it stopped working this week. A few departments at the City use TrackIt for addressing requests through their emails, and the form messes up that process.

**Comment by mmcgowanBOS** [comment]
Worked on a fix with James over the last few days. Fix is now on Production and seems to be working as expected. Closing for now. @duffy-james , feel free to re-open if you catch anything else related to this.

Thanks.
