### ISSUE TITLE
Resolve # of photos overlay layout bug on mobile

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1986]
On mobile, the "2 photos" overlay on the image gallery floats over the header map. It seems to happen at any screen width under 1366px. See images in comment below!

**Comment by lizcormack-bos** [comment]
![Screen Shot 2021-03-29 at 3.49.44 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/944f7e6c-8752-47cf-8054-bd406eeb9d5a)

![Screen Shot 2021-03-29 at 3.42.17 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/1d1cd8ef-28c6-4350-ab66-26f86d60179d)

**Comment by rachelsater** [comment]
this is on Production so I'm closing the ticket
