### ISSUE TITLE
Remove 'page sections' bar on mobile BH homepage

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1987]
![IMG_8781.PNG](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/acefa7e6-de3a-4096-b41a-fb8427e7b73e)

**Comment by reillyzlab** [comment]
Being addressed as a larger issue so this shouldn't be worked on as a one off but leaving ticket open so that this is checked.
