### ISSUE TITLE
Remove additional padding from text updates

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#1990]
It looks like text updates have some sort of additional padding baked into the top of the component. I'm not sure what's causing it but ideally these have the same margins as other components (should reduce that space above it by ~50%).

![Screen Shot 2021-03-29 at 4.08.24 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/523c8340-ee94-4e3d-87be-3ac69faf5d6e)

![Screen Shot 2021-03-29 at 4.08.54 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/7b7f8594-2898-4527-b593-6283d4b49454)

**Comment by padora-cob** [comment]
This is done and fixed on PRD.

**Comment by lizcormack-bos** [comment]
Amazing, thank you!
