### ISSUE TITLE
Remove extra spacing throughout various drupal modules

### ISSUE THREAD

**Issue by rachelsater** [CityOfBoston/boston.gov-d8#1995]
There are a few different places/modules where the spacing isn't consistent.

**1.** In the WYSIWYG fields of Boston.gov for the "formatted text" component, you have options to add different photo stylings to images. The "full column wide (embedded)" options, located here:
![image](https://user-images.githubusercontent.com/72876352/113007199-00134a80-9144-11eb-8f21-3d9df66b2fe5.png)
creates a lot of white space on the left and right of the image:
![image](https://user-images.githubusercontent.com/72876352/113007428-351f9d00-9144-11eb-9d23-1e6fa0c353e3.png)
![image](https://user-images.githubusercontent.com/72876352/113007554-51233e80-9144-11eb-8489-8d4234ad1e10.png)

To be clear, in the "body" field of our content types, this option for some reason works. However, in the "formatted text" component, it does not fully embed in its container. I'm hoping we can remove this extra spacing and make sure the image is fully embedded and responsive in these text components.

**2**. Standardize the spacing for hero images across content types. EX: Spacing for hero images is tighter to the top of the page for events than for department profile pages. 

**3**. Decrease padding on all components so that there is less white space above and below each component.

**Comment by rachelsater** [comment]
Another example is all the padding around an image. One example is the image in the "About" section here https://content.boston.gov/cancer-prevention-and-control

**Comment by reillyzlab** [comment]
Related: https://github.com/CityOfBoston/boston.gov-d8/issues/2050

**Comment by rachelsater** [comment]
@padora-cob An example where an embedded images have a lot of padding around them is https://content.boston.gov/water-safety and https://content.boston.gov/bicycle-safety

**Comment by rachelsater** [comment]
work completed
