### ISSUE TITLE
Add additional trigger to ensure new webUpdate in SF generates BH web URL 

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#2006]
A DND Development Officer (Stephen) created a new web update for this project, but the Boston.gov Link field did not populate with the resulting BH project URL. Ensure that new webUpdate objects generate a URL in that field even if the project object isn't update.

https://www.boston.gov/buildinghousing/61-65-woodrow-ave

**Comment by lizcormack-bos** [comment]
@lizcormack-bos to see if we can validate - is any DO launching a new project soon? Once QA'd, ready to close.

**Comment by rachelsater** [comment]
@padora-cob how do I test this one? Should I go into SF?

**Comment by stephaniemar** [comment]
This looks done -- can we close

**Comment by duffy-james** [comment]
@davidrkupton has done some work on url validation issues. This hasn't been a recent problem.
