### ISSUE TITLE
"revision" links are broken

### ISSUE THREAD

**Issue by padora-cob** [CityOfBoston/boston.gov-d8#2009]
https://github.com/CityOfBoston/boston.gov-d8/blob/dde1352a9b832e5c7e54564994680f3f83c79692/docroot/modules/custom/bos_vocab/modules/vocab_contact/vocab_contact.module#L64

Just need to add a check that the '$node' variable is an object and not a string (something that the Revisions module does).

**Comment by rachelsater** [comment]
@padora-cob can this ticket be closed?
