### ISSUE TITLE
Longer email addresses in 'email' field of 'person profile' content type overlapping text

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2022]
If a person has a longer email in a "person profile" content type, that email will often bleed into the "body" of the "person profile". Here's an example where the email is 33 characters. It overlaps just slightly on desktop:
![image](https://user-images.githubusercontent.com/7929556/114551605-a32e8e80-9c31-11eb-9d3a-22adc275102f.png)

But looks worse at a tablet screen size:

![image](https://user-images.githubusercontent.com/7929556/114551632-aaee3300-9c31-11eb-8a9e-c10434d9e2a4.png)

It looks like we'd need to keep the email in the "contact" section, either by resizing the text at a certain breakpoint, or by causing a break in the email itself. Since this is a field in Drupal, content authors / editors can't adjust with html.

**Comment by padora-cob** [comment]
I think I found the problem in the BOS theme overrides CSS file (docroot/themes/custom/bos_theme/css/bos_theme_overrides.css:1319).

It looks like some code was added last year that causes all email links to not break and stay on one line:
```
a[href^="mailto:"] {
  white-space: nowrap;
}
```

This is what it looks like normally, without that change (Patterns default?): 
<img width="732" alt="image" src="https://user-images.githubusercontent.com/62249548/116265064-cd5f7080-a748-11eb-9010-9f095b65184f.png">

I think we have three options:
- [ ] Make the override in the BOS theme override more specific so it does not affect the sidebar email
- [ ] Make another override that targets just the emails in the sidebar / specific classed block
- [ ] Remove the override all together if it is not needed

**Comment by duffy-james** [comment]
@padora-cob do we have any idea why the override was added? I'm fine with making the email wrap, but wonder if it would be easier to make that the rule globally instead of being specific.

**Comment by duffy-james** [comment]
@subaha-cob suggested changing the link to "send an email" — I think that works if it's just for the "person profile" content type and could be a solution to this issue.

**Comment by duffy-james** [comment]
@subaha-cob addressed this issue; we're all set.
