### ISSUE TITLE
Fix Developer website links so they don't show 404 pages

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#2024]
**Done criteria:** Developer Website links open the Developer's website (in a new tab if possible).

Righ now, Developer Profile links are showing up at the end of a longer URL, so they're showing a 404 page. Example: https://www.boston.gov/buildinghousing/872-morton-street-homeownership

![Screen Shot 2021-04-15 at 12.06.39 PM.png](https://images.zenhubusercontent.com/5f89dbb0e9099f29a126af1d/542193cd-09ed-4071-a88e-47d084fca37f)

**Comment by rachelsater** [comment]
this is complete and on Production
