### ISSUE TITLE
RSS feed issue (news and event) - extra characters getting added to the links in the feed

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#2028]
In the RSS feed issue (news and event) - extra characters getting added to the links in the feed -- /news// is getting added into the links on both feeds:

https://www.boston.gov/rss/news

https://www.boston.gov/rss/events

Example 1 (news):
<item>
  <title>Make your spring cleaning zero waste</title>
  **<link>https://www.boston.gov/news//news/make-your-spring-cleaning-zero-waste</link>**
  <description>&lt;p&gt;&lt;span&gt;&lt;span&gt;&lt;span&gt;&lt;span&gt;&lt;span&gt;&lt;span&gt;&lt;span&gt;The past year, a lot of Boston residents have spent more time at home than usual to stop the spread of Covid-19. Now that warmer weather is upon us, many Boston residents will be spring cleaning. It’s important to keep in mind the right ways to discard the different materials in your home.&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;&lt;span&gt;&lt;span&gt;&lt;span&gt;&lt;span&gt;&lt;span&gt;&lt;span&gt;&lt;span&gt;The City of Boston has resources for Boston residents to reduce, repair, and reuse the materials in our lives. The Zero Waste Boston initiative strives to take action through planning, policy, and community engagement. &lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;
&lt;p&gt;Whether you are spring cleaning your entire home or just your bedroom, living room, kitchen, office, outdoor space, bathroom, and the refrigerator, check out our resources below to learn best practices on discarding your unwanted items.&lt;/p&gt;

&lt;p&gt;&lt;b&gt;Contact Department:&lt;/b&gt; &lt;a href="https://www.boston.gov/contact/environment" hreflang="en"&gt;Environment&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Publish Date:&lt;/b&gt; &lt;time datetime="22Z"&gt;Tue, 04/20/2021 - 3:15pm&lt;/time&gt;&lt;/p&gt;
</description>
  <pubDate><time datetime="22Z">2021-04-20T15:15:22-0400</time>

</pubDate>
    <dc:creator/>
    <guid isPermaLink="true">https://www.boston.gov/14918186</guid>
    </item>

Example 2 (events):
<item>
  <title>Get Hired: Construction Career Fair</title>
  **<link>https://www.boston.gov/news//calendar/get-hired-construction-career-fair</link>**
  <description>&lt;p&gt;&lt;b&gt;Event Date:&lt;/b&gt;   &lt;/p&gt;&lt;div class="date-recur-date"&gt;&lt;time datetime="00Z"&gt;Thu, 04/22/2021 - 4:00pm&lt;/time&gt;
-&lt;time datetime="00Z"&gt;Thu, 04/22/2021 - 6:00pm&lt;/time&gt;&lt;/div&gt;

&lt;p&gt;&lt;b&gt;Address:&lt;/b&gt; &lt;/p&gt;&lt;p class="address" translate="no"&gt;&lt;span class="address-line1"&gt;Virtual&lt;/span&gt;&lt;br /&gt;&lt;span class="locality"&gt;Boston&lt;/span&gt;,&lt;br /&gt;&lt;span class="country"&gt;United States&lt;/span&gt;&lt;/p&gt;

&lt;p&gt;The virtual career fair will be the second in a series of virtual events and will focus on employment opportunities for non-union laborers.&lt;/p&gt;
 
&lt;p&gt;We are specifically seeking Boston residents, women, and people of color to fill positions presently available or becoming available with construction projects in the City of Boston. Candidates that are interested in employment in the construction industry at any experience level are encouraged to attend.&lt;/p&gt;

&lt;p&gt;&lt;b&gt;Contact Department:&lt;/b&gt; &lt;a href="https://www.boston.gov/contact/economic-development" hreflang="en"&gt;Economic Development&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;b&gt;Publish Date:&lt;/b&gt; &lt;time datetime="21Z"&gt;Tue, 04/20/2021 - 1:55pm&lt;/time&gt;&lt;/p&gt;
</description>
  <pubDate><time datetime="21Z">2021-04-20T13:55:21-0400</time>

</pubDate>
    <dc:creator><a href="/contact/economic-development" hreflang="en">Economic Development</a></dc:creator>
    <guid isPermaLink="true">https://www.boston.gov/14991561</guid>
    </item>

**Comment by padora-cob** [comment]
Also an issue with the pubDate on the items. I updated to format to match the RFC 822 spec for dates (what is used by RSS2). `D, d M Y G:i:s T`

**Comment by rachelsater** [comment]
work completed
