### ISSUE TITLE
Boston.gov/news listing page adjustments - so all items have teaser text

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#2046]
On boston.gov/news, if intro text has not been set on a post then there is no teaser text that appears for the news items. 

Intro text should be the first option for the teaser text.

We should adjust this page so that if intro text is not set on a post, then the beginning of the body copy becomes the teaser text. The teaser text should be the same character limit as the other items with ellipses. 

<img width="1146" alt="Screen Shot 2021-04-28 at 11 39 44 AM" src="https://user-images.githubusercontent.com/20731897/116446145-aa09f380-a824-11eb-90bb-b750e84ab6f2.png">

**Comment by duffy-james** [comment]
@subaha-cob took care of this; closing ticket
