### ISSUE TITLE
Publish VPAT to Boston.gov

### ISSUE THREAD

**Issue by mmcgowanBOS** [CityOfBoston/boston.gov-d8#2048]

**Comment by mmcgowanBOS** [comment]
Reilly has suggested we get the VPAT published to Boston.gov by end of May. Let's mark the day May 28th (Friday). The following is a list of things to complete by then.

1. Finish up outstanding items in Iterators project board (Stella and David W / Iterators)
2. Clean up of Google Doc version of the blog post (Reilly and James)
3. Take Google Doc and transfer to Drupal article / post complete with VPAT in table structure (James and Matt)

**Comment by duffy-james** [comment]
I took a [final pass through the blog post](https://docs.google.com/document/d/1YwB7WK5YLIxupHNtgQlMCKYJ43yeFqhbYvSlLYtkwwY/edit) and updated the notes from Reilly about social media accessibility (as an addition at the end of the post). This feels good to publish at this point once we get the "final" version of the report we want to share.

**Comment by subaha-cob** [comment]
[City of Boston, VPAT Accessibility Report, 2020 11, DRAFT v1.docx](https://github.com/CityOfBoston/boston.gov-d8/files/6549435/City.of.Boston.VPAT.Accessibility.Report.2020.11.DRAFT.v1.docx)

**Comment by duffy-james** [comment]
This was published: https://www.boston.gov/news/building-bostongov-accessible-all
