### ISSUE TITLE
Update Schema / Metatag info for Department Profile Pages

### ISSUE THREAD

**Issue by mmcgowanBOS** [CityOfBoston/boston.gov-d8#2049]
Higher Level goal is to give content editors the ability to update office hours for their department profile / page on Boston.gov. This in turn will publish the hours as Schema and Metadata in the source code as well.  A list of features are below...

1. Enable "office Hours" module that will be available in the "Contact Information" section of Department Profile content type. 

2. Content editor will have the choice of displaying the hours in the sidebar and in schema / metadata...or just one of the 2.

3. If Department profile "office hours" are left blank, then default hours will published as Schema markup only visible in the source code for search engines.

**Comment by rachelsater** [comment]
@padora-cob I see the ability to add hours on this page so it looks like task 1 is complete. I'm not seeing items #2 and #3. Is that correct?
