### ISSUE TITLE
Spacing between words & embedded images

### ISSUE THREAD

**Issue by rachelsater** [CityOfBoston/boston.gov-d8#2050]
There is a large space between words and embedded images.

Here is an example:

boston.gov/buckle-boston

![image](https://user-images.githubusercontent.com/72876352/116929127-fb065700-ac2b-11eb-8360-e78956736e4f.png)

**Comment by duffy-james** [comment]
Tested on ci, embedded images changes look great for the WYSIWYG field and ready to move forward. As part of this work, @padora-cob is going to looking into the slight spacing issue when adding a 1/2, 1/3, or thumbnail image and lining it up on the left or right of text. You can see in the screenshot that it's not quite flush:

![image](https://user-images.githubusercontent.com/7929556/121225714-ca7f9180-c857-11eb-9fb3-c2efbf9fdd59.png)

**Comment by duffy-james** [comment]
@padora-cob updates to lining up 1/2, 1/3, or thumbnail image with text on the left and right side look great. We can move forward with this one.
