### ISSUE TITLE
Updates to procurement advertisement content type

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#2052]
After speaking with Erik DeMarco, we should implement the following items to the procurement advertisement content type: 

- [x] Project Name: If there is a way to prevent pre-populating the field that would be great. If there isn't a way for us to block this on Drupal, then Erik will try to set up a block on his browser.
- [x] "Not Awarded" status doesn't seem to be working. Please review and ensure this is showing up on the front end at the top of the right sidebar when the 'not awarded' button is selected in the back end of the website. It should match what appears on an item that is awarded, such as: https://www.boston.gov/bid-listings/ev00007826. Erik was trying to update the Ventrac 4500 one and it wouldn't update with 'not awarded' status.
- [x] These fields are currently required, but should be changed to not required: 
  - [x] Awarded by
  - [x] UNSPSC
  - [x] Contact Email
  - [x] Contact Phone
- [x] Award Date doesn't need a time and it is making more work for Erik. Can we remove time and/or auto-populate with something so that Erik doesn't have to enter every time? Preference would be to remove but pre-populate is a fine back up.
- [x] Can we create an internal dashboard for Erik for him to easily know what is/isn't entered so he can go back and enter missing details. Fields desired are project name, event number, paper versus electronic, award status filled in (y/n), and department? Let's move forward with this unless it creates a large complexity. If it does create complexity, then let's discuss as a team prior to implementing anything.
  - [x] Change the title of the dashboard
- [x] When a user is on boston.gov/bids-listings and they search for a procurement item sometimes they get a 'no results found' page because that procurement has moved to the archive page. Can we create an experience in which the user could find the procurement item regardless of whether it's on the active or archived page?
  - [x] Copy for the no-results found in active search but results were found in archived search
  - [x] General layout and copy style

**Comment by rachelsater** [comment]
@padora-cob please use this copy "There are no active bids or RFPS with that search term. Please search again to find open bids and/or RFPs."

**Comment by reillyzlab** [comment]
Think tickets got conflated -- @padora-cob copy for this can be found here: https://github.com/CityOfBoston/boston.gov-d8/issues/2053

**Comment by duffy-james** [comment]
@padora-cob text looks great. Can we shave down on this extra spacing and maybe add a <hr>  (if that makes sense to you)?

![image](https://user-images.githubusercontent.com/7929556/119732577-5cde6900-be46-11eb-971c-c02cace968e1.png)

Also, the new titles you added look huge on mobile:

![image](https://user-images.githubusercontent.com/7929556/119732631-6c5db200-be46-11eb-913a-dce1d4a06c3b.png)

**Comment by reillyzlab** [comment]
These all pass testing and should go to production. 

We will push these live Tuesday.

Reilly will let Eric/Purchasing now.

**Comment by reillyzlab** [comment]
A note so folks are aware: Erik/whomever is entering procurement ads onto boston.gov are sent them sometime on Wednesday. Then, they have Wed, Thu, and Fri to work on them before the following Monday when they go live.
