### ISSUE TITLE
Build a web form in drupal

### ISSUE THREAD

**Issue by rachelsater** [CityOfBoston/boston.gov-d8#2059]
Please make a new drupal webform similar to this BPHC page https://bphc.org/whatwedo/childrens-health/boston-healthy-start-initiative/Pages/CAN-Signup-Form.aspx. This particular form goes to one email.

**Comment by padora-cob** [comment]
Ready to review on CI: https://d8-ci.boston.gov/community-action-network

Will want to make some adjustments to style still (close button and modal header)

**Comment by rachelsater** [comment]
@padora-cob  I'm testing and a few things need to change please

1. Remove the seal at the top of the page and the frozen row
2.  Something is hiding behind the frozen row but I can't tell what it is (see the screenshot)
![image](https://user-images.githubusercontent.com/72876352/118166927-17587f80-b3f4-11eb-9ee7-ad5d39d86590.png)
3. the Submit button is sitting on top of the footer. Can there be some space between the two?
4. Is it possible to remove some of the default settings? For example, could we remove the default yes checkbox for "Degree Visible" and "Middle Name" on the name element?
