### ISSUE TITLE
Filters not showing for boston.gov/news on mobile/small tablets

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#2064]
Filters are not showing up on boston.gov/news on mobile/small tablets -- they disappear. 

This should be fixed. 

See boston.gov/bid-listings for comp.

**Comment by padora-cob** [comment]
Ready for review on CI: https://d8-ci.boston.gov/news

**Comment by reillyzlab** [comment]
Approved - can go to production.
