### ISSUE TITLE
Apostrophe in the Events > Location field is causing an error code

### ISSUE THREAD

**Issue by rachelsater** [CityOfBoston/boston.gov-d8#2075]
On the one of the parks pages, we found a bug https://content.boston.gov/calendar/parks-fitness-salsa-metamovements
The location in the sidebar should say "O'Day Playground" but it keeps throwing an error code. The apostrophe is causing issues and we can't change it in the source code.

**Comment by padora-cob** [comment]
I found a quick/hacky fix, add a space after the apostrophe.
