### ISSUE TITLE
Figure out strategy for posts - how long and what they stay on the site

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#2076]
Updated on 6/2/21 by Reilly:

Why it matters that we do this. One reason: Old, outdated, irrelevant content/posts can have a negative effect on SEO.

Findings: Archives does do a weekly harvest of boston.gov, so some of this content may already be archived, but Archives can be a deeper harvest of boston.gov/news

Next steps:

- [ ] More research needed on what should be removed and how (i.e. the storytelling and/or misc. fun versus the one-time announceables). Few examples that are more storytelling: Items on boston.gov/digital and parks coloring book/zoom backgrounds
       - [ ] Is it everything within a year or are there exceptions? 
       - [ ] Should there be an exercise to do a manual content (at least posts) audit completed in partnership with departments on a yearly basis and posts are manually archived based on criteria (i.e. is it purely an announceable or is it more of the fun, longer term sustainable content)? On most platforms (unsure about Drupal) you can set certain content types up for a 'renewal'/'review' to make sure the content is reviewed and marked as still relevant.
       - [ ] Check Google Analytics, particularly page views and incoming/referral links
       - [ ] Figure out what amount of posts (in any given year) are true storytelling versus press releases (are there departments that primarily post only press releases?)
       - [ ] Consider updating 'older, but still relevant' posts so they keep current. I.e. build on old posts about accessibility with timely updates.

Regardless of what is chosen to delete there should be a 

_Then:_

Once all final research is complete and open questions are answered then:
- [ ] Ensure digital, archives, and press are 100% on the same page about what will happen
- [ ] Communicate the change to departments and let them know how they can still find/use archived posts if they want to copy the content from a previous post
- [ ] Archives do a deep harvest/crawl of boston.gov/news 
- [ ] Implement whatever path forward is taken. There will need to be a one-time run of this process given this has not been done on boston.gov since launch + a yearly repeat of the process at the beginning of each calendar year.
       - [ ] Ensure that all archived posts have a redirect to the authoring department, department page. If this is too difficult, then at least a redirect to boston.gov/news
- [ ] If constituents contact the City saying they can't find a post, then either let them know they can search the Archives or contact the authoring department and submit a request to Google to remove the old post from search results.

--

Original ticket:
Since the website launch using Drupal, posts (i.e. often press releases posted online) have built up without any archiving, etc so there are now a lot of posts taking up database storage as well as causing some pain points for content editors/departments. 

Some press releases have much more historic relevance/context than others.

Example of one that has created complication for department/public (i.e. you'll see BTD added extra info to show it was from 2016): https://www.boston.gov/news/june-1-2016-boston-expands-bike-share-east-boston

There are a few different use cases to why we'd want to keep these accessible:
1. Historical context/archival reasons
2. Support content editors process and time - For announceables that happen every years (few examples: mayoral speeches, seasonal parks openings/announcements) content editors simply copy the content from the year prior, create a new post and change the dates/other relevant info that's changed. Content editors could do this in Google Docs, but that does include all the images, metadata, etc that they might have already put into the page. Users sometimes get confused by similar content to announceables but with different publish dates, because the content is so similar (or nearly an exact replica).

A strategy should be figured out to revisit/archive, etc. posts from time-to-time.

Archives can and does archive content when asked to do so. Digital should meet with Marta Crilly and discuss the best process for this.

**Comment by stephaniemar** [comment]
@duffy-james This seems more like a policy suggestion on how to move forward with keeping boston.gov up to date
