### ISSUE TITLE
Remove Developer Profile from Inactive Parcels

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#2077]
The developer profile on an inactive plot of land will always be "To be Decided." Let's remove that component from all  projects that are using the inactive project template!

Done = Developer profile does not appear on inactive parcels (no changes to other project types).

![Screen Shot 2021-05-11 at 4 59 53 PM](https://user-images.githubusercontent.com/72943225/117884178-4f3bb780-b27a-11eb-8695-11081cffbb61.png)

**Comment by padora-cob** [comment]
Ready to test on CI.
