### ISSUE TITLE
Make Disposition Projects in an "Awarded" stage show up as in "City Planning" stage on BH

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#2078]
Our existing logic didn't account for a Disposition Project being in an "Awarded" stage (we probably thought only NHD Development projects could be in that stage). See my comment in [the logic doc here](https://docs.google.com/document/d/1MWRYqvD4i4tC6mjlo1SGhECa5Z8YOYE7kgR8FXe9CBY/edit?usp=sharing).

This project is a Disposition Project + Awarded stage, and it makes the timeline very confused: https://boston.gov/buildinghousing/150-river-street

Here's that project's SF record: https://boston-dnd.my.salesforce.com/a041A00000YqHjs

**Done = Disposition AND Development projects in an awarded stage appear as in 'City Planning' stage, and following stages appears as "future stages."**

**Comment by padora-cob** [comment]
Ready to test on CI: https://d8-ci.boston.gov/buildinghousing/150-river-street
vs.
https://www.boston.gov/buildinghousing/150-river-street

**Comment by rachelsater** [comment]
@padora-cob Sorry I don't know what I'm looking for when I'm testing
