### ISSUE TITLE
Image resizing issues

### ISSUE THREAD

**Issue by rachelsater** [CityOfBoston/boston.gov-d8#2080]
The image resizing functionality needs some custom JS to address the positioning of the image

**Comment by padora-cob** [comment]
The issue was some JS that would resize all embedded WYSIWYG images styles. Added a condition where if the Media tag is wrapped by an element with a class of ".no-resize" it will not trigger the JS resizing. 

Can be tested at: https://d8-ci.boston.gov/bphc-permits
