### ISSUE TITLE
If Housing 'Project Type' is blank, leave sub-type blank in sidebar

### ISSUE THREAD

**Issue by lizcormack-bos** [CityOfBoston/boston.gov-d8#2089]
"Housing - NHI" is showing up as the sub-type in the project type component for [61-65 Woodrow Ave](https://www.boston.gov/buildinghousing/61-65-woodrow-ave) since the "Project Type" field is blank on the project. 

The desired behavior is that if "Project Type" is blank, the sub-type is blank.

Done = for Housing projects without a Project Type filled in, use a simplified version of the project type component (see lower of the two designs below).

**Details on how the type component works:**

- We look to the Disposition Type first. 
- IF Dispo Type is housing, then we look at the Project Type for further details.
- Project Types are displayed as a public-friendly sub-type (ie. grouped into public friendly categories).

![Screen Shot 2021-05-18 at 3 23 58 PM](https://user-images.githubusercontent.com/72943225/118711027-11e0a800-b7ed-11eb-8f85-12e2f5ee68b2.png)

**Comment by padora-cob** [comment]
This is ready for review on CI: https://d8-ci.boston.gov/buildinghousing/61-65-woodrow-ave
vs.
https://www.boston.gov/buildinghousing/61-65-woodrow-ave
