### ISSUE TITLE
Update department page based on UX research and design (product decisions still needed)

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#2101]
Implement updates to department page based on:

https://drive.google.com/drive/folders/1Ebafwf5IqBFo4-UfLcZ9cxSxP05TsXEw?usp=sharing

and 

https://drive.google.com/file/d/1Rv6vLeEo6tTk54VeEgfm4EBpSLyuxHNa/view?usp=sharing

**Comment by rachelsater** [comment]
closing because it's not clear. thanks!
