### ISSUE TITLE
Mobile header styles are center aligned on department page on mobile (should be left aligned)

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#2102]
Mobile header styles are center aligned on department page on mobile, but should be left aligned. 

Example: ![IMG_9A0D0C187DF3-1](https://user-images.githubusercontent.com/20731897/119712165-2d633880-be15-11eb-8020-2b85c928830b.jpeg)

**Comment by rachelsater** [comment]
@sebastianebarb what are your thoughts about this change?

**Comment by sebastianebarb** [comment]
Yes, they should be left-aligned!

**Comment by subaha-cob** [comment]
Currently on: https://d8-uat.boston.gov/departments/innovation-and-technology

**Comment by rachelsater** [comment]
@subaha-cob looks good to me! @duffy-james do you agree?

**Comment by duffy-james** [comment]
@subaha-cob looks like this one was already pushed to production, closing out now.

**Comment by subaha-cob** [comment]
Yes this was pushed already.
