### ISSUE TITLE
These are notes from a historical convo/grooming on boston.gov navigation/site adjustments. Needs implementation

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#2107]
These are notes from a historical convo/grooming on boston.gov navigation/site adjustments. 

Reilly has put all notes here but they should be sussed out and broken into actionable tickets. Some may need more discussion/planning.

Leaving for @rachelsater to do this:

1.    - Convert the ‘short titles’ to a right sidebar (in page nav)
        - To do: Review all content types and where it does/doesn’t apply
        - Open question: What happens to the other sidebar items?
        - Open question: What happens with pages that don’t have sidebar? > James believes this is only ‘not available’ on landing content type. Building housing and metrolist don’t use the sidebar
        - Not on events page/content type?
        - Not on person profiles
        - To do: Review whether short titles are and work on all content types
        - Have it be sticky
        - In tandem: Do we move contact info to the bottom and then have this navigation live there?
            - To do: Review which departments ‘need’ contact info at the top (i.e. Returning Citizens, Age Strong, MOIA)
                - Think through whether it just drops down on tablet/mobile
            - Consideration: Rachel has been promoting the contact info at the top of BPHC pages as part of migration
            
2.    - For later: Do we take the recommendation of the menu being open on desktop/at a certain break point?

3.    - For later: Does the open menu and the in page nav work together? (Can’t remember whether that was part of the test, so may need to look through report again for this info.)
 
4.    - Open question: Do we bring back the accessibility toolbar/menu?
    - Go forth with the recommendation for top versus left navigation: Recommendation Make the top nav tasks only. Make the left navigation topics. 
        - Potentially run A/B test? For this and menu open always
        
5.    - For later grooming/lower priority: Do we implement the department page changes from other research/recs from Craft and general assembly? As well as creating an alphabetical view?

6.    - Open question: Do we allow the entire site to show up when people have the left menu open (can’t currently see the entire site)?

**Comment by stephaniemar** [comment]
@rachelsater What do you want to do with this? Keep it open for now?

**Comment by rachelsater** [comment]
nope! let's close it.
