### ISSUE TITLE
Bid event - UX needed for new component / template review

### ISSUE THREAD

**Issue by jfalvey** [CityOfBoston/boston.gov-d8#2129]
See: https://www.boston.gov/bid-listings/ev00009219 and try finding the way to view the actual full document. 

Background: Full bid documents are not added to these pages or stored in Drupal, they are primarily housed in the City's Supplier Portal (some bid events are still paper based such as for construction projects and those are not*) 

Because some are paper based, we can't put an omnipresent component that links you to the supplier portal page, but needs to be something producers can check or uncheck. 

It can be templated though, as the link to the supplier portal then requires login, so all we can do is more clearly get them to that homepage and set expectations that it requires an account to view. 

Questions can be directed to Erik DeMarco / James Duffy

**Comment by padora-cob** [comment]
@rachelsater, we are going to need a little more info / direction for this one. Maybe talk with @duffy-james about the functionality and @sebastianebarb about how it will look. I don't think it will take too long :)

**Comment by rachelsater** [comment]
@padora-cob sounds good! @duffy-james Should we chat about this one?

**Comment by duffy-james** [comment]
@rachelsater sorry for not responding sooner! Happy to chat about moving this one forward. I should have more time now to work on this.

**Comment by rachelsater** [comment]
@duffy-james no problem! let me know when you are free to chat

**Comment by duffy-james** [comment]
@rachelsater just set up a meeting with you, Jeanethe, and I — including Alex as optional, but he may not need to be there.

**Comment by duffy-james** [comment]
@padora-cob let's try this for text for now:

Title: Apply through Supplier Portal

Body: To respond to this event, please apply through the City of Boston Supplier Portal.

Button: Go to Supplier Portal

Pretty positive we may need to adjust this with Erik, but it's a start.
