### ISSUE TITLE
"Canceled" meetings causing bug in event component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2135]
There's extra text appearing above "canceled" events and public notices in the front-end of the events component on Boston.gov. You can see the error below:

![image](https://user-images.githubusercontent.com/7929556/125325350-d2c36480-e30e-11eb-83cd-9557fb40d172.png)

We need to remove the extra text above the title. [Here's a link to a page on Boston.gov](https://www.boston.gov/departments/tourism-sports-and-entertainment) where you can currently see the issue.

**Comment by mmcgowanBOS** [comment]
Hi Everyone, 
I'm adding @subaha-cob as I believe she worked on this last. Stella, are you able to take a look at this when you have a chance?

Thanks.

**Comment by subaha-cob** [comment]
Sure, I will take a look at this later today or first thing in the morning.

**Comment by subaha-cob** [comment]
I added Alex back in because it was a simple fix that he added to his local already. He also has some items ready to go this week that will be included in this week's deploy.
