### ISSUE TITLE
Change red #D22D23 on the dark blue background across all components/the site

### ISSUE THREAD

**Issue by rachelsater** [CityOfBoston/boston.gov-d8#2148]
we should check that the red #D22D23 is accessible on the dark blue background, when I check it it fails. The lighter red #FB4D42 passes though!

Example: 
![Screenshot 2021-05-11 150342](https://user-images.githubusercontent.com/22770827/117885244-9e361c80-b27b-11eb-9d74-a91984a39c6b.png)

_Originally posted by @carolinestj in https://github.com/CityOfBoston/boston.gov-d8/issues/322#issuecomment-839171922_

**Comment by carolinestj** [comment]
@rachelsater I believe when it's on the dark blue we should use the lighter red version and when it's on a white background we should use the dark red version!

**Comment by rachelsater** [comment]
@carolinestj totally agree! This ticket will change the darker red to the lighter red across the whole site.

**Comment by carolinestj** [comment]
@rachelsater perfect sounds great!

**Comment by padora-cob** [comment]
@subaha-cob, This was that ticket that I was talking about yesterday, I think it just needs a variable updated in Patterns.

**Comment by subaha-cob** [comment]
Currently on UAT:
https://d8-uat.boston.gov/departments/digital-team/test-page

**Comment by rachelsater** [comment]
@subaha-cob looks good! thank you!

**Comment by duffy-james** [comment]
@subaha-cob was this taken care of? Can I close the ticket?

**Comment by subaha-cob** [comment]
@duffy-james this was also addressed when we removed legacy CSS.
