### ISSUE TITLE
Content order on Events detail pages

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/boston.gov-d8#2149]
Change the content order on mobile to be: breadcrumbs, intro text, sidebar, then body. See image below -

![Screen Shot 2021-07-26 at 4 03 38 PM](https://user-images.githubusercontent.com/57374913/127051748-97337dd4-6a36-438e-a5e3-8e42d1402015.png)

**Comment by duffy-james** [comment]
@subaha-cob addressed this issue; closing ticket
