### ISSUE TITLE
News page - limit number of rows/characters in the headline

### ISSUE THREAD

**Issue by rachelsater** [CityOfBoston/boston.gov-d8#2165]
We want to limit the headline characters so it doesn't break outside the box. This occurs on the boston.gov/news page

Here's an example,
![image](https://user-images.githubusercontent.com/72876352/129924758-76dc45e6-0ed0-4ab6-898f-7f6c8bca8476.png)

The max character limit should be 100 characters including spaces.

**Comment by padora-cob** [comment]
Do we want to limit it on the editor's side of things or just limit the output and add an ellipsis?

**Comment by rachelsater** [comment]
@padora-cob I forgot to add that so that's for the reminder! Yes, please limit the output and add an ellipsis

**Comment by padora-cob** [comment]
Sounds good, thanks!

**Comment by padora-cob** [comment]
Was able to solve this on with a small adjustment to the twig template using the twig extension function truncate() (https://github.com/twigphp/Twig-extensions/blob/master/doc/text.rst#truncating-text)

**Comment by padora-cob** [comment]
Ready to test on CI: https://d8-ci.boston.gov/news

![image](https://user-images.githubusercontent.com/62249548/129942843-0ea2f9cb-2580-478d-9a2d-c2b09fd28d39.png)

**Comment by duffy-james** [comment]
@padora-cob looks good! would this also add a character limit to the "new and announcements" component, or is this just for the listing page?

**Comment by padora-cob** [comment]
@duffy-james, just for the listing page at the moment but would be easy to add the same treatment for any other places on the site if we want to add those to this ticket. Just let me know what ones and/or add an example and we can knock a bunch out at once!

**Comment by duffy-james** [comment]
@padora-cob great, these would be those other locations.

"News and Announcements" components:

![image](https://user-images.githubusercontent.com/7929556/129948035-084c1e43-336c-43ae-8112-88f750bb9ceb.png)

"Events and Notices" components:

![image](https://user-images.githubusercontent.com/7929556/129948088-2488657f-7d84-4580-a0be-2a1a46eb798b.png)

You can find examples of both on the homepage. I can find other locations if that's helpful.

**Comment by duffy-james** [comment]
@padora-cob this is definitely working on boston.gov/news

In the "news and announcements" component, the "contact" title is still getting pushed outside of the container:

![image](https://user-images.githubusercontent.com/7929556/130262793-1af23e16-3f7b-4b3a-8309-46f8953ad294.png)

Can you adjust that to keep it in the container?

**Comment by rachelsater** [comment]
@padora-cob can I close this ticket?

**Comment by padora-cob** [comment]
Not yet, It is ready for PROD but that adjustment that James was talking about above has been taken care of for the most part but another change will have to be made with the legacy CSS changes to make that "Mayor's Office" not jump out of the block/container. 

I would say this one is ready also though.

**Comment by rachelsater** [comment]
agreed
