### ISSUE TITLE
Styling issue with title of "mini grid" component on "how-to" content type

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2167]
The title is being squeezed a bit and overlapping the box for the links in the "mini grid" component:

![image](https://user-images.githubusercontent.com/7929556/130126907-8fd73751-cc20-42f7-9174-f94070e925c4.png)

[Here's an example for testing](https://www.boston.gov/departments/parking-clerk/how-pay-parking-ticket).

**Comment by duffy-james** [comment]
The "newsletter" component appears to be going wide outside of the new layout. [Here's an example](https://www.boston.gov/departments/archaeology/how-get-involved-city-archaeology):

![image](https://user-images.githubusercontent.com/7929556/130127841-3e4aa4bb-4f90-4f53-95b3-d59f0daf8796.png)

**Comment by subaha-cob** [comment]
Currently on UAT:
https://d8-uat.boston.gov/departments/digital-team/test-page

**Comment by rachelsater** [comment]
@duffy-james I think it's still wide but what are your thoughts?

**Comment by duffy-james** [comment]
This is fixed. @subaha-cob addressed this bug.
