### ISSUE TITLE
Review content editor theming

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#219]
Ensure that editor theming is displaying accurate and we've reviewed in particular the moderation state views/options.

Ensure that the items on the right sidebar and bottom of the page are combined.

Get rid of: comment setting, comment settings, rabbit hole settings, promotion options

Ensure that there is a way to tell who was the last person to edit the page was.

For content editors only show revision log information
Require revision log message, but don't pre-populate with any information so that content editors are forced to put information about what they changed.

Move: publishing workflow info into right block

Remove 'preview' functionality

**Comment by jimafisk** [comment]
Just flagging a post because I know we talked about combining the moderation state and save button. Looks like the Drupal core folks already had a lengthy discussion about separating the "save" and "publish" buttons: https://www.drupal.org/project/drupal/issues/2068063

**Comment by reillyzlab** [comment]
Closing per confirmation with David
