### ISSUE TITLE
Title stretching over "show" and "hide" in drawers on "how-to" pages on mobile

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2191]
This is a mobile-only issue. The "tab title" field is bleeding over into the "show" and "hide" option in the drawers in the ["get married in Boston" page](https://www.boston.gov/departments/registry/how-get-married-boston):

![how-to-mobile](https://user-images.githubusercontent.com/7929556/135126166-97f7e4f3-9039-4e31-8604-2e2d906c39ad.png)

It seems like we just need to resize the text. I tested on an iPhone 12 in both Chrome and Safari.

**Comment by padora-cob** [comment]
Do we know what we would like the mobile to look like? Maybe a question for @carolinestj or @sebastianebarb?

**Comment by duffy-james** [comment]
Definitely defer to them, but I as thinking bottom rand-hand side of the button?

I think we'd need to set a character limit on that going forward as well, because it definitely won't look right breaking to a second line.

**Comment by subaha-cob** [comment]
@duffy-james I fixed the issues with the tabs tittle, but given the conversation above, this may require further discussion. I feel strongly we should look at "How to Guides" in general because for a module we just built, it shouldn't have this much problems.

**Comment by duffy-james** [comment]
@subaha-cob addressed this; the work is accounted for in Jira. Closing the ticket now.
