### ISSUE TITLE
Remove extra <hr> rule in sidebar of "department profile" content type

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2192]
In the sidebar of our department pages, under the hours in the sidebar, there's an extra hr rule:

![image](https://user-images.githubusercontent.com/7929556/135255476-73c6d354-9374-416e-8d6c-761eacbbc949.png)

I believe we flagged this before, but I can't find a ticket. We should have one of those extra hr rules removed.

I'm pretty sure because the "Contact" information is separate in the department pages, that's what's causing the extra rule:

![image](https://user-images.githubusercontent.com/7929556/135255902-1444c757-00a6-44df-8704-6a4da1b217bd.png)

Every other content type has that contact information automatically pulled onto the page or created in the sidebar component.

**Comment by duffy-james** [comment]
@subaha-cob did you address this bug already? I'm not seeing it one the site.

**Comment by subaha-cob** [comment]
@duffy-james This was addressed earlier this year when the sidebar was updated.
