### ISSUE TITLE
"Transactions grid" component display broken on "how-to" pages

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2218]
The display doesn't line up properly in the "transactions grid" component on our how-to pages:

![image](https://user-images.githubusercontent.com/7929556/139088943-06f093c1-e37b-4675-994d-d6c4db38e22b.png)

[Here's a link on staging](https://d8-stg.boston.gov/how-respond-eviction) where you can see the display issues. We probably need to test out the different components on our how-to pages at this point to rule out an other bugs. I'm going to set up a separate ticket for that.

**Comment by rachelsater** [comment]
@padora-cob It looks like there are a few issues with this one.

1. the Eviction Resources box isn't as wide as the other page modules
![image](https://user-images.githubusercontent.com/72876352/142063059-fd5b0efe-2764-4414-bf5e-415681557322.png)

2. It looks like the title is right up against the grey box. There should be some padding between the box and the title.
![image](https://user-images.githubusercontent.com/72876352/142063134-fa24cb09-9bcb-4849-82b6-77d5484bbd2a.png)

3. The left margin is cutting off for this module
![image](https://user-images.githubusercontent.com/72876352/142063269-117f583a-bbdc-410c-963b-a06b06cea533.png)

**Comment by padora-cob** [comment]
@rachelsater, could please you make a new ticket for those other issues? Thanks!

**Comment by subaha-cob** [comment]
@duffy-james This is multiple issues. Some are already in another ticket. ([https://github.com/orgs/CityOfBoston/projects/54/views/4](url)

**Comment by duffy-james** [comment]
Closing this ticket; @subaha-cob has been making updates and they're accounted for in Jira.
