### ISSUE TITLE
List Component

### ISSUE THREAD

**Issue by zweishar** [CityOfBoston/boston.gov-d8#223]
There is no migration path for views from D7 -> D8. Core maintainers recommend re-building each view in D8 as the core architecture is different. There is a [module](https://www.drupal.org/project/view_migration) that claims to provide a migration path, but it has not been updated in over 1 year and I don't trust that it will work.

So we need to do the following to port this component:
- [x] Re-build the referenced views in D8:
    - [x] `bids_rfps`
    - [x]  `bos_department_listing`
    - [x] `bos_news_landing`
    - [x] `calendar`
    - [x] `metrolist_affordable_housing`
    - [x] `places`
    - [x] `public_notice`
    - [x] `status_displays`
    - [x] `topic_landing_page`
    - [x] `transactions`
- [x] Port theme for each view
- [x] Update the reference field on the list component
- [x] Theme the list component

**Comment by zweishar** [comment]
We've decided to put this on hold until we wrap up the content types that these views rely on.

**Comment by jimafisk** [comment]
On D7 it appears `field_list` is indeed a [viewfield](https://www.drupal.org/project/viewfield) `/admin/reports/fields`

**Comment by jimafisk** [comment]
Broken View template suggestions: https://drupal.stackexchange.com/questions/249854/i-dont-see-views-theme-suggestions

**Comment by jimafisk** [comment]
Running into this same issue: https://www.drupal.org/project/viewfield/issues/202794

In the past it looks as though we've added views via the list component: https://www.boston.gov/metrolist/affordable-properties even though the view has a page URL of `/metrolist-affordable-housing`
