### ISSUE TITLE
Remove bos_profile

### ISSUE THREAD

**Issue by zweishar** [CityOfBoston/boston.gov-d8#224]
I don't think we need `bos_profile` any longer. It's almost entirely empty, save for the `config_installer` module. We shouldn't need `config_installer` as I think you can do everything that module does with drush (`drush config-set "system.site" uuid "452fac34-8a25-4346-b005-f85d26dd3cf9" && drush cim -y`).

It's confusing to have an empty profile laying around. Let's change over to `standard` or `minimal`. I'd vote for `standard` because it's what I'm used to, but in practice, it doesn't really matter which we choose.

**Comment by davidrkupton** [comment]
yep I confirm `bos_profile` does nothing for the build now.
The build script changes the site UUID prior to install so `config_installer` is also not used an more.
Even though it is empty, the only reason I can see for having a custom profile is to allow a centralized place for `hook_updates`.  If we all agree that `hook_updates` can be added into the `bos_core` module, then we don't need `bos_profile` at all.

If we use `standard` we just need to make sure no contributed modules or unwanted core modules creep in.  Maybe `minimal` is better ??

If we all agree then I can make these changes to `develop`.

**Comment by zweishar** [comment]
Yah I agree that hook updates can go into `bos_core`, it's the most logical place for them at this point. `minimal` is fine by me. I don't think changing the profile will change which modules get installed at this point because we have our config exported, but better safe than sorry I guess.
