### ISSUE TITLE
flaws in e-mail service at https://www.boston.gov/departments/mayors-office#cabinet-heads

### ISSUE THREAD

**Issue by het-t** [CityOfBoston/boston.gov-d8#2245]
# Fatal flaw in e-mail sending 
[https://www.boston.gov/departments/mayors-office#cabinet-heads](url) webpage provides service to send email to individual staff member and it has some fatal flaws which can put the whole website in danger.

## Service which allows user to send an e-mail and its flaws :

![Screenshot (12)](https://user-images.githubusercontent.com/89692764/141672670-f72c924d-2c74-4f0e-8abe-1dc2ce714dbe.png)

When user click on **_SEND AN EMAIL_** button it opens up the form ( shown in next image ) which asks for full name, e-mail address  , subject and message.  Using this type of custom built e-mail sender comes at cost of control over unauthorized users. For example I have filled completely wrong information in e-mail address ( there is no such e-mail address "johndoe@fake.service" which exists ). But it still allows me to send e-mail.

![Screenshot (13)](https://user-images.githubusercontent.com/89692764/141672678-902234d7-bf58-488b-b365-78484741e80a.png)

![Screenshot (14)](https://user-images.githubusercontent.com/89692764/141672683-7c004b2f-b950-4e2a-a891-de937979dd8b.png)

## Why this flaw need to be fixed 

This flaw can make service vulnerable to **"e-mail bombs"**. 
E-mail bombs are a type of Denial of Service (DoS) attack. 
It can cause disruption over particular staff member and if attack is done on large scale can disrupt whole network and service.

More information regarding e-mail bombs can be found here [https://appriver.com/blog/email-bombs-disguise-fraudulent-activity](url) or [https://en.wikipedia.org/wiki/Email_bomb](url)

## Footnote 

- You must stop user from sending unnecessary or malicious e-mails without even getting noticed. 
Current service is providing a way to harm the system without revealing true identity because user can send mails with their fake accounts which don't exists.

**Comment by stephaniemar** [comment]
@duffy-james This seems fairly recent. Has this come up before?

**Comment by het-t** [comment]
> @duffy-james This seems fairly recent. Has this come up before?

Sorry but I am not aware about that.

But I have one solution to resolve this issue, can you please guide me I want to work on it ?
