### ISSUE TITLE
Content Type: Procurement Advertisement

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#225]
Adjustments are taking place here: https://github.com/CityOfBoston/boston.gov-d7/pull/1241

**Comment by zweishar** [comment]
This also relates to #223 because we need to port the `bids_rfps` view as part of that issue, which displays nodes of this type.

**Comment by zweishar** [comment]
@jimafisk are we ready to start porting this content type, or are we still waiting?

> Yeah good point @davidrkupton. I'm going to leave this open for now, we need some clarification on a couple of things from the original issue. Once we determine exactly the changes that need to be done, we'll have to account for them in D8. Thanks!

I'm considering doing as part of #223, but only if it's not still changing in D7
