### ISSUE TITLE
Rethink the BuildingHousing map page

### ISSUE THREAD

**Issue by rachelsater** [CityOfBoston/boston.gov-d8#2263]
This is the overarching ticket for any ticket related to the BuildingHousing map page(s) and its functionality.

- Projects with Meetings Pinned in List View #1769 
- Include project photos in list view #1875 
- Filter list view by keyword search #1871 
- Display icon legend on map overlay #1947 
- Project Stage Search Facet for Map #1658

**Comment by duffy-james** [comment]
Closing issue for now.
