### ISSUE TITLE
Pictures in the Photos section are appearing multiple instances 

### ISSUE THREAD

**Issue by rachelsater** [CityOfBoston/boston.gov-d8#2274]
The same photos are appearing multiple times in the Photos section. 

Steps to reproduce:
1. Go to https://www.boston.gov/buildinghousing/37-wales-street
2. Click on 10 Photos
3. Scroll through the images. The same 2 pictures appear 5 times

**Comment by duffy-james** [comment]
@ebshrier this should be updated:

https://www.boston.gov/buildinghousing/37-wales-street

The duplicate photos were removed. There's just the two photos now in the top right.

Not 100 percent sure, but the issue may have been that the images were added as "attachments" as well as images in one of the updates. Drupal only accepts certain file types for attachments (.ppt, .pdf., .txt), not .jpg files.

**Comment by ebshrier** [comment]
Wait - Drupal doesn't accept jpgs?? I'm pretty certain there have been jpgs added to WUs... what about png files?
