### ISSUE TITLE
Step 7: Review Information UI

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/boston.gov-d8#2302]
**Step 6: Review Information Acceptance Criteria** 

- [x] As a user I see the progress bar at the top of the screen move to step 7 of 7	

- 	The progress bar is on top of each screen of the application and shows user what step they on are on. In this case the user is on Step 7 of 7.

- [x] As a user I see the title of this Step so I know which step in the application I am on	

- 	User sees Step 7: Review Information

- [x] As I user I should see my total score out of my target score for the strategies I selected throughout the application	

- 	Your Total Score should be in CAPs and Bold
- 	The total score and target score should be green if the target score is equal to or exceeds 90
-       If the total score is below the target score it will show in Red
	
**Application Information**	

- [x] As a user I see the Filer Info Title above this section with an edit link 	

- [x] As a user I see all my filer information displayed so I can make sure my application information is correct 	

	The user sees the following information:

- 	Full Name 
- 	Email
- 	Your Role
- 	Real Estate Developer/Filer/Project Proponent 
- 	Development Name
- 	Have you submitted an application before? Yes or No

- [x] As a user I see an edit link so I can go back to edit my application information if needed.	

- 	When the user clicks the edit link it should navigate them back to Step1: Filer information of the application where they can update/edit the information
- 	The user will have to navigate back through application to get to review screen again
- 	If the user updated any information in Step 1, the updates should be reflected when they navigate back to the review screen

**Land Info**	

- [x] As a user I see the Land Info Title above this section with an edit link 	

- [x] As a user I see the the Land Information displayed so I can make sure my application information is correct	

	The user sees the following information:

- 	Target Score: 90 in blue
- 	Final Mobility Score: in blue
- 	Parcel Address 
- 	Proposed Land Use
- 	Type
- 	Your Proposed Net New Parking Spaces 
- 	Development Square Footage 
- 	Residential Only?
- 	Additional Details

- [x] As a user I see an edit link so I can go back to edit my land information if needed	

- 	When the user clicks the edit link it should navigate them back to Step 2: Land Information of the application where they can update/edit information on this screen
- 	The user will have to navigate back through application to get to review screen again
- 	If the user updated any information in Step 2, the updates should be reflected when they navigate back to the review screen

**Additional Land Information**	

- [x] As a user I see the Additional land Information Title above this section with an edit link 	

- [x] As a user I should see the Additional Land Information checkboxes and if checked in the application I will see this reflected on the screen	

- The user sees the parking freeze area check box with the description
- The user sees the compact living pilot check box with the description
- If the user checked these boxes in the application they will show as checked on the review screen
- The user will not have to the ability to check or uncheck these boxes on the review screen
- When the user clicks the edit link it should navigate them back to Step 2: Land Information of the application where they can update information on this screen
- If the user updated any information in Step 2, the updates should be reflected when they navigate back to the review screen

**Selected TDM Strategies**	

- [x] As a user I see the Selected TDM Strategies above this section 	

- [x] As a user I see three drawers representing the TDM strategies as part of the application with the total points for each strategy area 	

	The user sees three grey drawers that open and close for the following strategies

- 	Baseline Strategies | 40 Points Total
- 	Impact Strategies | 25 Points Selected
- 	Elective Strategies | 40 Points Total 

- 	Each drawer has a blue plus sign and the word 'show' indicating it is clickable to open/close the drawer

- [x] As user I see a Baseline strategy drawer when opened will show me the associated strategies and points total 	

- 	Once the drawer is open it will go from grey to blue
- 	The user sees a '-' symbol and the word 'hide' indicating the drawer is open and can be clicked to close it
- 	The user sees a clickable edit link that will navigate them back to this area of the application to make any edits
- 	The user sees all the strategies they picked and the points listed as well as any comments they made for this strategy area
- 	The user sees their points total for each subsequent area of strategies they picked

- [x] As user I should see an Impact strategy drawer when opened will show me the associated strategies and points total 	

- 	Once the drawer is open it will go from grey to blue
- 	The user sees a '-' symbol and the word 'hide' indicating the drawer is open and can be clicked to close it
- 	The user sees a clickable edit link that will navigate them back to this area of the application to make any edits
- 	The user sees all the strategies they picked and the points listed as well as any comments they made for this strategy area
- 	The user sees their points total for each subsequent area of strategies they picked

- [x] As user I should see an Elective strategy drawer when opened will show me the associated strategies and points total 	

- 	Once the drawer is open it will go from grey to blue
- 	The user sees a '-' symbol and the word 'hide' indicating the drawer is open and can be clicked to close it
- 	The user sees a clickable edit link that will navigate them back to this area of the application to make any edits
- 	The user sees all the strategies they picked and the points listed as well as any comments they made for this strategy area
- 	The user sees their points total for each subsequent area of strategies they picked

- [x] The user sees a Submit button -- The Submit button will be blue and turn read upon hover  

When clicked:

-  It will submit the application to BTD for review
-  The filer will receive a confirmation email with the details of their application(email details here --https://github.com/CityOfBoston/boston.gov-d8/issues/2358)
- The user is taken to the Submitted Application screen

- [x] The user sees a Previous Section button - when clicked it should move the user back to the previous screen

- The previous section buttons are dark blue and turn read upon hover 
- If the user goes back in the application the information they entered should be auto saved

**Comment by carolinestj** [comment]
Can we change the Montserrat title on this screen to be regular and not italic  
<img width="1304" alt="Screen Shot 2022-04-22 at 09 26 29" src="https://user-images.githubusercontent.com/22770827/164723579-06a610c5-7002-4d3a-bce3-99b8fc7ad45e.png">

Can we change the lora to be lower case instead of uppercase 
<img width="1309" alt="Screen Shot 2022-04-22 at 09 26 44" src="https://user-images.githubusercontent.com/22770827/164723857-cce3e2ca-7c11-44b4-b102-c2fe154c10c9.png">
