### ISSUE TITLE
Intro Screen UI

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/boston.gov-d8#2304]
**Acceptance Criteria for Filer Information screen**

- [ ] As a user I want to easily navigate to the Transportation Demand Management (TDM) Point System Tool on Boston.gov to start my TDM Application as part of the development review process	

- **Need URL for the tool (Q)**

- 	User navigates to TDM Tool intro screen on Boston.gov --  Dept of Transportation> Transportation Development review> TDM tool page

- [ ] As a user I want to see an intro page for the TDM Tool with information links and a begin application button so I can start my TDM Application	

- 	User sees welcome language copy introducing the application to users
- 	User sees Calculating Your Score information before starting the application
- 	User sees Mobility Score language and a Learn More link
- 	If the user clicks on the Mobility Score Learn More link they will open a new tab containing a mobility 
score page- https://d8-uat.boston.gov/departments/transportation/maximum-parking-ratios
- 	User sees TDB Target score language and a Learn More link
- 	If the user clicks on the TDM Target Score link they will open a new tab containing a TDM Target Score fact sheet (Need to know where this should navigate the user)
- 	The user sees a  blue Begin Application button, blue that turns red upon hover, when clicked it will start their application

**Comment by stephaniemar** [comment]
This page looks good -- We just need to solidify a couple of things here:

1. The App URL on Boston.gov
2. Where the Mobility Score Learn More link navigates the user
3. Where the TDM Target Score Learn More link navigates the user

**Comment by subaha-cob** [comment]
@stephaniemar I need more Information:

1. The App URL on Boston.gov - _what is the actual url? Add here pls._
2. Where the Mobility Score Learn More link navigates the user - I just updated this one
3. Where the TDM Target Score Learn More link navigates the user - _What is the url of the target score? Add here pls._

**Comment by stephaniemar** [comment]
Can we open the Learn More links in a new tab? 

I still have an open question about the TDM Target Score learn more link.
