### ISSUE TITLE
Public use of City of Boston Copyright material

### ISSUE THREAD

**Issue by ugintl** [CityOfBoston/boston.gov-d8#2325]
Can I use it for a client project?

**Comment by stephaniemar** [comment]
@davidrkupton @duffy-james Do you know what this is about?

**Comment by davidrkupton** [comment]
I think we need a paragraph on site copyright.
Ideally a page on boston.gov, that we can direct people to when this question arises.

**Comment by stephaniemar** [comment]
@carolinestj Can you provide a paragraph or two summarizing Sebestian's policy on Copyright of Design icons etc. @duffy-james do you think we should publish the policy on boston.gov? and fleet for the patterns lib?

**Comment by carolinestj** [comment]
@stephaniemar here's a blog post that I think Sebastian and James wrote 

But basically our code is open source but our brand is copyrighted, so you can't copy our look and feel

**Comment by stephaniemar** [comment]
It seems like we need some language to highlight that on Boston.gov and Patterns. We can defer to @duffy-james on this.

**Comment by ugintl** [comment]
@carolinestj It means that if I change the design, I can use it for a client.

**Comment by davidrkupton** [comment]
@ugintl - Yes, in summary the code is in the public domain but some of the design elements are not and the graphic elements are not.  So you can use the PHP, js and other code in this repository as the base for your own site (or one for your clients). We would however object if you use any of our images and icons (which are all copyright of the City of Boston).  We would also object if the final site was presented in a way which might confuse the public into thinking it was a City of Boston site, or suggested that it was in any way associated to the City. Please feel free to continue the dialog if you have more specific questions on use - and we will be happy to advise you.

**Comment by ugintl** [comment]
@davidrkupton One word comes to my mind "complicated". Nice design though.
