### ISSUE TITLE
Code error for bos_list component

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/boston.gov-d8#2330]
Local environment version is throwing loads of errors:

`Notice: Undefined index: #title in bos_list_preprocess_form_element() (line 215 of modules/custom/bos_components/modules/bos_list/bos_list.module).`

Update code with:
`if ($variables['element']['#title'] != NULL && .... )`

**Comment by subaha-cob** [comment]
` if (isset($variables['element']['#title']) && strtolower($variables['element']['#title']) === 'search' || $variables['element']['#attributes']['id'] === "edit-title") { ... }`

**Comment by davidrkupton** [comment]
actually there is another issue.  This is the current fix:
 ```if ((isset($variables['element']['#title']) && strtolower($variables['element']['#title']) === 'search') || (isset($variables['element']['#attributes']['id'] ) && $variables['element']['#attributes']['id'] === "edit-title")) {```

**Comment by rachelsater** [comment]
@davidrkupton should I close this ticket?
