### ISSUE TITLE
Old versions of the site are public and leaking [recheck May 2022]

### ISSUE THREAD

**Issue by mattl** [CityOfBoston/boston.gov-d8#2334]
ie. https://d8-ci.boston.gov -- is coming up in search results and has the previous acting mayor's name at the top, etc.

**Comment by davidrkupton** [comment]
Yes
We should have some no-index directives on those sites/dns.
So keep this ticket.

**Comment by davidrkupton** [comment]
Check this in early May to see if the links for d8-dev/d8-uat etc are off google.

**Comment by stephaniemar** [comment]
@davidrkupton Do we need to move this to JIRA?

**Comment by mattl** [comment]
How do we access Jira as the general public? @stephaniemar
