### ISSUE TITLE
Thumbnail image stretched on tablet screen size in "news" component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2341]
A user flagged for us that the thumbnail image is stretched on smaller screen sizes and tablet screen sizes in the "news and announcements" component. Example here on the [Archives homepage](https://www.boston.gov/departments/archives-and-records-management):

![image](https://user-images.githubusercontent.com/7929556/153012865-25e8a439-f9b2-4c39-a9b5-d7c6ec221fd1.png)

At the 1300 px width breakpoint, the view switches to this stretched look down to mobile view. Ideally in the "news" component, we'd mimic what we do on [Boston.gov/news](https://www.boston.gov/news), where the stories switch to a 50/50 split at smaller and tablet screen sizes until a user gets to a mobile screen size:

![image](https://user-images.githubusercontent.com/7929556/153013385-7dbb17da-c3ba-45b7-9b29-80f5602146fe.png)

**Comment by subaha-cob** [comment]
This may need a rewrite. 4 - 8 hours.

**Comment by duffy-james** [comment]
@subaha-cob we may need to work on this one together.

Essentially, for the "news and announcements" component, I want the tablet view to be the same thing as what we do right now on [our news website](https://www.boston.gov/news). On the news site, the tablet view looks like this, with a 50 / 50 split:

![Image](https://user-images.githubusercontent.com/7929556/170352366-3c479b72-cb93-4ea5-a7d6-8605a1435c03.png)

Currently, in tablet view, the "news and announcements" component has this stretched look:

![Image](https://user-images.githubusercontent.com/7929556/170352693-c172094e-eb90-48cf-8f76-f69c3b1e45bf.png)

Is it possible for us to have the 50 / 50 split view, instead of stretching the images?

**Comment by subaha-cob** [comment]
It can be done.
