### ISSUE TITLE
Apostrophe displaying character error in "events and notices" component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2342]
The apostrophe in the events and notices component displays the character code -- &#039; --  instead of an apostrophe:

![image](https://user-images.githubusercontent.com/7929556/153023633-acaef92d-dae2-4465-81af-f3680dcf5880.png)

Example here is from the [Winter Express page](https://www.boston.gov/civic-engagement/boston-winter-express).

I believe this is a bug that was addressed before, maybe by @padora-cob?

**Comment by subaha-cob** [comment]
I fixed this bug before. Bot sure why it is happening again. This should take about 2 - 4 hours.

**Comment by duffy-james** [comment]
@davidrkupton any chance we can prioritize this bug fix? we're starting to get more events added to the site for the summer and I have multiple examples where this is happening.

**Comment by duffy-james** [comment]
tested on staging, looks good to me.
