### ISSUE TITLE
Font error text of "how-to contact step" section

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2343]
On "how-to" content types in Drupal, a user is given the option to add a "how-to contact step". It provides some introductory text and then contact-specific information. Here's what it looks like in the back-end:

![image](https://user-images.githubusercontent.com/7929556/153029975-9e23a1a8-19f3-4801-b933-c4bacbe3870b.png)

Since the latest legacy CSS update, the text above is no longer displaying as normal text. Instead, it appears that an h5 or similarly sized tag is getting added to the text on the front-end:

![image](https://user-images.githubusercontent.com/7929556/153030138-6b865766-7360-41ee-bb3e-e4f708df988a.png)

Example above is from the [personal exemption how-to on the website](https://www.boston.gov/departments/assessing/how-file-personal-exemption).

We should switch this back to normal text above the contact specific information in that section.

**Comment by subaha-cob** [comment]
This will be 4 - 8 hours. Maybe more because the sidebars is very broad.

**Comment by duffy-james** [comment]
this looks good to me on staging, closing ticket.
