### ISSUE TITLE
"Formatted text" component issue at bottom of page

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2345]
A user noticed that on the [Housing Stability page](https://www.boston.gov/departments/housing/office-housing-stability), the "formatted text" component is taking up the full with of the page instead of staying within the container of the components:

![image](https://user-images.githubusercontent.com/7929556/153079573-a241b64e-05d1-41ee-8b26-0974b476814f.png)

Couldn't figure out what was happening through testing. Moving the component up makes it display correctly, but at the second-to-bottom and very bottom spots, the component takes up the full width.

This is a "program / initiative" content type. I've also noticed the same issue on a "listing" page. I can test on other content types if needed.

**Comment by subaha-cob** [comment]
This is actually a bug. I need to investigate this to know for sure. but if I have to guess about 4 - 8 hours.

**Comment by subaha-cob** [comment]
@duffy-james I cannot reproduce this bug. Is this still happening?

**Comment by duffy-james** [comment]
@subaha-cob looks like this is resolved, will close for now.
