### ISSUE TITLE
Bold and italics don't work together on front-end display

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2347]
When a user attempts to bold and italicize text in the backend of Drupal through the WYSIWYG field, it looks correct in the "edit" version of the page:

![image](https://user-images.githubusercontent.com/7929556/153601314-52fb8a95-9213-471d-ae7f-0155f7636a93.png)

But, when you save and view the draft, or publish, it looks like the "bold" is being removed from the text:

![image](https://user-images.githubusercontent.com/7929556/153601921-6c1f7a2b-62cc-44d2-a8e0-a9b5feeebc68.png)

The front-end should match the back-end, both when the user views the draft and on the published version of the site.

**Comment by subaha-cob** [comment]
This should take between 2 -  3 hours.

**Comment by duffy-james** [comment]
@subaha-cob looks like someone grabbed this one -- maybe @davidrkupton with the move to Drupal 9? Either way, going to close this ticket.
