### ISSUE TITLE
Logos not resizing / too big on "programs / initiatives" content type

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2348]
In the "programs / initiatives" content type in Drupal, a user has the option to add a logo to their page under "additional information":

![image](https://user-images.githubusercontent.com/7929556/153602537-c2eebd30-e386-4723-ba2a-b3a07b133e46.png)

The logo should be resizing and fitting the width of the sidebar component on the page, but instead, it's displaying its full width on the site:

![image](https://user-images.githubusercontent.com/7929556/153602705-03ca5503-db9d-4ad1-945e-635903408a59.png)

The example above is from the [Car Share Boston website](https://www.boston.gov/departments/transportation/car-share-boston).

We need to switch this page so that the logo resizes to the same width as the sidebar component, instead of its default width.

**Comment by subaha-cob** [comment]
This will take about 2 hours.

**Comment by duffy-james** [comment]
This still needs work. When I add the Car Share logo to the "program/initiative logo" section of a "program/initiative" page here:

![Image](https://user-images.githubusercontent.com/7929556/170353591-6433a1cb-407b-4b15-bede-7fd2ba247072.png)

It's still showing the full width of the logo image instead of resizing to fit the width of the sidebar:

![Image](https://user-images.githubusercontent.com/7929556/170353789-8d0c3998-a964-4e5d-a6f4-7f68dd941192.png)

It should be looking something like this:

![Image](https://user-images.githubusercontent.com/7929556/170353914-ef367166-30d2-4174-b62b-c8e8587b6e0d.png)

[Here's an example on staging](https://d8-stg.boston.gov/departments/transportation/car-share-boston). Let me know if you want to discuss, Stella.

**Comment by subaha-cob** [comment]
This is updated. Can you check this again @duffy-james.

**Comment by duffy-james** [comment]
[looks like that's working](https://d8-stg.boston.gov/departments/transportation/car-share-boston), Stella, closing this out
