### ISSUE TITLE
Boston.gov news listing page forcing title case on "post" titles

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2349]
On the [Boston.gov news listing page](https://www.boston.gov/news), the titles of the "posts" on the page all appear to be forcing title case in the display, where each word in the title of each "post" has a capital letter:

![image](https://user-images.githubusercontent.com/7929556/153603864-a443e190-2a46-48f3-8259-b75378143f50.png)

Here's what the top two posts look like in the backend:

![image](https://user-images.githubusercontent.com/7929556/153604263-d1966c4b-3e73-497e-88ed-f4fb313df86d.png)

![image](https://user-images.githubusercontent.com/7929556/153604299-4dd95c1c-6801-4033-94d1-6236924c00e3.png)

This happened after the recent CSS update. 

We should switch back to just displaying whatever the format of the title is in the "post", instead of forcing "title" case in the display of the news listing page.

**Comment by subaha-cob** [comment]
This should take 2 hours.

**Comment by duffy-james** [comment]
@subaha-cob Title case is still being forced on boston.gov/news

[Here's an example of an updated post on staging](https://d8-stg.boston.gov/news/mayor-wu-provides-updates-city-efforts-mass-ave-and-melnea-cass). There's sentence case in Drupal:

![Image](https://user-images.githubusercontent.com/7929556/170351215-00a7d419-ee4d-40e1-85ad-d7f42d8ba327.png)

But on display, the title is still in title case, where every word is capitalized:

![Image](https://user-images.githubusercontent.com/7929556/170351368-20b09dad-e6d4-4fbb-bc94-ead62c0ecbc7.png)

**Comment by subaha-cob** [comment]
Retest this please. I needed to reset the patterns Staging was pointing to again after every push to staging.

**Comment by duffy-james** [comment]
looks good to me, closing ticket
