### ISSUE TITLE
Spacing issues in sidebar components of content types

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2351]
When a user adds text to a sidebar component, the spacing on the backend and front are not consistent. For example, [on this ERG page on the website](https://www.boston.gov/equity-and-inclusion/asian-pacific-islander-american-employee-resource-group), I had to add extra spacing to make the display work on the front-end.

Here's the back-end:

![image](https://user-images.githubusercontent.com/7929556/153608584-4c37f7fd-712f-4189-be14-2a2e31d526ab.png)

And here's what the display looks like on the front-end:

![image](https://user-images.githubusercontent.com/7929556/153609450-3e18dd5d-b84f-419b-a6d7-71937f8bb744.png)

The issue only appears to be related to the sidebar component -- the spacing in the other WYSIWYG fields on the site, in components and under "basic information", appears to be correct.

**Comment by subaha-cob** [comment]
I am not sure what this is so I will estimate between 2 - 4 hours.

**Comment by duffy-james** [comment]
looks good to me, closing ticket
