### ISSUE TITLE
Make CSS consistent / the same on back-end and front-end

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2352]
Discussed this with @subaha-cob briefly after the latest CSS update, but there are spots on Boston.gov where the CSS isn't consistent. The most obvious spot is with the "formatted text" component. 

On the back-end, the columned layout appears to squeezing the text together, but it looks fine on the front-end display.

Back-end display:

![image](https://user-images.githubusercontent.com/7929556/153613340-798ee04e-a74e-4c99-8436-3eee7a906dcd.png)

![image](https://user-images.githubusercontent.com/7929556/153613391-f6176965-4eff-42d4-b58b-7ec3be7f757e.png)

Front-end display:

![image](https://user-images.githubusercontent.com/7929556/153613501-4e22c8a5-ebfc-40ab-a7b6-8a5d16f18356.png)

![image](https://user-images.githubusercontent.com/7929556/153613531-532eeca9-42da-4bf1-afec-973784cdfa74.png)

Ultimately just hope we can make the css consistent across the back- and front-end.

**Comment by subaha-cob** [comment]
This will take between 2 to 8 hours. Maybe more because I don't know why this is happening at all. I need to try and figure it out.
