### ISSUE TITLE
Abutters Mail generator does not include all addresses

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#2360]
From Penny Zhang (via Sarah Figalora)

Lastly, some teams in our department who use the [Abutter Mailing List Generator](https://www.boston.gov/abutter-mailing-list-generator) to generate contact addresses for mailings, but they have noticed that the generate does not generate addresses all property owners in various districts. Do you happen to know who manages this generator / website?

**see: https://www.boston.gov/abutter-mailing-list-generator**

Penny Zhang <peggy.zhang@boston.gov>
Jennifer Gaugler <[jennifer.gaugler@boston.gov](mailto:jennifer.gaugler@boston.gov)>
Kira Torrieri <[kira.torrieri@boston.gov](mailto:kira.torrieri@boston.gov)>

**Comment by duffy-james** [comment]
this appears to be working and I have not received any recent complaints; closing ticket
