### ISSUE TITLE
Metrolist feedback form returning html tags

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2411]
Nolin in the Mayor's Office of Housing is reporting an issue with the feedback forms on our Metrolist pages:

_Starting late last week (March 17-18), we began to receive a number of Metrolist Webform Submissions with this HTML format. It looks like they may be generated when an anonymous submission is made, and are coming from a Matthew Crist email address_

Here's an example of the message below:

![image](https://user-images.githubusercontent.com/7929556/159351265-a9c3e21b-6487-4fc9-9354-95cb29bb9092.png)

There's a correlation here from when we switched from Drupal 8 to 9 last week.

**Comment by davidrkupton** [comment]
We belive this has been fixed - waiting for confirmation from MOH

**info:** We needed to update our settings to accommodate server-side settings made by our web hosting provider Acquia.
These changes have been made and other webform emails are now sending correctly, so we expect BH webform generated emails will be too.

**Comment by duffy-james** [comment]
@ebshrier is this still an issue on your end?

**Comment by ebshrier** [comment]
Issue fixed. These are coming in correctly.
thanks
