### ISSUE TITLE
Content Type: Emergency Alert

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#242]

**Comment by davidrkupton** [comment]
-- comment has been copied from issue #63 --

> Partially complete. Content Type built and deployed.
> Requires clarity on where and how emergency alerts are to be deployed. They have been removed from the list component and we are considering including as a swap out of the hero image?

@reillyzlab - Should I mark this as blocked for now, waiting on a quick confirmation ?

**Comment by reillyzlab** [comment]
Confirmed with David that he doesn't need anything from me at the moment.

**Comment by jimafisk** [comment]
On #573
