### ISSUE TITLE
Metrolist changes in Salesforce not reflected on Boston.gov

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2424]
It seems that the [Metrolist listings on the website](https://www.boston.gov/metrolist) aren't updating. The Mayor's Office of Housing flagged some recent issues they're running into. This is from Nolin:

It looks like we're having some disruption with Metrolist now too. Visibility around the site's unit listings is usually controlled by an "Availability Status" field on the Development Unit record. We changed this status field to "Closed" on a few units yesterday but are still seeing the listings on Metrolist. Conversely, we're not able to post new listings to Metrolist. We've changed that "Availability Status" field to "Available" on several new listing forms. but are not seeing the listings render on Metrolist.

Here are two screenshots for the former example. We'd expect to see this listing off of metrolist because of the value highlighted below in Salesforce, but it seems like the site isn't refreshing its sync with Salesforce. 

![image](https://user-images.githubusercontent.com/7929556/160663017-02ade738-4d6d-4ee9-93c7-83b236e83eee.png)

![image](https://user-images.githubusercontent.com/7929556/160663048-133b8b10-8b03-4bd8-9ad3-00cf17c20e7a.png)

**Comment by duffy-james** [comment]
From Nolin: It does appear that the Drupal-to-Salesforce integration through the online listing form is still creating Salesforce records as expected. It appears to just be the Salesforce-to-Drupal integration where we are experiencing a block in listing updates / visibility.

**Comment by padora-cob** [comment]
Good news, it seem to work and update when I manually request a pull from Drupal (SF->Drupal).

99 Chestnut Hill Avenue Unit \#1 now seems to be updated to "closed" and de-listed on the site. 

I did not see any errors with the sync itself. Will look into a few other things. 

I will run a re-sync for the "metrolist-developments" and "metrolist-units" later tonight. This, at the least, should get us back to a point of being in sync with SF. The batch process may take a couple of hours to run but is low risk, we have a rate limit and a lot of units :) 

I will also keep an eye out the next few weeks. Looks like I may need to get some elevated access to be able to log-in to SF again. That would let me make a change and watch the process run every 5 minutes. May not need that quite yet though.

**Comment by davidrkupton** [comment]
- Moved to QAT while this is monitored.

**Comment by duffy-james** [comment]
@davidrkupton will do

**Comment by padora-cob** [comment]
I think that should be fine, thanks!

**Comment by duffy-james** [comment]
@padora-cob @davidrkupton The Metrolist team is reporting that updates aren't being reflected on Boston.gov.

[Watermills](https://www.boston.gov/metrolist/search/housing/watermills?type=rent&assignment=waitlist) was updated in Salesforce on Wednesday to reflect rent at $2,003, but it's still listed at $1,908.

The team also added a bunch of units for a Kingston lottery earlier today (Monday, April 4) that haven't appeared yet.

**Comment by duffy-james** [comment]
Closing this ticket; we have a few different tickets related to addressing sync issues in Jira.
