### ISSUE TITLE
Abutters Mailing List Generator Mapbox errors on console.

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#2430]
Issues with current [Abutters Mailing List Generator](https://boston.gov/abutter-mailing-list-generator)
- mapbox misconfiguration (in js console), 
   ![image](https://user-images.githubusercontent.com/4700050/161775418-02de7060-e18b-4c18-8e55-890045ffea65.png)
- an "undefined" which is returned after the search, next to the parcel #
   ![image](https://user-images.githubusercontent.com/4700050/161775148-c7cffff4-0ae5-42d8-aa33-bdda3404697e.png)

**Comment by stephaniemar** [comment]
@davidrkupton is this metrolist? Can it be closed?

**Comment by davidrkupton** [comment]
This is an issue with Abutters not Metrolist.
Both issues identified in the ticket still exist on prod.
We should move this to JIRA.

**Comment by stephaniemar** [comment]
https://bostondoit.atlassian.net/browse/DIG-1027
