### ISSUE TITLE
Step 3: Search Language Update

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/boston.gov-d8#2461]
Issue: We are not providing the functionality for users to search parcels for v1- the search language/ Find Parcel text label should be updated to reflect the user should just enter the address into find parcel field 

Steps to reproduce:
1. Navigate to Step 3: Land Information screen the user sees the following instructional language 'Search by address or select the map below to select your development site.' 
2. The is no map or search functionality on this screen 

Expected results: User should see appropriate instructions to enter parcel addresses on screen

**Comment by carolinestj** [comment]
@stephaniemar 
Should probably have James check the language on this but maybe something along the line of: 

FIND PARCEL
Add the address of your parcel, for example, 1234 street, Boston MA 02127"

**Comment by stephaniemar** [comment]
@duffy-james for v1 we are not implementing a parcel search, this will be an input screen for uses to enter one or more addresses. See Caroline's suggesting above, we need a language update here to reflect that is this is an input screen not a search screen.

![image](https://user-images.githubusercontent.com/92751818/165979360-c62f9af8-c487-4344-9d4d-00bd19d49bec.png)

**Comment by stephaniemar** [comment]
@subaha-cob you can use the following language here: 

- [ ] Under the Step 3: Land Information replace what is there now with this ---> Add the address of your parcel, for example, 1234 street, Boston MA 02127

- [ ] ADD PARCEL should be above the input box

**Comment by stephaniemar** [comment]
This bug has been fixed
