### ISSUE TITLE
Step 6: Bike Share membership/Subsidy and Mixed Use Development drop down dependencies

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/boston.gov-d8#2472]
Issue: 
1. Under the Bicycling strategy there is a dependency between the two drop downs. The bottom drop down should only activate if the user choses platinum in the top dropdown. There is only one option in the bottom drop down if it is active. If the user chooses platinum in the top drop down and picks the option in the second dropdown that option still appears if the user goes back and changes the level from platinum to something else. 
2. Under the Mixed Use Development there is a dependency between the two drop downs. The bottom drop down should only activate if the user choses Child Care Component in the top dropdown. There are two options in the bottom drop down if it is active. If the user chooses Child Care Component in the top drop down and picks one of the options in the second dropdown that option still appears if the user goes back and changes the component option. 

Steps to reproduce:
1. Navigate to Step 6 Elective Strategies 
2. Pick the platinum level bike share membership or Child Care Component in the top drop down
3. Pick an option in the second drop down
4. Go back to top drop down and choose another membership level/Component 
5. The bottom drop down becomes inactive but the option you first picked still appears to the user which is confusing 

Expected results:
Not sure how we should handle this scenario to make it more intuitive. Need UX/Dev to weigh in on options here

**Comment by carolinestj** [comment]
**Step 1:** click platinum -> get 7 points 
**Step 2:** click bottom box -> two options should appear "none | 0 points" and "subsidy 50%" 
**Step 3:** Choose one option -> in this scenario "subsidy 50%" -> get 5 points 
**Step 4**: Realize you don't want platinum -> choose another option 
_Action:_ second box that had  "subsidy 50%" selected should go back to the default state and be greyed out. The points should go down to 0 for this option

**Comment by subaha-cob** [comment]
@carolinestj I am having a hard time getting this to show zero because of some of Drupal form behavior that can as 'is'. Will it be okay to simply hide the section instead? See below:


![Image](https://user-images.githubusercontent.com/57374913/167458849-9895e82c-cfef-4569-aeb5-ed475ffd4c89.png)

**Comment by stephaniemar** [comment]
Hey @subaha-cob I am testing this bug- when I click the platinum option the bottom drop down becomes active and I can choose something here however when I go back up and choose a different level I am still seeing the option in the lower dropdown. Also if I go up and choose None this is what I am seeing. Not sure if this is what we want. 
![image](https://user-images.githubusercontent.com/92751818/167849864-09acc8a5-9732-4b5e-b5d9-f845ba1c54a2.png)

cc @miyekay94 @carolinestj

**Comment by stephaniemar** [comment]
Hey @carolinestj @miyekay94 can you take a look and see if the behavior here looks ok. I am thinking we can get user feedback during UAT testing.

**Comment by stephaniemar** [comment]
Here is the following behavior for the three strategies that have two drop downs:

**Comment by stephaniemar** [comment]
This looks good and has been fixed.
