### ISSUE TITLE
Spelling Updates(NEW)

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/boston.gov-d8#2484]
Issue; There are a couple of misspellings that need to be updated

Steps to reproduce: 

1. Navigate to any step that has Learn more links 
2. Learn in the Learn More link is spelled wrong -- They all say Lean no Learn
3. Step 4: Baseline Strategies --->>> Programming is spelled incorrectly it should have two M's

Expected Results: 
We need to update the page to reflect the correct spellings

**Comment by stephaniemar** [comment]
Hey @subaha-cob I am still seeing these errors.

**Comment by subaha-cob** [comment]
@stephaniemar I am not sure what the spelling is going to be. Please can you spell it out exactly because I see:
<img width="1236" alt="Screen Shot 2022-05-10 at 11 23 37 AM" src="https://user-images.githubusercontent.com/57374913/167665491-a0cf2783-d908-45e1-a7da-235b2e80d405.png">

**Comment by miyekay94** [comment]
@subaha-cob "Learn More" is showing as "Lean More" on steps 2, and 4

**Comment by stephaniemar** [comment]
@subaha-cob Programming is now spelled correctly but Learn is Lean on every screen 

![image](https://user-images.githubusercontent.com/92751818/167665861-ef075166-9219-4508-9c93-0aa2008014a3.png)

**Comment by stephaniemar** [comment]
This bug has been fixed.
