### ISSUE TITLE
Bos311: Multilanguage Supporting docs

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#2490]
Repository for project related documents.

**Comment by davidrkupton** [comment]
** Receiving API requirements
[Connected Bits API](https://github.com/CityOfBoston/boston.gov-d8/files/8661984/posts.api.pdf)

**Comment by davidrkupton** [comment]
## Resources
[Drupal Translation Management Tool](https://www.drupal.org/project/tmgmt)
[Walk through](https://www.amazeelabs.com/en/journal/multilingual-drupal-part-1-process) by AmazeLabs

for [localization](https://www.drupal.org/community/contributor-guide/reference-information/localize-drupal-org) of Drupal itself
- Need to `drush en locale` to get string translations.

**Comment by stephaniemar** [comment]
Work has been completed documented in JIRA
