### ISSUE TITLE
Add points to Step 6 check mark strategies in application

### ISSUE THREAD

**Issue by stephaniemar** [CityOfBoston/boston.gov-d8#2497]
Issue: The user does not see the points values for some of the check mark strategies in the application. Can we update these checkboxes to indicate the points value if checked so they appear like this: 

![image](https://user-images.githubusercontent.com/92751818/167890771-65408728-82cb-4e88-8017-56a8a731084b.png)

Step 6: Elective Strategies

- [x] E-Bike/E-Cargo Bike Program: 5 Points
- [x] Multimodal Transportation Subsidy: 10 Points
- [x] Parking Cashout: 10 Points
- [x] Bundled Transportation Options(GoHubs!): 4 Points

**Comment by subaha-cob** [comment]
@stephaniemar Just to clarify this, we don't need the points added to Baseline Strategies because it is already added there.
