### ISSUE TITLE
Filtering by "date" option missing in our news page

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2499]
On our [latest City of Boston news page](https://www.boston.gov/news), the "date" filer is appearing as an empty box with no option to filter by start and end dates:

![image](https://user-images.githubusercontent.com/7929556/167889426-c3d6cd6b-54f9-43b3-8978-ed430051f23c.png)

This may be related to the existing permissions issue noted in Ticket #2498

**Comment by davidrkupton** [comment]
@duffy-james I believe you are correct and this is related to #2498

**Comment by davidrkupton** [comment]
see comments on https://github.com/CityOfBoston/boston.gov-d8/issues/2498
