### ISSUE TITLE
Cape Verdean Translation for Status Item

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#2509]
Google translate does not translate Cape Verdean (aka Cabo Verdean / lang-code `cv`).
We require the following translations:
## Tow-Lot
- [ ] Tow lot
- [ ] How to get your towed car back
- [ ] The tow lot is closed. Automated kiosks are available 24 hours a day, seven days a week for vehicle releases.
- [ ] The tow lot is only open Monday through Friday, from 7 a.m. - 10:30 p.m. Automated kiosks are available 24 hours a day, seven days a week for vehicle releases.
- [ ] The tow lot is open from 7 a.m. - 11 p.m. Automated kiosks are available 24 hours a day, seven days a week for vehicle releases.
- [ ] The tow lot is open from 9 a.m. - 1 p.m. on Saturdays. Automated kiosks are available 24 hours a day, seven days a week for vehicle releases.
- [ ] The tow lot is closed on Sundays. Automated kiosks are available 24 hours a day, seven days a week for vehicle releases.

**Comment by stephaniemar** [comment]
Work has been done/documented in Jira
