### ISSUE TITLE
WEST END LIBRARY synch

### ISSUE THREAD

**Issue by ebshrier** [CityOfBoston/boston.gov-d8#2520]
Another project for which changes are not appearing in Drupal.

Issues are
- Site is not appearing on map
- A WU chatter entry was deleted but still appears on site (the May 18 entry)

Note: A second WU object was added to this site and then deleted same day it was created. The original WU object is what remains.

https://boston-dnd.lightning.force.com/lightning/r/Project__c/a048b00000cdoyfAAA/view
https://boston-dnd.lightning.force.com/lightning/r/Website_Update__c/a568b000000BxcfAAC/view
https://www.boston.gov/buildinghousing/west-end-library-housing-public-assets

thanks

**Comment by duffy-james** [comment]
@ebshrier I was able to remove the extra chatter entry, but I'm not sure why the project isn't showing up on the map, but my guess is that has to do with the second WU object. Will run this by @padora-cob

**Comment by duffy-james** [comment]
@ebshrier thanks for flagging, we'll investigate further

**Comment by davidrkupton** [comment]
Comments in [Jira](https://bostondoit.atlassian.net/browse/DIG-41)

**Comment by duffy-james** [comment]
@ebshrier Notes from @davidrkupton in Jira:

### Resolution

The record needs to have a Disposition Type which is not in the list appended to this comment.

Changing the `Disposition Type` to `Other` solved the problem on my local environment.

### Knowledgebase

The map is generated from a “Building Housing Maps” view display which is at /admin/structure/views/view/bhmaps/edit/livemap.

### Full Display Rules

A BH Project record will appear on the map if:

1. The `Content type` is **BH Project**, and

2. The record is **Published**, and

3. The `Public Stage` (Drupal: field_bh_public_stage) (SF: Project Stage) is one of:

- Project Launch
- Selecting Developer
- City Planning Process
- In Construction
- Project Completed

(The Drupal field links to a term in the taxonomy vocab Public Stage (BH))

4. The `Disposition Type `(Drupal: field_bh_disposition_type )(SF: Disposition Type ) is NOT any of:

- N/A
- Disposition Planning Project
- Disposition complete
- Incoming Transfer
- Interagency Transfer
- Non-active/Postponed
- Open Space - TBD
- Tax Title - Foreclosure Prevention
- Tax Title - Problem Property
- Tax Title - Redemption
- Tax Title - Revenue
- Tax Title - Site Assembly
- To be deleted

(The drupal field links to a term in the taxonomy vocab `Disposition Type (BH)`)

5. The Coordinates Boundary (Drupal: field_bh_coordinates) (SF: Parcel X Coordinate & Parcel Y Coordinate)
Actually, not sure how this works, I think the lat/long for the record must be inside a dynamic view variable which defines the map boundaries.

**Comment by duffy-james** [comment]
@ebshrier we can't find the images in the web update in Salesforce or any images in Drupal, but that could just be on us. Can you check to see if the images are there in Salesforce and point @davidrkupton to them? I want to see if we can make the sync work before I add them directly to Drupal.

**Comment by ebshrier** [comment]
@duffy-james Images may have been taken down. I've pinged Joe to find out if he still wants photos uploaded.
There is a slide deck .pdf attached in files that isn't appearing on website. Thanks

**Comment by ebshrier** [comment]
@duffy-james Just confirmed with Joe, no images to post. It's the slide deck pdf that he wants showing up. thanks

**Comment by duffy-james** [comment]
@ebshrier got it, thanks Ethan. I'll touch base with David on this one again.

**Comment by ebshrier** [comment]
Files now appearing on site.
