### ISSUE TITLE
New social media icons needed for Boston.gov

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#2527]
In our "add social media links" sidebar component, users are given the option to add Twitter, Facebook, Instagram, YouTube, Flickr, Tumblr, and TikTok. We need to add two more options: Glassdoor and LinkedIn.

Next steps:

- [x] @carolinestj please provide updated .svg versions of the attached icons matching the City of Boston brand.
- [x] Once we have the correct designs, @davidrkupton or @subaha-cob please add these as "Social Icon" options in Drupal.

Current icons:
![LinkedIn](https://user-images.githubusercontent.com/7929556/172379496-0516a1b9-c0d3-4f65-8435-64d471bd157d.png)
![glassdoor-icon](https://user-images.githubusercontent.com/7929556/172379499-1e4f7b8d-a9da-4ac3-b667-1b2b8dad55f0.png)

**Comment by carolinestj** [comment]
@stephaniemar hoping to make them this week!

**Comment by stephaniemar** [comment]
Great, Thanks @carolinestj!

**Comment by carolinestj** [comment]
@stephaniemar See if these work! 
![glassdoor](https://user-images.githubusercontent.com/22770827/176706831-e8a59dfe-4878-49f8-9f26-a91c113f9df0.svg)
![linkedin](https://user-images.githubusercontent.com/22770827/176706836-60aeaeed-fca1-461f-ac4e-6c4c7eea1976.svg)
