### ISSUE TITLE
WILLIAM BARTON ROGERS project synch

### ISSUE THREAD

**Issue by ebshrier** [CityOfBoston/boston.gov-d8#2574]
There are 12 photos listed on the website, but only 3 files in the website updated. Please resynch to remove duplicates. Thanks

https://www.boston.gov/buildinghousing/william-barton-rogers-middle-school-pryde
https://boston-dnd.lightning.force.com/lightning/r/Website_Update__c/a560y000000WILMAA4/view

**Comment by davidrkupton** [comment]
I will of course try to stop duplicates from being created in the first place, but this is a good example reason why a metrolist author role might exist, allowing MOH staff be able to modify Drupal records for metrolist and Building Housing apps.
