### ISSUE TITLE
Update AMI Rate table & calculation

### ISSUE THREAD

**Issue by ebshrier** [CityOfBoston/boston.gov-d8#2588]
We need to update the BPDA rate table (again). The table needs to be updated in the AMI calculator (https://www.boston.gov/metrolist/ami-estimator) and on the Income Restricted page (https://www.boston.gov/income-restricted-housing-guide)

The table to use can be found here: http://www.bostonplans.org/housing/income-asset-and-price-limits

### Summary of how AMI works and current state as of 7/15/22 (from David email):
What we know:

1. The AMI values are contained in a Taxonomy, as you know.
2. There are 3 sets figures for each XX% AMI level:
      - HUD (defined by a State Agency)
      - BPDA (defined by a City Agency)
      - A Maximum

3. The taxonomy values for HUD and BPDA are used in the construction of tables on the various metrolist web pages. These tables are built from a block created in a Drupal view. 
4. The taxonomy values for Maximum are used to estimate the %AMI threshold for the information provided in the wizard. The wizard is written in js, and the values (i.e. the maximum) used is taken from an API call to a Drupal view. 
5. It looks like the HUD data is out of date, and the Maximum data is very out of date (making the estimator provide incorrect estimations).

Our residual problem: (Note: Additional info from Tim Davis shown in **bold**)
- We are not sure on the "source of truth" for the AMI figures (presumably it would be with the relevant agency) or if there are situations where the MOH would seek to adjust those figures. **Going forward, BPDA and MOH rates will be in synch. The rates we should use are stored in the [Income Limits Google Sheet](https://docs.google.com/spreadsheets/d/190UYOANxp59q3G1cRy962tyYcBhv_k_v55mWk154XKQ/edit#gid=0)**
- For HUD, we are not sure which figures we should actually use (there are columns for different housing types). **Delete HUD table from page, just have one table.**
- We do not know why, for example we have 30% AMI and not 40% AMI. **We should include all thresholds (e.g. add 40% to table)**
- We do not know whether the Maximum figure is the max of HUD and BPDA or some other figure sourced from elsewhere. **We should only use BPDA/MOH rates. HUD table to be removed.**

Next Steps:
- Ethan will seek guidance as to which part of the [HUD-sourced table](https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.google.com_spreadsheets_d_190UYOANxp59q3G1cRy962tyYcBhv-5Fk-5Fv55mWk154XKQ_edit-23gid-3D0&d=DwMFaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=LJfD7EJ-tu83elRZa7zxbxxNNQUsKGEhrHoc6u-hn4U&m=BaxqcrkBHxybmfJqnl9p4o9A00RSsaUvno0VFGOofK80CFz6ELMicSfoYQ9WpXFO&s=VrxoO4p2xHYnL80gqLbEgj5WkBm6C7UJIxlznyPsR-A&e=) we should be inputting into the Taxonomy. **Use fields F5 to M10 (LIHTC/City Funded values)**
- Once resolved, James can input the HUD figures so the HUD table is correct on [boston.gov](http://boston.gov/) **N/A**
- Ethan will seek guidance as to what the Maximum figure is and how or where it is sourced. **N/A**
- Once resolved, James can input the Maximum figures so the estimator table is correct on [boston.gov](http://boston.gov/) **N/A**
- Ethan will do a bit of digging to see if we can find an electronic source of truth for HUD and BPDA (and maybe Maximum) (if MOH never alter those figures), so we can plan to import the data in the future. **From Tim:**

> I update the one spreadsheet. But I would be concerned about your system being to mechanized. For example, we made big changes to the format this year, and if someone is not aware it is tied to your site, your site could all the sudden be very messed up.

- I will put some language on the Taxonomy input page to help explain what each block of data is, and where it is sourced and what it is used for. **Tim's recommended language: "The Area Median Incomes used for this estimator are as follows (update date). Income limits do vary somewhat by program. View the full data, by program and for higher incomes, here. [insert link to MOH table] [provide table of F5-M10]"**

**Comment by duffy-james** [comment]
I'll pick this up, Ethan.

**Comment by duffy-james** [comment]
@ebshrier can you double check this? It should be set now:

https://www.boston.gov/income-restricted-housing-guide

**Comment by ebshrier** [comment]
Hi @duffy-james Numbers in table look correct, I'll have to check calculator. However, the AMI order on left is out of whack. Starts with 60%, then 30.

**Comment by duffy-james** [comment]
@ebshrier I noticed that as well -- I wasn't sure if it was intentional. That should be set now, though:

https://www.boston.gov/income-restricted-housing-guide

Everything is in order as far as I can tell and the numbers should be updated. @davidrkupton can we make sure the settings for that [Metrolist: AMI view](https://content.boston.gov/admin/structure/views/view/metrolist_ami/edit/ami_table_hud) are kept before our next deploy?

**Comment by ebshrier** [comment]
Hi @duffy-james table looks good. thanks.
The calculator, however, doesn't seem to be updated with new rates. Can you confirm those were updated as well?

**Comment by davidrkupton** [comment]
Hi Ethan

James is out today
I'll take a look at this in a few mins.

David.

On Fri, Jul 15, 2022 at 11:04 AM ethan shrier ***@***.***>
wrote:

> Hi @duffy-james
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_duffy-2Djames&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=I_xd1B4TcoerZD0cfelDi2nYa-O9wq1U9RSw7sL7u4s&m=3xhke_EFCB42XGJme8RK0pV4q-F2EBgknAjl9h1uvY11ekL9w5xTjmdijAhaoqn6&s=8qPOMQBUO_F4vxfZUlmLv0oQvE3Q7pe4JI4ZF1Gma9k&e=>
> table looks good. thanks.
> The calculator, however, doesn't seem to be updated with new rates. Can
> you confirm those were updated as well?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CityOfBoston_boston.gov-2Dd8_issues_2588-23issuecomment-2D1185634157&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=I_xd1B4TcoerZD0cfelDi2nYa-O9wq1U9RSw7sL7u4s&m=3xhke_EFCB42XGJme8RK0pV4q-F2EBgknAjl9h1uvY11ekL9w5xTjmdijAhaoqn6&s=LJr2lYhZSVdeWMFUq8RpcWzcQl5nGcOd_lqRqp2fDQY&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABD3PES7OHX5PLTNUAXRQ4TVUF4YJANCNFSM53P337TQ&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=I_xd1B4TcoerZD0cfelDi2nYa-O9wq1U9RSw7sL7u4s&m=3xhke_EFCB42XGJme8RK0pV4q-F2EBgknAjl9h1uvY11ekL9w5xTjmdijAhaoqn6&s=a4M2QfwDrMsSEdpkQiXX5dTfuG-X5NVciTWJe_UViiI&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 

[image: COB_B_Blue_square-01.png]

David Upton

Digital Team / Operations Team

Department of Innovation and Technology

781 330 5041 (c)

**Comment by duffy-james** [comment]
Next steps:

- [ ] Only have BPDA table showing on the page (remove HUD); rename it to something else
- [ ] [Fields F5 - M10](https://docs.google.com/spreadsheets/d/190UYOANxp59q3G1cRy962tyYcBhv_k_v55mWk154XKQ/edit#gid=0) are displayed in table (one and only one table)
- [ ] Add this language to the top of the one table: "The Area Median Incomes used for this estimator are as follows (update date). Income limits do vary somewhat by program. View the full data, by program and for higher incomes."
- [ ] We may need to also update the maximum table; David will investigate potentially pointing to one table.

**Comment by duffy-james** [comment]
@ebshrier just confirming I addressed the first few items related to the AMI in our next steps. [You can see the changes on the site](https://www.boston.gov/income-restricted-housing-guide).

One question for you is the description above the table. I tweaked the language slightly and added a link to the estimator itself. Let me know what you think.

**Comment by ebshrier** [comment]
Hi @duffy-james Looks good! I'm happy we only have one table now. 
On a second reading, some of Tim's language is a little awkward. Since you asked, here's my preferred version (but I'm not going to squawk one way or the other at this point).

"Each agency calculates AMI slightly differently. Our AMI estimator uses the following Area Median Income thresholds (updated 7/22/2022). Click here to see the full <Income Limits> data set."

**Comment by duffy-james** [comment]
@ebshrier would you mind if it was slightly tweaked [to this](https://www.boston.gov/income-restricted-housing-guide)?

"Each agency calculates AMI slightly differently. [Our AMI estimator](https://www.boston.gov/metrolist/ami-estimator) uses the following Area Median Income thresholds (updated 7/22/22). [View the full dataset](https://www.boston.gov/departments/housing/housing-and-urban-development-income-limits)."

I just don't like "click here" links. The link itself should be updated too.

**Comment by ebshrier** [comment]
Perfect.

**Comment by duffy-james** [comment]
I believe this ticket has been addressed, but feel free to open back up if not, Ethan.
