### ISSUE TITLE
Calendar Events causing 503 error on project page

### ISSUE THREAD

**Issue by ebshrier** [CityOfBoston/boston.gov-d8#2595]
When a calendar event is added to a web update in Salesforce, the drupal project page throws a 503 error. This was an issue if TBD was entered into URL field, but now occurs any time the calendar event is created. 
Jira ticket: DIG-431

**Comment by duffy-james** [comment]
@ebshrier This event should be displaying properly now: https://www.boston.gov/buildinghousing/251-255-259-washington-street

Events should be displaying properly now.

**Comment by duffy-james** [comment]
@ebshrier these should be fixed as well. @davidrkupton deployed a hotfix last night to address this, and also knows what the overall problem was that was breaking these pages with events. There was logic around a character limit issue related to the events, but that has been addressed.
