### ISSUE TITLE
Calendar events do not show physical location

### ISSUE THREAD

**Issue by ebshrier** [CityOfBoston/boston.gov-d8#2606]
Calendar events are not showing the physical address of the event, and instead say the event is being held virtually. These need to grab the physical address (field name = "Address") from the calendar event object. (Note: the address field is a single field for all street, city and zip info, which may be the reason...?)

https://www.boston.gov/calendar/community-celebration-food-fun-and-site-development-discussion-0
https://boston-dnd.lightning.force.com/lightning/r/Community_Meeting_Event__c/a558b000000HKlQAAW/view

**Comment by ebshrier** [comment]
Hi @duffy-james @davidrkupton  have you had a chance to look into this?
thanks

**Comment by duffy-james** [comment]
@ebshrier we were able to just go ahead and update the location in the calendar event:

https://www.boston.gov/calendar/community-celebration-food-fun-and-site-development-discussion-0

@davidrkupton is going to look into what's happening that's preventing the address from coming over, but that should at least be resolved for this specific event. Let us know if there are others where the address field is incorrect.

**Comment by duffy-james** [comment]
Closing issue; addressed in Jira.
