### ISSUE TITLE
Review moderation for the site.

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#261]
Adds moderation_sidebar to get a menu for content editors.
Need to review roles & permissions to some extent.

-- https://www.drupal.org/project/moderation_sidebar
-- https://www.drupal.org/project/moderation_note

**Comment by zweishar** [comment]
This work looks great to me, the moderation sidebar is a really nice touch and in general things seem to be really smooth. Nice work here.

One thing that may need some love is the workbench dashboard, but I think it's ok to wait on that until later. It's perfectly functional, it's just really ugly :) . If content editors actually use that (which I don't know if they do), then we should likely talk to James and see what he would find most helpful.

**Comment by zweishar** [comment]
@davidrkupton I'll assign this back to you for final decision. If you agree that we can wait on dealing with the moderation dashboard then we can close this issue.

**Comment by davidrkupton** [comment]
Thanks.
The `moderation notes` was not working for me when I did the last PR - so I'll spend a few mins on that, and shelve all other moderation/workflow until after review by James et al.

I agree about the dashboard, we can look to add/modify some new views and then theme it a bit to get the columns sitting better ...  in a way it falls under a wider discussion about the admin/content-editor UX & design.

**Comment by davidrkupton** [comment]
- [  TODO: Revise this to manage buttons on moderation sidebar according to the
  moderation state.
  -> Create an array and implement on moderation workflow config page to set a
  default state to move to from the state the entity is currently in.
  e.g. When moderation state is "published", the default next state should be
  "draft" etc. ]

**Comment by reillyzlab** [comment]
Pretty much done. May make small tweaks here and there.
