### ISSUE TITLE
Search not working - SwiftType settings & optimization. - 

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#263]
Note: There are some metatags in `bos_theme.theme`.

**Comment by reillyzlab** [comment]
@davidrkupton what needs to be done here?

Trying to figure out whether launch blocker or not.

**Comment by davidrkupton** [comment]
Assigned to Jim.  I know swift type is used to provide/assist search but I am not sure if there are specific drupal settings we need to make/add to optimize this ?

**Comment by jimafisk** [comment]
hmmm I think Matt Crist had to modify the [swiftype module](https://www.drupal.org/project/swiftype) in order to fit our requirements, not sure if those got contributed back. I can take a look.

**Comment by reillyzlab** [comment]
Search doesn't seem to currently be working.

**Comment by reillyzlab** [comment]
See relevant ticket: https://github.com/CityOfBoston/boston.gov-d7/issues/1393
