### ISSUE TITLE
Configure and test salesforce integration

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#271]

**Comment by davidrkupton** [comment]
Throws an error on Acquia that need SUPER user privileges to DROP TRIGGER as part of module install.  This is likely because the Acquia server  has tighter permissions for the drupal DB account than we have on local development machines.

**Comment by jimafisk** [comment]
To fix the SF connection for local dev, in lando, temporarily mapped ports:
- 80:80
- 443:443

Also adjusted key/secret values and added [config_ignore](https://www.drupal.org/project/config_ignore) for https://www.drupal.org/project/salesforce/issues/2961514
