### ISSUE TITLE
Paragraph: Bibblio

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#277]

**Comment by davidrkupton** [comment]
This is now implemented in D7.  
This is a port for D7->D8.
Assigned to @mmcgowanBOS .

**Comment by reillyzlab** [comment]
Defer to @mmcgowanBOS or @jfalvey on whether this is a launch blocker or not?

**Comment by andrebtlima** [comment]
Resolved so closing.
