### ISSUE TITLE
Component: Potential Decommission iframe component

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#279]
Potential Decommission iframe component contingent on review of how it’s currently used

- [x] Zach will pull a list of places it’s used throughout the site for James to review

- [ ] James will review and work with team to determine whether its needed moving forward

- [ ] If not needed, developers will remove as component in D8

- [ ] If not needed, James will convert iframe components into WYSWIG before full data/content migration

**Comment by zweishar** [comment]
This component is used on 79 published nodes:
```

**Comment by zweishar** [comment]
This component has already been ported into D8.

Given that the work has been done to port it and that the number of pages that would need to be updated is so high, my recommendation is to leave this component as is.

I'm happy to be overruled on this one, I don't feel super strongly either way.

**Comment by zweishar** [comment]
These are the node id's of the pages it's on:

```
mysql> SELECT nid FROM paragraphs_item as p JOIN field_data_field_components as f ON f.field_components_value=p.item_id JOIN node as n on n.nid=f.entity_id WHERE p.bundle='iframe' AND n.status='1';
+-------+
| nid   |
+-------+
|  1806 |
|  2191 |
|  3871 |
|  3881 |
|  4961 |
|  5691 |
|  7931 |
|  7961 |
|  8161 |
|  8176 |
|  8361 |
| 10271 |
| 10451 |
| 10661 |
| 11396 |
| 11856 |
| 11986 |
| 12221 |
| 12281 |
| 12306 |
| 12311 |
| 12371 |
| 12431 |
| 12436 |
| 12441 |
| 12446 |
| 12471 |
| 12476 |
| 12911 |
| 13026 |
| 13066 |
| 13366 |
| 13371 |
| 15191 |
| 15621 |
| 16901 |
| 17356 |
| 22501 |
| 23096 |
| 25626 |
| 26296 |
| 26631 |
| 29441 |
| 31746 |
| 32666 |
| 32751 |
| 33621 |
| 34176 |
| 34201 |
| 34211 |
| 34771 |
| 35181 |
| 35481 |
| 35486 |
| 35496 |
| 35506 |
| 36206 |
| 36701 |
| 37286 |
| 39991 |
| 41161 |
| 41476 |
| 43141 |
| 45336 |
| 47736 |
| 47991 |
| 49901 |
| 49911 |
| 49921 |
| 50776 |
| 50821 |
| 50841 |
| 51511 |
| 51511 |
| 51511 |
| 51511 |
| 51511 |
| 52331 |
| 55791 |
+-------+
```

You can visit these pages by going to https://www.boston.gov/node/{id}

**Comment by zweishar** [comment]
I'm going to assign this back to Reilly / James so that they can weigh in.

**Comment by duffy-james** [comment]
I completely forgot that DND was using the iframe component for its class signups.

If we decided to remove, I'd have to work with Gary on updating those pages. If the work has already been done to bring it over to D8, I think it's fine if we keep. It doesn't necessarily hurt to have it.

**Comment by reillyzlab** [comment]
All agreed this is fine to keep as is.
