### ISSUE TITLE
Align logo with D7 push.

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#291]
refer https://github.com/CityOfBoston/boston.gov-d7/pull/1277

- Add css from `bos.theme.overides.css` to boston theme,
- Update logo template, changing class `lo-b` to `lo-b-cont`.
- Remove the 'B' logo from the hero images component.

**Comment by jimafisk** [comment]
@davidrkupton is this done per https://github.com/CityOfBoston/boston.gov-d7/pull/1277?

**Comment by davidrkupton** [comment]
Not sure.  I raised this to keep track of a change @mmcgowanBOS made a change to D7.  Maybe we should refer to him.
