### ISSUE TITLE
Pull in Hemingway app readability grades to CKEditor

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#292]
Using the PHP API at https://github.com/DaveChild/Text-Statistics, make real-time Hemmingway style calculations of readability (e.g. US School Grade) and complexity available on-site to content-editors.

https://ipeirotis-hrd.appspot.com/

Proposed visualization strategy:
1. When a node is saved, run an assessment on content and provide selected grade and complexity statistics as an on-screen message.
1. Add grammar/readability and grade-level statistics for a node/page to a new panel on the moderation sidebar

Proposed calculation:
-  use the API to generate statistics on "analyzable content" contained within textboxes that have a WYSIWYG editor (i.e. Drupal Text Long types).  The node itself and any components on the node would be analyzed.
- Join all "analyzable content" fields into s single text block to give an overall complexity for the page.
- Initially would have a global target for complexity and grade across all pages and page types, possible extension is to set targets for complexity and grade for each node (page type).

**Comment by davidrkupton** [comment]
-Note this could be a second, stand-alone module that the city could contribute to the Drupal community.

**Comment by davidrkupton** [comment]
The grammar element of Hemmingway could possibly be achieved by downloading a JS based grammar checker into the WYSIWYG editor (if there is not already on there) and have it ON by default.  
- Also some browsers may have extensions that do this which could be enabled for frequently active content editors ...

**Comment by davidrkupton** [comment]
More info: https://drive.google.com/file/d/1W9sEdAPJqn-FlV3clB8pxtXhOtpVXbO4/view?usp=sharing

**Comment by reillyzlab** [comment]
Pulling in Hemingway app readability grades to CKEditor might require significant effort if there isn't an exiting solution.

Not sure if this is usable, prob worth evaluating: https://www.drupal.org/project/hemingway (From @jimafisk on 5/7/19)

**Comment by reillyzlab** [comment]
Matt and Stella did some research but we will de-prioritize for now.

**Comment by mgifford** [comment]
This looks like what you are asking for https://github.com/wooorm/readability

But also some work and other options are explored here https://github.com/nextcloud/text/issues/3

**Comment by rachelsater** [comment]
@duffy-james Do you want to have us look into this again?

**Comment by rachelsater** [comment]
closing this ticket and will create a new one if needed
