### ISSUE TITLE
Update: Status Item Title

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#321]
On mobile-portrait, decrease font size so that all of the date fits on one line. 

Ex. Wednesday, February 20 breaks onto two lines on mobile portrait

![IMG_0563](https://user-images.githubusercontent.com/20731897/55744536-2db8d380-5a03-11e9-90b5-cabd0b237eca.PNG)

**Comment by rachelsater** [comment]
@subaha-cob Is this something the fellows can help with?

**Comment by subaha-cob** [comment]
@rachelsater probably not yet. It will require us setting them up on Drupal. We are not there yet. But if they finish what they are currently working on, they can definitely work on this.

**Comment by duffy-james** [comment]
tested on my phone @padora-cob — looks good

**Comment by rachelsater** [comment]
@padora-cob should we close this ticket? thanks!

**Comment by padora-cob** [comment]
Yep, looking good on PROD with my iPad and iPhone!

**Comment by rachelsater** [comment]
yay!! thank you!
