### ISSUE TITLE
Short term fix to tables on mobile

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#323]
There are plans to do more of a longer term solution to create a better experience for tables or data currently displayed in tables on boston.gov, but in the meantime we'd like to implement a short term fix to make the mobile experience better.

Short term fix: Adjust the breakpoints so that the content doesn't bleed off of the page.

Examples: https://www.boston.gov/metrolist/lottery-and-resale

Potentially fix through
- Through WYSIWIG
- Through Drupal View

**Comment by jimafisk** [comment]
Good point a bout multiple / separate implementations for tables @reillyzlab.

**Comment by padora-cob** [comment]
I believe this ticket is covered by https://github.com/CityOfBoston/boston.gov-d8/issues/646 and can be closed. 
See for working example: (https://www.boston.gov/news/awardees-vaccine-equity-grant-initiative-announced)

Updates to the table styles are being worked on under https://github.com/CityOfBoston/boston.gov-d8/issues/1084.

**Comment by duffy-james** [comment]
@padora-cob looks correct to me — closing this ticket.
