### ISSUE TITLE
Update upcoming events component styling to reflect IDEO recs

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#324]
Implement styling for the ‘upcoming events’ component to reflect how it was actually proposed by IDEO in functional specs.

+(from Jeanethe) include "add to calendar" javascript. 

See upcoming events section here: https://drive.google.com/file/d/0B_zP1ba56BBEbnM5TVNtOWVoTHM/view

**Comment by jimafisk** [comment]
Designs proposed by IDEO:

![upcoming_events](https://user-images.githubusercontent.com/5913244/57316591-25b48800-70c4-11e9-9ed7-7bb0380f977b.png)

Actual design on https://www.boston.gov/events:

![actual](https://user-images.githubusercontent.com/5913244/57316685-5eecf800-70c4-11e9-84da-947ed90af6ff.jpg)

**Comment by andrebtlima** [comment]
Closing because this is duplicative of ticket #1745.
