### ISSUE TITLE
Decrease padding on all components and create consistency across site

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#325]
Decrease padding on all components so that there is less white space above and below each component.

**Comment by reillyzlab** [comment]
Dependent on: https://github.com/CityOfBoston/creative-team-workflow/issues/1172

**Comment by jimafisk** [comment]
If we can get design comps it would help the dev team understand the scope of this change. For now, putting as one-day LOE assuming it's targeted at a specific number of components.

**Comment by rachelsater** [comment]
Closing this ticket as I added the details into ticket #1995
