### ISSUE TITLE
Update: Revisit typeface throughout entire site

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#326]
It has been reported that the site/pattern library typeface styling as built does not match original design specs.

- [ ] We should change the type face for headers throughout the website and web applications and css class t--title
Few use cases that are bad/long: posts, public notices, some print [some find it unfriendly]

**Comment by reillyzlab** [comment]
Dependent on: https://github.com/CityOfBoston/creative-team-workflow/issues/1173

**Comment by jimafisk** [comment]
@reillyzlab can you point me to which specific sections need to be updated? If it's just a single universal change to font size, that would be quick but I assume it is more involved than that.

**Comment by reillyzlab** [comment]
@rachelsater to work with @sebastianebarb @duffy-james to groom this ticket

**Comment by reillyzlab** [comment]
Closing this and moving this to the Patterns repository
