### ISSUE TITLE
featured_item

### ISSUE THREAD

**Issue by kdonaldson** [CityOfBoston/boston.gov-d8#35]
depends on:

- content

**Comment by jimafisk** [comment]
**We should decommission this paragraph type and not migrate over to D8.**

The only place the `featured_item` paragraph is referenced is on `field_header_component` of Listing Page (`listing_page`) nodes. You can see all references to the paragraph using [Paragraphs Reference Manager](https://www.drupal.org/project/paragraphs_reference_manager) `/admin/structure/paragraphs/featured-item/manage-references`)

I checked prod on 12/19/18 and we only have 14 Listing Pages created. None of these Listing Pages actually use the `featured_item` paragraph. That means this paragraph type is not actually used anywhere in production.

There is a similar, but unrelated "featured item" on News & Announcements and Upcoming Events. News & Announcements use `field_featured_post` which is separate and Upcoming Events uses `field_featured_item` which is the same field used in the component `featured_item`, but it doesn't reference the component itself, just the common field.

Also the component does not appear to be working correctly in D7, so we'd be porting a broken component:

![featured_item2](https://user-images.githubusercontent.com/5913244/50233289-1933cb00-0381-11e9-879c-2844911fe7da.png)
