### ISSUE TITLE
Update: Revise footer

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#353]
Revise footer bashed on new designs:

https://github.com/CityOfBoston/creative-team-workflow/issues/258

Creative team will be coming up to with final design during May 20, 2019, bash week.

**Comment by rachelsater** [comment]
@sebastianebarb is this something we still want to do or nah?

**Comment by sebastianebarb** [comment]
Yep I think this is good to go!

**Comment by rachelsater** [comment]
@sebastianebarb great - thanks! Is this what you want the footer to look like? 
![image](https://user-images.githubusercontent.com/72876352/126834290-d371574e-c161-47ae-a314-c8b0de1954af.png)

**Comment by sebastianebarb** [comment]
Yep
On Fri, Jul 23, 2021 at 3:52 PM rachelsater ***@***.***>
wrote:

> @sebastianebarb
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sebastianebarb&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=Ojfn8jzyZqnDhEJtmlbvT_EqiZq5hiJihBNLGp5RAC8&m=FcfhvGGvHmosV4fi7y9VGjOktNQNyhGRHjkdNwNjviA&s=k38X31tCKQOs6kEohJw71UGKudYmePWmA2H7fFTIEWo&e=>
> great - thanks! Is this what you want the footer to look like?
> [image: image]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_72876352_126834290-2Dd371574e-2Dc161-2D47ae-2Da314-2Dc8b0de1954af.png&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=Ojfn8jzyZqnDhEJtmlbvT_EqiZq5hiJihBNLGp5RAC8&m=FcfhvGGvHmosV4fi7y9VGjOktNQNyhGRHjkdNwNjviA&s=r8Z8l4JQpixVPk6Ba8O8m6bAPj3VHSdNf8AmHNUP7-U&e=>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CityOfBoston_boston.gov-2Dd8_issues_353-23issuecomment-2D885879196&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=Ojfn8jzyZqnDhEJtmlbvT_EqiZq5hiJihBNLGp5RAC8&m=FcfhvGGvHmosV4fi7y9VGjOktNQNyhGRHjkdNwNjviA&s=J1zbqs2joklHiJhKb-D5u1FnFHf0xjbwm0CqQ-fGiz4&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AE5PT67K7ARE2OQP6JJNCA3TZHB77ANCNFSM4HJMHTNA&d=DwMCaQ&c=jHPlKdF3zLuO12CD8lDt5g&r=Ojfn8jzyZqnDhEJtmlbvT_EqiZq5hiJihBNLGp5RAC8&m=FcfhvGGvHmosV4fi7y9VGjOktNQNyhGRHjkdNwNjviA&s=K4ARpKHXtqdwEkvzbrpGiiBu79WOxJAXzen5NxbB-W0&e=>
> .
>
-- 

Sebastian Ebarb (*pronouns he/him/his*)

Design Director for the City of Boston

Department of Innovation & Technology

www.boston.gov/digital

You can check out *www.boston.gov/brand <http://www.boston.gov/brand>* for
all your *BOSTON* brand needs. You can sign up for design/Canva class here
<http://Boston.gov/canva>, and you can also see samples of our work at
*boston.gov/design-portfolio
<http://boston.gov/design-portfolio>.*

**Comment by rachelsater** [comment]
@padora-cob Can you help figure out how we would pull the "Most Viewed" and "Reported Issues" onto the footer? thank you!

**Comment by rachelsater** [comment]
closing this ticket because we don't want such a large footer. But I'm opening a new ticket for the "Most Viewed" and "Reported Issues".
