### ISSUE TITLE
Update: Breadcrumbs styling and functionality

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#354]
Review accessibility and update styling of breadcrumbs. 

Dependency on creative providing updated styling.

**Comment by jimafisk** [comment]
Style updates should be relatively quick pending design complexity. 

Estimates do not include accessibility updates, could we get more info here?

**Comment by reillyzlab** [comment]
Keep formatting of breadcrumbs and add an underline under each item of the breadcrumb that is a link (i.e. all the pages that are not the active page)

**Comment by reillyzlab** [comment]
From Drupal 7 build: https://docs.google.com/document/d/1fTLsI4tXrAPwRq7wdfavEqcvzlxGDgOluhbzyw_QKTE/edit#heading=h.ojcmiy5wtx0e
