### ISSUE TITLE
Implement schema.org and standard metatags.

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#358]
.

**Comment by davidrkupton** [comment]
For each node module, need to:

1. Add module.token.inc file following template in event.token.inc. Add in a token for all the fields that should be displayed in the metatags. See discussion below.
1. Select the metatag types required for the node in "metatag settings" then create a "default metatag" entry for the node type using tokens created above.
1. Add a field_metatag field to the node's fields (Note: re-use the existing field_metatag).
1. Add the field_metatag into the node "form display", and remove from the "display".

***Objective is to reduce or totally remove the need for metatag adjustment by content editors***

For schema.org metatags (ld-json):
* In the metatag settings pages we can apply tokens into metatag fields to be subsituted when the page is rendered and displayed.
* We can create custom tokens.
* In `module.tokens.inc - hook_event_tokens` we can control the content that is substituted during rendering.
* Most of the substitutions are pretty straight-forward, but the images and addresses and dates may need some tweaking.
* Images: google and bibblio are the big targets here.  Getting the right image tagged in the metatag is important. We could be dull and add a `field_metatag-image` to those node types which depend on image tagging, (and not display it to the end user - just use the url in the tag) - or we have the opportunity to be quite clever. using event as an example, we could make a rule to use the `field_intro_image` if it exists, if not then find all images in the body and select the biggest one, if there are no images in the body then use from a selection of default images based on say, the neighborhood or some other piece of info in the content.
- Being dull does have the advantage that we can constrain the editor to provide an appropriate (e.g. dimension or filesize) image - but does add workload on the editor and makes things a bit less "organic".

**Comment by davidrkupton** [comment]
Assigned to @mmcgowanBOS and @reillyzlab for comments and thoughts.

**Comment by reillyzlab** [comment]
Makes sense to me. Adding as item to our Tuesday sync so all have awareness.

**Comment by davidrkupton** [comment]
Matt has this working on D7.
This issue now becomes a port from D7->D8.
Assigned to @mmcgowanBOS.

**Comment by reillyzlab** [comment]
@mmcgowanBOS is this a launch blocker so that this works well/we don't lose historical info for Bibblio?

**Comment by mmcgowanBOS** [comment]
This has been completed and is displaying properly as far as I can see in the Dev branch of d8. Closing for now.
