### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by kdonaldson** [CityOfBoston/boston.gov-d8#36]
depends on:

- content - Advanced Poll

**Comment by zweishar** [comment]
This component is only used on one published page, `/node/17356/`. This is an Article node called "test page", which indicates to me that this component is not used any longer.

I spoke to James and he confirmed that this component is not actively used. His response:
> That was built for our pilot website, but it hasn’t been re-used anywhere

**Comment by davidrkupton** [comment]
Removed feedback configs from `config/default` per #360 .
