### ISSUE TITLE
Update: Hemingway Editor additions to content editor experience

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#363]
Update: Hemingway Editor additions to content editor experience

**Comment by jimafisk** [comment]
Pulling in [Hemingway app](http://www.hemingwayapp.com/) readability grades to CKEditor might require significant effort if there isn't an exiting solution. 

Not sure if this is usable, prob worth evaluating: https://www.drupal.org/project/hemingway

**Comment by reillyzlab** [comment]
duplicate ticket
