### ISSUE TITLE
Remove config split and replace with scripts.

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#381]
Add scripts into travis deploy for various environments.

**Comment by davidrkupton** [comment]
This can wait.  The current setup does deploy correctly, this is a housekeeping issue.

**Comment by reillyzlab** [comment]
@davidrkupton is this still a thing that needs to be done or can we close?

**Comment by rachelsater** [comment]
@davidrkupton Hiya! Can I close this ticket or do we still need to work on it?

**Comment by rachelsater** [comment]
Matt said I could close this one
