### ISSUE TITLE
Field group does not always indicate required children fields

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#400]
In some cases (not all), the parent field group does not get a red asterisk when it contains child fields that are required. 

**Example 1:** Event > Event Information > Event Details (contains required "Event Type")

![event_detail](https://user-images.githubusercontent.com/5913244/60513725-f1b1a980-9ca5-11e9-97f1-edfa42dad6b0.png)

**Example 2:** Department Profile > Advanced > Page Metadata (contains required "Published Date" and "Updated Date"

![page_meta_data](https://user-images.githubusercontent.com/5913244/60514061-ae0b6f80-9ca6-11e9-904c-d58d734bc30c.png)

**Comment by reillyzlab** [comment]
Not going to do unless content editors flag this.
