### ISSUE TITLE
Setup Pathauto module to create URL alias patterns

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#431]
https://docs.google.com/document/d/1fTLsI4tXrAPwRq7wdfavEqcvzlxGDgOluhbzyw_QKTE/edit?usp=sharing

**Comment by reillyzlab** [comment]
https://docs.google.com/document/d/1fTLsI4tXrAPwRq7wdfavEqcvzlxGDgOluhbzyw_QKTE/edit?usp=sharing

**Comment by reillyzlab** [comment]
We can revise some of these if it gets too complex

**Comment by reillyzlab** [comment]
From Drupal 7 build: https://docs.google.com/document/d/1fTLsI4tXrAPwRq7wdfavEqcvzlxGDgOluhbzyw_QKTE/edit#heading=h.ojcmiy5wtx0e
