### ISSUE TITLE
Homepage: Boston.gov hero image missing

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#462]
"welcome to Boston.gov" header is missing from the homepage.
This issue is present on Chrome 75, Safari 12, Firefox 68, and iOS Safari. (Tested on Mac Mojave and iPhone X on browserstack)

D7: 
<img width="1440" alt="Screen Shot 2019-07-31 at 2 40 00 PM" src="https://user-images.githubusercontent.com/42783424/62238502-28600a00-b3a1-11e9-8498-37465050d0e2.png">

D8:
<img width="1440" alt="Screen Shot 2019-07-31 at 2 40 03 PM" src="https://user-images.githubusercontent.com/42783424/62238518-2c8c2780-b3a1-11e9-9d49-8e93a1f1bede.png">

**Comment by davidrkupton** [comment]
This is an issue with the migration not bringing across all components for some reason.
