### ISSUE TITLE
Homepage: status updates are missing

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#463]
Status updates are missing from the homepage.
This issue is present on Chrome 75, Safari 12, Firefox 68, and iOS Safari. (Tested on Mac Mojave and iPhone X on browserstack)

D7:
<img width="1440" alt="Screen Shot 2019-07-31 at 2 42 01 PM" src="https://user-images.githubusercontent.com/42783424/62238773-a58b7f00-b3a1-11e9-99e9-2c188a0f18db.png">

D8:
<img width="1440" alt="Screen Shot 2019-07-31 at 2 41 58 PM" src="https://user-images.githubusercontent.com/42783424/62238793-ade3ba00-b3a1-11e9-9584-a6fbbae43060.png">

**Comment by davidrkupton** [comment]
View status_displays is not working.
I think this is because Zach changed the reapeating date/time component, and so the view needs to be changed too.

**Comment by jimafisk** [comment]
The data migration seems to be ok:

![d7](https://user-images.githubusercontent.com/5913244/62734212-7060db80-b9f6-11e9-889b-208db9968546.png)
