### ISSUE TITLE
Homepage: "City Building Hours" status update doesn't highlight light blue on mouse hover

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#464]
"City Building Hours" status update doesn't highlight light blue on mouse hover. Other images in the status update section highlight light blue on mouse hover. Example with trash and recycling:
<img width="1440" alt="Screen Shot 2019-07-31 at 2 44 53 PM" src="https://user-images.githubusercontent.com/42783424/62239006-116de780-b3a2-11e9-989d-5b13214f06f8.png">

This issue is present on Chrome 75, Safari 12, Firefox 68, and iOS Safari. (Tested on Mac Mojave and iPhone X on browserstack)

**Comment by davidrkupton** [comment]
This is an issue on D7 only I think b/c we dont have this component working in D8 yet.
- I epect this is to do with the svg saving method during creation, and the svg does not have the internal classes to allow line colors to be changed.

**Comment by davidrkupton** [comment]
Closed as part of issue #513.
