### ISSUE TITLE
Homepage: On Common Resources grid, issues with SVGs on both current state and hover state

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#465]
On Common Resources grid, some SVGs are missing lines/borders. Ex: "Apply for a city job", "Pay a parking ticket", etc.
D7:
![image](https://user-images.githubusercontent.com/42783424/62239259-8e00c600-b3a2-11e9-89cb-326c8f4e6353.png)

D8:
<img width="1440" alt="Screen Shot 2019-07-31 at 2 50 14 PM" src="https://user-images.githubusercontent.com/42783424/62239253-88a37b80-b3a2-11e9-856f-7059bce385d2.png">

This issue is present on Chrome 75, Safari 12, Firefox 68, and iOS Safari. (Tested on Mac Mojave and iPhone X on browserstack)

**Comment by davidrkupton** [comment]
This is an issue with icons I think.  I will delete all icons from the images folder prior to the next migration and I hope that will fix this issue.

**Comment by davidrkupton** [comment]
Closed - replaced by #513

**Comment by davidrkupton** [comment]
Closed - replaced by #513
