### ISSUE TITLE
Homepage: department icon does not display on main news component

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#466]
On the news component, the department icon on the featured item does not display. Displays alt text instead. In example, instead of Public Health Commission logo, it displays "Public Health Commission"
D7:
![image](https://user-images.githubusercontent.com/42783424/62239511-0071a600-b3a3-11e9-9593-4a2594cf968f.png)

D8:
![image](https://user-images.githubusercontent.com/42783424/62239519-036c9680-b3a3-11e9-9c57-21be46984930.png)

This issue is present on Chrome 75, Safari 12, Firefox 68, and iOS Safari. (Tested on Mac Mojave and iPhone X on browserstack)

**Comment by maxbahar** [comment]
Retested on Chrome 76 on OS X Mojave, icon on D8 is larger than icon on D7. Unsure if this is fine?

D7:
![image](https://user-images.githubusercontent.com/42783424/62645350-0a068b00-b91a-11e9-8ff5-b3243b2a6e08.png)

D8:
![image](https://user-images.githubusercontent.com/42783424/62645358-0d017b80-b91a-11e9-9da1-22481f84b9f9.png)

**Comment by davidrkupton** [comment]
The message "no upcoming posts" is correct, the dev site has no upcoming posts.
The image is slightly larger in D8 than D7, so I have reduced to be the same (width=60px).

**Comment by maxbahar** [comment]
Looks good!
