### ISSUE TITLE
Homepage: "upcoming events" component missing

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#467]
The Upcoming Events component is not present on the D8 Homepage.
D7:
![image](https://user-images.githubusercontent.com/42783424/62239653-4e86a980-b3a3-11e9-9ee7-43c635254c9e.png)

D8:
![image](https://user-images.githubusercontent.com/42783424/62239652-4d557c80-b3a3-11e9-8a2a-399a0ffd3b3a.png)

This issue is present on Chrome 75, Safari 12, Firefox 68, and iOS Safari. (Tested on Mac Mojave and iPhone X on browserstack)

**Comment by davidrkupton** [comment]
We can retest this when we have more data.  
There is now a placeholder showing no upcoming posts exist, so the component is present now.
![image](https://user-images.githubusercontent.com/4700050/62592621-d4be5680-b8a1-11e9-9a16-aab7920a7413.png)
