### ISSUE TITLE
Homepage: City Council subtitles inconsistent

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#469]
Discrepancies between D7 and D8 subtitles for all City Council Members i.e. 
D7: “Andrea Campbell City Council President, City Councilor, District 4”
D8: “Andrea CampBell Council President, District 4”
etc.

D7:
![image](https://user-images.githubusercontent.com/42783424/62240488-1b451a00-b3a5-11e9-880e-96bd6462ed97.png)

D8:
![image](https://user-images.githubusercontent.com/42783424/62240496-213afb00-b3a5-11e9-8351-1f4758608fd5.png)

This issue is present on Chrome 75, Safari 12, Firefox 68, and iOS Safari. (Tested on Mac Mojave and iPhone X on browserstack)

**Comment by davidrkupton** [comment]
This appears to be a data issue.
The data in D8 does not match the data in d7.
Maybe it has been changed recently?

**Comment by davidrkupton** [comment]
Nope this is a migration issue.  For this field the current revsision is set to be the previous but one published revision. *sigh this is a reversion of an earlier issue in migration.
