### ISSUE TITLE
Some person_profile pages are badly formatted.

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#475]
example-bad: https://boston.lndo.site/city-council/mark-ciommo
example-good:https://boston.lndo.site/age-strong-commission/emily-shea

-- has to do with components I think.
-- Don't worry about the page-top/breadcrumbs being hidden, I am working on that fix separately.

**Comment by jimafisk** [comment]
@davidrkupton just wanted to flag to you on this that the URL patterns for Person Profiles are different on D7 and D8:
- D7: https://www.boston.gov/departments/city-council/mark-ciommo
- D8: https://boston.lndo.site:3443/city-council/mark-ciommo

D8 is missing the `/departments/`

**Comment by jimafisk** [comment]
Looks like this visual defect is caused by trying to render `field_components`:

![cmmit](https://user-images.githubusercontent.com/5913244/62718036-0d118200-b9d3-11e9-9b07-d92a2c8ce3c0.png)

**Comment by jimafisk** [comment]
Also fixed:
- Social media links / icons in sidebar
- Address line 2 printing
- field_components
