### ISSUE TITLE
Global: Page bookmark headers don't shift when menu toolbar is opened

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#482]
When 'Menu' toolbar is expanded, page bookmark header doesn't shift accordingly. This causes the header to cover some of the menu toolbar.

D7: 
![image](https://user-images.githubusercontent.com/42783424/62493723-cf78e300-b79f-11e9-8d17-5b972a33ca3e.png)

D8: 
![image](https://user-images.githubusercontent.com/42783424/62493714-cb4cc580-b79f-11e9-8cca-acb97bd41e67.png)

Tested on chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
In procress:

Not happening on all content types. 

Happening on:

- Guide pages


Not happening on: 

- Homepage
- Department pages

**Comment by reillyzlab** [comment]
Resolved
