### ISSUE TITLE
Summer in Boston Guide: Image issues for 'Departments you may need"

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#488]
Under 'Departments you may need', some icons are missing. 
Additionally, BCYF logo is low-res on D8 site.

D7: https://www.boston.gov/summer-boston
![image](https://user-images.githubusercontent.com/42783424/62494792-457e4980-b7a2-11e9-9279-65523a008532.png)

D8: http://bostond8dev.prod.acquia-sites.com/summer-boston
![image](https://user-images.githubusercontent.com/42783424/62494794-47480d00-b7a2-11e9-8148-0bbf56809ac8.png)

Tested on chrome 76 on OS X Mojave

**Comment by maxbahar** [comment]
Tested again on Chrome 76 on OS X Mojave, now the svg files are present but are smaller than the D7 images. The BCYF logo is still low-res and blurry.

D7:
![image](https://user-images.githubusercontent.com/42783424/62645083-83ea4480-b919-11e9-9a77-495e98439883.png)
![image](https://user-images.githubusercontent.com/42783424/62645094-88166200-b919-11e9-80f8-928f7a1d7ed1.png)

D8:
![image](https://user-images.githubusercontent.com/42783424/62645088-85b40800-b919-11e9-85d6-e0fa005a68c2.png)
![image](https://user-images.githubusercontent.com/42783424/62645104-8ba9e900-b919-11e9-852d-4b6dd46b5f1d.png)

Additionally, header subtitle "Whether you're looking ..." is now missing on D8 site.

**Comment by davidrkupton** [comment]
Increased size to 56px.

**Comment by maxbahar** [comment]
The issue has been partially fixed but the "Tourism, Sports, and Entertainment" thumbnail is still the same size and the BCYF logo is still low-res.

D7:
![image](https://user-images.githubusercontent.com/42783424/62707523-830bee00-b9bf-11e9-95cf-aed0d4072907.png)

D8:
![image](https://user-images.githubusercontent.com/42783424/62707541-8a32fc00-b9bf-11e9-975b-cd9dee0a280b.png)
