### ISSUE TITLE
Getting Around Boston Guide: Image issues on get started links

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#489]
Under the "Get Started" section, image thumbnails have issues

D7: https://www.boston.gov/getting-around-boston
![image](https://user-images.githubusercontent.com/42783424/62558800-b3308100-b847-11e9-8663-2074640a17d8.png)

D8: http://bostond8dev.prod.acquia-sites.com/getting-around-boston
![image](https://user-images.githubusercontent.com/42783424/62558811-b62b7180-b847-11e9-8b17-884bf8f5de85.png)

Tested on chrome 76 on OS X Mojave

**Comment by davidrkupton** [comment]
We need to revise re-allocate the svg icons to things.  Some of these icons are old.
Going to close and make a new issue to collect all of these types of issue.
Closed - replaced by #513
