### ISSUE TITLE
Getting Around Boston Guide: Page shortcut header spacing issue

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#490]
In the page shortcut header (get started, vision zero, etc.), there is an extra space to the right of "Transit"

D7: https://www.boston.gov/getting-around-boston
![image](https://user-images.githubusercontent.com/42783424/62559078-3f42a880-b848-11e9-92a6-d49adbc66d09.png)

D8: http://bostond8dev.prod.acquia-sites.com/getting-around-boston
![image](https://user-images.githubusercontent.com/42783424/62559074-3ce04e80-b848-11e9-9022-5dfad435a194.png)

Tested on chrome 76 on OS X Mojave

**Comment by davidrkupton** [comment]
Fixed.

**Comment by maxbahar** [comment]
Fixed!
