### ISSUE TITLE
Getting Around Boston Guide: Car Sharing Image missing

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#492]
Image for the right column under "Car Sharing" is missing on D8 site.

D7: https://www.boston.gov/getting-around-boston
![image](https://user-images.githubusercontent.com/42783424/62559354-d14ab100-b848-11e9-8476-70c26c8c0869.png)

D8: http://bostond8dev.prod.acquia-sites.com/getting-around-boston
![image](https://user-images.githubusercontent.com/42783424/62559350-cee85700-b848-11e9-8304-881d1c27d85f.png)

Tested on chrome 76 on OS X Mojave

**Comment by davidrkupton** [comment]
Missing image issue.
Will address missing images as part of migration review.

**Comment by maxbahar** [comment]
I just retested this and it seems to be fixed
