### ISSUE TITLE
Getting Around Boston Guide: Some missing grid components

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#493]
Grid components are missing for "Public Transit" and "Resources for People with Disabilities"

D7: https://www.boston.gov/getting-around-boston
![image](https://user-images.githubusercontent.com/42783424/62559517-28508600-b849-11e9-92df-5d1844028311.png)
![image](https://user-images.githubusercontent.com/42783424/62559551-33a3b180-b849-11e9-98e5-f6759822b1d5.png)

D8: http://bostond8dev.prod.acquia-sites.com/getting-around-boston
![image](https://user-images.githubusercontent.com/42783424/62559508-25ee2c00-b849-11e9-9c70-d59b106c16e8.png)
![image](https://user-images.githubusercontent.com/42783424/62559555-36060b80-b849-11e9-8551-8d6e34c6d487.png)

Tested on chrome 76 on OS X Mojave

**Comment by davidrkupton** [comment]
This seems OK now.
Poss. fixed by some other issue solution.

**Comment by maxbahar** [comment]
Looks great!
