### ISSUE TITLE
Getting Around Boston Guide: Unordered guide numbers

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#494]
Numbering for the links to the other guides are unordered. (2, 3, 4, 4)

D7: https://www.boston.gov/getting-around-boston
![image](https://user-images.githubusercontent.com/42783424/62559717-71a0d580-b849-11e9-8129-187a6a73e6f1.png)

D8: http://bostond8dev.prod.acquia-sites.com/getting-around-boston
![image](https://user-images.githubusercontent.com/42783424/62559721-749bc600-b849-11e9-8854-1dbe75127ca9.png)

Tested on chrome 76 on OS X Mojave

**Comment by davidrkupton** [comment]
Fixed.

**Comment by maxbahar** [comment]
Fixed!
