### ISSUE TITLE
Getting Around Boston Guide: Missing images for "Departments you may need"

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#495]
Under Departments you may need, images are missing for all of the departments.

D7: https://www.boston.gov/getting-around-boston
![image](https://user-images.githubusercontent.com/42783424/62559790-9e54ed00-b849-11e9-84dd-00e34c0bb92c.png)

D8: http://bostond8dev.prod.acquia-sites.com/getting-around-boston
![image](https://user-images.githubusercontent.com/42783424/62559799-a01eb080-b849-11e9-8151-23f8326c2292.png)

Tested on chrome 76 on OS X Mojave

**Comment by davidrkupton** [comment]
Duplicate of #488
