### ISSUE TITLE
Public Notice 11601: Missing content for "Discussion Topics"

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#501]
The content under "Discussion Topics" is missing on the D8 site.

D7: https://www.boston.gov/public-notices/11601
![image](https://user-images.githubusercontent.com/42783424/62562734-ac0d7100-b84f-11e9-81f8-6c6aa1775964.png)

D8: http://bostond8dev.prod.acquia-sites.com/public-notices/11601
![image](https://user-images.githubusercontent.com/42783424/62562743-ae6fcb00-b84f-11e9-9896-cee968353f84.png)

Tested on chrome 76 on OS X Mojave

**Comment by andrebtlima** [comment]
Resolved so closing.
