### ISSUE TITLE
Public Notice 11601: Missing "Resources" files

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#502]
Under Resources on the right column, no files are present on the D8 site.

D7: https://www.boston.gov/public-notices/11601
![image](https://user-images.githubusercontent.com/42783424/62562814-d4956b00-b84f-11e9-9208-a06fc5901a99.png)

D8: http://bostond8dev.prod.acquia-sites.com/public-notices/11601
![image](https://user-images.githubusercontent.com/42783424/62562809-d2cba780-b84f-11e9-81b4-3976e15a45dc.png)

Tested on chrome 76 on OS X Mojave

**Comment by davidrkupton** [comment]
The first file is missing on the live site https://www.boston.gov/public-notices/11601 (link showing but is actually broken)
I've marked this as done b/c the second file which exists is there.

**Comment by andrebtlima** [comment]
Resolved, so closing.
