### ISSUE TITLE
Posts: Oversized department logo

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#505]
The department logo near top of the right column is significantly larger than the D7 site's logo.

D7: https://www.boston.gov/news/mayor-declares-heat-emergency-opens-bcyf-cooling-centers-and-pools-residents
![image](https://user-images.githubusercontent.com/42783424/62563405-00fdb700-b851-11e9-87bc-1739eae79b45.png)

D8: http://bostond8dev.prod.acquia-sites.com/news/mayor-declares-heat-emergency-opens-bcyf-cooling-centers-and-pools-residents
![image](https://user-images.githubusercontent.com/42783424/62563402-ff33f380-b850-11e9-994b-8ebb857a0cf4.png)

Tested on chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
Resolved
