### ISSUE TITLE
Mayor on Main Post: Missing breadcrumbs

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#506]
On the very top of the page, the D8 site is missing the breadcrumbs (i.e. Home > Latest City of Boston News > ...)

D7: https://www.boston.gov/news/new-dates-2019-mayor-main-trolley-tour
![image](https://user-images.githubusercontent.com/42783424/62563674-7e292c00-b851-11e9-816a-96f0b5f98589.png)

D8: http://bostond8dev.prod.acquia-sites.com/news/new-dates-2019-mayor-main-trolley-tour
![image](https://user-images.githubusercontent.com/42783424/62563677-7ff2ef80-b851-11e9-89ca-38ad60b29acc.png)

Tested on chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
Putting as a launch blocker to ensure there isn't a larger issue with the breadcrumbs.

**Comment by andrebtlima** [comment]
Resolved so closing.

**Comment by andrebtlima** [comment]
Resolved so closing.
