### ISSUE TITLE
In-line images not displaying correctly

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#507]
Image of program flier is not displaying properly in the D8 site. 

D7: https://www.boston.gov/news/new-dates-2019-mayor-main-trolley-tour
![image](https://user-images.githubusercontent.com/42783424/62563791-bb8db980-b851-11e9-93a2-b450e8818641.png)

D8: http://bostond8dev.prod.acquia-sites.com/news/new-dates-2019-mayor-main-trolley-tour
![image](https://user-images.githubusercontent.com/42783424/62563798-bd577d00-b851-11e9-84e8-8342646a4081.png)

Tested on chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
Two other examples with issues:

http://bostond8stg.prod.acquia-sites.com/news/mayor-signs-home-rule-petition-strengthen-ability-create-affordable-housing-fund-workforce

http://bostond8stg.prod.acquia-sites.com/news/new-mortgage-program-first-time-homebuyers

**Comment by andrebtlima** [comment]
Resolved so closing.
