### ISSUE TITLE
Styling of external links arrow on group of links - list

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#508]
Under the "Benefits" component, the grid component has small boxes with arrows in it to signify that it's a link. This arrow/box image is different in D8 compared to D7.

D7: https://www.boston.gov/career-center
![image](https://user-images.githubusercontent.com/42783424/62566810-d9f6b380-b857-11e9-8b39-d6d87a63a412.png)

D8: http://bostond8dev.prod.acquia-sites.com/career-center
![image](https://user-images.githubusercontent.com/42783424/62566816-dbc07700-b857-11e9-869d-2952d702aa79.png)

Tested on chrome 76 on OS X Mojave

**Comment by rachelsater** [comment]
@subaha-cob Is this a good one for the fellows? thanks!

**Comment by subaha-cob** [comment]
@rachelsater not yet. They have not be introduced to Drupal yet :)

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine The arrow looks ok to me but you let me know if this needs to changed. thanks!

**Comment by rachelsater** [comment]
no longer an issue
