### ISSUE TITLE
Career Center Landing Page: "Additional Ways to Search for Jobs" missing grids

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#509]
Under "Additional Ways to Search for Jobs", there is no content where there is supposed to be grids

D7: https://www.boston.gov/career-center
![image](https://user-images.githubusercontent.com/42783424/62566950-204c1280-b858-11e9-8fc8-86ff9c27b545.png)

D8: http://bostond8dev.prod.acquia-sites.com/career-center
![image](https://user-images.githubusercontent.com/42783424/62566953-2215d600-b858-11e9-8845-690c6563ad07.png)

Tested on chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
Resolved so closing
