### ISSUE TITLE
Career Center Landing Page: Under "Contact Human Resources" images for contact info not present

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#510]
Under "Contact Human Resources" images for contact info (phone, email, and address) are missing

D7: https://www.boston.gov/career-center
![image](https://user-images.githubusercontent.com/42783424/62567043-5ee1cd00-b858-11e9-89d8-81f94025741f.png)

D8: http://bostond8dev.prod.acquia-sites.com/career-center
![image](https://user-images.githubusercontent.com/42783424/62567044-61442700-b858-11e9-922e-0d92b452f0ce.png)

Tested on chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
Putting as a launch blocker in case there's a larger image issue.

**Comment by reillyzlab** [comment]
Closing this because doesn't appear to actually be an issue.
