### ISSUE TITLE
Grid of quotes issue - Career Center Landing Page: Missing last initials for "Hear From Employees"

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#511]
Missing last initials for "Hear From Employees"

D7: https://www.boston.gov/career-center
![image](https://user-images.githubusercontent.com/42783424/62567109-88025d80-b858-11e9-97ea-3ec565a8e9ac.png)

D8: http://bostond8dev.prod.acquia-sites.com/career-center
![image](https://user-images.githubusercontent.com/42783424/62567112-8a64b780-b858-11e9-9a93-dfefa9e6de0e.png)

Tested on chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
Applies to all grid of quotes

**Comment by reillyzlab** [comment]
This is resolved so closing
