### ISSUE TITLE
Articles: Missing subtitles

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#515]
On all article pages, the subtitle in the italicized Lora font right below the main title is missing. Attached is an example from the "Downtown Parking Freeze" page, the subtitle "The Downtown parking freeze is ..." is missing on the D8 site.

D7: https://www.boston.gov/departments/environment/air-pollution-control-commission/downtown-parking-freeze
![image](https://user-images.githubusercontent.com/42783424/62654819-aa66aa80-b92e-11e9-818e-e78ef327a0f7.png)

D8: http://bostond8dev.prod.acquia-sites.com/downtown-parking-freeze
![image](https://user-images.githubusercontent.com/42783424/62654820-acc90480-b92e-11e9-8133-85257dcc1d89.png)

Tested on Chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
This page is missing altogether, but still live/published on D7.

**Comment by andrebtlima** [comment]
Resolved so closing.
