### ISSUE TITLE
Articles: Address thumbnail image formatting issues

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#516]
Under the right column where the phone number, email, and address is listed, the address thumbnail image does not snap to the top like the D7 site.

D7: https://www.boston.gov/departments/environment/air-pollution-control-commission/downtown-parking-freeze
![image](https://user-images.githubusercontent.com/42783424/62655005-13e6b900-b92f-11e9-81cf-fa83b79a44e1.png)

D8: http://bostond8dev.prod.acquia-sites.com/downtown-parking-freeze
![image](https://user-images.githubusercontent.com/42783424/62655000-121cf580-b92f-11e9-8a78-85019d7db9fc.png)

Tested on Chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
Resolved so closing
