### ISSUE TITLE
Downtown Parking Freeze Article: Incorrect grid titles under "Parking Freeze Information"

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#518]
Under the section "Parking Freeze Information", instead of the actual titles showing up, it displays "Migration Stub: Link Title"

D7: https://www.boston.gov/departments/environment/air-pollution-control-commission/downtown-parking-freeze
![image](https://user-images.githubusercontent.com/42783424/62655550-3cbb7e00-b930-11e9-9bc2-1b7a3958c1f7.png)

D8: http://bostond8dev.prod.acquia-sites.com/downtown-parking-freeze
![image](https://user-images.githubusercontent.com/42783424/62655556-40e79b80-b930-11e9-8f47-e48687aecd2e.png)

Tested on Chrome 76 on OS X Mojave

**Comment by davidrkupton** [comment]
This is a migration issue.  For some reason the titles are not migrating across from d7.  Strange because the rest of the content is ....

**Comment by andrebtlima** [comment]
Resolved so closing
