### ISSUE TITLE
Articles: Missing a few directory paths (breadcrumbs issue)

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#519]
Near the top of the page, instead of having the full directory to the article, it just shows a direct path from home to the article title (i.e. "Home > Downtown Parking Freeze" instead of "Home > Departments > ...")

D7: https://www.boston.gov/departments/environment/air-pollution-control-commission/downtown-parking-freeze
![image](https://user-images.githubusercontent.com/42783424/62655685-84420a00-b930-11e9-800c-52393c68a09d.png)

D8: http://bostond8dev.prod.acquia-sites.com/downtown-parking-freeze
![image](https://user-images.githubusercontent.com/42783424/62655707-8efc9f00-b930-11e9-9788-4c4291f47f5f.png)

Tested on Chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
Issue with breadcrumbs

**Comment by davidrkupton** [comment]
Duplicate of #635. 
Closed this one.
