### ISSUE TITLE
Discounted Blue Bikes Article: Indent formatting issues

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#520]
Throughout the whole article, there are a few formatting issues: the shortcuts on the top of the page, the ordered list under 'How to sign up', and the unordered list under 'proof of participation'.

D7: https://www.boston.gov/departments/boston-bikes/discounted-blue-bikes
![image](https://user-images.githubusercontent.com/42783424/62656033-527d7300-b931-11e9-9e13-c6870fde7e46.png)
![image](https://user-images.githubusercontent.com/42783424/62656035-54dfcd00-b931-11e9-8f09-00def05dea3e.png)
![image](https://user-images.githubusercontent.com/42783424/62656040-57dabd80-b931-11e9-9b85-8ea96063fb41.png)

D8: http://bostond8dev.prod.acquia-sites.com/boston-bikes/discounted-blue-bikes
![image](https://user-images.githubusercontent.com/42783424/62656051-5dd09e80-b931-11e9-8a3a-db0e4e7c4eae.png)
![image](https://user-images.githubusercontent.com/42783424/62656074-6de87e00-b931-11e9-8a32-68a2c258d66f.png)
![image](https://user-images.githubusercontent.com/42783424/62656061-632de900-b931-11e9-95e0-36438ac26481.png)

Tested on Chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
Lists should be indented and they're currently not on Drupal 8.

**Comment by rachelsater** [comment]
@Micah-Levine @duffy-james This doesn't look like an issue to me anymore but what do you think?

**Comment by rachelsater** [comment]
no longer an issue so I'm closing this ticket

**Comment by duffy-james** [comment]
@rachelsater agree, no longer an issue.
