### ISSUE TITLE
Guide: Missing subtitles under hero image

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#521]
Directly under the main hero image, the subtitles are missing for all guide pages. Example is the "With our rich history, ..." subtitle is missing from the "Visiting Boston" Guide.

D7: https://www.boston.gov/visiting-boston
![image](https://user-images.githubusercontent.com/42783424/62656479-4219c800-b932-11e9-8546-9ef7c8d52a9a.png)

D8: http://bostond8dev.prod.acquia-sites.com/visiting-boston
![image](https://user-images.githubusercontent.com/42783424/62656476-40500480-b932-11e9-912a-d1afb0fa01db.png)

Tested on Chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
Content now appears but is still having formatting/display issues.

**Comment by reillyzlab** [comment]
Believe this is fixed.
