### ISSUE TITLE
Global: extra element "And Apply" at the headers of all pages

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#523]
On the top header of all pages on the D8 site, there is an extra element titled "And Apply" at the top of the page. This is not supposed to be there.

D8:
![image](https://user-images.githubusercontent.com/42783424/62707986-67551780-b9c0-11e9-899d-beeaf51c5bf4.png)

Tested on Chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
Closing b/c seems to be resolved.
