### ISSUE TITLE
Summer in Boston Guide: "BCYF Charlestown" subtitle discrepancy and formatting issue

### ISSUE THREAD

**Issue by maxbahar** [CityOfBoston/boston.gov-d8#524]
On the D8 site, the subtitle for "BCYF Charlestown" under "Community Center Pools" is formatted weirdly and is inconsistent with the D7 site.

D7:
![image](https://user-images.githubusercontent.com/42783424/62708235-f6fac600-b9c0-11e9-8f11-8c7c43837da8.png)

D8:
![image](https://user-images.githubusercontent.com/42783424/62708209-e9454080-b9c0-11e9-823a-f44f9c00cf7e.png)

Tested on Chrome 76 on OS X Mojave

**Comment by reillyzlab** [comment]
Labeled launch blocker to ensure it's not a larger data/content issue.

**Comment by andrebtlima** [comment]
Resolved so closing.
