### ISSUE TITLE
list

### ISSUE THREAD

**Issue by kdonaldson** [CityOfBoston/boston.gov-d8#54]
depends on:
- contact

**Comment by jimafisk** [comment]
`Table 'drupal.paragraph__field_list' doesn't exist` -> need to manually create `field_list` viewfield.

![list](https://user-images.githubusercontent.com/5913244/44356572-bb987c00-a47d-11e8-8b41-aa7f4e37e5b0.png)

**Comment by jimafisk** [comment]
We'll also need to create the following Views in order to set the "allowed values" for this field:
- bids_rfps
- bos_department_listing
- bos_news_landing
- calendar
- metrolist_affordable_housing
- places
- public_notice
- status_displays
- topic_landing_page
- transactions
