### ISSUE TITLE
Views filters uses autocomplete instead of checkboxes

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#547]
<details>
<summary>Example on D8</summary>

![autocomplete](https://user-images.githubusercontent.com/5913244/63541958-27784f00-c4ed-11e9-8f8b-4b97b445dd8b.png)

</details>
Link: https://boston.lndo.site:3443/public-notices

<br /><br />

<details>
<summary>Example on D7</summary>

![checkboxes](https://user-images.githubusercontent.com/5913244/63542123-9ce41f80-c4ed-11e9-8788-0fdc1cfe321c.png)

</details>
Link: https://bos-d7.lndo.site:3443/public-notices

**Comment by jimafisk** [comment]
- [ ] Update views filter to "Allow multiple selections"
- [ ] Update views filter to "selection type" to be "dropdown"
- [ ] Update views better exposed filter (bef) settings to use "Checkboxes/Radio Buttons"
- [ ] Add new theme suggestions for `fieldset` and `bef_checkboxes` hook
- [ ] Override core fieldset template `core/themes/stable/templates/form/fieldset.html.twig` using new theme suggestions
- [ ] Override bef checkbox template `modules/contrib/better_exposed_filters/templates/bef-checkboxes.html.twig` using new theme suggestions

**Comment by jimafisk** [comment]
<details>
<summary>D8 updates WIP</summary>

![d8_updates](https://user-images.githubusercontent.com/5913244/63542504-85596680-c4ee-11e9-927a-d53a27857501.png)

</details>

**Comment by jimafisk** [comment]
This appears to regressed from the fix I made here: https://github.com/CityOfBoston/boston.gov-d8/pull/548#issuecomment-524046517

@davidrkupton was this reverted for some reason?

**Comment by jimafisk** [comment]
Still outstanding:
- https://www.boston.gov/public-notices

**Comment by jimafisk** [comment]
This should be all set on next deploy.

<details>
<summary>Screenshots</summary>

Previous:

![previous](https://user-images.githubusercontent.com/5913244/71524328-11174100-289b-11ea-90db-a5359a5c4d88.png)

Now:

![fixed](https://user-images.githubusercontent.com/5913244/71524331-15435e80-289b-11ea-9fde-c8d9f55f05ea.png)


</details>

**Comment by reillyzlab** [comment]
Resolved.

**Comment by andrebtlima** [comment]
Resolved so closing.
