### ISSUE TITLE
Global: Hamburger Menu Links Not Working

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#590]
When a user opens the hamburger menu and tries to click on any of the items, nothing happens.

These should be links to elsewhere.

Tested on Chrome, Firefox, and Safari on OS Mojave

**Comment by jimafisk** [comment]
Oh interesting, I see what you're talking about:

![nested_menus](https://user-images.githubusercontent.com/5913244/64723233-1f814e80-d49e-11e9-84e0-f5b58a5c5f64.png)

 This was not happening for me locally, but it appears each link on the remote site (http://bostond8dev.prod.acquia-sites.com/) is now getting a `route:<nolink>` value:

![route_none](https://user-images.githubusercontent.com/5913244/64723242-23ad6c00-d49e-11e9-96ad-13ebd2afe841.png)

Something must be broken in the process plugin I wrote for nested menus:
- https://github.com/CityOfBoston/boston.gov-d8/issues/456
- https://github.com/CityOfBoston/boston.gov-d8/issues/458

@davidrkupton I _think_ this was working previously, has anything changed that you're aware of?

**Comment by reillyzlab** [comment]
Retested and working so closing
