### ISSUE TITLE
Wrong display migrated for Public Notices view

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#593]
The public notices page in D8 (https://boston.lndo.site:3443/public-notices) is actually showing the Archived public notices because the wrong display is being migrated over from D7:

![archive_display](https://user-images.githubusercontent.com/5913244/64628684-d529a000-d3bf-11e9-8669-ebf635b3006f.png)

Edit link: https://boston.lndo.site:3443/node/11666/edit

Similarly the Archived notices page (https://boston.lndo.site:3443/archived-public-notices) is showing the current notices because it is getting the "Landing" display:

![landing](https://user-images.githubusercontent.com/5913244/64628929-4c5f3400-d3c0-11e9-9e74-d5a92160dc85.png)

Edit link: https://boston.lndo.site:3443/node/11671/edit

**Comment by reillyzlab** [comment]
Resolved so closing
