### ISSUE TITLE
Remove 'My Workbench' from D8

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#596]
If we keep the workbench, we should remove the "change log" for anyone but site admins. Only suggesting we remove because "my edits" and "all recent content" already exist as tabs near the top of the page.

**Comment by reillyzlab** [comment]
Work with @duffy-james to get this worked out post-launch.

**Comment by reillyzlab** [comment]
'All recent content' on D8 is doing what 'my workbench' did on D7. 

Remove 'my workbench' as a menu item and drive people to 'all recent content'

**Comment by reillyzlab** [comment]
We should hold off on this until we get results from General Assembly group.

**Comment by andrebtlima** [comment]
Some of the General Assembly group's recommendations (which are now tickets) cover this so I'm going to close this ticket.
