### ISSUE TITLE
Does the workbench search work/does it add value to back end experience?

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#597]
The search bar in the workbench doesn't appear to currently be bringing value/working as expected. 

![image](https://user-images.githubusercontent.com/7929556/64716492-7849ea80-d490-11e9-8fec-a49799779584.png) -- return no results

@jimafisk @davidrkupton would be good for us to groom what is currently happening/what's possible here to figure out what next steps should be.

**Comment by reillyzlab** [comment]
Closing because no longer seeing this in the back end
