### ISSUE TITLE
Make page titles required on all content types (some currently have, some don't)

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#598]
The following content types need to be adjusted:

- articles
- how to
- events
- guide
- landing
- listing
- posts
- place profile
- procurement advertisement (title is 'project name')
- program / initiative profiles
- script

The following content types do not need to be adjusted: 
- department
- person
- public notice
- tabbed
- transaction

**Comment by davidrkupton** [comment]
see undocumented drupal feature at:
https://www.drupal.org/forum/support/upgrading-drupal/2018-08-28/drupal-7-drupal-8-node-title-isnt-mandatory#comment-12843336

**Comment by reillyzlab** [comment]
Required title still missing (or now missing when previously wasn't) from the following content types: 

- [ ] Article
- [ ] Department
- [ ] Event
- [ ] How to
- [ ] Landing
- [ ] Listing
- [ ] Procurement advertisement (title is 'project name')
- [ ] Program/Initiative
- [ ] Guide
- [ ] Status Item
- [ ] Script

**Comment by andrebtlima** [comment]
All fixed except for Department Profile.

**Comment by andrebtlima** [comment]
Resolved so closing.
