### ISSUE TITLE
Remove red astersik from Sidebar Title field in Sidebar w/ icon sidebar component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#599]
We need to make the title optional, similar to a regular sidebar item. It looks like this:

![image](https://user-images.githubusercontent.com/7929556/64718531-623e2900-d494-11e9-8140-f0e3659e0b76.png)

But should be optional, like this:
![image](https://user-images.githubusercontent.com/7929556/64718554-76822600-d494-11e9-93dd-e5fb94ac7f42.png)

**Comment by duffy-james** [comment]
@jimafisk I completely missed that the title wasn't required, but the image instead. I think if you removed the red star from the top here that would go a long way:
![image](https://user-images.githubusercontent.com/7929556/64972704-be7bc100-d877-11e9-909e-c9a5010f71de.png)

Where it says "sidebar with icon". I don't think this is a blocker, though, just a minor UX issue.

**Comment by rachelsater** [comment]
@duffy-james is this still an issue? thanks!

**Comment by duffy-james** [comment]
@rachelsater think this is fine — Jim is correct, you can still save without a title.
