### ISSUE TITLE
Extra space in sidebar items

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#601]
When I combine two sidebar items on top of each other, there appears to be some extra spacing above and below the text:

![image](https://user-images.githubusercontent.com/7929556/64721202-f5c62880-d499-11e9-8c9d-aaa7a2432c49.png)

Looking for something closer to this:
![image](https://user-images.githubusercontent.com/7929556/64721266-14c4ba80-d49a-11e9-954c-c7ca92b2339a.png)

It's important because, on some of our pages, we're not using the "contact" field in basic information to automatically add the generic department email and phone number to the page. In those instances, I've manually built more custom contact info in the sidebar using these sidebar items to mirror how it would normally look.

**Comment by reillyzlab** [comment]
Related to #517

**Comment by reillyzlab** [comment]
@duffy-james can you put in a page where this is still happening, if it is still happening

Or, close if it's resolved.

**Comment by andrebtlima** [comment]
Having trouble reproducing this. James could you test?

**Comment by duffy-james** [comment]
Here's an example from the live site:

https://www.boston.gov/economic-development/food-trucks

![image](https://user-images.githubusercontent.com/7929556/71485271-54f84080-27de-11ea-9b65-dc47fa256933.png)

**Comment by davidrkupton** [comment]
Having trouble replicating.  I have added 2 sidebar items to a department and there appeared to be extra space below the upper item, so I have removed that extra spacing.
