### ISSUE TITLE
Issues with Department profile content type custom / daily hours

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#602]
http://bostond8stg.prod.acquia-sites.com/departments/boston-bikes

Styling on FYI completely off on article page.

![Screen Shot 2019-09-11 at 2 04 37 PM](https://user-images.githubusercontent.com/20731897/64722801-2eb3cc80-d49d-11e9-9066-660fff60378e.png)

**Comment by duffy-james** [comment]
That's actually not the FYI component. @davidrkupton it looks like the styling on custom hours in the contact information section is off:

![image](https://user-images.githubusercontent.com/7929556/64727226-5fe4ca80-d4a6-11e9-9f5a-6e8b295a61e3.png)

**Comment by davidrkupton** [comment]
Done.

**Comment by reillyzlab** [comment]
Confirming fixed.
