### ISSUE TITLE
WYSIWYG: Preview of text

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#603]
When a content author is editing a page they do not see the formatting/styles of the content in the workbench.

The preview of the text in the field is not reflecting how the text will look on the page:
![image](https://user-images.githubusercontent.com/7929556/64724479-915a9780-d4a0-11e9-9da3-07d7f2831ef6.png)
![image](https://user-images.githubusercontent.com/7929556/64724456-86a00280-d4a0-11e9-8228-88c61cc77935.png)

This is currently working on D7 and does not match one-to-one on D8.

Example:
D7:
![Screen Shot 2019-09-27 at 1 33 11 PM](https://user-images.githubusercontent.com/20731897/65789426-653f4780-e12b-11e9-8467-179ef85a5447.png)

D8:
![Screen Shot 2019-09-27 at 1 33 20 PM](https://user-images.githubusercontent.com/20731897/65789450-6d978280-e12b-11e9-9d16-3317599726ba.png)

**Comment by reillyzlab** [comment]
@davidrkupton @jimafisk you want all of these as individual tickets? 

A few seem blocking and a few seem not.

**Comment by jimafisk** [comment]
@reillyzlab that's a good idea. If some are blocking, it'd be helpful if we could focus on those independently from the nonblocking issues. Thanks!

**Comment by andrebtlima** [comment]
Resolved so closing.
