### ISSUE TITLE
'Create new document' option doesn't appear to work

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#604]
I flagged this for @davidrkupton already, but the "new document" option here isn't working, and it's also a bit confusing:

![image](https://user-images.githubusercontent.com/7929556/64729322-f4e9c280-d4aa-11e9-99a8-662240321f61.png)

When you click on that option, here's the next window you see:

![image](https://user-images.githubusercontent.com/7929556/64729407-18ad0880-d4ab-11e9-82f0-24cfad6958ef.png)

If you click on "document", there's a tab to upload, but it's not working. There just doesn't appear to be a way to upload and save. This is definitely a blocker for going live with D8.

**Comment by reillyzlab** [comment]
Related to #578

**Comment by andrebtlima** [comment]
Resolved so closing.
