### ISSUE TITLE
Updates needed to document uploading through media entity

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#605]
When you go through the upload process for a document through the media entity in our WYSIWYG field, you're only option is to embed the document image:

![image](https://user-images.githubusercontent.com/7929556/64730515-86f2ca80-d4ad-11e9-89f8-9f2ece28c477.png)

I'll also like the option to contextual link to text in the WYSIWYG field itself. Generally speaking, the idea is that I could highlight over text, upload, and then save, turning the text I highlighted over into a clickable link. Until we figure out document uploading, I'd consider this a blocker for moving forward.

**Comment by reillyzlab** [comment]
Related to #604

**Comment by andrebtlima** [comment]
Resolved so closing.
