### ISSUE TITLE
'Paste from word' and 'paste as plain text' not working in WYSIWYG

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#606]
I'm seeing this error when trying to use those options in the toolbar:
![image](https://user-images.githubusercontent.com/7929556/64807734-d693cd80-d563-11e9-8da6-0933059c1615.png)

The message mentions a browser issue, but it's not working in Chrome, Firefox, or Internet Explorer. I'd consider this a blocker for moving forward.

**Comment by reillyzlab** [comment]
Solve for now since this is a global issue outside of City of Boston:

- [ ] Remove buttons from WYSIWIG
- [ ] Add description below 'body' that says 'Press ctrl-shift-v to paste your content'.

**Comment by davidrkupton** [comment]
https://www.drupal.org/project/drupal/issues/2948171
OK so its acknowledged as broken on Drupal > 8.4.
It looks like it will be fixed in Drupal 8.8.
Rather than lots of work arounds and patches etc, can we wait a few weeks for Drupal 8.8 ?, We will remember to install as soon as it ships.

**Comment by reillyzlab** [comment]
Won't fix/resolve until December.
