### ISSUE TITLE
Blockquote not working properly in WYSIWYG field

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#607]
The button technically works, but there's no option to add the owner of the quote to a blockquote. In D7, a second box pops up, allowing me to add the quote and the author of the quote:

![image](https://user-images.githubusercontent.com/7929556/64808405-30e15e00-d565-11e9-8ef8-0a8696c55736.png)

Ideally, we'd keep something like this going forward.

**Comment by reillyzlab** [comment]
@duffy-james I can't see how to adjust the 'properties' of the block quote. Is this still a desire. If so, let's connect on it.

**Comment by padora-cob** [comment]
This was a custom CKEditor plug-in in D7: https://github.com/CityOfBoston/boston.gov-d7/tree/develop/docroot/sites/all/modules/features/bos_text_formats/plugins/citedblockquote

I think I could get it back without too much effort. 

These are the 3 custom CKEditor plug-ins that D7 was using:
![image](https://user-images.githubusercontent.com/62249548/113892469-02088980-9794-11eb-8fba-176ff802394b.png)

**Comment by duffy-james** [comment]
@rachelsater would like to add this back if we can. Having that second pop-up window allowing users to add a citations would be helpful.

**Comment by rachelsater** [comment]
@duffy-james sounds good! @padora-cob I'm assigning this back to you. Please let me know if you need more info in the ticket. thanks!
