### ISSUE TITLE
Components: Minor issue adding component while another still open

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#608]
If one component is open and a user attempts to add another, then the selection drop down list of the components gets cut off on the workbench/screen.

Example:
![image](https://user-images.githubusercontent.com/7929556/64808798-eca28d80-d565-11e9-8bf6-ed0b63bc07e0.png)

**Comment by duffy-james** [comment]
@reillyzlab looking at this ticket again, I think this is actually a blocker. It gets a little frustrating not being able to see all of your options with components.

**Comment by reillyzlab** [comment]
Happens when trying to add a new component as well: 

![Screen Shot 2019-09-20 at 5 13 52 PM](https://user-images.githubusercontent.com/20731897/65359479-97502700-dbca-11e9-98bc-adc63c5b21ef.png)

**Comment by davidrkupton** [comment]
Removed the chosen module.

**Comment by reillyzlab** [comment]
Still an issue.

See http://bostond8dev.prod.acquia-sites.com/test-article-10-4

![Screen Shot 2019-10-04 at 3 33 41 PM](https://user-images.githubusercontent.com/20731897/66234741-77396100-e6bc-11e9-880f-7d8b5a258945.png)

**Comment by andrebtlima** [comment]
Resolved so closing.
