### ISSUE TITLE
In-line/in-page editing issues

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#615]
1. If a user clicks on an “edit” icon on a component, that works accurately the first time a user edits. 

However, after it's saved and a user tries to edit again, the options in the dropdown change:
![image](https://user-images.githubusercontent.com/7929556/64808904-24a9d080-d566-11e9-839c-69bac8d5d5a9.png)

These should stay the same every time they are used and should not display as different items. Will be confusing for content authors/editors.

2. As a content author, if a user in line edits with the pencil icon the content automatically publishes. They should not be able to publish.

**Comment by davidrkupton** [comment]
This is turned off for content-editors and content-authors for the time being.

**Comment by andrebtlima** [comment]
@reillyzlab I'm having trouble reproducing this issue, at least #1. Need to change my role to test the second one.

**Comment by reillyzlab** [comment]
@duffy-james do you know if this is still an issue?

**Comment by duffy-james** [comment]
@rachelsater think we're all set here. I can't reproduce the issue.

**Comment by rachelsater** [comment]
woohoo! thanks
