### ISSUE TITLE
Breakpoints on workbench

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#616]
Breakpoints on workbench need to be reviewed. They are displaying less than ideal.

One example, this is breakpoint at 2560 x 1600 (regular screen size at City Hall).

![Screen Shot 2019-09-17 at 10 56 41 AM](https://user-images.githubusercontent.com/20731897/65054003-dd8f5700-d93a-11e9-9fc6-ef3c0d48fe3e.png)

Few additional examples for breakpoint at half screen on 13" computer:

![Screen Shot 2019-09-17 at 1 46 00 PM](https://user-images.githubusercontent.com/20731897/65066090-b55f2280-d951-11e9-9e6f-b8f5f8cdb334.png)

![Screen Shot 2019-09-17 at 1 46 10 PM](https://user-images.githubusercontent.com/20731897/65066091-b55f2280-d951-11e9-97de-d65c9e205a8e.png)

**Comment by rachelsater** [comment]
@duffy-james I'm not able to reproduce this but maybe it's browser/machine specific? can you see it?
