### ISSUE TITLE
Make page body copy not required on all content types (some currently have, some don't)

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#618]
Make page body copy not required on all content types (some currently have, some don't). These should all be optional.

The following content types need to be adjusted:

- article
- department
- event
- posts

The following content types do not need to be adjusted: 
- guide
- how to
- landing
- listing
- metrolist
- person
- place profile
- procurement advertisement
- program / initiative profiles
- public notice
- script
- tabbed
- transaction

**Comment by duffy-james** [comment]
@padora-cob @rachelsater can confirm this is working. These content types no longer have "required" body fields:

- article
- department
- event
- posts

**Comment by rachelsater** [comment]
great - thanks!
