### ISSUE TITLE
Bug with "featured" item in events and news components

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#620]
When a user adds a featured item to an events or news components, it removes that event or post from showing up in the automatically generated list of four items at the bottom of the component.

An issue that we've run into, though, is that if you add an event or post as a featured item to a component, it also prevents that same event or post from automatically appearing in other events and news components on Boston.gov.

For example, if I publish a new BCYF event and make it a "featured" item on their homepage, but I also tag one of the community centers, the event won't automatically appear on the community center page. It's prevented from appearing because it's a "featured" item on their homepage.

@jimafisk is aware of this issue, but I just wanted to document somewhere. This isn't a blocker for D8.

**Comment by andrebtlima** [comment]
@duffy-james been fiddling around with this one on staging, haven't been able to replicate it. Once things have cooled down a bit maybe we can take another look.

**Comment by duffy-james** [comment]
@reillyzlab I think? There's still duplication where — if you add a featured item — it will still appear in the bottom four. But the issue of events just completely missing from pages is resolved.

**Comment by rachelsater** [comment]
@duffy-james I wasn't able to reproduce this. Can I close it?

**Comment by duffy-james** [comment]
@rachelsater this can be resolved. The issue of the "featured" item also appearing in the automatically pulled in events still exists, but that would be a separate ticket, I think.
