### ISSUE TITLE
Adjust image in Cabinet component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#625]
The image for the associated person profile for our cabinets component is showing up as a square instead of an oval:
![image](https://user-images.githubusercontent.com/7929556/65264003-b3c16600-dadb-11e9-8dfb-b57a19e9a3de.png)

It should look like this:
![image](https://user-images.githubusercontent.com/7929556/65264032-c340af00-dadb-11e9-81fb-bcc8c5c178ce.png)

**Comment by reillyzlab** [comment]
This is even more broken as of 9/26:

http://bostond8stg.prod.acquia-sites.com/testing-cabinet-component-9-26

![Screen Shot 2019-09-26 at 11 33 02 AM](https://user-images.githubusercontent.com/20731897/65702684-6d2ab900-e051-11e9-80f3-354e1d290afe.png)

**Comment by andrebtlima** [comment]
Resolved so closing.
