### ISSUE TITLE
Remove lists from commission members component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#626]
The drop-down list in the component is looking at more than just the boards and commissions. The list includes Cityscore metrics, 311 requests, and more:

![image](https://user-images.githubusercontent.com/7929556/65264241-3518f880-dadc-11e9-9de4-950560016646.png)

We need to remove everything but the boards and commissions. For what it's worth the commission "summary" component is working correctly and only displaying boards and commissions.

**Comment by reillyzlab** [comment]
Blocker because it could mean there is an issue with the view.

**Comment by andrebtlima** [comment]
Resolved so closing.
