### ISSUE TITLE
Images in transaction_grid overflowing container

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#629]
![search_jobs](https://user-images.githubusercontent.com/5913244/65266166-7e6b4700-dae0-11e9-9534-d464ab9583ac.png)

Link: http://bostond8dev.prod.acquia-sites.com/career-center

This appears to be because an image in the `transaction_grid` is not getting resized to the appropriate image style:

![image_size](https://user-images.githubusercontent.com/5913244/65266415-05202400-dae1-11e9-99b6-a7483ec14af7.png)

**Comment by davidrkupton** [comment]
/node/19261/edit - on components the Transaction Grid has some issue.

**Comment by andrebtlima** [comment]
Resolved so closing
