### ISSUE TITLE
bos_signup_emergency_alerts

### ISSUE THREAD

**Issue by kdonaldson** [CityOfBoston/boston.gov-d8#63]
depends on:
- contact

**Comment by davidrkupton** [comment]
Partially complete.  Content Type built and deployed.
Requires clarity on where and how emergency alerts are to be deployed.  They have been removed from the list component and we are considering including as a swap out of the hero image?

**Comment by davidrkupton** [comment]
Closing as this is a ticket for the sign-up form which is working OK .
My comment is better suited to #242 which is the display of alerts on-site.
