### ISSUE TITLE
SVGs not rendering in departments view

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#630]
![svgs](https://user-images.githubusercontent.com/5913244/65266595-592b0880-dae1-11e9-87b1-7f3946095e49.png)

Link: http://bostond8dev.prod.acquia-sites.com/departments

**Comment by reillyzlab** [comment]
Most showing, but not all. A few are smaller in size too.

**Comment by reillyzlab** [comment]
Still an issue

**Comment by reillyzlab** [comment]
Check on 10/10/19

**Comment by andrebtlima** [comment]
Most are showing. 

Language and Communications Access has no department icon. 

Problem with box sizes for row containing Parks, BPDA and Police. Police Department icon appears as link. 

<img width="1429" alt="Screen Shot 2019-10-29 at 9 36 27 AM" src="https://user-images.githubusercontent.com/57111927/67772029-c1013700-fa2f-11e9-94f3-38a826aacb40.png">
<img width="1437" alt="Screen Shot 2019-10-29 at 9 38 57 AM" src="https://user-images.githubusercontent.com/57111927/67772213-10476780-fa30-11e9-9000-8415e78dfb44.png">

**Comment by andrebtlima** [comment]
Still a problem with this row:

<img width="1431" alt="Screen Shot 2019-11-07 at 1 59 28 PM" src="https://user-images.githubusercontent.com/57111927/68418825-04ae1c00-0167-11ea-9756-a15c858afefe.png">

**Comment by duffy-james** [comment]
@davidrkupton these icons aren't centered properly:

http://d8-dev.boston.gov/departments/archaeology
http://d8-dev.boston.gov/departments/archives-and-records-management
http://d8-dev.boston.gov/departments/boston-centers-youth-families
http://d8-dev.boston.gov/departments/fair-housing-and-equity
http://d8-dev.boston.gov/departments/fire-operations
http://d8-dev.boston.gov/departments/immigrant-advancement
http://d8-dev.boston.gov/departments/intergovernmental-relations
http://d8-dev.boston.gov/departments/law
http://d8-dev.boston.gov/departments/new-urban-mechanics
http://d8-dev.boston.gov/departments/registry-birth-death-and-marriage
http://d8-dev.boston.gov/departments/tax-collection
http://d8-dev.boston.gov/departments/youth-engagement-and-employment

These pages are all slightly off. The issue might have to do with the image:

http://d8-dev.boston.gov/departments/environment
http://d8-dev.boston.gov/departments/fire-prevention
http://d8-dev.boston.gov/departments/food-access
http://d8-dev.boston.gov/departments/library
http://d8-dev.boston.gov/departments/parks-and-recreation
http://d8-dev.boston.gov/departments/police
http://d8-dev.boston.gov/departments/public-facilities
http://d8-dev.boston.gov/departments/small-business-development

**Comment by andrebtlima** [comment]
I think some department icons (on both the departments page and individual department pages) are still not centered properly. Dropping this back into in progress.

**Comment by davidrkupton** [comment]
I'm going to close this ticket and create a new one (#874) for James' list of old icons as its a different thing.

**Comment by andrebtlima** [comment]
Ok great, closing this ticket.
