### ISSUE TITLE
Gap before hero image on Listing Page

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#633]
![gap_before_hero_image](https://user-images.githubusercontent.com/5913244/65267420-f0449000-dae2-11e9-8d8f-a95ea1a8d833.png)

Link: http://bostond8dev.prod.acquia-sites.com/latest-city-boston-news

**Comment by reillyzlab** [comment]
@duffy-james there isn't currently an image as the background for boston.gov/news 

If you want to add one back in, please do so and then close this ticket.

If not, please just close this ticket.
