### ISSUE TITLE
Autocomplete instead of checkboxes for News view

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#634]
![autocomplete](https://user-images.githubusercontent.com/5913244/65267565-46193800-dae3-11e9-953e-d1b17f760a64.png)

Link: http://bostond8dev.prod.acquia-sites.com/latest-city-boston-news

D7 link (for comparison): https://www.boston.gov/news

**Comment by reillyzlab** [comment]
Put launch blocker label, because it doesn't direct match what's going on in Drupal 7. 

But, James and I both believe that it's not heavily used, so if we're okay with saying we know it doesn't 100% match Drupal 7 we are fine removing the launch blocker and fixing later.

**Comment by andrebtlima** [comment]
Resolved so closing.
