### ISSUE TITLE
Events & Notices not coming across

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#636]
Example 1: http://bostond8dev.prod.acquia-sites.com/departments/boston-centers-youth-families

<details>
<summary>screenshots</summary>

D7:

![d7_upcoming_events](https://user-images.githubusercontent.com/5913244/65268847-fb4cef80-dae5-11e9-8c52-5b4994e1ce42.png)

D8:

![d8_upcoming_events](https://user-images.githubusercontent.com/5913244/65268857-01db6700-dae6-11e9-8fc1-41c57e6da17f.png)

</details>

Example 2: http://bostond8dev.prod.acquia-sites.com/ (homepage)

<details>
<summary>screenshots</summary>

D7:
![D7_upcoming_events_2](https://user-images.githubusercontent.com/5913244/65268903-17e92780-dae6-11e9-89a0-b9b85a55e687.png)

D8:
![d8_upcoming_events_2](https://user-images.githubusercontent.com/5913244/65268917-1e779f00-dae6-11e9-88c7-0e09e167969b.png)

</details>

**Comment by andrebtlima** [comment]
Resolved so closing.
