### ISSUE TITLE
Grid of guides component doesn’t display title text

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#637]
Here's all I'm seeing from the component:
![image](https://user-images.githubusercontent.com/7929556/65269048-6696c180-dae6-11e9-9073-0c2352fb61b3.png)

And here's how it looks on the D7 site:
![image](https://user-images.githubusercontent.com/7929556/65269328-f3da1600-dae6-11e9-959c-c6a810361e26.png)

This is not a blocker.

**Comment by reillyzlab** [comment]
Resolved so closing
