### ISSUE TITLE
News & Announcements component: Thumbnail images missing

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#638]
Link: http://bostond8dev.prod.acquia-sites.com/departments/boston-centers-youth-families

![news_annoncements](https://user-images.githubusercontent.com/5913244/65269545-677c2300-dae7-11e9-9c72-9bbded193015.png)

<details>
<summary>D7 info for reference</summary>

Link: https://www.boston.gov/departments/boston-centers-youth-families#latest-news

![d7_news_and_announcements](https://user-images.githubusercontent.com/5913244/65269500-4a475480-dae7-11e9-8303-fecce6c45449.png)

</details>

**Comment by reillyzlab** [comment]
The short link is behaving as expected. If you look at the content in the workbench 'news' is put in.

![Screen Shot 2019-09-20 at 4 32 52 PM](https://user-images.githubusercontent.com/20731897/65357188-55bc7d80-dbc4-11e9-9a04-82429c3bc207.png)

But, the thumbnails are still missing.

**Comment by reillyzlab** [comment]
Putting as launch blocker given it's related to the other media issues, but could potentially not be a blocker.

**Comment by reillyzlab** [comment]
Duplicate so closing
