### ISSUE TITLE
Grid of Card Component: External links adjustment

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#639]
For external links, these should open in a new tab for anonymous users.

**Comment by reillyzlab** [comment]
@subaha-cob you're doing this as part of your current work, correct or no?

**Comment by subaha-cob** [comment]
@reillyzlab yes I am. I have a fix currently on UAT.

**Comment by reillyzlab** [comment]
This is being covered by: https://github.com/CityOfBoston/Iterators/issues/156 which is actively in process
