### ISSUE TITLE
Make all component titles required

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#640]
We're inconsistent with making titles required on our components. Just taking a quick look, it's required on "grid of cards" and "grid of programs" components, but not required on "grid of people", "group of links - grid", and "group of links - list."

If we want to make it so titles aren't required, that's fine too. But, we should be consistent one way or the other

Titles current required on:
- 3-column w/image
- Cabinet
- Drawers
- Grid of guides
- Grid of Programs/Initiatives
- Hero
- FYI
- Grid of places
- Grid of cards
- Transaction grid
- Map
- Signup Emergency Alerts
- News & Announcements

Titles currently not required on: 
- BOS: 311
- Featured Guides
- Group of Links - Grid
- Grid of quotes
- Group of Links - Mini Grid
- Group of Links - List
- Photo
- Grid of People
- Formatted text
- Video
- Newsletter Signup
- iframe
- Events and Notices

**Comment by reillyzlab** [comment]
Want to groom a little more with @duffy-james

**Comment by rachelsater** [comment]
@duffy-james another one. I'm thinking this is still an issue but please confirm. thanks!

**Comment by duffy-james** [comment]
@rachelsater yes, this is still an issue. It doesn't look like it was ever addressed.

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine thanks! Since this ticket is 2 years old, I suspect the examples above aren't the only affected areas. If that's correct can we come up with a plan to document the right sections?
