### ISSUE TITLE
Style call-to-action button on 'group of links - grid' component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#642]
The call-to-action button on the 'group of links - grid' component needs styling to make the words appear. Here's what it looks like without the hover state for an internal or external link:
![image](https://user-images.githubusercontent.com/7929556/65275644-13c40680-daf4-11e9-8a74-f9f2a0c91552.png)

And here's what it looks like with me hovering:
![image](https://user-images.githubusercontent.com/7929556/65275764-4cfc7680-daf4-11e9-930d-83495053cebf.png)

Here's what the call-to-action button looks like for document links:
![image](https://user-images.githubusercontent.com/7929556/65275927-b41a2b00-daf4-11e9-920b-1ba0927a7aef.png)

We should also make the "title" on the call-to-action button required. You can technically save this and the link and title won't appear:
![image](https://user-images.githubusercontent.com/7929556/65275368-854f8500-daf3-11e9-9071-2071dd05a01b.png)
![image](https://user-images.githubusercontent.com/7929556/65275525-dcedf080-daf3-11e9-86a1-0d43fd574174.png)

**Comment by duffy-james** [comment]
This appears to be just isolated to the "group of links - grid" component. I had assumed it would also affect the "group of links - list" component.

**Comment by andrebtlima** [comment]
Resolved, so closing.
