### ISSUE TITLE
Make title required for documents in "group of links - mini grid" component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#643]
Right now, the title field is optional when you add a document link to the mini grid component:
![image](https://user-images.githubusercontent.com/7929556/65276866-b087a380-daf6-11e9-96ba-17e108b0f680.png)

We need to make this required. Technically, you could save without a headline and it creates an unclickable box:
![image](https://user-images.githubusercontent.com/7929556/65276973-ea58aa00-daf6-11e9-9964-a3385f7f453c.png)

**Comment by andrebtlima** [comment]
Closing because this issue is part of another ticket #640
