### ISSUE TITLE
WYSIWYG: Linking GUI

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#644]
The link option is a little confusing. It looks like an internal link, but it appears that you can also just add full external urls. Can we add options for email and phone? We had options in D7 to adjust the protocol and link type.

D8:
![image](https://user-images.githubusercontent.com/7929556/64724906-64f34b00-d4a1-11e9-947c-935f2d0e83d0.png)

D7:
![image](https://user-images.githubusercontent.com/7929556/64725035-b13e8b00-d4a1-11e9-81d7-3e50b6e1ce26.png)

Related to media.

**Comment by andrebtlima** [comment]
Resolved so closing.
