### ISSUE TITLE
WYSIWYG: styling dropdown

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#645]
Bare minimum the styling dropdown in the WYSIWYG should match the styles in D7 for content authors, etc.

There are currently only options for red text and intro text. 

![image](https://user-images.githubusercontent.com/7929556/64725177-0f6b6e00-d4a2-11e9-8d64-991bf4067cc2.png)

**Comment by andrebtlima** [comment]
There's still an issue here. In D7 the WYSIWYG includes a paragraph formatting drop down that includes Normal, Address, Formatted, Heading 2 - 6, and Normal (DIV) options. 

<img width="1408" alt="Screen Shot 2019-11-01 at 10 09 27 AM" src="https://user-images.githubusercontent.com/57111927/68030386-be9d1800-fc8f-11e9-8870-415818eafd79.png">

In D8 there's Paragraph formatting dropdown in the WYSIWYG, only the Styles dropdown with Block and Inline Styles.

<img width="1435" alt="Screen Shot 2019-11-01 at 10 11 49 AM" src="https://user-images.githubusercontent.com/57111927/68030529-13d92980-fc90-11e9-8f37-e57b85effc01.png">

**Comment by andrebtlima** [comment]
Another issue with the styling dropdown in the WYSIWYG here, the Intro Text style is adding a squiggly line below the text: 

<img width="1429" alt="Screen Shot 2019-11-07 at 1 51 02 PM" src="https://user-images.githubusercontent.com/57111927/68418331-07f4d800-0166-11ea-9ca2-da0fa345ab47.png">

Additionally, the actual drop down has got some spacing issues and the Reset isn't working and appears shaded as if its been selected:

<img width="1432" alt="Screen Shot 2019-11-07 at 1 51 50 PM" src="https://user-images.githubusercontent.com/57111927/68418458-425e7500-0166-11ea-9e92-08b110db082e.png">

**Comment by reillyzlab** [comment]
The styles dropdown has all of the elements, so closing.
