### ISSUE TITLE
WYSIWYG: Ability to make tables responsive

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#646]
We're missing the responsive tables option in the WYSIWYG field:

![image](https://user-images.githubusercontent.com/7929556/64726122-f82d8000-d4a3-11e9-877b-75d6f2565cd4.png)

Appears here on D7:
![image](https://user-images.githubusercontent.com/7929556/64726242-34f97700-d4a4-11e9-8cb0-2fa9e513d114.png)

**Comment by duffy-james** [comment]
Here's a small example:

https://www.boston.gov/departments/assessing/how-we-tax-your-property

**Comment by reillyzlab** [comment]
All previously created tables will be responsive. 

No one will be able to create a new responsive table until this is fixed.

**Comment by padora-cob** [comment]
Looks like we just need to add a option to the creditor table plug-in that will add a couple of new classes for us to the <table> tag: ("responsive-table", "responsive-table--horizontal")

`<table border="1" cellpadding="1" cellspacing="1" class="responsive-table responsive-table--horizontal">`

**Comment by padora-cob** [comment]
I think I found the old custom CKEditor plug-in that was on Drupal 7. We maybe able to take most of that code and just include it in the new way that Dupal 8 handles the CKEditor plug-ins. 

https://github.com/CityOfBoston/boston.gov-d7/tree/develop/docroot/sites/all/modules/features/bos_text_formats/plugins/responsive_table

https://www.drupal.org/node/1793710

**Comment by duffy-james** [comment]
@padora-cob @rachelsater this works great. I'll flag here again that we need to revisit the styling for the headers on mobile, but functionally this is great. I actually think we move this to production because it fixes an existing bug related to our headers on mobile and we create a separate ticket for the styling.

**Comment by rsater-storycorps** [comment]
closed because other tickets solved this issue.
