### ISSUE TITLE
Can only edit first item in "status items" list

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#651]
For the homepage status items, I can only edit the first alert in the list by clicking the pencil icon at the top right:
![image](https://user-images.githubusercontent.com/7929556/65345262-d28d2e80-dba7-11e9-8f9d-0fafdc68ede7.png)

If I try to edit the other two alerts for trash in the screenshot above by clicking the pencil icon, nothing happens.

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine is this still an issue? thanks!

**Comment by duffy-james** [comment]
@rachelsater looks like this one was resolved at some point. closing out.
