### ISSUE TITLE
Remove inline option from "maps" component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#653]
It's located here:
![image](https://user-images.githubusercontent.com/7929556/65347068-28fc6c00-dbac-11e9-9990-ae2e9b9e627a.png)

Confirmed with @paylakatel -- it's OK to remove. It doesn't do anything.

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine Do you still want to remove the inline option on this page? just checking :)

**Comment by duffy-james** [comment]
@rachelsater yes please, it still doesn't do anything.
