### ISSUE TITLE
Description text for "newsletter" component not styled for blue theme

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#654]
We need to add white for the text below:
![image](https://user-images.githubusercontent.com/7929556/65347728-9b218080-dbad-11e9-984d-830a97926e67.png)

It should look like this:
![image](https://user-images.githubusercontent.com/7929556/65347752-a5dc1580-dbad-11e9-8e96-e811c3721d88.png)

**Comment by reillyzlab** [comment]
Could remove launch blocker if we could commit to ensuring through governance that we wouldn't allow someone to use newsletter component using blue theming until we could resolve. Leaving as blocker for now.

**Comment by reillyzlab** [comment]
Resolved so closing
