### ISSUE TITLE
Call-to-action button not appearing in "photo" component for documents

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#655]
If you choose to add a "document" as a link in the CTA button on a photo component, nothing appears:
![image](https://user-images.githubusercontent.com/7929556/65348606-99f15300-dbaf-11e9-9d13-4ba832dc72d5.png)

It should look like this:
![image](https://user-images.githubusercontent.com/7929556/65348655-b42b3100-dbaf-11e9-8bea-3ac922f6eced.png)

**Comment by andrebtlima** [comment]
Resolved so closing.
