### ISSUE TITLE
/News: Department icon missing

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#656]
On http://bostond8dev.prod.acquia-sites.com/latest-city-boston-news the department icon is missing:

![Screen Shot 2019-09-20 at 4 20 10 PM](https://user-images.githubusercontent.com/20731897/65356513-a92dcc00-dbc2-11e9-88c0-d7dae739ff34.png)

**Comment by reillyzlab** [comment]
Most showing up, but a few still missing.

All icons formatted at the top of each news item and they should be formatted in the middle.

**Comment by andrebtlima** [comment]
Resolved so closing.
