### ISSUE TITLE
Workbench: Inconsistency in component list display

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#657]
In the workbench there is inconsistency in the display of the active component list.

All should look the same.

All should have a small icon with them (and currently do not). Missing icons on:

- Grid of quotes
- Event and Notices

Would also like to review what's fed into the 'teaser text'

![Screen Shot 2019-09-20 at 4 31 01 PM](https://user-images.githubusercontent.com/20731897/65357382-e98e4980-dbc4-11e9-961c-86f70bdd10cd.png)

**Comment by andrebtlima** [comment]
Closing because we are no longer using icons for this view of compenents.
