### ISSUE TITLE
Grid of Card Component Image Issue

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#658]
The image associated with each card is missing "alt" and "title" text, and you can't upload an image from the media library. The media library is something @davidrkupton is working on.

**Comment by reillyzlab** [comment]
@duffy-james can you recheck this one and see if it's still an issue

**Comment by andrebtlima** [comment]
The image associated with each card now has "alt" but no "title" text. Can successfully upload from media library.

**Comment by andrebtlima** [comment]
Resolved so closing.
