### ISSUE TITLE
Workbench - components: Edit all button not working

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#659]
Workbench - components: Edit all button not working

![Screen Shot 2019-09-20 at 4 57 11 PM](https://user-images.githubusercontent.com/20731897/65358525-c9ac5500-dbc7-11e9-9d17-d2d31dd2a83b.png)

**Comment by reillyzlab** [comment]
Want to groom more with @duffy-james

**Comment by andrebtlima** [comment]
Resolved so closing.
