### ISSUE TITLE
Event: Date Not Required

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#663]
Event: Date Not Required and should be.

Start date should be required. 

End date optional.

Want to groom with @duffy-james a little more re: requirements of start and end time.

**Comment by reillyzlab** [comment]
Date still not being required to save and publish. 

Start date and time should be required.

End date and time should remain optional.

**Comment by davidrkupton** [comment]
Appears fixed.  Start date is required, end date/time is optional.

**Comment by reillyzlab** [comment]
Resolved.
