### ISSUE TITLE
Event content type: Remove feature item check box/item

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#673]
![Screen Shot 2019-09-24 at 2 36 25 PM](https://user-images.githubusercontent.com/20731897/65541497-77c34200-dedb-11e9-8b9a-c32a5bf34285.png)

The 'feature' item on events does not do anything. 

Please remove this from the content creator for all permissions levels.

**Comment by andrebtlima** [comment]
Resolved so closing.
