### ISSUE TITLE
"My edits" and "all recent content" display the same information

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#675]
When a user clicks on "my edits" and "all recent content" in the Drupal navbar at the top:
![image](https://user-images.githubusercontent.com/7929556/65612943-2c646e80-df83-11e9-8639-8fb95ae26cf0.png)

It displays the same information. "My edits" should filter on only the pages that the user created, or however we've set it up in D7.

**Comment by andrebtlima** [comment]
Resolved so closing.
