### ISSUE TITLE
Add option to filter by "contact" in the workbench

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#676]
In D7, a user is able to filter by "contact":
![image](https://user-images.githubusercontent.com/7929556/65613232-a4cb2f80-df83-11e9-9718-c22992a801ab.png)

"Contact" is a taxonomy for departments. I'd like to bring that back to allow users to filter by "contact" in D8 as well. It's currently missing:
![image](https://user-images.githubusercontent.com/7929556/65613176-8cf3ab80-df83-11e9-879d-4d84cd93dea1.png)

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine Is this something we still want addressed?

**Comment by duffy-james** [comment]
@padora-cob addressed this in a separate ticket. It's all set now.
