### ISSUE TITLE
Metrolist: Functionality not working

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#678]
Metrolist listings are not populating at all.

http://bostond8stg.prod.acquia-sites.com/lottery-and-resale-opportunities

![Screen Shot 2019-09-25 at 11 46 25 AM](https://user-images.githubusercontent.com/20731897/65617072-1f974900-df8a-11e9-9bb5-a00e8522c09a.png)

**Comment by reillyzlab** [comment]
Someone from DND should verify that the records showing up are accurate prior to go live.

**Comment by jimafisk** [comment]
I was having trouble authorizing to SF locally, then rediscovered this: https://github.com/CityOfBoston/boston.gov-d8/issues/271#issuecomment-493155256

I updated `.lando.yml`:
```yml
appserver:
  overrides:
    ports:
      - 80:80
      - 443:443
```
Then needed to `lando destroy` and `lando start`. That exposes a local url like https://localhost:443 (which hooks into oauth callback https://0.0.0.0/salesforce/oauth_callback on the SF app).

**Comment by jimafisk** [comment]
It appears there is a bug in `simplesamlphp_auth` that causes forms to not be able to be submitted with the following error: `The form has become outdated. Copy any unsaved work in the form below and then reload this page. `

<details>
<summary>Screenshot</summary>

![salesforce_auth_form](https://user-images.githubusercontent.com/5913244/67976542-ab853c00-fbec-11e9-8614-36755bc03aef.png)

</details>

This patch looks promising: https://www.drupal.org/project/simplesamlphp_auth/issues/2837029#comment-12381818

**Comment by jimafisk** [comment]
That patch worked ^ was able to authorize sf app. Then a quick `lando drush cron` populates `metrolist_affordable_housing` records:

![metrolist_records](https://user-images.githubusercontent.com/5913244/67979212-30268900-fbf2-11e9-93ef-c00dc473e4bf.png)

**Comment by jimafisk** [comment]
Local urls:
- https://0.0.0.0/lottery-and-resale-opportunities
- https://0.0.0.0/affordable-properties

All the records are coming across as unpublished and without "Publish to Metrolist" checked. If I manually update these, you can start seeing them in the tables:

![lottery](https://user-images.githubusercontent.com/5913244/67983390-fc039600-fbfa-11e9-8b5f-5fa8ae4da8e2.png)

**Note:** I need to update the table styling.

**Comment by jimafisk** [comment]
Fixed table style:

![style](https://user-images.githubusercontent.com/5913244/67985501-628ab300-fbff-11e9-911f-7dea5129a541.png)

**Comment by jimafisk** [comment]
Helpful command to easily delete all content of a certain type:
- `lando drush en devel_generate`
- `lando drush genc --kill --types=metrolist_affordable_housing 0 0`

Note: I needed to update `drupal/devel`  from "^1.2" to "3.*": `lando drush genc 0 --bundles=metrolist_affordable_housing --kill`

**Comment by jimafisk** [comment]
with drush 9: `lando drush entity:delete node --bundle=metrolist_affordable_housing`

**Comment by jimafisk** [comment]
With the latest `git pull develop` I'm getting the following error: `GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: login.salesforce.com`

<details>
<summary>Full error message</summary>

```
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">GuzzleHttp\Exception\ConnectException</em>: cURL error 6: Could not resolve host: login.salesforce.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in <em class="placeholder">GuzzleHttp\Handler\CurlFactory::createRejection()</em> (line <em class="placeholder">200</em> of <em class="placeholder">/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php</em>). <pre class="backtrace">GuzzleHttp\Handler\CurlFactory::finishError(Object, Object, Object) (Line: 105)
GuzzleHttp\Handler\CurlFactory::finish(Object, Object, Object) (Line: 43)
GuzzleHttp\Handler\CurlHandler-&gt;__invoke(Object, Array) (Line: 28)
GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object, Array) (Line: 51)
GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object, Array) (Line: 66)
GuzzleHttp\PrepareBodyMiddleware-&gt;__invoke(Object, Array) (Line: 29)
GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object, Array) (Line: 70)
GuzzleHttp\RedirectMiddleware-&gt;__invoke(Object, Array) (Line: 59)
GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object, Array) (Line: 67)
GuzzleHttp\HandlerStack-&gt;__invoke(Object, Array) (Line: 277)
GuzzleHttp\Client-&gt;transfer(Object, Array) (Line: 125)
GuzzleHttp\Client-&gt;requestAsync(&#039;post&#039;, Object, Array) (Line: 131)
GuzzleHttp\Client-&gt;request(&#039;post&#039;, &#039;https://login.salesforce.com/services/oauth2/token&#039;, Array) (Line: 89)
GuzzleHttp\Client-&gt;__call(&#039;post&#039;, Array) (Line: 85)
Drupal\salesforce\Controller\SalesforceController-&gt;oauthCallback()
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber-&gt;Drupal\Core\EventSubscriber\{closure}() (Line: 582)
Drupal\Core\Render\Renderer-&gt;executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber-&gt;wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber-&gt;Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache-&gt;pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache-&gt;handle(Object, 1, 1) (Line: 50)
Drupal\ban\BanMiddleware-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel-&gt;handle(Object, 1, 1) (Line: 693)
Drupal\Core\DrupalKernel-&gt;handle(Object) (Line: 19)
</pre>
```

</details>
<details>
<summary>Screenshot</summary>

![sf_error](https://user-images.githubusercontent.com/5913244/68246766-7b241000-ffe7-11e9-91b5-add1d777c62f.png)


</details>

**Comment by jimafisk** [comment]
Added new `data_feed` workflow and released `metrolist_affordable_housing` nodes from `default_workflow` and added to the new workflow. Nodes come through published now:

![workflow](https://user-images.githubusercontent.com/5913244/68503514-08a67080-0231-11ea-8d9a-2c3b7d6072dc.png)

Also updated the form display so moderation state is a select list instead of a plain text field.

**Comment by jimafisk** [comment]
Need to manually fix view display on list component after migration has run. It's currently getting "Master" display but should be "Page - Lottery" instead.

<details>
<summary>See screenshot</summary>

![lottery_wrong_view](https://user-images.githubusercontent.com/5913244/68684500-98506580-0536-11ea-8158-ffc6577eb6fd.png)


</details>

**Comment by jimafisk** [comment]
Was getting AJAX errors when changing the "Has taxonomy term" settings to use "dropdown" and then trying to click on "Exposed form style" settings for BEF.

This patched fixed the issue: https://www.drupal.org/project/better_exposed_filters/issues/3019535#comment-13031058

**Comment by jimafisk** [comment]
If you're running `lando drush cron` and new `metrolist_affordable_housing` records are _not_ being created, it's likely you have orphaned salesforce object mappings left over.

<details>
<summary>See screenshot</summary>

![mappings](https://user-images.githubusercontent.com/5913244/68712473-cbf8b300-0569-11ea-8bc1-6dd64b7b3be4.png)

</details>

You can delete these mappings by running: `lando drush salesforce_mapping:purge-drupal`

<details>
<summary>See screenshot</summary>

![delete_mappings](https://user-images.githubusercontent.com/5913244/68712569-019d9c00-056a-11ea-9f01-6078e47e2610.png)

</details>

**Comment by jimafisk** [comment]
**Note:** You need to run the migration twice to get "active" and "published to metrolist" values.

**Comment by reillyzlab** [comment]
@jimafisk going to write up testing steps that we can send to DND so that they can test for us.

**Comment by jimafisk** [comment]
The testing steps essentially are comparing the D7 tables to the D8 tables for data accuracy:

Lottery and Resale:
- On D7: https://www.boston.gov/metrolist/lottery-and-resale
- On D8: http://d8-stg.boston.gov/lottery-and-resale-opportunities

Affordable Properties:
- On D7: https://www.boston.gov/metrolist/affordable-properties
- On D8: http://d8-stg.boston.gov/affordable-properties

We can also test updating a record in Salesforce on their end, then forcing a cron run in Drupal to make sure the change comes across.

**Comment by reillyzlab** [comment]
Not working on staging or production.

http://d8-stg.boston.gov/lottery-and-resale-opportunities
![Screen Shot 2019-11-15 at 10 54 09 AM](https://user-images.githubusercontent.com/20731897/68956555-502f7e00-0796-11ea-9eb5-3a748150bdca.png)

http://d8-stg.boston.gov/affordable-properties
![Screen Shot 2019-11-15 at 10 54 42 AM](https://user-images.githubusercontent.com/20731897/68956575-5e7d9a00-0796-11ea-8dc3-7c35b721d3b3.png)

**Comment by jimafisk** [comment]
@reillyzlab I connected the Salesforce app on staging, can you retest when you get a chance:
- https://d8-stg.boston.gov/lottery-and-resale-opportunities
- https://d8-stg.boston.gov/affordable-properties

**Comment by andrebtlima** [comment]
Looks like the listings are coming through for both Lottery and Resale Opportunities and Affordable Properties. Not sure if we want to have folks at DND take a look, but going to close tentatively and leave the ticket in retest.

**Comment by reillyzlab** [comment]
Going to have DND test this before 100% calling it good/closed. 

Reilly will email Susanna now.

**Comment by reillyzlab** [comment]
Would like to see this working on production before I send to DND to verify. Only been able to verify this up to staging.

**Comment by jimafisk** [comment]
Should be all set on prod:
- https://content.boston.gov/affordable-properties
- https://content.boston.gov/lottery-and-resale-opportunities

**Comment by reillyzlab** [comment]
Reilly sent to DND to test on 11/19. Won't close until they verify.

**Comment by reillyzlab** [comment]
Sent a reminder re: testing to Susanna on 11/22, but didn't hear back prior to launch.

Seems to be working on prod.
