### ISSUE TITLE
"Grid of quotes" component image upload should mirror other components

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#679]
Users are forced to add media, and then find that image in a search box:

![image](https://user-images.githubusercontent.com/7929556/65620041-2b393e80-df8f-11e9-8794-3f8a5b834596.png)

Could we just use the functionality that we've used in other components for image uploading for this component as well?

**Comment by duffy-james** [comment]
The component also doesn't appear to display the image:

![image](https://user-images.githubusercontent.com/7929556/65621014-ea422980-df90-11e9-9b46-05de748f9765.png)

**Comment by duffy-james** [comment]
@rachelsater folks do typically add a photo for these quotes when they get used. There's a default "quote" icon now if there is no image, but we should give people the option to add a headshot if they want. Right now, there's no option to upload.

**Comment by rachelsater** [comment]
@duffy-james So the request of this ticket is to add an option to upload an image in the grid of quotes component? just making sure I'm getting the requirement right :)

**Comment by duffy-james** [comment]
@rachelsater yea -- you used to be able to upload an image for a small headshot (or some other photo). Currently, you have to pull from our existing photos, and that's a bit clunky / confusing. I think this bug was introduced when we moved to D8.

**Comment by rsater-storycorps** [comment]
sounds good! just checking. thanks!

**Comment by duffy-james** [comment]
Closing this ticket out; now accounted for in Jira.
