### ISSUE TITLE
Icon bleeding into exterior circle on "emergency alerts" component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#680]
You can see the icon here:

![image](https://user-images.githubusercontent.com/7929556/65624134-3a23ef00-df97-11e9-9154-0d61137c753e.png)

It just looked a bit off.

**Comment by reillyzlab** [comment]
@davidrkupton this seems to say 'merged' but looks to be an issue on production. Any ideas?

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine is this an issue still?

**Comment by duffy-james** [comment]
@rachelsater yea, the icon is still off. [Live example here](https://www.boston.gov/departments/emergency-management).

**Comment by rachelsater** [comment]
@duffy-james thanks! Assigning to @padora-cob
