### ISSUE TITLE
Change dropdown in "news and announcements" component to "recently published"

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#682]
For the drop down list here:
![image](https://user-images.githubusercontent.com/7929556/65628673-ef5aa500-df9f-11e9-8c47-83e3a0e9afd6.png)

Instead of "upcoming," can we change that to "Recently published"? "Upcoming" only makes sense in context with the "events and notices" component.

**Comment by rachelsater** [comment]
No longer an issue so I'm closing this ticket
