### ISSUE TITLE
"Featured event" issues with "events and notices" component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#684]
The blue button link to the "featured" event doesn't go to the event. Also, the call-to-action button at the bottom doesn't work when you choose the "document" option:

![image](https://user-images.githubusercontent.com/7929556/65631355-60508b80-dfa5-11e9-89b9-fcf28420c454.png)

As you can see in the screenshot, we're also missing the date in the top left side of the "featured" event.

**Comment by andrebtlima** [comment]
Resolved so closing.
