### ISSUE TITLE
Can't edit call-to-action button in "news" and "events" components

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#685]
After adding a CTA button and saving, I can't then go back into the component and edit or remove the link. When I try to add an "external" link instead of an "internal" link, or vice versa, it just keeps reverting back to the original link. Sometimes, it displays the "drawers" component on the page.

Here's a video to explain what I'm talking about:

https://drive.google.com/file/d/1sZX4vPXcapSUX8O-z3unjgeG9sVPz266/view

As part of this, the "document" option in the "events" component doesn't display properly:

![image](https://user-images.githubusercontent.com/7929556/65632516-deae2d00-dfa7-11e9-8496-f1d649aaca62.png)

We don't have a "document" option in the "news" component. So, for consistency, we should either add the "document" option to the "news" component, or remove it from the "events" component.

**Comment by davidrkupton** [comment]
The add/remove is resolved now as a result of previous activities..
I have added "document" link option to the new & announcements component .

**Comment by andrebtlima** [comment]
Resolved so closing.
