### ISSUE TITLE
Issues with removing components 

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#686]
This one is a little confusing to explain, but essentially you can only remove the component at the bottom of the components section. If you try to jump up and remove a component higher on the page, it doesn't work. Here's a video to help explain:

https://drive.google.com/file/d/1A-533fxX6tyEfwQeB_IATaqAyvKRgVt8/view

**Comment by andrebtlima** [comment]
Tested this problem in a couple of different scenarios, depending on the how many total components have been added.

With one component added, no problems removing said component. 

With two components added, trying to remove the first component, nothing happens until you either collapse or remove the second component. In this scenario, removing the second component does not result in both components being removed, only one component is removed. 

With three components added, trying to remove the middle component, nothing happens until you remove or collapse the first or third component. In both cases, collapsing first or third component removes last two components, leaving only the first 

With four or more components added, when trying to remove any middle components (i.e. not first or last) results are similar. Removing a middle component does not work initially, but subsequently collapsing or removing any _other_ component results in all components except first being removed. 

Haven't tested this across all component types.

**Comment by andrebtlima** [comment]
Resolved so closing.
