### ISSUE TITLE
Remove "search..." from title in "event" content type

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#687]
The word search is appearing here in all title fields:

![image](https://user-images.githubusercontent.com/7929556/65633574-6dbc4480-dfaa-11e9-9fed-0d684360dd66.png)

The title field should just be blank. You can't really search for anything or any nodes. Plain text entry field operationally.

**Comment by duffy-james** [comment]
This isn't just the events. Includes these content types as well:

- Articles
- Change
- Department profiles
- Emergency alerts
- Guides
- How-tos
- Landing pages
- Listing pages
- Metrolist Affordable Housing items
- Person profiles
- Place profiles
- Posts
- Procurement Advertisements
- Program Initiative profiles
- Public notices
- Script pages
- Status items
- Tabbed content
- Transactions

Only content type not included is site alerts. For these, the title is blank with no placeholder.

**Comment by padora-cob** [comment]
It seems that we have a template override that was affecting all of the content types that have a title field. Not sure why that placeholder attribute was hardcoded into the template but I have removed it for now. If we see a title field that needs the placeholder of "Search..." then I can add it programmatically to be selective in the pre-processor.

**Comment by rachelsater** [comment]
@padora-cob "Search" is gone from every content type so this is good to move to the next step
