### ISSUE TITLE
Change "description" to "intro text" in "event" content type; remove summary

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#688]
Please update the text below to say "intro text" instead of "description." I think we can also remove the summary, since it's not doing anything on the site. It's a little confusing having that and the body.

![image](https://user-images.githubusercontent.com/7929556/65633864-094db500-dfab-11e9-9953-f6e2a2df8b5b.png)

**Comment by andrebtlima** [comment]
Resolved so closing.
