### ISSUE TITLE
Explore changes to link fields

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#691]
Potentially combine external and link fields into one.

If we keep them separate, then should we add http:// or https:// as default to the external field so that people don't have to remember to do that?

**Comment by rachelsater** [comment]
@padora-cob Do we need this ticket? I was thinking about de-coupling it from #1357 and then closing it

**Comment by padora-cob** [comment]
We could keep it open but it would be a big lift and not a lot of benefits, just my opinion. 

Kind of changing the "default" way that those features work, can be done but not sure if we should?
