### ISSUE TITLE
Pixalated images on page: PLACES TO STAY COOL IN HOT WEATHER

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#695]
Pixalated images on page: PLACES TO STAY COOL IN HOT WEATHER in the BCYF COOLING CENTERS component/grid

http://bostond8dev.prod.acquia-sites.com/health-and-human-services/places-stay-cool-hot-weather

![Screen Shot 2019-09-26 at 11 49 00 AM](https://user-images.githubusercontent.com/20731897/65703956-a8c68280-e053-11e9-93e9-b312031a4a25.png)

**Comment by reillyzlab** [comment]
Flagging in case larger image issue.

**Comment by davidrkupton** [comment]
Rolled into #809.
