### ISSUE TITLE
Page metadata: Published and updated dates

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#698]
There are currently different ways that the published and updated dates on page metadata works on all of the content types. This should be updated on all of the content types to operate the following way:

- [ ] Content authors should not be able to see or alter any page metadata, including published and updated dates.

For all/regardless of role:
- [x] The published date should default to current time. 

- [x] If possible, the published and updated dates shouldn't go down to the second.

- [x] The updated time should automatically update with the current time when it goes from draft straight to published or from needs review to published. 
One except here: Site administrators should be the user allowed to ever changed the published date of public notices

**Comment by davidrkupton** [comment]
Link #779.

**Comment by reillyzlab** [comment]
If this works on one content type, then it should work globally across the site.

**Comment by reillyzlab** [comment]
Still an issue

**Comment by reillyzlab** [comment]
Related to #799

**Comment by reillyzlab** [comment]
Related to #922

**Comment by reillyzlab** [comment]
Not resolved.

**Comment by andrebtlima** [comment]
Not resolved.

**Comment by davidrkupton** [comment]
I have updated the permissions for content_editor for posts, and have changed the notes on the posts edit form. I also disabled the required flag for the updated field on posts.

**Comment by andrebtlima** [comment]
Resolved so closing
