### ISSUE TITLE
If "contact" field is empty on an article page, no text should appear in sidebar

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#699]
If a user doesn't add a "contact" to the basic information section on an article page:

![image](https://user-images.githubusercontent.com/7929556/65716957-28f9e180-e06e-11e9-9386-e0a302170854.png)

The text for "have questions?" still appears:

![image](https://user-images.githubusercontent.com/7929556/65716915-11225d80-e06e-11e9-9ad7-9ec2f9da152f.png)

Instead of this, the sidebar section should be blank.

**Comment by andrebtlima** [comment]
Resolved so closing
