### ISSUE TITLE
seamless_doc

### ISSUE THREAD

**Issue by kdonaldson** [CityOfBoston/boston.gov-d8#70]

**Comment by jimafisk** [comment]
Examples:
- https://www.boston.gov/additional-dwelling-unit-pilot-program-preliminary-application
- https://www.boston.gov/mayors-event-request-form

Note the both use the `script_page` content type which uses `field_embed_list` to reference the `seamless_doc` paragraph type.

**Comment by jimafisk** [comment]
IDs for above forms for testing:
- Mayor's Event Request form: 25298fbb61b5db0f46e747785ae30f1c
- Additional Dwelling Unit pilot program preliminary application: lkfsf0lzwj1
