### ISSUE TITLE
Photo component: inconsistency with images coming through

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#700]
Photo component: inconsistency with images coming through

On this page: http://bostond8dev.prod.acquia-sites.com/career-center one of the photos is coming through and one is not.

The photo that is working is a jpg and the photo that isn't working is a png.

**Comment by reillyzlab** [comment]
Photo on ice skating here not coming through to D8. When you look at editing interface no current photo appears.

http://bostond8dev.prod.acquia-sites.com/boston-outdoors

**Comment by andrebtlima** [comment]
Boston Outdoors page still experiencing this issue.

**Comment by andrebtlima** [comment]
Resolved so closing.
