### ISSUE TITLE
Allow content authors to edit pages in "needs review"

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#706]
If a content author sends a page to "needs review", they should still have the "edit content" option in their tasks. Right now, once a page is sent to "needs review," they can't do anything with the page (there's also no pencil icon):

![image](https://user-images.githubusercontent.com/7929556/65782221-33be8000-e11b-11e9-874f-aaaba8ac302c.png)

**Comment by andrebtlima** [comment]
Will test with content editor permissions once dev is running again.

**Comment by andrebtlima** [comment]
no problems jumping back in as content editor.

**Comment by reillyzlab** [comment]
Content authors not being allowed to edit items in needs review.
