### ISSUE TITLE
Remove "department type" option on "department profile" pages

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#707]
The "department type" option is located under "contact information":

![image](https://user-images.githubusercontent.com/7929556/65784420-fb6d7080-e11f-11e9-8e9e-cc22f040a619.png)

Can we remove this? We don't have cabinet pages. I'm pretty sure this section doesn't do anything.

**Comment by reillyzlab** [comment]
I seem to remember this was being used to populate/filter something around departments and cabinets. 

@jimafisk or @davidrkupton can you remind us if this is doing anything?

**Comment by duffy-james** [comment]
@padora-cob I'm so sorry, I wish I had seen this. I think we need to keep it as is.

When I first created this ticket, we had no cabinet profile pages on the site. Since then, two have been built:

https://www.boston.gov/government/cabinets/equity-and-inclusion-cabinet
https://www.boston.gov/government/cabinets/health-and-human-services

I'm not sure what the future will be, but I could see us needing to make more cabinet pages in the future. The only reason these exist is because they're offering programs for folks that don't go through one of the departments they oversee.

**Comment by padora-cob** [comment]
Note: Do not merge branch "feature/#707".
