### ISSUE TITLE
"Description" field for "newsletter signup" should not be required

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#708]
The "description" field for both the regular component and sidebar component for "newsletter signup" is currently required. Please make it optional for both components.

![image](https://user-images.githubusercontent.com/7929556/65785026-6ec3b200-e121-11e9-8fc0-a3cee24c11ae.png)

**Comment by rachelsater** [comment]
@Micah-Levine I don't see a newsletter module. if you can, can you please see if Description is still required?

**Comment by Micah-Levine** [comment]
> @Micah-Levine I don't see a newsletter module. if you can, can you please see if Description is still required?

It's titled as newsletter signup and it looks like the description is still required

**Comment by duffy-james** [comment]
looks good @padora-cob

**Comment by rachelsater** [comment]
@padora-cob should I move this ticket into "Ready for Production or nah?

**Comment by padora-cob** [comment]
@rachelsater, sure! I just did it for this one but feel free to generally move the ticket to "Ready for Production" whenever you or the stakeholder approves it.

**Comment by rachelsater** [comment]
@padora-cob is this one good to close?

**Comment by padora-cob** [comment]
Yep, should be good to go!

**Comment by rachelsater** [comment]
thanks!
