### ISSUE TITLE
Change word 'bundle' in image upload

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#709]
Change word 'bundle' in image upload to say 'type of media'

![Screen Shot 2019-09-27 at 12 55 20 PM](https://user-images.githubusercontent.com/20731897/65787188-5dc96f80-e126-11e9-9e8b-d2ffdcf0a5cf.png)

**Comment by andrebtlima** [comment]
Resolved so closing.
