### ISSUE TITLE
Need to add "needs review" section for site admins and content editors

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#713]
The "needs review" section where all pages in "needs review" can be seen appears to be missing. In D7, it appears here:

![image](https://user-images.githubusercontent.com/7929556/65790197-185c7080-e12d-11e9-99c3-0723d67f8012.png)

It would be great to add it here:

![image](https://user-images.githubusercontent.com/7929556/65790227-3033f480-e12d-11e9-864f-c9e734ca6e96.png)

**Comment by andrebtlima** [comment]
Resolved so closing. 

<img width="1431" alt="Screen Shot 2019-11-18 at 10 46 28 AM" src="https://user-images.githubusercontent.com/57111927/69067245-be6f7d00-09f0-11ea-846d-ba930573e810.png">
