### ISSUE TITLE
Add help text to "event types" section in events

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#714]
Right now, to select multiple event types, you have to hold CTRL and click. We need to add instructions on how that's done below that field:

![image](https://user-images.githubusercontent.com/7929556/65790729-43938f80-e12e-11e9-997d-0881073b7251.png)

**Comment by rachelsater** [comment]
Please add a tool tip or hover with the following copy "Hold CTRL and click (PC) or press and hold the Command key (Mac) to select more than one event type."

**Comment by duffy-james** [comment]
looks good @padora-cob — great idea switching these to checkboxes

**Comment by rachelsater** [comment]
@padora-cob is this ticket ready to be closed? thanks!

**Comment by padora-cob** [comment]
Ready to close, thanks!

**Comment by rachelsater** [comment]
thank you!
