### ISSUE TITLE
Article: Contact should not be at the top of the workbench

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#716]
Article: Contact should not be at the top of the workbench.

Should be at the bottom of the first page.

![Screen Shot 2019-09-27 at 3 34 19 PM](https://user-images.githubusercontent.com/20731897/65797161-852b3700-e13c-11e9-8be2-76bb09029899.png)

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine Would you rather the Contact field at the bottom of the page or is it ok where it's currently located (top of the page)

**Comment by duffy-james** [comment]
@rachelsater not a big deal, but moving it down would keep it consistent with "posts" and "program/initiative" content types. Both of those have the "contact" below the "body".

**Comment by rachelsater** [comment]
@padora-cob whatcha think?
