### ISSUE TITLE
Department profile contact: small style bug - extra spacing

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#717]
Department profile contact: small style bug - extra spacing between city and state

Remove space

![Screen Shot 2019-09-27 at 3 42 57 PM](https://user-images.githubusercontent.com/20731897/65797610-a93b4800-e13d-11e9-85ac-339aa069b015.png)

**Comment by andrebtlima** [comment]
In addition to fixing the style bug, we removed the country from the address, which is redundant and not in the patterns guide.
