### ISSUE TITLE
Can't cancel an event 

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#718]
The event cancellation option doesn't appear to work:

![image](https://user-images.githubusercontent.com/7929556/65799836-130a2080-e143-11e9-9001-e2a3292a8411.png)

Nothing displays here:

![image](https://user-images.githubusercontent.com/7929556/65799903-3339df80-e143-11e9-846e-c9d4ab2496e5.png)

**Comment by andrebtlima** [comment]
Tested this on staging and it's working. Closing but will take a look on production once the fix is pushed to make sure.

**Comment by andrebtlima** [comment]
<img width="1427" alt="Screen Shot 2020-01-02 at 4 19 23 PM" src="https://user-images.githubusercontent.com/57111927/71694036-fa318c80-2d7b-11ea-979e-2ee2f1591a8f.png">
