### ISSUE TITLE
Table Styling Incorrect

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#719]
Table styling is not working. 

D8:
![Screen Shot 2019-09-27 at 3 50 57 PM](https://user-images.githubusercontent.com/20731897/65801719-c2e18d00-e147-11e9-98be-fad1da05750f.png)

D7:
![Screen Shot 2019-09-27 at 4 58 20 PM](https://user-images.githubusercontent.com/20731897/65801825-076d2880-e148-11e9-852b-5e6e6bd8131a.png)

**Comment by reillyzlab** [comment]
Potentially fix/implement this alongside this ticket: https://github.com/CityOfBoston/boston.gov-d8/issues/323

**Comment by reillyzlab** [comment]
@sebastianebarb to advise on what the header styling with link should be

**Comment by davidrkupton** [comment]
Is this metrolist?? from salesforce ??

**Comment by reillyzlab** [comment]
This was just attempting to add any table to any page.

**Comment by sebastianebarb** [comment]
the Link should be #288BE4 when on #091F2F

**Comment by reillyzlab** [comment]
Tables were migrated okay from Drupal 7 to 8. Last time this ticket was reviewed no new tables would be styled accurately. Should retest to determine the state of this.

**Comment by padora-cob** [comment]
I believe this ticket is covered by https://github.com/CityOfBoston/boston.gov-d8/issues/646 and can be closed. 
See for working example: (https://www.boston.gov/news/awardees-vaccine-equity-grant-initiative-announced)

Updates to the table styles are being worked on under https://github.com/CityOfBoston/boston.gov-d8/issues/1084.

**Comment by duffy-james** [comment]
@padora-cob you are correct — this has been fixed, we're working on potential enhancements now.
