### ISSUE TITLE
Mobile: transaction grid not populating icons

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#730]
Found on Safari, iPhone 6s

Icons associated with the transaction grid component aren't loading on mobile (screengrabs from Boston.gov homepage and Guide to Summer in Boston):

![IMG-5798](https://user-images.githubusercontent.com/28716225/66078250-a9698800-e52f-11e9-8be1-ec7930423b0e.PNG)
![IMG-5799](https://user-images.githubusercontent.com/28716225/66078260-ad95a580-e52f-11e9-8563-355f11c029d6.PNG)

**Comment by reillyzlab** [comment]
Not sure on the similar breakpoint when you shrink screen on desktop as well.

**Comment by reillyzlab** [comment]
Flagging as launch blocker in case a larger image issue, but would be willing to make this a non-launch blocker if it's not a larger image issue.

**Comment by duffy-james** [comment]
resolved, closing
