### ISSUE TITLE
Latest news component - no photos showing up

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#731]
Found on Safari, iPhone 6sI

Images not populating, and looks like "featured" news item has super broken up test (images from Digital Team page). Featured news item also repeated right underneath

![IMG-5803](https://user-images.githubusercontent.com/28716225/66079688-8f7d7480-e532-11e9-96ad-8e3d06e9b913.PNG)
![IMG-5805](https://user-images.githubusercontent.com/28716225/66079693-91473800-e532-11e9-9e67-4c0b0df9cd72.PNG)
![IMG-5804](https://user-images.githubusercontent.com/28716225/66079696-92786500-e532-11e9-8a9d-1a2e69678368.PNG)

**Comment by reillyzlab** [comment]
Happening on desktop too -- no images are showing up on news component

**Comment by andrebtlima** [comment]
Resolved so closing.
