### ISSUE TITLE
Mobile: grid of cards not populating images

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#733]
Found on Safari, iPhone 6s

Grid of cards not populating images, screengrabs from Boston.gov/digital and Guide to Summer in Boston

![IMG-5800](https://user-images.githubusercontent.com/28716225/66080248-b5574900-e533-11e9-8aeb-5b5d84f382e1.PNG)
![IMG-5806](https://user-images.githubusercontent.com/28716225/66080252-b5efdf80-e533-11e9-9b11-6d5b6eaf4d34.PNG)
![IMG-5807](https://user-images.githubusercontent.com/28716225/66080255-b7b9a300-e533-11e9-8e89-73d2db771756.PNG)

**Comment by reillyzlab** [comment]
Seems to be resolved so closing.

**Comment by andrebtlima** [comment]
Resolved so closing.
