### ISSUE TITLE
Mobile: page navigation bar in footer goes to second line

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#735]
Found on Safari, iPhone 6s

Also not a huge deal, but it looks like the page navigation bar in the footer breaks into a second line when on any page but the first. Screenshot taken from Boston.gov/news

![IMG-5811](https://user-images.githubusercontent.com/28716225/66081786-c3f32f80-e536-11e9-8eb9-755140ab84e5.PNG)
![IMG-5812](https://user-images.githubusercontent.com/28716225/66081787-c5245c80-e536-11e9-972d-0f0ab812b96c.PNG)

**Comment by reillyzlab** [comment]
Seems to be resolved.
