### ISSUE TITLE
Miscellaneous Pages Not Working

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#738]
Career Center Page Note Working

http://bostond8dev.prod.acquia-sites.com/career-center

![Screen Shot 2019-10-03 at 4 27 26 PM](https://user-images.githubusercontent.com/20731897/66161620-b7380f80-e5fa-11e9-80e6-1ba6608b7c1f.png)

**Comment by reillyzlab** [comment]
Another: http://bostond8dev.prod.acquia-sites.com/departments/animal-care-and-control

with same error message

**Comment by davidrkupton** [comment]
The card image component needs to be changed to a media type.

**Comment by reillyzlab** [comment]
Retest on 10/10/19

**Comment by andrebtlima** [comment]
Career Center page working now, but Animal Care and Control page still not working.
