### ISSUE TITLE
Newsletter signup: Center description text 

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#743]
On newsletter signup, the description text should be centered.

It is currently positioned towards the bottom of the boxes.

![Screen Shot 2019-09-27 at 3 37 14 PM](https://user-images.githubusercontent.com/20731897/66237091-32b0c400-e6c2-11e9-99d5-66cbc2d8d856.png)

**Comment by andrebtlima** [comment]
Resolved so closing.
