### ISSUE TITLE
status_override

### ISSUE THREAD

**Issue by kdonaldson** [CityOfBoston/boston.gov-d8#75]
depends on:
-  Message for the Day (https://github.com/CityOfBoston/boston.gov-d8/issues/61)
-  Status Item

**Comment by zweishar** [comment]
None of these currently exist on the system, so I think we should not migrate this. I'll dig into this a bit to see what it's meant to do.

**Comment by zweishar** [comment]
From what I can tell, this is meant to allow an emergency alert to take the place of a status item. We're considering refactoring how status items work already, plus this is not used, so I think it's safe to ignore this for now.
