### ISSUE TITLE
Towed Cars license plate entry broken

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/boston.gov-d8#754]
Screengrab/videos (insert file names here)
Towed Cars license plate entry broken.png

Link
http://bostond8stg.prod.acquia-sites.com/winter-boston

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Winter in Boston > Towed Cars > Your License Plate

Brief Description
The Drupal 7 version of the “Towed Cars” section of the Winter in Boston page includes a license plate lookup feature; the Drupal 8 version of that feature appears as broken HTML and lacks functionality.
 Steps to reproduce
1.	Go to Winter in Boston page on both Drupal 7 and 8 sites
2.	Scroll down to “Towed Cars” section
3.	Compare the two sites’ versions of “Your License Plate”

Desired Result
The two are near-identical in form and function.

Actual Result
Only the D7 version appears and functions as desired.

![Towed Cars license plate entry broken](https://user-images.githubusercontent.com/49662945/64807032-5ae55100-d562-11e9-8e8a-63cd45ede1f8.png)

**Comment by davidrkupton** [comment]
Done

**Comment by andrebtlima** [comment]
Resolved so closing
