### ISSUE TITLE
Winter in Boston- Heating Resources broken link

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/boston.gov-d8#755]
Screengrab/videos (insert file names here)
Winter in Boston- Heating Resources broken link.mp4

Link
http://bostond8stg.prod.acquia-sites.com/winter-boston

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Mac Desktop > OS 12.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Winter in Boston > Help Paying For Fuel > Various

Brief Description
The Drupal 7 version of the “Help Paying For Fuel” section of the Winter in Boston page features a link in a blue box labeled “Heating Resources.” On the Drupal 8 version, this box is truncated and textless, and contains no link at all.
This is similar to bug CityOfBoston/Iterators#83 (Winter in Boston broken links); it has been reported separately because the link is not broken (404) but inert.

 Steps to reproduce
1.	Go to Winter in Boston page on both Drupal 7 and 8 sites
2.	Scroll down to “Help Paying For Fuel” section
3.	On D7 site, click on Heating Resources link (link is fully functional)
4.	On D8 site, attempt to do the same

Desired Result
Link is present and properly labeled.

Actual Result
The area where the link should be is visible, but it is neither labeled nor functional.

[Winter in Boston- Heating Resources broken link.zip](https://github.com/CityOfBoston/Iterators/files/3606701/Winter.in.Boston-.Heating.Resources.broken.link.zip)

**Comment by davidrkupton** [comment]
This presently looks OK, but it has a title of ABCD, which I think I added manually to d8 in this migration.  Need to check again after next migration to confirm the right title text shows.

**Comment by davidrkupton** [comment]
The title is ABCD !

**Comment by reillyzlab** [comment]
This is resolved so I'm closing.
