### ISSUE TITLE
The Trash Day Video has the wrong image (all blue) on the Drupal 8 page

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/boston.gov-d8#756]
Screengrab/videos (insert file names here)
2019 09 13, Watch - Trash Day in the City has wrong image on Drupal 8 page.mp4
[2019 09 13, Watch - Trash Day in the City has wrong image on Drupal 8 page.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3610549/2019.09.13.Watch.-.Trash.Day.in.the.City.has.wrong.image.on.Drupal.8.page.MP4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/trash-and-recycling-guide

Dupral 7 Link:
•	https://www.boston.gov/trash-and-recycling-guide

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > Windows 10 (1903) > Chrome 77

Section
(Page > Area > Element)
Trash and Recycling Guide > Trash Day Video > Image

Brief Description
The Trash Day Video has the wrong image (all blue) on the Drupal 8 page

Steps to reproduce
1. Go to the Rash and Recycling Guide page for Drupal 7 and Drupal 8
2. Go to the Trash Day Video 

Desired Result
•	Both sections have the proper image for the video

Actual Result
•	The Trash Day video for the Drupal 8 page has the wrong image (all blue)

**Comment by davidrkupton** [comment]
This video image is now present.
The intro image is however missing.  I believe this is due to duplicate image issue being resolved now.

**Comment by reillyzlab** [comment]
Resolved so closing.
