### ISSUE TITLE
Side Menu can move sideways on iPhone without moving the X button with it

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/boston.gov-d8#757]
Screengrab/videos (insert file names here)
2019 08 21, Side Menu can move sideways on iPhone without moving the X button with it.mp4
[2019 08 21, Side Menu can move sideways on iPhone without moving the X button with it.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3525908/2019.08.21.Side.Menu.can.move.sideways.on.iPhone.without.moving.the.X.button.with.it.MP4.zip)

Link and Node #
Side Menu

Type of User:  Anonymous
 
Environment
(Device > OS > Browser)
Phone > iOS 12.4 > Safari

Section
(Page > Area > Element)
Side Menu > Movement > X button

Brief Description
The Side menu can be moved from side to side on the iPhone and the X button does not move with it. This can be done on other devices like tablets or Android phones, but the X button moves with the Side Menu (though it does not close the Side Menu)
 Steps to reproduce
1. Open the Dupral 8 page
2. Open the Side Menu
3. Move the page to the left to hide the Side Menu without closing it

Desired Result
1.	The Side Menu cannot be moved to the left without closing it
2.	If it were possible to move the Side Menu without closing it, the X button would move with the Side Menu

Actual Result
1.	The Side Menu is able to be moved to the left without closing it on mobile devices (Tablets, and phones)
2.	On the iPhone, the Side Menu is able to be moved to the left and the X button is not moving with it
a.	There is a bug that I am unable to reproduce currently when the X button was able to move to the left with the Side Menu on the iPhone, which caused the Side Menu button to become invisible and be unable to be clicked, even after refreshing the page. I had to click on the URL field and press to go to the page again for the Side Menu button to be visible again

**Comment by rachelsater** [comment]
@duffy-james is this still an issue?

**Comment by padora-cob** [comment]
It is working as expected and looks good on my iPhone 7 and my iPad.

**Comment by rachelsater** [comment]
me too so I'll close this ticket
