### ISSUE TITLE
Images become blue on Resilient Boston Harbor page at a certain width

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/boston.gov-d8#759]
Screengrab/videos (insert file names here)
2019 08 20, Images become blue on Other page at a certain width
[2019 08 20, Images become blue on Other page at a certain width.MP4.zip](https://github.com/CityOfBoston/Iterators/files/3521756/2019.08.20.Images.become.blue.on.Other.page.at.a.certain.width.MP4.zip)
.mp4

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/departments/environment/resilient-boston-harbor 

Dupral 7 Link:
•	https://www.boston.gov/departments/environment/resilient-boston-harbor 

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > Windows 10 (1903) > Internet Explorer 11.356.18362

Section (Page > Area > Element)
Resilient Boston Harbor page > Links > Images for Links

Brief Description
On the Resilient Boston Harbor page the Images for most of the links on the page are blue

Steps to reproduce
1. Open the Dupral 8 and Dupral 7 pages for Resilient Boston Harbor
2. Check out the links with the images on the page

Desired Result
•	The images are not blue on the Drupal 8 page

Actual Result
•	The images are blue on the Drupal 8 page

**Comment by davidrkupton** [comment]
Cannot replicate this issue.  Must have been resolved.
However the featured event is missing an image.  Believe this is related to the duplicate images issue being resolved.

**Comment by reillyzlab** [comment]
Resolved for closing
