### ISSUE TITLE
Assessing, Guide to application dates broken links

### ISSUE THREAD

**Issue by taylor-iterators** [CityOfBoston/boston.gov-d8#760]
Screengrab/videos (insert file names here)
2019 08 21 Assessing, Guide to application dates broken links.mp4

Link
http://bostond8stg.prod.acquia-sites.com/assessing/how-file-personal-property-tax-abatement
http://bostond8stg.prod.acquia-sites.com/node/12806

Type of User:  Anonymous
 Environment
(Device > OS > Browser)
Windows Laptop > Windows 10 (1903) > Chrome 76

Section
(Page > Area > Element)
How to file for a personal property tax abatement > Body > Various links

Brief Description
The property tax abatement page features two links, “Guide to Application Dates” and “Assessing.” Clicking on the former prompts the site’s usual “Looks like the page went overboard” failure page; clicking on the latter prompts a different failure page in lower-level language.
 Steps to reproduce
1.	Go to the “How to file for a personal property tax abatement” page
2.	Scroll down to links
3.	Click on “Guide to Application Dates” (0:03 in video)
4.	Return to How to file…
5.	Click on “Assessing” (0:08)

Desired Result
Both links lead to the desired, fully-functional pages.

Actual Result Links both lead to different failure pages.

[2019 08 21 Assessing, Guide to application dates broken links.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3526541/2019.08.21.Assessing.Guide.to.application.dates.broken.links.mp4.zip)

**Comment by andrebtlima** [comment]
Resolved so closing
