### ISSUE TITLE
404 Errors

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/boston.gov-d8#761]
Screengrab/videos (insert file names here)
client_error_(4xx)_inlinks.xlsx

Link and Node #
www.boston.gov

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Does not apply

Brief Description
An automated tool was used to check for 404 errors on the main boston.gov website (Drupal7)

Steps to reproduce
1.  See the attached spreadsheet
2.  Go to the Source Link, and look for the “Anchor” text listed in the spreadsheet.
3.  Click on this link and obtain a 404 error.  Note:  you can also go to the Destination URL in the spreadsheet to go directly to the 404 error.

Desired Result
No 404 errors

Actual Result
404 errors are observed.
[client_error_(4xx)_inlinks.xlsx](https://github.com/CityOfBoston/Iterators/files/3590588/client_error_.4xx._inlinks.xlsx)

**Comment by reillyzlab** [comment]
Closing because we're going to retest this with siteimprove.
