### ISSUE TITLE
3 column with image mobile styling issue

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#770]
On tablet and mobile, 3 column with image has a styling issue.

When you shrink the page, the content is becomes center aligned, but should stay left aligned.

Currently happening on Drupal 7, so not a launch blocker.

![3 column with image styling bug](https://user-images.githubusercontent.com/20731897/66846018-225cdc80-ef3f-11e9-9919-f0e335777b25.PNG)

**Comment by rachelsater** [comment]
@Micah-Levine this looks fixed to me. what do you think?

**Comment by Micah-Levine** [comment]
> @Micah-Levine this looks fixed to me. what do you think?

Looks fixed to me as well!

**Comment by rachelsater** [comment]
@Micah-Levine thank you!
