### ISSUE TITLE
Map Styling Issue on Tablet/Mobile

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#772]
Map Styling Issue on Tablet/Mobile

Marking as blocker since it doesn't align one-to-one from Drupal 7 to Drupal 8, but would be open to negotiate resolving this post-launch.

Viewing on boston.gov/winter-boston:

Drupal 8:
Android:
![maps component fomatting on mobile - android](https://user-images.githubusercontent.com/20731897/66848861-d06a8580-ef43-11e9-80ad-272d3d8899cd.PNG)

Iphone:
![maps component fomatting on mobile - iphone](https://user-images.githubusercontent.com/20731897/66848882-d95b5700-ef43-11e9-90d7-769ccab2ed80.PNG)

Drupal 7 mobile:
![Screen Shot 2019-10-15 at 12 11 31 PM](https://user-images.githubusercontent.com/20731897/66849492-f5abc380-ef44-11e9-8418-1dc29bfb2e0b.png)

**Comment by davidrkupton** [comment]
This fixed it for me, and seems to work on pc's too.

![image](https://user-images.githubusercontent.com/4700050/96935949-277a3300-1493-11eb-961b-fabc5cbf6b52.png)

**Comment by subaha-cob** [comment]
I think this is all set. This ticket should be closed @rachelsater. Please test before closing.

**Comment by rachelsater** [comment]
@subaha-cob Screenshot from my windows 10 machine using chrome (iphone)

![image](https://user-images.githubusercontent.com/72876352/109720375-fe238f00-7b77-11eb-8a7e-f23d5fcca583.png)

**Comment by rachelsater** [comment]
closing this ticket as it looks good on live and staging
