### ISSUE TITLE
Guide landing page styling fix - top spacing on Microsoft Edge

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#773]
On the Guide landing page (http://bostond8dev.prod.acquia-sites.com/guides) the top spacing/padding on Microsoft Edge is far larger than it should be. 

This is currently an issue in Drupal 7, so not a launch blocker.

Chrome:
![image](https://user-images.githubusercontent.com/20731897/66948259-5957ee80-f022-11e9-890b-fd9152ca5e8d.png)

Microsoft Edge:
![image](https://user-images.githubusercontent.com/20731897/66948282-683ea100-f022-11e9-803b-19a406634712.png)

**Comment by rachelsater** [comment]
I tested this today and it's no longer an issue

![image](https://user-images.githubusercontent.com/72876352/113008571-24bbf200-9145-11eb-89d1-c79ebec7070d.png)
