### ISSUE TITLE
Role adjustment needed: Person Profile

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#774]
For the person profile, site admins are the only user able to see and interact with unpublished versions of person profiles.

These nodes are 'hidden' from content authors and editors, but they sometimes add draft person profiles to draft pages with grid of people to get the entire layout of their content set up. 

A role adjustment is needed so that all roles can view and edit drafts person profiles.

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine Do we still need this role adjustment? thanks!

**Comment by duffy-james** [comment]
@rachelsater yes, I think this would be great to address. It's come up a few times in the past year.

**Comment by stephaniemar** [comment]
Permissions issue

**Comment by duffy-james** [comment]
there's a ticket for this in Jira; closing this for now
