### ISSUE TITLE
Remove extra <hr> at bottom of sidebar on "department profile" content type

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#778]
You can see the extra <hr> rule here:

![image](https://user-images.githubusercontent.com/7929556/67122325-8a1f5b80-f1bb-11e9-8993-a22e2d8abae1.png)

**Comment by subaha-cob** [comment]
@rachelsater currently on uat V
https://d8-uat.boston.gov/

**Comment by rsater-storycorps** [comment]
@subaha-cob It looks like the margins are blown out

![image](https://user-images.githubusercontent.com/84156441/139491466-45b37e2f-2550-4f44-8f30-2ec4aa33cba2.png)

**Comment by subaha-cob** [comment]
Please test again on UAT:
https://d8-uat.boston.gov/departments/public-works/street-sweeping-city

**Comment by rachelsater** [comment]
@subaha-cob way better! thank you!

**Comment by duffy-james** [comment]
@subaha-cob looks like you addressed this -- we also have another ticket for this one.
