### ISSUE TITLE
The Header links in the How to pay a parking ticket page are spaced differently on the Drupal 8 page than on the Drupal 7 page

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#783]
Moved over from Iterators board because still outstanding:

Screengrab/videos (insert file names here)
2019 09 12, How to pay parking tickets header links spaced differently on Drupal 8 page than on Drupal 7 page.mp4
2019 09 12, How to pay parking tickets header links spaced differently on Drupal 8 page than on Drupal 7 page.MP4.zip

Link and Node #
Dupral 8 Link:
• http://bostond8stg.prod.acquia-sites.com/departments/parking-clerk/how-pay-parking-ticket

Dupral 7 Link:
• https://www.boston.gov/departments/parking-clerk/how-pay-parking-ticket

Type of User: Anonymous

Environment
(Device > OS > Browser)
Computer > Windows 10 (1903) > Internet Explorer 11.295.18362.0

Section
(Page > Area > Element)
How to Pay a Parking Ticket > Header > Header links

Brief Description
The Header links in the How to pay a parking ticket page are spaced differently on the Drupal 8 page than on the Drupal 7 page

Steps to reproduce

Go to the Drupal 7 and 8 pages for ‘How to pay a parking ticket’
Make sure the Drupal 8 page is wide enough so that the header links are on two levels
Desired Result
• The Drupal 8 header links do not go on two levels

Actual Result
• The Drupal 8 header links go on two levels at a certain width

See https://github.com/CityOfBoston/Iterators/issues/84 for original issue entry.

**Comment by andrebtlima** [comment]
Resolved so closing.
