### ISSUE TITLE
Cabinet component: Styling issue when no cabinet head entered

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#785]
On the cabinet component, there is a styling issue when no cabinet head is entered.

If no cabinet head is entered, then the component so push flush left.

Right now on D8 the space for cabinet head is remaining open. 

See here: http://bostond8dev.prod.acquia-sites.com/311/city-boston-government

![Screen Shot 2019-10-21 at 12 27 46 PM](https://user-images.githubusercontent.com/20731897/67223938-3486c100-f3fe-11e9-892b-39d5375168c1.png)

**Comment by rachelsater** [comment]
no longer an issue so I'm closing this ticket
