### ISSUE TITLE
Permissions issue with adding icon to "department profile"

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#791]
When you create a department profile as a content editor or author, here's what pops up when you try to upload an icon:
![image](https://user-images.githubusercontent.com/7929556/67514740-55a01980-f66b-11e9-8f0c-67b125efbc35.png)

Checked with @davidrkupton and it looks like you can upload as a site admin. We just need to allow content editors and authors to also be able to upload.

**Comment by duffy-james** [comment]
To clarify, the media browser in the WYSIWYG field appears to still work, so content authors and editors can add images there.

**Comment by andrebtlima** [comment]
Resolved so closing.
