### ISSUE TITLE
Department profile contacts read as string of letters 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#796]
**Expected Behavior/Acceptance Criteria**
Contacts should read as department names (i.e. 311, Transportation, etc.) 

**Actual Behavior**
Contacts read as string of letters.

**Browser**
Chrome 

**Device**
Mac > OS Mojave 

**Example URL**
http://bostond8dev.prod.acquia-sites.com/winter-boston
https://www.boston.gov/winter-boston

**Relevant Screenshot(s) or Logs**

<img width="1419" alt="Screen Shot 2019-10-28 at 4 12 19 PM" src="https://user-images.githubusercontent.com/57111927/67714259-e80f2880-f99d-11e9-8996-a79127b61358.png">
<img width="1428" alt="Screen Shot 2019-10-28 at 4 12 54 PM" src="https://user-images.githubusercontent.com/57111927/67714261-e9d8ec00-f99d-11e9-920f-3f394e0b07e3.png">

**Steps to Reproduce the Behavior/How to Test**

**Comment by andrebtlima** [comment]
Think it's a larger content issue.

<img width="1420" alt="Screen Shot 2019-10-28 at 4 22 18 PM" src="https://user-images.githubusercontent.com/57111927/67714871-29540800-f99f-11e9-820a-0bcd1c574bdb.png">

**Comment by reillyzlab** [comment]
Resolved so closing
