### ISSUE TITLE
Can't add "events" or "news" components to content types

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#798]
When I attempt to add an "events and notices" or "news & announcements" component to an existing page or a new page, nothing happens. I tested on article, department, event, program, and post content types. I'm still able to add other components to the page, just not those two.

**Comment by duffy-james** [comment]
My permissions levels at the time of testing:
- administrator
- Site Administrator
- Content Editor
- Content Author

**Comment by andrebtlima** [comment]
Resolved so closing.
