### ISSUE TITLE
Issues with "public notice" content type

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#799]
The start and end date times should be required fields. They are not currently:
![image](https://user-images.githubusercontent.com/7929556/67790907-f49e8a00-fa4c-11e9-9cd9-4d15d36f4b05.png)

The meeting location section should default to the "United States":
![image](https://user-images.githubusercontent.com/7929556/67790994-14ce4900-fa4d-11e9-849a-d62d8f7508e9.png)

It's currently a required field, but at the moment, the country dropdown is creating a situation where a notice could be created and published without a location:
![image](https://user-images.githubusercontent.com/7929556/67791270-85756580-fa4d-11e9-8494-352024271e14.png)

I haven't been able to test an "events" component, but this content type should be looked at as part of the related content issues: https://github.com/CityOfBoston/boston.gov-d8/issues/690

**Comment by andrebtlima** [comment]
Resolved so closing.
