### ISSUE TITLE
Issue with photo components across multiple pages

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#809]
There's an issue with  photo (and video?) components across multiple pages. Something to do with sizing, images are zoomed, easiest to observe in this screenshot from Departments> Animal Care and Control :

<img width="1428" alt="Screen Shot 2019-11-01 at 11 16 44 AM" src="https://user-images.githubusercontent.com/57111927/68035031-315ec100-fc99-11e9-8668-ddc367ec1324.png">

Not sure if launch blocker, probably depends on whether photo components on other pages affected by this issue are zoomed to the point that seriously impacts ux...

**Comment by andrebtlima** [comment]
here's what it looks like on D7:

<img width="1303" alt="Screen Shot 2019-11-01 at 11 23 28 AM" src="https://user-images.githubusercontent.com/57111927/68035471-10e33680-fc9a-11e9-8224-b484a3bbd0a6.png">

**Comment by reillyzlab** [comment]
This will move to launch blocker if we find certain examples where this is particularly bad.

**Comment by davidrkupton** [comment]
Rolled into #815
