### ISSUE TITLE
Remove the following files from the deployment candidate:

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#813]
from repo root (/var/www/html/bostond8/)
- composer.json
- composer.lock
- .lando.yml
- (f) patches
- (f) scripts

from docroot root (/var/www/html/bostond8/docroot)
- .csslintrc
- .editorconfig
- .eslintignore
- .eslintrc.json
- .gitattributes (?)

**Comment by reillyzlab** [comment]
Defer to @davidrkupton to close if appropriate

**Comment by reillyzlab** [comment]
@davidrkupton is this still a thing or can/should we close this ticket?

**Comment by davidrkupton** [comment]
Done ages ago.
