### ISSUE TITLE
Resolve image resolution across the website

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#815]
Most images across the website are having resolution issues. We discussed completely replacing all images to ensure they're accurately coming through.

Examples: 
- Career Center
- Parks and Playgrounds
- Animal Care and Control

**Comment by andrebtlima** [comment]
Related:

http://bostond8dev.prod.acquia-sites.com/news/mayor-signs-home-rule-petition-strengthen-ability-create-affordable-housing-fund-workforce

**Comment by reillyzlab** [comment]
Resolved so closing
