### ISSUE TITLE
Component: 3-column with image not working

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#822]
Component: 3-column with image not working. 

Cannot currently 'add text with image'/columns.

Tested on dev on chrome and safari.

![Screen Shot 2019-11-05 at 4 38 34 PM](https://user-images.githubusercontent.com/20731897/68248389-baa02b80-ffea-11e9-9acb-8438a1d515d8.png)

**Comment by andrebtlima** [comment]
Resolved so closing.
