### ISSUE TITLE
Remove character limit on excluded dates for status alerts

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#826]
I'm getting an error message preventing me from adding dates to the trash and recycling status alerts:

![image](https://user-images.githubusercontent.com/7929556/68329131-a0c02080-009e-11ea-9f6d-a531f9519e92.png)
![image](https://user-images.githubusercontent.com/7929556/68329113-9867e580-009e-11ea-9186-bc65da990851.png)

Can we remove the character limits for this "excluded dates" section? This probably isn't a launch blocker, just annoying.

**Comment by andrebtlima** [comment]
Still an issue 

<img width="593" alt="Screen Shot 2019-11-18 at 10 04 57 AM" src="https://user-images.githubusercontent.com/57111927/69063672-eb209600-09ea-11ea-9e34-85b1a8c822b8.png">

**Comment by davidrkupton** [comment]
This was 256, so I extended to 512.
We have to have some char limit and James said he almost had got what he needed when it was 256, so I just doubled it.

- Can you back check with James that he does in fact need more than 512 chars.
