### ISSUE TITLE
Updated Commissions Search for D8

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#829]
https://github.com/CityOfBoston/digital/issues/222

I believe this may have been already done and just needs deploying on the web-app side?
I am happy to dig in on the Drupal side, but checking out the digital repo issue linked above, maybe Phil or Matt are better placed to look into this b/c Fiona may have pushed the change in the PR referenced in the ticket???

**Comment by mmcgowanBOS** [comment]
The fix and update that I merged into Dev and then up to Stg now works. When David and I were viewing the page on staging on Thursday we were not using https / ssl. Doing this in fact solves the issue and you can see it working properly here. 

https://d8-stg.boston.gov/civic-engagement/boards-and-commissions

Closing for now.
