### ISSUE TITLE
Workbench: Issues with 'my edits' and 'all recent content'

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#830]
On the workbench, there are issues with 'my edits' and 'all recent content'.

You can see the first page of 'my edits', but cannot get to page 2 -- get taken to a 403 page.

For all recent content, get taken to 403 page.

Logged in as cob-admin on dev site.

For more info: https://drive.google.com/file/d/1GrlXZ6ldS9D2y_QstI3mcHXnTMcHBU6X/view

**Comment by reillyzlab** [comment]
Potentially related: https://github.com/CityOfBoston/boston.gov-d8/issues/675

**Comment by andrebtlima** [comment]
Resolved so closing.
