### ISSUE TITLE
cannot link to a document which is already in library (validation error) -- DU

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#833]
cannot link to a document which is already in library (validation error) -- DU

Converting to issue so our issues number matches our project board.

duplicated by #862

**Comment by andrebtlima** [comment]
I'm still getting a validation error here. 

<img width="1433" alt="Screen Shot 2019-11-18 at 11 58 36 AM" src="https://user-images.githubusercontent.com/57111927/69073137-cf24f080-09fa-11ea-915b-f9dff71081fb.png">

**Comment by andrebtlima** [comment]
Resolved so closing.
