### ISSUE TITLE
Finalize procurement content type

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#842]
We will use this/deploy this in Drupal 8.

We need to

- [ ] Re-orinet/re-show all stakeholders this
- [ ] Determine if the work is actually done or what else might need to be done + finish that work
- [ ] Set up a work flow
- [ ] Train folks
- [ ] Deploy and communicate.

Deliver/deploy by end of 2019 calendar year. 

Related work while on Drupal 7: https://github.com/CityOfBoston/boston.gov-d7/issues/1235https://github.com/CityOfBoston/boston.gov-d7/issues/1235

**Comment by andrebtlima** [comment]
Closing because we have a Procurements Project now where most of this info is consolidated
