### ISSUE TITLE
Problem with city seal after site alert is published

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#843]
After publishing a test site alert, noticed that the seal, which should disappear, is still hanging out at the top of the screen. 

<img width="1431" alt="Screen Shot 2019-11-12 at 3 03 38 PM" src="https://user-images.githubusercontent.com/57111927/68706364-b3829b80-055d-11ea-9405-3ed54e56b918.png">

This should disappear when someone scrolls up.

**Comment by reillyzlab** [comment]
Resolved so closing
