### ISSUE TITLE
Cannot revert pages

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#844]
Pages cannot be reverted.

If a user goes into 'revisions' on any page and and hits revert a user gets taken to this error message:

![Screen Shot 2019-11-12 at 3 07 32 PM](https://user-images.githubusercontent.com/20731897/68706743-66eb9000-055e-11ea-8c8e-5fc550f888f7.png)

"The website encountered an unexpected error. Please try again later."

See one example here: http://d8-stg.boston.gov/node/32946/revisions/579356/revert

**Comment by duffy-james** [comment]
Also can't view old revisions for pages on the site. I'm seeing the same error when I click on these links:

![image](https://user-images.githubusercontent.com/7929556/68796140-54398f80-0620-11ea-9daa-625acb7a6533.png)

**Comment by andrebtlima** [comment]
Resolved so closing.
