### ISSUE TITLE
Staging site - cannot log out of site

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#847]
On staging, once cob-admin logs in they cannot log out.

**Comment by davidrkupton** [comment]
Interestingly this does not occur locally.

This is now (partially) addressed using the auto-logout module.
All users are logged out after 600 secs (10mins),  except site_admin and user1 show are logged out after 1800 seconds (30 mins).

**Comment by davidrkupton** [comment]
This is resolved, you can log out of the site on acquia now.
