### ISSUE TITLE
Issues with Cityscore

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#849]
There are a few issues with Cityscore:

1. Current URL: http://d8-stg.boston.gov/innovation-and-technology/cityscore
URL is actually: boston.gov/cityscore

2. Data is displaying differently:

D8:
![Screen Shot 2019-11-12 at 5 02 08 PM](https://user-images.githubusercontent.com/20731897/68714633-39a6de00-056e-11ea-84bc-e7832af69f00.png)

D7:
![Screen Shot 2019-11-12 at 5 02 40 PM](https://user-images.githubusercontent.com/20731897/68714662-4a575400-056e-11ea-80c9-1ac74eb490f8.png)

**Comment by reillyzlab** [comment]
Related issue that was happening on Drupal 7 - https://github.com/CityOfBoston/boston.gov-d7/issues/1323 (which I closed)

**Comment by davidrkupton** [comment]
So, when an import occurs the order will reset to the same order as the import provides.
We can run an import into the dev area once the migration is completed to verify.

**Comment by davidrkupton** [comment]
Not sure why this is back out of retest.  Maybe just a bit of confusion in managing tickets.  Here's the low-down on this:
1. The url (/cityscore) does resolve to the correct page, even though the address bar shows the longer address.  If this is address display an issue we can manually change the address that displays after launch (the downside of that is that I think the breadcrumb would be lost and only show `home > cityscore` and not the department..
2. The data values in the table are dependent on the most recent import from the data team, so D7 and D8 wont have same values except immediately after a migration and before the data team send an update to the D7 site.
3. The order is an issue for some reason during the migration, however after we run a data import/update (like the data team would in prod) the order is correct.

-- not sure what else is different.

**Comment by andrebtlima** [comment]
Resolved so closing.

**Comment by andrebtlima** [comment]
Thanks David. The ordering was the issue I was focusing, so I'm going to close this.
