### ISSUE TITLE
Events like node/3756 have a recurring date.  At the moment we do not support recurring dates in D8.

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#857]
Is this a blocker?

**Comment by reillyzlab** [comment]
Yes

**Comment by jimafisk** [comment]
@davidrkupton it looks dates with multiple occurrences don't display the date on the actual node. Here's an example:
- D8: https://d8-dev.boston.gov/calendar/free-immigration-consultations-volunteer-attorneys
- D7: https://www.boston.gov/calendar/free-immigration-consultations-volunteer-attorneys

![missing_date](https://user-images.githubusercontent.com/5913244/69359144-0cd18580-0c56-11ea-95af-3161df79f5b8.png)

**Comment by reillyzlab** [comment]
Tested on staging. Able to set recurring in the workbench, but the functionality is not working.

Still only see one event on /calendar page - you should see the event each time it is supposed to occur.

Tested with: https://d8-stg.boston.gov/calendar/testing-recurring-event-multiple-days

**Comment by duffy-james** [comment]
@davidrkupton here's a current example of this issue:
https://www.boston.gov/calendar/winter-family-gym-bcyf-menino

Only showing up once on the events page:
![image](https://user-images.githubusercontent.com/7929556/70534745-ab505880-1b29-11ea-8d35-428a8c1ef599.png)

**Comment by jimafisk** [comment]
@duffy-james here's a related issue for that: https://github.com/CityOfBoston/boston.gov-d8/issues/975

**Comment by reillyzlab** [comment]
Closing this because the functionality of working although it's not ideal state.

Other tickets related will stay open: #975 and #1144
