### ISSUE TITLE
Manually set the URLs for metrolist

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#859]
URLs need to be manually set for Metrolist, etc.

@jimafisk can you drop in the URLs that we'll need to set.

**Comment by jimafisk** [comment]
Lottery and Resale:
- On D7: https://www.boston.gov/metrolist/lottery-and-resale
- On D8: http://d8-stg.boston.gov/lottery-and-resale-opportunities

Affordable Properties:
- On D7: https://www.boston.gov/metrolist/affordable-properties
- On D8: http://d8-stg.boston.gov/affordable-properties

**Comment by reillyzlab** [comment]
Plus test it's functionality

**Comment by jimafisk** [comment]
Adjusted the URL aliases and deleted any redirect loops. The following URLs should work:
- https://www.boston.gov/metrolist/lottery-and-resale
- https://www.boston.gov/metrolist/affordable-properties

<details>
<summary>Example redirect loop page</summary>

![redirect_loop](https://user-images.githubusercontent.com/5913244/69499954-2a585680-0ec5-11ea-86e6-4ac7b2b5b213.png)

</details>

<details>
<summary>Redirect to delete</summary>

![redirect_to_delete](https://user-images.githubusercontent.com/5913244/69499980-478d2500-0ec5-11ea-9d54-52572e9ce7eb.png)


</details>

**Comment by reillyzlab** [comment]
Complete

**Comment by jimafisk** [comment]
I also just converted the external (absolute) links on the metrolist page to internal (relative) links. Previously looking at these on local / dev / stg would send you to the production site, now the should remain on the correct environment.

<details>
<summary>Previous external link example</summary>

![absolute_url](https://user-images.githubusercontent.com/5913244/69500330-2d087b00-0ec8-11ea-8e7c-aa5c557cea47.png)

</details>
<details>
<summary>New internal link example</summary>

![internal](https://user-images.githubusercontent.com/5913244/69500333-342f8900-0ec8-11ea-8f09-cb2e6c25704f.png)


</details>
