### ISSUE TITLE
Issue with listing page front end template

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#864]
There is an issue with the styling of the front end template.

Small example on D8: ![Screen Shot 2019-11-14 at 4 33 09 PM](https://user-images.githubusercontent.com/20731897/68897985-9506d680-06fc-11ea-8d7a-a9533caa92f3.png)

Small example on D7: 
![Screen Shot 2019-11-14 at 4 39 31 PM](https://user-images.githubusercontent.com/20731897/68898412-5faeb880-06fd-11ea-884c-5851db3b5b9e.png)

**Comment by andrebtlima** [comment]
Resolved so closing.
