### ISSUE TITLE
global image issue 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#869]
Some images not coming through on content.boston.gov. USE THIS TICKET FOR LINKS TO PAGES WITH MISSING IMAGES. 

Examples
- http://d8-stg.boston.gov/lottery-and-resale-opportunities [header image missing]
- http://d8-stg.boston.gov/affordable-properties [header image missing]
- homepage status icons missing - https://github.com/CityOfBoston/boston.gov-d8/issues/868

**Comment by reillyzlab** [comment]
Closing this ticket. Resolving intermittent image issues as we find them on the site.
