### ISSUE TITLE
Minor styling issue on list component on guides page

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#870]
There's an issue with the styling of the list component (Topic Landing Page view, Guides display) on the guides page. Each guide should be white against the grey backdrop, but instead I'm seeing white-on-white. Wouldn't say this is a blocker, but something to fix post launch. 

D8: 

<img width="1426" alt="Screen Shot 2019-11-15 at 11 08 25 AM" src="https://user-images.githubusercontent.com/57111927/68957983-2fb4f300-0799-11ea-816d-7c0087ea9809.png">

D7 for reference:

<img width="1395" alt="Screen Shot 2019-11-15 at 11 15 31 AM" src="https://user-images.githubusercontent.com/57111927/68958032-48bda400-0799-11ea-8882-c521e7f4e41d.png">

**Comment by andrebtlima** [comment]
Not sure if this is a larger issue than just the guides display or the topic landing page view.

**Comment by rachelsater** [comment]
@duffy-james @Micah-Levine is this still an issue? thanks!

**Comment by duffy-james** [comment]
@rachelsater this looks fine to me, going to close out.
