### ISSUE TITLE
Problem with list component on events page

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#871]
The calendar view in the list component on events page is displaying events with no date organization and no time:

D8:

<img width="1356" alt="Screen Shot 2019-11-15 at 1 21 02 PM" src="https://user-images.githubusercontent.com/57111927/68965890-e2da1800-07aa-11ea-800e-d36cc30099b7.png">
<img width="1424" alt="Screen Shot 2019-11-15 at 1 21 11 PM" src="https://user-images.githubusercontent.com/57111927/68965908-ea012600-07aa-11ea-93cf-b056a190992a.png">

D7 for reference:

<img width="1429" alt="Screen Shot 2019-11-15 at 1 21 21 PM" src="https://user-images.githubusercontent.com/57111927/68965922-f1283400-07aa-11ea-8be5-a5f41987e864.png">

**Comment by jimafisk** [comment]
**Note:** when fixing date I needed to use false flag `{{ start_date|date('g:ia', false) }}`  per https://www.drupal.org/forum/support/theme-development/2019-04-07/date-time-displays-different-times#comment-13064495

**Comment by jimafisk** [comment]
This view needs to be updated in a couple of places:
1. The field grouping needs to use the new `field_event_date_recur`
2. The date filter needs to use `field_event_date_recur`

<details>
<summary>See screenshot</summary>

![field_grouping](https://user-images.githubusercontent.com/5913244/69358216-81a3c000-0c54-11ea-854b-bc39abe140b7.png)

</details>
