### ISSUE TITLE
Problem with 403 page graphic 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#884]
The white line underneath the ACCESS DENIED message should run behind the steeple of the church illustration, not strike through it. 

<img width="865" alt="Screen Shot 2019-11-19 at 4 27 23 PM" src="https://user-images.githubusercontent.com/57111927/69188172-01614b80-0aea-11ea-845f-8b72cf6198ac.png">

<img width="1426" alt="Screen Shot 2019-11-19 at 4 27 17 PM" src="https://user-images.githubusercontent.com/57111927/69188167-fe665b00-0ae9-11ea-913c-c90ef2a1eee8.png">

**Comment by reillyzlab** [comment]
@duffy-james do you know if this is still an issue?

**Comment by rachelsater** [comment]
it looks correct on production so I'm closing this ticket
