### ISSUE TITLE
CTA for external links in "Events and Notices" component not styled 

### ISSUE THREAD

**Issue by andrebtlima** [CityOfBoston/boston.gov-d8#890]
When you add an external link to a Events and Notices component the link is not styled properly. 

<img width="1302" alt="Screen Shot 2019-11-21 at 11 41 19 AM" src="https://user-images.githubusercontent.com/57111927/69357942-08a46880-0c54-11ea-8d94-ca4cff9fabeb.png">

It is styled properly tho when you add an internal link for Events and Notices, and styled properly when you add both internal and external links to News and Announcements component. 

For reference, this is what is should look like:

<img width="1328" alt="Screen Shot 2019-11-21 at 11 44 32 AM" src="https://user-images.githubusercontent.com/57111927/69358112-51f4b800-0c54-11ea-86a2-adaaca643e44.png">

**Comment by andrebtlima** [comment]
Still getting this unstyled call to action when I add an external link to the events and notices component: 

<img width="1213" alt="Screen Shot 2019-11-22 at 3 39 01 PM" src="https://user-images.githubusercontent.com/57111927/69458854-56959b00-0d3e-11ea-82f9-f669f7fd0c8b.png">

**Comment by jimafisk** [comment]
Updated the preprocess in `bos_link` to also check for a `cta_button` view mode:

<details>
<summary>Before</summary>

![before](https://user-images.githubusercontent.com/5913244/69462871-2bb04480-0d48-11ea-9650-25fab8f493fc.png)

</details>
<details>
<summary>After</summary>

![after](https://user-images.githubusercontent.com/5913244/69462841-163b1a80-0d48-11ea-9190-9acc33426f60.png)

</details>

**Comment by reillyzlab** [comment]
Resolved so closing
