### ISSUE TITLE
Homepage: Date ribbon not showing on Events and Notices

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#903]
On the homepage the ribbon overlay on featured image is not displaying.

This is most likely related to the date_recurr field on the events content type.

![image](https://user-images.githubusercontent.com/4700050/69479870-2f87a980-0dd0-11ea-8e80-df51d964c1ab.png)

**Comment by reillyzlab** [comment]
This is resolved so closing
