### ISSUE TITLE
Homepage: Why is email label blue

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#904]
On the homepage, why is the second cards email link blue even when not hovering over it?

![image](https://user-images.githubusercontent.com/4700050/69480193-3bc13600-0dd3-11ea-9274-487e1c254e64.png)

**Comment by reillyzlab** [comment]
@davidrkupton I'm not seeing this on Safari, Firefox or Chrome.

**Comment by jimafisk** [comment]
I don't see this either
