### ISSUE TITLE
Node/51781: Boards and Commissions search has js errors

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#905]
Load the page and inspect the js console.

Looks like some js variables are not passing through ?

https://content.boston.gov/civic-engagement/boards-and-commissions

**Comment by reillyzlab** [comment]
Will defer to @mmcgowanBOS to fix by latest next week.

But, this will not be a launch blocker.

**Comment by mmcgowanBOS** [comment]
I just checked this and am not seeing any errors. See attached screengrab.
![b_and_c_screen](https://user-images.githubusercontent.com/44584567/69488239-a5256100-0e34-11ea-8e08-81b44812ae6b.png)

Closing for now.
