### ISSUE TITLE
Status report: salesforce

### ISSUE THREAD

**Issue by davidrkupton** [CityOfBoston/boston.gov-d8#906]
This is being reported on the Manage > Reports > Status Repot  page:

![image](https://user-images.githubusercontent.com/4700050/69481173-de31e700-0ddc-11ea-9592-066fb8d0f294.png)

Maybe the salesforce settings need to be set ??

**Comment by jimafisk** [comment]
All set, I fixed the connection and reran the import. It looks ok on my end:

![metrolist](https://user-images.githubusercontent.com/5913244/69483008-666db780-0df0-11ea-8779-0fc6f9156d2c.png)

and

![affordable_properties](https://user-images.githubusercontent.com/5913244/69483009-6a99d500-0df0-11ea-89c9-62f52656ac71.png)

**Comment by reillyzlab** [comment]
Metrolist seems to be working.``
