### ISSUE TITLE
Text issue in title of news component

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#908]
Found on the news component on the Mayor's Office page: https://content.boston.gov/departments/mayors-office
![Screen Shot 2019-11-23 at 1 05 14 PM](https://user-images.githubusercontent.com/28716225/69483162-f102e680-0df1-11ea-8568-ef18bd92a743.png)

**Comment by davidrkupton** [comment]
Argh!
Related to migration.  Can fix [1] by redoing migration or [2] by altering the template.
[1] means we dont go live, [2] can be done monday

**Comment by andrebtlima** [comment]
related to #1077

**Comment by subaha-cob** [comment]
Thanks Andre, that is super helpful.

**Comment by andrebtlima** [comment]
This looks good on staging. Ready to push to production.
