### ISSUE TITLE
Images embedded in blog posts are very, very large

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#909]
Images embedded into this blog post are really large: 
https://content.boston.gov/news/what-reward-ms-grays-tea-kwon-do-class-hot-cocoa

![Screen Shot 2019-11-23 at 1 09 44 PM](https://user-images.githubusercontent.com/28716225/69483226-9322ce80-0df2-11ea-85fe-dc6057e605f9.png)

**Comment by davidrkupton** [comment]
I have a hotfix for this which could be deployed this evening.

**Comment by davidrkupton** [comment]
dupliacte of #923. close this one.
