### ISSUE TITLE
LAUNCH: Doubles of pages showing up in "needs review"

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#910]
Pages switched to the "needs review" moderation state are appearing twice in this "needs review" view:
![image](https://user-images.githubusercontent.com/7929556/69483285-50152b00-0df3-11ea-8153-74b918dd9126.png)

Here are the url differences when I hover over:

https://content.boston.gov/node/68116/revisions/585786/view
https://content.boston.gov/hyde-park-avenue-multimodal-corridor

https://content.boston.gov/node/67816/revisions/585746/view
https://content.boston.gov/north-washington-street-bus-lane

Looks like the draft and the page itself are showing up. This isn't a blocker for launch, just a bug.

**Comment by andrebtlima** [comment]
Not seeing duplicates any more so going to close this ticket.
