### ISSUE TITLE
Photo component isn't showing photo

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#911]
Photo component for CityScore not showing a photo (unless there's no photo attached there)
https://content.boston.gov/departments/mayors-office
![Screen Shot 2019-11-23 at 1 18 47 PM](https://user-images.githubusercontent.com/28716225/69483322-da5d8f00-0df3-11ea-9b0f-6cc507d2f527.png)

**Comment by davidrkupton** [comment]
Done - uploaded image (there was an icon which was probably incorrectly attached because it was detected as a duplicate and then replaced with an icon).
