### ISSUE TITLE
Image isn't showing up for grid of icons

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#912]
One icons is broken in the grid of icons on the City Council page
https://content.boston.gov/departments/city-council

Testing on Google Chrome

![Screen Shot 2019-11-23 at 1 23 04 PM](https://user-images.githubusercontent.com/28716225/69483362-653e8980-0df4-11ea-9cbb-d8c60897321e.png)

**Comment by davidrkupton** [comment]
Done - icon mapping issue.
