### ISSUE TITLE
Component on play and apply page missing title

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#913]
Not a huge deal, but one of the links along the grid of icons is missing a title on the pay and apply page: https://content.boston.gov/pay-and-apply
![Screen Shot 2019-11-23 at 1 28 05 PM](https://user-images.githubusercontent.com/28716225/69483411-1ba26e80-0df5-11ea-9fa9-108a1d4725d5.png)

Testing on Google Chrome

**Comment by davidrkupton** [comment]
Done. Dunno why its broken ... but its now fixed forever.
