### ISSUE TITLE
Issues with Search

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#914]
Went I went to search for "Arts and Culture" I received a 404 error, when I click on the search bar on the 404 page I can't actually type anything in the box: https://content.boston.gov/search?utf8=%E2%9C%93&query=arts+and+culture
![Screen Shot 2019-11-23 at 1 34 42 PM](https://user-images.githubusercontent.com/28716225/69483498-fd893e00-0df5-11ea-8b76-4f623730b4bd.png)

Testing on Google Chrome

**Comment by davidrkupton** [comment]
Yup search will be all over the place.
This needs to be re-tested after we switch the boston.gov domain.
