### ISSUE TITLE
Top news component on Boston.gov has title spacing issue

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#915]
Small spacing issue on top news item on homepage, looks like title is spaced a little too far to the left (or there's something that is in the upper left that's not showing up) https://content.boston.gov/

Testing on Google Chrome

![Screen Shot 2019-11-23 at 1 42 15 PM](https://user-images.githubusercontent.com/28716225/69483570-ec8cfc80-0df6-11ea-849e-db189cef6875.png)

**Comment by davidrkupton** [comment]
This is related to previous issue #903.
