### ISSUE TITLE
Can't add document to "site alert" without throwing error message

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#916]
When adding a document to the "call-to-action" button in a site alert, I can't get past this error message, event though I'm trying to add pdfs:

![image](https://user-images.githubusercontent.com/7929556/69483619-8ce32100-0df7-11ea-9eee-73552a98c486.png)

Not a launch blocker, just needs to be fixed post launch.

**Comment by davidrkupton** [comment]
Dup of #928 closing this one.
