### ISSUE TITLE
Creating article as site editor - editing page not responsive (wonky view)

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#918]
This may be a known issue/not a big deal: went to edit an article while not in full screen, and options below looked a little wonky (not responsive, only lines up correctly when full screen)

Testing on Google Chrome
Link: https://content.boston.gov/node/add/article

Not full screen:
![Screen Shot 2019-11-23 at 2 04 45 PM](https://user-images.githubusercontent.com/28716225/69483832-4642f600-0dfa-11ea-9b51-0d553a8f2274.png)

Full screen:
![Screen Shot 2019-11-23 at 2 06 47 PM](https://user-images.githubusercontent.com/28716225/69483841-58249900-0dfa-11ea-9895-dae3b67afa2d.png)

**Comment by reillyzlab** [comment]
Breakpoint issue, known, closing
