### ISSUE TITLE
'Related content' links missing context and "view" option

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#920]
In Drupal 7, searches for content under "related content" would reveal the link title, the content type, and a view button. Drupal 8 is missing the content type and the view button:

![image](https://user-images.githubusercontent.com/7929556/69483943-7a6ae680-0dfb-11ea-910f-9ae248b9d167.png)

This was an addition @jimafisk made the last time he worked on related content in Drupal 7. It's not a launch blocker, but should be immediately addressed after launch.

**Comment by jimafisk** [comment]
Hey @duffy-james good catch, I was trying to get this working on Friday but D8 seems to be handling this differently than D7. I felt like it was taking too much time to figure out so I moved on to other things that seemed more urgent. Thanks for flagging it here, we should definitely take another look.

**Comment by jimafisk** [comment]
This is a Drupal core bug: https://www.drupal.org/project/drupal/issues/2174633

This patch fixes it so multiple fields can appear in the autocomplete list: https://www.drupal.org/files/issues/2019-10-14/2174633-351.patch

<details>
<summary>See screenshot</summary>

![content_type](https://user-images.githubusercontent.com/5913244/69884363-14240f00-12a6-11ea-818e-e673fd5ec73c.png)

</details>

It looks like this field is only returning Person Profile content, which is not correct. I'll fix these filters and return more than 10 results as well.

**Comment by jimafisk** [comment]
Added another patch to allow us to set the number of autocomplete results on form display: https://www.drupal.org/project/drupal/issues/2863188

**Comment by jimafisk** [comment]
I needed to upgrade core to 8.7.10 and use a patch from a different issue (https://www.drupal.org/project/drupal/issues/3024404) in order to increase the number of results for the autocomplete filter:

<details>
<summary>See screenshot</summary>

![more_results](https://user-images.githubusercontent.com/5913244/69889601-dfbd4c80-12bf-11ea-9f79-0080d47ac31e.png)


</details>

**Comment by jimafisk** [comment]
Ultimately choose another patch that looks more likely to get pulled into core: https://www.drupal.org/project/drupal/issues/2863188#comment-13284743

**Comment by jimafisk** [comment]
@duffy-james in D8 they've made it more difficult to setup the preview link to go directly to the page, how critical is that? For now, I've increased the number of results and added the Content Type and Node ID to the results:

<details>
<summary>Click to see screenshot</summary>

![links](https://user-images.githubusercontent.com/5913244/69891004-4bef7e80-12c7-11ea-9596-f7d8d7c60bf0.png)

</details>

If this is ok for now, we can always revisit once we've taken care of other critical issues. Just let me know! Thanks!

**Comment by duffy-james** [comment]
@jimafisk That's perfect, Jim. The "view" part isn't critical, we circle back on that later.

**Comment by reillyzlab** [comment]
@duffy-james can you check to see if this is resolved. I'm going to open a separate issue for the view portion.

**Comment by duffy-james** [comment]
@reillyzlab looks good
