### ISSUE TITLE
Image broken in 3 column w/ image component

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#921]
Found on the Arts page - 3 column with image component has one of the icons broken: https://content.boston.gov/departments/arts-and-culture

Testing on Google Chrome

![Screen Shot 2019-11-23 at 2 25 23 PM](https://user-images.githubusercontent.com/28716225/69484083-ef8aeb80-0dfc-11ea-9859-289fe77b2e2d.png)

**Comment by jimafisk** [comment]
This looks ok for me in Chrome + Firefox:

![arts](https://user-images.githubusercontent.com/5913244/69486068-a1361680-0e15-11ea-8ce2-eabd88e996c5.png)

**Comment by reillyzlab** [comment]
Closing because working for me too.
