### ISSUE TITLE
"Updated" and "published" dates not automatically added

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#922]
Looks like users are still forced to add the dates manually for the "post" content type:

![image](https://user-images.githubusercontent.com/7929556/69483983-de8daa80-0dfb-11ea-826e-80caa52f6440.png)

I don't remember where we landed with this. We can work around it for now, but should be addressed immediately post launch.

**Comment by davidrkupton** [comment]
OK I see the issue.
The updated date is only populated after the node is saved, but it is required so it never gets saved.
I think I just need to remove the required condition on this.

**Comment by reillyzlab** [comment]
Duplicate so closing
