### ISSUE TITLE
Embedded images blown up in WYSIWYG field

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#923]
The images embedded in this post are blown up:

https://content.boston.gov/news/what-reward-ms-grays-tea-kwon-do-class-hot-cocoa

Also, the text is no longer wrapped around the small, vertical image in the post. Looks like all styling was lost on these images. This needs to be addressed before launch.

**Comment by duffy-james** [comment]
Other examples:

https://content.boston.gov/news/summer-just-getting-started-boston
https://content.boston.gov/news/summer-highlights-and-updates-bostongov


We've also lost the black border and captions for these images. In my initial example, the way the images should look with a caption is like this:

![image](https://user-images.githubusercontent.com/7929556/69484284-74770480-0dff-11ea-9634-19723bd80ff2.png)

**Comment by davidrkupton** [comment]
linked to #909.  The separate issue here is the caption, so closing #909 in favour of this one.

**Comment by reillyzlab** [comment]
Resolved
