### ISSUE TITLE
Grid of programs/initiatives has broken images

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#924]
There are a few images that aren't showing up on the guide to Take Action on Climate Change - I think it's the grid of programs/initiatives component: https://content.boston.gov/take-action-climate-change

Tested using Google Chrome

![Screen Shot 2019-11-23 at 2 42 12 PM](https://user-images.githubusercontent.com/28716225/69484290-82c52080-0dff-11ea-8713-b4b8b299ceea.png)

**Comment by reillyzlab** [comment]
Asked James to fix the images, but closing as a ticket in here.
