### ISSUE TITLE
Issues with public notices in upcoming events component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#926]
I created a [public notice](https://content.boston.gov/public-notices/99701) for this Sunday at 1 p.m. As such, it should be appearing under the upcoming events section on the homepage, but it's not:
![image](https://user-images.githubusercontent.com/7929556/69484398-cf5d2b80-0e00-11ea-8fb8-0018bbf536da.png)
![image](https://user-images.githubusercontent.com/7929556/69484402-dab05700-0e00-11ea-957f-9145a67f96e9.png)

**Comment by jimafisk** [comment]
This should now work for both upcoming and related displays. Both public_notices and events should display in the same Events & Notices component sorted by date:

![events_and_notices](https://user-images.githubusercontent.com/5913244/70166656-32698080-1693-11ea-8311-6a987029d983.png)

I also found another bug while working on this that I've fixed. Previously the public_notice dates were always displaying the current date:

![related](https://user-images.githubusercontent.com/5913244/70166834-81171a80-1693-11ea-81f1-a23dee8f1da4.png)

I fixed this in the view and updated the template so it works:

![related_w_updated_date](https://user-images.githubusercontent.com/5913244/70166926-ac9a0500-1693-11ea-80a1-6c15e98b2a20.png)

**Comment by duffy-james** [comment]
@jimafisk looks good to me. Please just change the dropoff time to 30 minutes instead of three hours.

**Comment by duffy-james** [comment]
@reillyzlab keeping the ticket open for that last comment, but this is good to deploy
