### ISSUE TITLE
"Temporarily Unavailable" error when creating Public Notices or Status Items

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#927]
I created a Public Notice draft here: https://content.boston.gov/public-notices/119931

If I visit this node I get the following error:

```
Temporarily Unavailable
The website that you're trying to reach is having technical difficulties and is currently unavailable.

We are aware of the issue and are working hard to fix it. Thank you for your patience.
```

<details>
<summary>See screenshot</summary>

![unavailable](https://user-images.githubusercontent.com/5913244/69485607-ac864380-0e0f-11ea-9922-146ef406fb0b.png)

</summary>

**Comment by reillyzlab** [comment]
@jimafisk Emily has been randomly getting this as well. @emilyquinn2 which content type were you on when you got this.

**Comment by reillyzlab** [comment]
Reilly tried to put together and publish a public notice. Got temp. unavailable message:

![Screen Shot 2019-11-23 at 7 17 45 PM](https://user-images.githubusercontent.com/20731897/69487348-1f9ab480-0e26-11ea-8033-21eb1a32b9c9.png)
![Screen Shot 2019-11-23 at 7 17 41 PM](https://user-images.githubusercontent.com/20731897/69487349-20334b00-0e26-11ea-8762-2b11a9991a78.png)
![Screen Shot 2019-11-23 at 7 17 33 PM](https://user-images.githubusercontent.com/20731897/69487350-20334b00-0e26-11ea-8eb6-8aaddd0f3840.png)

**Comment by emilyquinn2** [comment]
> I created a Public Notice draft here: https://content.boston.gov/public-notices/119931
> 
> If I visit this node I get the following error:
> 
> ```
> Temporarily Unavailable
> The website that you're trying to reach is having technical difficulties and is currently unavailable.
> 
> We are aware of the issue and are working hard to fix it. Thank you for your patience.
> ```
> 
> See screenshot

**Comment by emilyquinn2** [comment]
I got this same screen as well - when I went to create a new public notice.

**Comment by davidrkupton** [comment]
OK so I have fixed the issue with public notices creation. Code in the validation was expecting a start date and an end date, but only a start date was suplied.  The code has been made more resillient to this condition as the end date is not required.

**Comment by davidrkupton** [comment]
Can't replicate with Status_item.

**Comment by reillyzlab** [comment]
Resolved
