### ISSUE TITLE
Document upload issue - grid of cards

### ISSUE THREAD

**Issue by emilyquinn2** [CityOfBoston/boston.gov-d8#928]
Can't choose document from list when trying to add it within a component example: grid of cards

Believe this was happening throughout.

Could upload new but could not insert one already in system.

Reilly can confirm working on group of links - mini grid.

**Comment by davidrkupton** [comment]
from #916:

![69483619-8ce32100-0df7-11ea-9eee-73552a98c486](https://user-images.githubusercontent.com/4700050/69491174-5e009580-0e5f-11ea-90c2-b42777bbc3dc.png)

**Comment by reillyzlab** [comment]
Resolved so closing
