### ISSUE TITLE
Misc. error messages when adding component with no identifier of where those errors are in line

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#931]
Misc. error messages when adding component with no identifier of where those errors are in line

**Comment by reillyzlab** [comment]
@emilyquinn2 can you provide more context

**Comment by emilyquinn2** [comment]
The errors show up in red at the top but there are no yellow triangles associated with a specific component. I cannot tell by the errors in red where within the components the problem is happening

**Comment by emilyquinn2** [comment]
@reillyzlab

**Comment by reillyzlab** [comment]
@emilyquinn2 do you know content types this was happening on?

**Comment by emilyquinn2** [comment]
all for me so far except department profile and article. Although some of them I received no error messages which I wrote (all worked for me).... those I am not sure because everything was perfect to begin with

**Comment by davidrkupton** [comment]
This is a WIP.
