### ISSUE TITLE
Content authors cannot revert

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#932]
Content authors cannot revert pages.

Believe they're role allows to in d7.

**Comment by reillyzlab** [comment]
For @duffy-james to review

**Comment by subaha-cob** [comment]
Test in UAT

**Comment by andrebtlima** [comment]
@subaha-cob we might need to test this one on prod since I'm running into this the same issue as before. The UI for Content Editors is missing on develop
