### ISSUE TITLE
Events filters referencing 311 Requests

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#934]
The filters on the left side of the events page (https://content.boston.gov/events) are still incorrect:

<details>
<summary>See screenshot</summary>

![wrong_event_filters](https://user-images.githubusercontent.com/5913244/69487300-6b992980-0e25-11ea-85a5-8cdff998b532.png)

</details>

This is simply because the view is using the wrong vocabulary:

<details>
<summary>See screenshot</summary>

![filter](https://user-images.githubusercontent.com/5913244/69487339-fa0dab00-0e25-11ea-88a0-8dfa48cd9ae3.png)

</details>

This will be a quick update, but we should also convert this widget from autocomplete to checkboxes like seen on D7:

<details>
<summary>See screenshot</summary>

![checkboxes](https://user-images.githubusercontent.com/5913244/69487351-26292c00-0e26-11ea-9dff-585f629d5361.png)

</details>

Also the "Filter By Dates" option is missing, probably because it doesn't account for the new date recur field.

**Comment by jimafisk** [comment]
To fix the checkboxes I made the BEF checkbox template (`bef_checkboxes_field_contact_target_id`) less specific (`bef_checkboxes_bef_checkboxes`).

<details>
<summary>See screenshot</summary>

![more_generic](https://user-images.githubusercontent.com/5913244/69654926-995bb980-1043-11ea-8809-08d7b66820c3.png)

</details>

**Comment by reillyzlab** [comment]
@jimafisk tested on staging

Still one issue here:
![Screen Shot 2019-11-29 at 10 03 37 AM](https://user-images.githubusercontent.com/20731897/69877271-c43a4d80-128f-11ea-8ff3-0868569fb08e.png)

**Comment by jimafisk** [comment]
So we're not entirely sure why, but those weird taxonomy terms came across in the data migration. The easiest thing to do is just delete this term from the Event Type vocabulary: https://d8-stg.boston.gov/admin/structure/taxonomy/manage/event_type/overview

I just did this on stg.

**Comment by reillyzlab** [comment]
Deleted the long string in filter from the list of available taxonomies. 

Resolved.
