### ISSUE TITLE
Mobile issue: using "Page Sections" drops too far down the content

### ISSUE THREAD

**Issue by jfalvey** [CityOfBoston/boston.gov-d8#939]
Tested with an Android device, screenshots attached. Expected behavior is that clicking on any of the page sections would bring you to the corresponding header further down the page, but it takes you to one scroll below. 

![Screenshot_20191124-132008](https://user-images.githubusercontent.com/33426674/69499203-b2d2f900-0ebd-11ea-909d-691ecc0a1e8b.png)
![Screenshot_20191124-132002](https://user-images.githubusercontent.com/33426674/69499205-b5355300-0ebd-11ea-90aa-598b617c65e3.png)
![Screenshot_20191124-131955](https://user-images.githubusercontent.com/33426674/69499206-b6668000-0ebd-11ea-96e5-09526359d72f.png)

**Comment by davidrkupton** [comment]
Example pages:

https://www.boston.gov/departments/tourism-sports-and-entertainment

https://www.boston.gov/departments/digital-team/test-page

**Comment by andrebtlima** [comment]
This is working on staging.

**Comment by reillyzlab** [comment]
Resolved so closing
