### ISSUE TITLE
Broken component on Landmarks page

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#941]
Testing on Google Chrome Desktop. Landmarks page has a broken component that is showing code https://www.boston.gov/departments/landmarks-commission#historic-districts

![Screen Shot 2019-11-24 at 1 29 30 PM](https://user-images.githubusercontent.com/28716225/69499294-7fdd3500-0ebe-11ea-9aa8-90e18bbe374a.png)

**Comment by davidrkupton** [comment]
This is a templating issue with adding a document to a grid of cards,
