### ISSUE TITLE
Broken icon on assessing

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#945]
Testing on Pixel 3, assessing icon broken (also seems to be missing for Google Chrome desktop)

Link: https://www.boston.gov/departments/assessing

![Screen Shot 2019-11-24 at 1 52 51 PM](https://user-images.githubusercontent.com/28716225/69499601-c54f3180-0ec1-11ea-8f8f-56269bce301b.png)

**Comment by reillyzlab** [comment]
Reilly fixed alongside content author from Assessing during the training on 11/6
