### ISSUE TITLE
Mobile issue with hamburger and search bar

### ISSUE THREAD

**Issue by jfalvey** [CityOfBoston/boston.gov-d8#947]
Search bar doesn't center and keep the search icon visible until you x out of the hamburger which most may miss. There are work arounds but not ideal UX. 
![Screenshot_20191124-134942](https://user-images.githubusercontent.com/33426674/69499640-3a226b80-0ec2-11ea-811c-1d86adb1bdaf.png)
![Screenshot_20191124-134957](https://user-images.githubusercontent.com/33426674/69499641-3a226b80-0ec2-11ea-81d4-e1c50146df88.png)
![Screenshot_20191124-134920](https://user-images.githubusercontent.com/33426674/69499643-3a226b80-0ec2-11ea-8485-fc88d918488e.png)

**Comment by andrebtlima** [comment]
I think this is resolved, so closing.
