### ISSUE TITLE
Contact Us e-mail doesn't seem to send

### ISSUE THREAD

**Issue by jfalvey** [CityOfBoston/boston.gov-d8#951]
Tried from the link under my picture, 10 minutes no e-mail. The confirmation message still showed up, might be a broken connection. 
![Screen Shot 2019-11-24 at 2 18 30 PM](https://user-images.githubusercontent.com/33426674/69500001-6b506b00-0ec5-11ea-94fc-2d3928a644db.png)

**Comment by reillyzlab** [comment]
Tried to put in two emails via 'feedback' and could complete the submission but not seeing a message coming through to feedback email

Jeanethe tried with her person profile email as well and didn't receiving anything.

**Comment by jimafisk** [comment]
So the issue with the Feedback form is it is supposed to POST to https://contactform.boston.gov/emails. However if you inspect the form HTML, the `action` attribute is blank:

![no_endpoint](https://user-images.githubusercontent.com/5913244/69501043-07cb3b00-0ecf-11ea-91ef-24fc36baa671.png)

**Comment by jimafisk** [comment]
Also note that when clicking on "send email" in a grid of people, it should open the contact form with a hidden input that has a `value` attribute of the specific person's email:

![email_person](https://user-images.githubusercontent.com/5913244/69501264-4feb5d00-0ed1-11ea-9fe0-2e7a9a8188e3.png)

When using the generic contact form in the top nav, this value should be 311supervisors@boston.gov
