### ISSUE TITLE
Metrolist filter question/potential issue

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#952]
On metrolist-affordable properties: https://www.boston.gov/metrolist/affordable-properties

Is the second filter supposed to say "has taxonomy term"?

![Screen Shot 2019-11-24 at 2 18 50 PM](https://user-images.githubusercontent.com/20731897/69500081-f29dde80-0ec5-11ea-845f-ef99ea34a058.png)

**Comment by jimafisk** [comment]
No this should be "Neighborhood"

From D7 (https://boston.prod.acquia-sites.com/metrolist/affordable-properties):

![neighborhood](https://user-images.githubusercontent.com/5913244/69501878-3ea54f00-0ed7-11ea-9230-23d0ffe2f39d.png)
