### ISSUE TITLE
Metrolist: Links in lottery/resale table not showing

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#953]
Metrolist: Links in lottery/resale table not showing

https://www.boston.gov/metrolist/lottery-and-resale

These help sort the listings.

![Screen Shot 2019-11-24 at 2 24 08 PM](https://user-images.githubusercontent.com/20731897/69500108-3c86c480-0ec6-11ea-81e6-e1073574fe9f.png)

Historically, links have shown as optimistic (light blue) in the header of the table. 

Reilly doesn't know which fields were links - would need to ask Susanna if @jimafisk doesn't know.

**Comment by jimafisk** [comment]
Good catch! 

Looks like Zipcode was the only sortable column for the Affordable Properties table in D7 (https://boston.prod.acquia-sites.com/metrolist/affordable-properties):

![zip](https://user-images.githubusercontent.com/5913244/69501780-3dbfed80-0ed6-11ea-86c9-d79837ae6079.png)

Type and Application Deadline are sortable for Lottery and Resale in D7 (https://boston.prod.acquia-sites.com/metrolist/lottery-and-resale): 

![sortable_2](https://user-images.githubusercontent.com/5913244/69501830-b0c96400-0ed6-11ea-981d-64b201330643.png)

**Comment by reillyzlab** [comment]
On staging: 

Affordable properties zip code filter not coming through: boston.gov/metrolist/affordable-properties
