### ISSUE TITLE
Overlap on picture component for mobile (Galaxy 10 + iPhone 6s)

### ISSUE THREAD

**Issue by SarahFigalora** [CityOfBoston/boston.gov-d8#954]
Using chrome on Galaxy 10 and Safari on iPhone 6s, both have overlapping on mobile for the photo component, screenshot taken from the Landmarks page
![Screen Shot 2019-11-24 at 2 28 36 PM](https://user-images.githubusercontent.com/28716225/69500168-b8810c80-0ec6-11ea-8675-e7c4319324c1.png)

**Comment by reillyzlab** [comment]
Duplicate ticket so closing
