### ISSUE TITLE
Issue editing guide pages in workbench

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#955]
Attempting to edit guides on firefox and safari tricked as microsoft edge Reilly either couldn't edit components at all and/or a long load time for a component to open if it did open.

**Specifically tested the following guides and got the same result: buying and owning a home and winter in Boston.**

Tried on digital test page to see if it was a result of many components on a page but did not have the same issue.

![Screen Shot 2019-11-24 at 2 35 23 PM](https://user-images.githubusercontent.com/20731897/69500344-50cbc100-0ec8-11ea-9608-021f91a7a819.png)

**Comment by reillyzlab** [comment]
Issues with: https://www.boston.gov/departments/neighborhood-development/metrolist/rental-listings > table items

Issue with: Ownership | Three Bedroom Single-Family in Plymouth11 Corvette Drive02360 - http://www.boston.gov/sites/default/files/imce-uploads/2019-10/11-corvette-dr.-%E2%80%A6

Fine here: https://www.boston.gov/departments/neighborhood-development/metrolist/rental-listings

Something about PDF mapping/migration from Salesforce

**Comment by reillyzlab** [comment]
@davidrkupton not a guide page but another page that can't edit components https://boston.gov/departments/digital-team/social-media-policy-and-guidelines

**Comment by davidrkupton** [comment]
I think these may have been resolved with other fixes deployed last week.
Can't replicate any issues with:
- https://boston.lndo.site/buying-and-owning-home
- https://boston.lndo.site/departments/digital-team/social-media-policy-and-guidelines
- https://boston.lndo.site/winter-boston
