### ISSUE TITLE
Public notice creation: burdensome date/time entry

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#956]
When creating a public notice there is no prompt for formatting - just blank boxes

![Screen Shot 2019-11-24 at 2 57 15 PM](https://user-images.githubusercontent.com/20731897/69500645-d8b2ca80-0eca-11ea-8313-77815f887974.png)

Can save but have to enter the formatting exactly correct, which will be confusing and burdensome for those entering content.

![Screen Shot 2019-11-24 at 2 53 51 PM](https://user-images.githubusercontent.com/20731897/69500638-c6389100-0eca-11ea-9175-21493b34a1d5.png)

![Screen Shot 2019-11-24 at 2 54 40 PM](https://user-images.githubusercontent.com/20731897/69500641-c89aeb00-0eca-11ea-89d3-1c732afc8f4f.png)

Saved after entered this way:
![Screen Shot 2019-11-24 at 2 55 03 PM](https://user-images.githubusercontent.com/20731897/69500632-bb7dfc00-0eca-11ea-92b5-036ee5a7c706.png)

Had this happen while tricking safari to act like microsoft edge

**Comment by davidrkupton** [comment]
Don't do that!

**Comment by reillyzlab** [comment]
Working fine on native Edge.
