### ISSUE TITLE
Minigrid styling issue - placement of link in minigrid item

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#957]
Minigrid styling issue - placement of link in minigrid item

Links/verbiage should be center aligned on vertical alignment

See:
https://content.boston.gov/departments/human-resources/apply-job-through-career-center > 'related links' section

![Screen Shot 2019-11-24 at 3 04 52 PM](https://user-images.githubusercontent.com/20731897/69500793-385da580-0ecc-11ea-8d11-b3788f789fc1.png)

**Comment by andrebtlima** [comment]
Looking at the example Reilly gave above, looks like this styling issue is affecting internal links only. Exams and Labor Service Applications (which is an external link) is aligned properly.

**Comment by subaha-cob** [comment]
Test on: https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
Tested on develop. Working properly.
