### ISSUE TITLE
'Trash and recycling' page appears to be down

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#962]
If I search "trash and recycling guide boston.gov" and click on the link in google, it goes to a 404 error and this url: https://www.boston.gov/node/32846

When I view the page on content.boston.gov, there appears to be broken images on the page that are preventing me from publishing or editing and saving the page.

**Comment by reillyzlab** [comment]
Potentially related related to #955

**Comment by mmcgowanBOS** [comment]
I created a new url redirect on the node 9781 for node 32846 and this seems to have fixed all the other redirects too for this node. I spoke to David Upton and he seems to think there must have been older version of the Trash and Recycling page that referenced an older node (32846) that does not exist anymore.

Closing for now.
