### ISSUE TITLE
'Search recycling' section missing image on Recycling in Boston page

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#963]
On the ['Recycling in Boston' page](https://www.boston.gov/recycling-boston), the image for the "search recycling" section is missing:

![image](https://user-images.githubusercontent.com/7929556/69507043-26492a80-0eff-11ea-9edd-59d6ade3ca95.png)

I think this is the same image that is missing from the page referenced in #962

**Comment by reillyzlab** [comment]
Duplicate so closing
