### ISSUE TITLE
Trash and recycling app / Recollect widget not appearing on page

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#967]
The recollect widget isn't working on this page:

https://www.boston.gov/trash-and-recycling-day-schedule-and-search

Search and trash and recycling directory aren't working.

**Comment by duffy-james** [comment]
Screenshot where's it's missing:
![image](https://user-images.githubusercontent.com/7929556/69550324-cab38700-0f68-11ea-8fcb-401e99971b73.png)

Also, I can't get in to edit the page. It has a "temporarily unavailable" message.

**Comment by reillyzlab** [comment]
Also can't get in to edit the page to try to triage.

**Comment by jimafisk** [comment]
Working example from D7: https://boston.prod.acquia-sites.com/trash-and-recycling-day-schedule-and-search

<details>
<summary>Screenshot of working example</summary>

![working_trash_day](https://user-images.githubusercontent.com/5913244/69553610-73181a00-0f6e-11ea-864a-e3d04a642fca.png)

</details>

**Comment by jimafisk** [comment]
Error messages when trying to edit the trash and recycling schedule page (https://boston.lndo.site/node/3081/edit):

```
Source image at public://img/event/thumbnails/2017/01/paint-thumbnail.png not found while trying to generate derivative image at public://styles/featured_image_d_full_1x/public/img/event/thumbnails/2017/01/paint-thumbnail.png.
```

<details>
<summary>See screenshot</summary>

![trash_error](https://user-images.githubusercontent.com/5913244/69560073-238b1b80-0f79-11ea-958a-4adc4ce49654.png)

</details>

```
InvalidArgumentException: Field field_left_column is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 587 of /app/docroot/core/lib/Drupal/Core/Entity/ContentEntityBase.php).
```
<details>
<summary>See screenshot</summary>

![error_2](https://user-images.githubusercontent.com/5913244/69560350-9b594600-0f79-11ea-8fe9-878409338e3c.png)


</details>

**Comment by jimafisk** [comment]
I was able to get the edit working locally, there appears to be a one_column_text paragraph on the page that is giving us trouble, if I simply delete it we can edit the page.

The script_page currently looks like it only accepts `seamless_docs`, I think we need to extend this to allow the recollect app.

<details>
<summary>See screenshot</summary>

![script_page](https://user-images.githubusercontent.com/5913244/69565074-335b2d80-0f82-11ea-81f9-097a6d1d36cc.png)


</details>

**Comment by jimafisk** [comment]
So it looks like this paragraph never got ported: https://github.com/CityOfBoston/boston.gov-d8/issues/68

I think we're going to need that in order to get this working.

**Comment by jimafisk** [comment]
Well I converted the `recollect_widget` paragraph, but upon closer inspection, it looks like we might just need to enable the `one_column_text` paragraph in the allowed values

<details>
<summary>See screenshot</summary>

![one_col_text](https://user-images.githubusercontent.com/5913244/69570787-90f57700-0f8e-11ea-8d14-e3235309a7f3.png)

</details>

This must have been added and eventually removed from the `script_page` content type.

Here's the value:

```
<script>_recollect_config = { area: "Boston", page: "tabbed_widget" }
</script><script src="https://assets.us.recollect.net/api/widget.js"></script>
```

**Comment by jimafisk** [comment]
Got this working on D8:

![d8_recollect](https://user-images.githubusercontent.com/5913244/69572917-19761680-0f93-11ea-8785-c3289af2fc82.png)

**Comment by jimafisk** [comment]
This should work now: https://boston.gov/trash-and-recycling-day-schedule-and-search

@duffy-james can you take a look ^ when you get a chance?

The edit is still broken, the fix I'm working on should fix that. Still there is another error on the page that will stop you from being able to save this node:
```
Validation error on collapsed paragraph events_and_notices (field_featured_item.0.target_id) - This entity (node: 14686) cannot be referenced.
```
<details>
<summary>See screenshot</summary>

![val_error](https://user-images.githubusercontent.com/5913244/69573367-f0a25100-0f93-11ea-8019-15a0784ec0f6.png)

</details>

That's unrelated to this issue though.

**Comment by jimafisk** [comment]
Also, to be clear the fix is adding the `one_column_text` component back to the script page:

![one_col](https://user-images.githubusercontent.com/5913244/69573629-7a521e80-0f94-11ea-8035-688bfbf837ae.png)

This must have been there when this node was originally created and later removed. @duffy-james is that ok?

**Comment by reillyzlab** [comment]
Confirming that I see the widget and can search my address.

**Comment by jimafisk** [comment]
For that other error, I needed to re-enable `news_and_announcements` and `events_and_notices` in `field_components` on `script_page` (https://github.com/CityOfBoston/boston.gov-d8/issues/967).

I also removed the date filter requirements that featured items are greater than or equal to "now" (https://boston.lndo.site/admin/structure/views/view/entity_reference_filters/edit/entity_reference_2) so nodes that feature old events or public_notices can still be saved.

**Comment by jimafisk** [comment]
@duffy-james once the PR related to this is deployed, here are the steps to be able to edit the page again:
1. Use the pencil icon to delete the existing `one_column_text` component
<details>
<summary>Screenshot</summary>

![delete_one_col_text](https://user-images.githubusercontent.com/5913244/69579409-69a7a580-0fa0-11ea-8855-d56ac7cf7bb2.png)

</details>

2. Now you can click "Tasks" in the upper right of the page and "Edit" the node.

3. Go to the "Script Information" tab and click the "Add One Column Text" button

4. Click "Source" in the WYSIWYG and make sure **full html** is selected in the widget at the bottom of the editor.

5. Paste in the following script:

```
<script>_recollect_config = { area: "Boston", page: "tabbed_widget" }
</script><script src="https://assets.us.recollect.net/api/widget.js"></script>
```

6. Now you can resave the page / make other edits.
