### ISSUE TITLE
'Content' editors shouldn't be able to see "needs review" items

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#970]
From the "my workbench" screen, content editors shouldn't be able to view items in "needs review":
![image](https://user-images.githubusercontent.com/7929556/69550482-123a1300-0f69-11ea-820b-f7bdd53059f4.png)

Only "admin" and "site admin" roles should have permissions to see "needs review" items.

**Comment by subaha-cob** [comment]
Test UAT: https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
@subaha-cob in order to test this i need to change my role to Content Editor, but i'll need you to change me back once I confirm that this is either fixed or still and issue.

**Comment by subaha-cob** [comment]
@andrebtlima okay, let me know when you are ready.

**Comment by andrebtlima** [comment]
So the needs review column is no longer showing in My Workbench for Content Editors (changed my role to confirm), but there's something funky happening with the menu bar: 
<img width="1437" alt="Screen Shot 2020-09-18 at 12 16 05 PM" src="https://user-images.githubusercontent.com/57111927/93621067-095b7780-f9a9-11ea-924d-23173ad50b81.png">
<img width="1440" alt="Screen Shot 2020-09-18 at 12 16 14 PM" src="https://user-images.githubusercontent.com/57111927/93621069-0b253b00-f9a9-11ea-81a8-596dccd703a9.png">

**Comment by subaha-cob** [comment]
@andrebtlima it probably has nothing to do with my fix since i didn't touch any code. This was strictly database fix. It looks like it is a separate issue. Probably have been there for a while since none of us have Editor access or login to have noticed it. You can create a new ticket for it and assign to me.

**Comment by andrebtlima** [comment]
@subaha-cob we might need to test this one on prod since I'm running into this the same issue as before. The UI for Content Editors is missing on develop
