### ISSUE TITLE
Rollover on guides landing page is red / it should be blue

### ISSUE THREAD

**Issue by sebastianebarb** [CityOfBoston/boston.gov-d8#971]
![Screen Shot 2019-11-25 at 9 52 43 AM](https://user-images.githubusercontent.com/20642299/69550699-79f05e00-0f69-11ea-84e7-8cd9de631c68.png)

**Comment by jimafisk** [comment]
We will need to update this in patterns.boston.gov since this was red in D7: https://boston.prod.acquia-sites.com/guides

**Comment by reillyzlab** [comment]
@sebastianebarb give @jimafisk finding, leave blue or change to blue?

**Comment by sebastianebarb** [comment]
Change to blue

**Comment by subaha-cob** [comment]
Test on: https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
Tested on develop. Working properly.
