### ISSUE TITLE
'Your most recent edits' from my workbench should show recent edits

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#972]
I just worked with a content editor who recently published pages on the site, but they weren't appearing at the top of the list here:

![image](https://user-images.githubusercontent.com/7929556/69550675-6d6c0580-0f69-11ea-9d61-9987ab4a8d69.png)

I'm guessing this is maybe just pulling everything, instead of looking at the recently published items.

**Comment by andrebtlima** [comment]
Need to test this with content editor role.

**Comment by andrebtlima** [comment]
Resolved so closing.
