### ISSUE TITLE
Only the first instance of recurring events appear on the Calendar page

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#975]
If you take a look at the Calendar page (https://www.boston.gov/events), only the first instance of recurring events is appearing:

![recurring_events](https://user-images.githubusercontent.com/5913244/69552594-b3769880-0f6c-11ea-8ab0-e9983e5521ae.png)

This should be fixed so all occurrences of an event appears.

**Comment by duffy-james** [comment]
Current examples of events where this isn't working:

https://www.boston.gov/calendar/free-immigration-consultations-volunteer-attorneys
https://www.boston.gov/calendar/winter-fitness-series-walking-group-snowshoeing
https://www.boston.gov/calendar/winter-fitness-series-yoga
https://www.boston.gov/calendar/winter-fitness-series-strength-training
https://www.boston.gov/calendar/winter-fitness-series-yoga-0
https://www.boston.gov/calendar/winter-fitness-series-zumba-gold
https://www.boston.gov/calendar/winter-fitness-series-boot-camp
https://www.boston.gov/calendar/winter-fitness-series-barre
https://www.boston.gov/calendar/winter-fitness-series-chair-yoga
https://www.boston.gov/calendar/winter-fitness-series-zumba-tone
https://www.boston.gov/calendar/winter-fitness-series-cardio-fitness

**Comment by andrebtlima** [comment]
this is ready to go to production
