### ISSUE TITLE
Broken images on Landmarks Commission page

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#976]
The grid of cards component here is missing an image:

![image](https://user-images.githubusercontent.com/7929556/69554481-db1b3000-0f6f-11ea-863f-c40c2e7a87b1.png)

Also, the icon for Article 85 is missing an image:

![image](https://user-images.githubusercontent.com/7929556/69554529-ecfcd300-0f6f-11ea-84c2-e706c3d615e9.png)

**Comment by reillyzlab** [comment]
Went in and checked this on boston.gov/departments/landmarks-commission

The items under 'spotlight' section are in the backend CMS portion but the grid of cards is broken. Developer needs to take a look at that.

The icon in get started is fixed.

**Comment by reillyzlab** [comment]
Duplicate
