### ISSUE TITLE
Page links broken in "needs review" section

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#978]
When I attempt to click on a link here in the ["needs review" section](https://content.boston.gov/admin/content/needs_review):
![image](https://user-images.githubusercontent.com/7929556/69557009-dbb5c580-0f73-11ea-9f97-606829e74eab.png)

I get a "temporarily unavailable" message, instead of going to the page:
![image](https://user-images.githubusercontent.com/7929556/69557038-ea9c7800-0f73-11ea-896f-bfdb138476da.png)

**Comment by reillyzlab** [comment]
Current work around: Hit the 'edit' link on the right side of the page.

**Comment by andrebtlima** [comment]
Resolved so closing.
