### ISSUE TITLE
"Needs review" section should only display content with the current status of "needs review"

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#979]
At the moment, it seems like any page that has been placed in "needs review" is displaying in this section. I just need the content with the current status of "needs review":
![image](https://user-images.githubusercontent.com/7929556/69557416-90e87d80-0f74-11ea-8bb2-c8c817f881ac.png)

In the example above, the five links were published from "needs review", but they still appear in this section.

**Comment by subaha-cob** [comment]
@andrebtlima Test UAT: https://d8-uat.boston.gov/. This is a Drupal admin login test only.

**Comment by andrebtlima** [comment]
Tested on develop. Working properly.
