### ISSUE TITLE
Phone option not working for links in WYSIWYG field

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#980]
When a user selects the phone option here after clicking the "link" button in the WYSIWYG field:
![image](https://user-images.githubusercontent.com/7929556/69558010-85e21d00-0f75-11ea-8e88-7e08dd997d35.png)

They never get an option to add a clickable phone link. It just stays as the "email" option.

**Comment by duffy-james** [comment]
Just tried to add a link and got this error message:
![image](https://user-images.githubusercontent.com/7929556/69726772-39225180-10ef-11ea-9c94-a39d569cf028.png)

Tried two formats for the phone number, and neither worked:

- 617-635-1185
- 6176351185

**Comment by andrebtlima** [comment]
Now when you try to add a phone link you consistently get the following error: 

<img width="490" alt="Screen Shot 2020-03-16 at 1 35 49 PM" src="https://user-images.githubusercontent.com/57111927/76785126-3b3a1a00-678b-11ea-83c3-dc1b7a8a9418.png">

No matter what the format is of the phone number I enter into the field (i.e. all numerals no spaces, numerals with spaces, numerals with dashes etc.)

**Comment by subaha-cob** [comment]
@andrebtlima Test on UAT: https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
Tested on develop. Working properly.
