### ISSUE TITLE
Broken images on New Urban Mechanics site

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#982]
Missing an image here on the [New Urban Mechanics Department page](https://www.boston.gov/departments/new-urban-mechanics):
![image](https://user-images.githubusercontent.com/7929556/69561479-72d24b80-0f7b-11ea-9040-b802bc7419ed.png)

The icon is also really small:
![image](https://user-images.githubusercontent.com/7929556/69561623-b88f1400-0f7b-11ea-9b90-76ab6a80ec9c.png)

**Comment by reillyzlab** [comment]
First issue: Related to #976 

Second issue with icon: Resolved

**Comment by reillyzlab** [comment]
Resolved
