### ISSUE TITLE
Broken pdf links on Age Strong pages

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#983]
The Age Strong Commission team has noticed a broken pdf links on their site:

https://www.boston.gov/sites/default/files/full_report_0.pdf
https://www.boston.gov/sites/default/files/fact_sheet_0.pdf
https://www.boston.gov/sites/default/files/document-file-11-2019/november_-_volume_43_number_10_0.pdf

They're going to share a google doc with us for any other links.

**Comment by reillyzlab** [comment]
Duplicate

**Comment by andrebtlima** [comment]
Looks like these links are working so closing this ticket.
