### ISSUE TITLE
Default 'canceled' message missing from public notices

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#984]
We used to have a default "canceled" message along the lines of: "Reason for cancellation: Contact the organizer." Now, there's just an empty space at the top. The location used to be here:
![image](https://user-images.githubusercontent.com/7929556/69569776-5b4f8e80-0f8c-11ea-82e6-7cac8d44c0da.png)

**Comment by reillyzlab** [comment]
@duffy-james any insight on what should be happening/what it should say?

Looked on D7 and couldn't find.

**Comment by subaha-cob** [comment]
Test on UAT: https://d8-uat.boston.gov/

**Comment by andrebtlima** [comment]
Tested on develop. Working properly.
