### ISSUE TITLE
'Grid of quotes' images not appearing in component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#989]
The images in the "grid of quotes" component are not appearing on the page:
![image](https://user-images.githubusercontent.com/7929556/69579630-e2a6fd00-0fa0-11ea-9a1b-9bfbc8538206.png)

It looks like the "alt" or "title" field is appearing instead. Example is located here:

https://www.boston.gov/civic-engagement/how-do-you-age-strong

**Comment by reillyzlab** [comment]
All images are the same.

Look on D7:
![Screen Shot 2019-11-25 at 4 50 51 PM](https://user-images.githubusercontent.com/20731897/69581102-e9833f00-0fa3-11ea-817d-eec2642f7ce0.png)
