### ISSUE TITLE
Salesforce: Issues with PDFs

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#990]
Salesforce: Issues with PDFs

Issues with: https://www.boston.gov/departments/neighborhood-development/metrolist/rental-listings > table items

Issue with: Ownership | Three Bedroom Single-Family in Plymouth11 Corvette Drive02360 - http://www.boston.gov/sites/default/files/imce-uploads/2019-10/11-corvette-dr.-%E2%80%A6

Fine here: https://www.boston.gov/departments/neighborhood-development/metrolist/rental-listings

Something about PDF mapping/migration from Salesforce

**Comment by reillyzlab** [comment]
View is truncated. Jim will fix this.

DND will need to remap the file locations for PDFs on boston.gov that are broken.

**Comment by davidrkupton** [comment]
Created redirects for 4 pdfs, the rest were to non-boston.gov hosted docs.

**Comment by reillyzlab** [comment]
Resolved
