### ISSUE TITLE
Can't run update.php script

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#994]
There aren't any pending database updates at the moment, but in the future we might have trouble running these unless we resolve this `date_recur` error:

![update_date_recur](https://user-images.githubusercontent.com/5913244/69649413-0028a500-103b-11ea-8740-c414abbbe1ed.png)

**Comment by subaha-cob** [comment]
@andrebtlima David started laughing and he couldn't stop for half an hour. The update is done every deploy and every local build. This is just the UI. I am going to move this to review. Please close because we don't have the problem.
