### ISSUE TITLE
'Feature' icons are broken in UI

### ISSUE THREAD

**Issue by reillyzlab** [CityOfBoston/boston.gov-d8#997]
All sidebar 'feature' icons are broken.

See here: https://www.boston.gov/parks/moakley-park

![Screen Shot 2019-11-26 at 12 03 40 PM](https://user-images.githubusercontent.com/20731897/69655605-edb36900-1044-11ea-9b7b-a2606d45ce4d.png)

Reilly checked the taxonomy for 'feature' and all the items have working icons in the CMS/database but they icons are not displaying accurately.

Seems to be most/all of pages for /parks/...

**Comment by reillyzlab** [comment]
See #1142 for related

**Comment by subaha-cob** [comment]
test on UAT: https://d8-uat.boston.gov/parks/moakley-park

Go and edit that page above and then add new features to be linked on page to test.

**Comment by andrebtlima** [comment]
still seeing the same issue:
<img width="1435" alt="Screen Shot 2020-09-11 at 2 23 55 PM" src="https://user-images.githubusercontent.com/57111927/92959829-81222300-f43a-11ea-9fc1-295193937659.png">

**Comment by subaha-cob** [comment]
@andrebtlima Sorry, I haven't pushed what is currently "in progress" yet. I will before the day ends.

**Comment by andrebtlima** [comment]
@subaha-cob still seeing this issue on UAT. Also there's this weird string of letters as one of the possible features selections in the editor, that I either didn't notice before or wasn't there before: 
<img width="1435" alt="Screen Shot 2020-09-14 at 1 52 41 PM" src="https://user-images.githubusercontent.com/57111927/93120729-c7bd8a80-f691-11ea-9bfb-cc586fcee0af.png">

**Comment by andrebtlima** [comment]
@subaha-cob  Ok this is almost all set except that there are some icons that aren't coming through (I selected all so you can see which one's are not renderings), the text is ever so slightly off center aligned with the icons, and this weird string of letters is still an option on the list of features in the editor (see comment above):


<img width="297" alt="Screen Shot 2020-09-22 at 1 39 40 PM" src="https://user-images.githubusercontent.com/57111927/93917512-147c1380-fcd9-11ea-9349-843af7c2ff8c.png">
<img width="323" alt="Screen Shot 2020-09-22 at 1 39 58 PM" src="https://user-images.githubusercontent.com/57111927/93917533-1e057b80-fcd9-11ea-9c7b-7116279a2a93.png">
<img width="304" alt="Screen Shot 2020-09-22 at 1 40 11 PM" src="https://user-images.githubusercontent.com/57111927/93917559-2493f300-fcd9-11ea-94f2-40cda803c782.png">

**Comment by subaha-cob** [comment]
@andrebtlima the missing icons are not in the database. To fix it you will have to go and find the correct icons and upload again to Drupal. I came across this when i was testing on my local. I assumed it was just my local.

**Comment by andrebtlima** [comment]
@subaha-cob what about that weird string of letters, any idea where that's coming from?

**Comment by subaha-cob** [comment]
@andrebtlima You can send this back to In progress, I will try and see if it is possible to replace the icons on my local and then copy the correct name and path to all the environment. 

I will take a look at removing the weird string of letters. I am not sure who added it and why.

**Comment by subaha-cob** [comment]
@andrebtlima Also the long text is a database change. I will take out from UAT, but will skip Dev and Staging and take it out from Production instead. The reason why I am taking it off from Production is because production database always overrides Dev and Staging, so it doesn't make sense to do much there.

**Comment by subaha-cob** [comment]
@andrebtlima I am going to manually update about 6 icons in production. I will however skip updating them in dev and staging. Dev and Staging should be fine once we update their databases.

**Comment by subaha-cob** [comment]
Teston UAT: https://d8-uat.boston.gov
