### ISSUE TITLE
Allow content authors to add document links to "grid of cards" component

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#998]
Right now, we give content authors the ability to add documents to the grid of cards component. But, it completely breaks the site:
![image](https://user-images.githubusercontent.com/7929556/69661063-ad0d1d00-104f-11ea-96bc-2cbbff5df0a6.png)

Hoping to just validate document links again for this component. If not, we're going to have to rebuild a few different pages.

Examples here:
https://www.boston.gov/improving-local-and-regional-transit-services
https://www.boston.gov/safer-more-accessible-walking-and-biking
https://www.boston.gov/smart-streets

**Comment by reillyzlab** [comment]
Same issue here: 
#976 
#983

**Comment by duffy-james** [comment]
More examples:
https://www.boston.gov/blue-hill-avenue-transportation-action-plan
https://www.boston.gov/silver-line-improvements-downtown
https://www.boston.gov/departments/transportation/brighton-avenue-bus-lane

**Comment by jimafisk** [comment]
This should be all set on the next deploy:

<details>
<summary>Broken screenshot</summary>

![previous](https://user-images.githubusercontent.com/5913244/69760356-588e9e00-1132-11ea-8323-2e6df1a8c4eb.png)

</details>
<details>
<summary>Fixed screenshot</summary>

![now](https://user-images.githubusercontent.com/5913244/69760363-5e847f00-1132-11ea-8d78-690cda7676cd.png)

</details>

**Comment by reillyzlab** [comment]
Fixed on staging. Not yet deployed to production.

**Comment by reillyzlab** [comment]
Fixed
