### ISSUE TITLE
Look into programmatic solution for broken pdf links on site

### ISSUE THREAD

**Issue by duffy-james** [CityOfBoston/boston.gov-d8#999]
@davidrkupton has been handling broken pdf links in one-off cases, but is investigating a more systematic approach. We're starting to get a lot of emails about broken pdfs on the site.

**Comment by duffy-james** [comment]
@davidrkupton also related to the pdfs, I think. I uploaded this pdf yesterday:

https://www.boston.gov/sites/default/files/file/2019/11/201911261644.pdf

But it's a dead link this morning. Unless I'm going crazy, I know this was working yesterday.

**Comment by reillyzlab** [comment]
Ongoing
